### ISSUE TITLE
Panic in Volume.createIfNotExist

### ISSUE THREAD

**Issue by bobrik** [docker/docker#10242]
I'm running build from master, getting the next error:

```
time="2015-01-21T19:30:34+03:00" level="warning" msg="WARNING: Udev sync is not supported. This will lead to unexpected behavior, data loss and errors"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x73c61c]

goroutine 9 [running]:
github.com/docker/docker/volumes.(*Volume).createIfNotExist(0xc2085071d0, 0x0, 0x0)
	/go/src/github.com/docker/docker/volumes/volume.go:91 +0xbc
github.com/docker/docker/volumes.(*Volume).initialize(0xc2085071d0, 0x0, 0x0)
	/go/src/github.com/docker/docker/volumes/volume.go:111 +0x9a
github.com/docker/docker/volumes.(*Repository).restore(0xc20850a1e0, 0x0, 0x0)
	/go/src/github.com/docker/docker/volumes/repository.go:100 +0x402
github.com/docker/docker/volumes.NewRepository(0xc208203980, 0x17, 0x7fc4d2e77c40, 0xc2081a68f0, 0x17, 0x0, 0x0)
	/go/src/github.com/docker/docker/volumes/repository.go:39 +0x1fa
github.com/docker/docker/daemon.NewDaemonFromDirectory(0x12d7c40, 0xc208078a50, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:892 +0x1114
github.com/docker/docker/daemon.NewDaemon(0x12d7c40, 0xc208078a50, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:779 +0x44
main.func·001()
	/go/src/github.com/docker/docker/docker/daemon.go:55 +0x46
created by main.mainDaemon
	/go/src/github.com/docker/docker/docker/daemon.go:78 +0x35e
```

Problematic snippet of code:

```go
	if stat, err := os.Stat(v.Path); err != nil && os.IsNotExist(err) {
		if stat.IsDir() {
			os.MkdirAll(v.Path, 0755)
		}
	// ...
	}
```

`err` is actually `stat error: stat : no such file or directory`.

**Comment by bobrik** [comment]
Wiping `/var/lib/docker` fixed the problem. I'm using devicemapper btw.

**Comment by tiborvass** [comment]
@bobrik Thank you very much for your report.
Would you be able to provide a way of reproducing it?

**Comment by bobrik** [comment]
@tiborvass unfortunately I can't do it anymore.

```
&volumes.Volume{ID:\"_tmp\", Path:\"\", IsBindMount:false, Writable:false, containers:map[string]struct {}{}, configPath:\"/var/lib/docker/volumes/_tmp\", repository:(*volumes.Repository)(nil), lock:sync.Mutex{state:1, sema:0x0}}
```

This is how `v` looked like when it was failing.

**Comment by cpuguy83** [comment]
I see in the code why the panic happened, but curious how to reproduce it.

**Comment by bobrik** [comment]
Thanks! :whale2:

**Comment by jfrazelle** [comment]
@bobrik thanks for testing master :D

**Comment by bobrik** [comment]
@jfrazelle I'm just trying to swap `gzip` with `cgzip`, see #10181. :turtle:
