### ISSUE TITLE
"fatal error: addspecial on invalid pointer"

### ISSUE THREAD

**Issue by jamshid** [docker/docker#10606]
Got a weird error, it appeared to cause my docker server (remote boot2docker) to crash. 
A docker restart (`/etc/init.d/docker start`) fixed it, will update if I see it again.
```
time="2015-02-06T03:15:32Z" level="info" msg="GET /v1.16/containers/c0d29822e5d8/json" 
time="2015-02-06T03:15:32Z" level="info" msg="+job container_inspect(c0d29822e5d8)" 
time="2015-02-06T03:15:32Z" level="info" msg="-job container_inspect(c0d29822e5d8) = OK (0)" 
fatal error: addspecial on invalid pointer

goroutine 55556 [running]:
runtime.throw(0x127ed3f)
	/usr/local/go/src/pkg/runtime/panic.c:520 +0x69 fp=0x7faa801ba308 sp=0x7faa801ba2f0
addspecial(0xc208f67000, 0x7faa83ce2578)
	/usr/local/go/src/pkg/runtime/mheap.c:655 +0x4d fp=0x7faa801ba348 sp=0x7faa801ba308
runtime.setprofilebucket(0xc208f67000, 0x7faa703b30a0)
	/usr/local/go/src/pkg/runtime/mheap.c:776 +0x73 fp=0x7faa801ba368 sp=0x7faa801ba348
runtime.MProf_Malloc(0xc208f67000, 0x100)
	/usr/local/go/src/pkg/runtime/mprof.goc:191 +0xc8 fp=0x7faa801ba4a0 sp=0x7faa801ba368
profilealloc(0xc208f67000, 0x100)
	/usr/local/go/src/pkg/runtime/malloc.goc:258 +0xb5 fp=0x7faa801ba4d0 sp=0x7faa801ba4a0
runtime.mallocgc(0x100, 0xbcd261, 0x0)
	/usr/local/go/src/pkg/runtime/malloc.goc:197 +0x218 fp=0x7faa801ba538 sp=0x7faa801ba4d0
growslice1(0xa90ac0, 0xc209371380, 0x4, 0x4, 0x5, 0x7faa801ba5f8)
	/usr/local/go/src/pkg/runtime/slice.goc:125 +0x107 fp=0x7faa801ba588 sp=0x7faa801ba538
runtime.growslice(0xa90ac0, 0xc209371380, 0x4, 0x4, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/runtime/slice.goc:76 +0xbb fp=0x7faa801ba5d0 sp=0x7faa801ba588
syscall.ParseNetlinkRouteAttr(0xc2093f68a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/syscall/netlink_linux.go:165 +0x279 fp=0x7faa801ba710 sp=0x7faa801ba5d0
net.interfaceTable(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/interface_linux.go:34 +0x4cf fp=0x7faa801ba970 sp=0x7faa801ba710
net.InterfaceByName(0xc2089b4830, 0xb, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/interface.go:116 +0x88 fp=0x7faa801baa58 sp=0x7faa801ba970
github.com/docker/libcontainer/network.SetInterfaceInNamespacePid(0xc2089b4830, 0xb, 0x420b, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/network/network.go:40 +0x43 fp=0x7faa801baa98 sp=0x7faa801baa58
github.com/docker/libcontainer/network.(*Veth).Create(0x129e4c8, 0xc209141680, 0x420b, 0xc208a9e7b0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/network/veth.go:45 +0x2c5 fp=0x7faa801bab78 sp=0x7faa801baa98
github.com/docker/libcontainer/namespaces.InitializeNetworking(0xc20865c900, 0x420b, 0xc208a9e7b0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/namespaces/exec.go:170 +0x21f fp=0x7faa801bac90 sp=0x7faa801bab78
github.com/docker/libcontainer/namespaces.Exec(0xc20865c900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc208c51890, 0xa, 0xc2093c8d90, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/namespaces/exec.go:70 +0x478 fp=0x7faa801bae98 sp=0x7faa801bac90
github.com/docker/docker/daemon/execdriver/native.func·003()
```

**Comment by LK4D4** [comment]
Yup, pretty weird. I think can be related to low memory available.

**Comment by jfrazelle** [comment]
please let us know if you are still able to reproduce on latest and how

**Comment by cpuguy83** [comment]
Closing due to no response.
If you can still reproduce (and hopefully provide repro steps) please ping here and we can re-open.
Thanks!
