### ISSUE TITLE
docker containers experience packet loss or slow network (EAI_AGAIN in application)

### ISSUE THREAD

**Issue by mlehner616** [docker/docker#12603]
I've had a similar issue to #12364 and/or #11407 where my production node.js apps inside the container simply stop responding. I thought the circumstances however were different enough to warrant a separate issue. 

Once a container stops responding they will not respond again until the docker daemon is restarted. Not all containers will stop responding at the same time. I'm led to the conclusion that this is a docker issue rather than node because I have several different services running on the same server and all of them experience apparent heavy packet loss hours before the error below occurs which eventually seems to crash node in turn. Restarting the docker daemon cleared up the error and also the packet loss. The exception caught in the app is interesting in that is a seldom occurring EAI_AGAIN error (DNS temporary timeout) (Also, not temporary in this case) which led me to believe it could be related to #12364 and/or #11407.

Errors I am seeing in the node app
```
2015-04-21T08:26:21.415Z - info: --> method:[GET] url:[/status] status:[200] time:[1ms]
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo EAI_AGAIN
    at Object.exports._errnoException (util.js:742:11)
    at errnoException (dns.js:46:15)
    at Object.onlookup [as oncomplete] (dns.js:91:26)
```

Details
```
[root@server1 root]# docker --version
Docker version 1.5.0, build a8a31ef/1.5.0

[root@server1 root]# uname -a
Linux server1 3.14.20-20.44.amzn1.x86_64 #1 SMP Mon Oct 6 22:52:46 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Thank you

**Comment by mavenugo** [comment]
@mlehner616 Just commented : https://github.com/docker/docker/issues/11407#issuecomment-95044564 Can you please check if this is applicable ?

**Comment by mlehner616** [comment]
@mavenugo Thanks for the suggestion. I checked and it looks like the Amazon Linux AMI has LRO disabled by default so it doesn't look like this would apply in this case.

```
[root@server1 root]# ethtool -k eth0
Features for eth0:
...
large-receive-offload: off [fixed]
...
```

**Comment by SaschaMoellering** [comment]
It seems that we ran into a similar issue, we have a high traffic, event driven application (millions of req/day) using Vert.x and the application suddenly stops working, LRO looks good for us as well:

# ethtool -k eth0 | grep large-receive-offload:
large-receive-offload: off

# docker --version
Docker version 1.5.0, build a8a31ef

# uname -a
Linux 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt7-1~bpo70+1 (2015-04-07) x86_64 GNU/Linux

**Comment by SaschaMoellering** [comment]
Any updates on this issue?

**Comment by brudrafon** [comment]
Looks related to this comment https://github.com/docker/docker/issues/11407#issuecomment-97746220

**Comment by mlehner616** [comment]
@brudrafon Thanks for the info. 

The symptoms here are very subtly different than the article you posted. The article describes the symptoms as the host losing connectivity. In this case, the docker containers are the instances that lose connectivity, not the host.

For example,
I have a single host running 5 containers
container a on port 3000
container b on port 3001
etc...

The symptoms are any one random container is suddenly unable to make outgoing calls in a timely fashion. The container is receiving requests but is not able to respond because it is unable to communicate with dependent services (e.g. DNS, DB, etc.) DNS being the most obvious example. Some, none, or all containers may or may not fail at the same time. All while this is happening, connectivity to/from the host remains unaffected. Restarting the docker daemon works around the issue temporarily but only delays the inevitable.

I will give the info in the article a try though but even if it helps it is still just a workaround. Docker really must either fix this in their project or champion the upstream fix in the bridge driver.

**Comment by mlehner616** [comment]
More info:
`docker 1.6.0`

It's not DNS like some other issues were referencing, because the issue is also apparent when curling an IP directly. Info below.

This is successful on the host which has one container:
```
[root@ip-1-2-3-4 ~]# curl 54.243.77.158
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

This is run inside the container running on the same host:
```
[ root@16f7c3e2daf8:/data ]$ curl 54.243.77.158
curl: (7) Failed to connect to 54.243.77.158 port 80: Connection timed out
```

**Comment by mlehner616** [comment]
If I restart the docker daemon it will work, for a while.

`[root@ip-1-2-3-4 ~]# service docker restart`

**Comment by cpuguy83** [comment]
@mlehner616 Is this still an issue on 1.7.1 (or master)

**Comment by cpuguy83** [comment]
Also ping @mavenugo @mrjana

**Comment by dverbeek84** [comment]
I have the same problem.
Both on CentOS 6.6 and 7 with docker version 1.5 and 1.6.2. these servers are running on VMware.
The server we use on AWS(Also CentOS) don't have this problem. Also this issue is very random.

**Comment by nielskrijger** [comment]
Experiencing the same problem using boot2docker on Mac OS. I'm hammering a small batch script in Node.js 12.7 connecting to a MongoDB 3 server which goes well for a couple of minutes until the inevitable:

```
Unhandled rejection Error: getaddrinfo EAI_AGAIN
    at Object.exports._errnoException (util.js:746:11)
    at errnoException (dns.js:49:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
```
When this happens no connections come through anymore and I have to reboot boot2docker to get it working again.

@cpuguy83 this is using docker 1.7.1

**Comment by dverbeek84** [comment]
I have followed #11407 but this did't not help.

**Comment by thaJeztah** [comment]
@mlehner616 are you still having this issue on the current release (1.9.1 / 1.10.0)?

**Comment by mlehner616** [comment]
@thaJeztah I am still experiencing this issue with 1.9.1. Don't have my hands on 1.10.0 yet.

The issue seems to have surfaced as an issue in the iptables-based bridging. Something happens where some containers simply stop sending valid outgoing traffic. tcpdump didn't really offer conclusive diagnostics. One work-around I found was to run iptables-save, restart iptables (flush), then iptables-restore. The networking to the container resumes without restarting the container instance.

**Comment by thaJeztah** [comment]
@mlehner616 thanks for the info; wondering if it's a docker issue then?

**Comment by kshcherban** [comment]
I have faced similar issue with apt-get `Temporary failure resolving` error that is caused by [EAI_AGAIN ](https://github.com/Debian/apt/blob/349c5c89454ff344e4cf693492e7cb62ff549886/methods/connect.cc#L208)getaddrinfo() error. I have build system ([OBS](http://openbuildservice.org/)) that spawns lxc containers and installs packages inside them using apt-get (i know that it's a bad idea and builds are not reproducible). From time to time apt-get exits with error and package build fails.
Seems that this name resolution issue is caused by some kernel heisenbug.

**Comment by nunorafaelrocha** [comment]
I'm having an issue on Docker App for Mac Version 1.11.0-beta6 that I don't know if is related is this one.

```sh
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

**Comment by thaJeztah** [comment]
@nunorafaelrocha no, that's probably not related, that's a docker-compose error, but if you keep seeing that, possibly report it on the Docker for Mac beta forum

**Comment by nuzz** [comment]
@nunorafaelrocha I'm seeing this as well, very similar setup (mac beta 1.11.0-beta7) mongo:3.0.7

**Comment by thaJeztah** [comment]
@nuzz can you report it on the Docker Mac "beta" forum as well? (Or see if there's a similar topic already)

**Comment by angeloluciani** [comment]
Thank you guys for share , I had the same problem and it is solve using **service docker restart**

**Comment by karelstriegel** [comment]
@angeloluciani  that is more a workaround then a solution...

**Comment by randunel** [comment]
I created a test application which resolves `asdqq.100.resolve.me` down to `asdqq.1.resolve.me`. I will restrict my logging to the beginning of the output (first 10 resolves), no point in showing all the errors.

Here is a tcpdump output from inside the container when EAI_AGAIN happens:

```
 $ tcpdump -i eth0 -n -l -vvvvv | grep asdqq

tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
    172.18.0.4.48992 > 8.8.8.8.53: [bad udp cksum 0xbc64 -> 0xce36!] 26742+ A? asdqq.99.resolve.me. (37)
    8.8.8.8.53 > 172.18.0.4.48992: [udp sum ok] 26742 q: A? asdqq.99.resolve.me. 1/0/0 asdqq.99.resolve.me. [9m59s] A 72.52.4.119 (53)
    172.18.0.4.48992 > 8.8.8.8.53: [bad udp cksum 0xbc64 -> 0xffff!] 7085+ AAAA? asdqq.99.resolve.me. (37)
    8.8.8.8.53 > 172.18.0.4.48992: [udp sum ok] 7085 q: AAAA? asdqq.99.resolve.me. 0/1/0 ns: asdqq.99.resolve.me. [29m59s] SOA ns1.sedoparking.com. hostmaster.sedo.de. 2015071001 86400 10800 604800 86400 (110)
    172.18.0.4.48992 > 8.8.8.8.53: [bad udp cksum 0xbc64 -> 0x3ff6!] 63926+ A? asdqq.96.resolve.me. (37)
    8.8.8.8.53 > 172.18.0.4.48992: [udp sum ok] 63926 q: A? asdqq.96.resolve.me. 1/0/0 asdqq.96.resolve.me. [9m59s] A 72.52.4.119 (53)
    172.18.0.4.48992 > 8.8.8.8.53: [bad udp cksum 0xbc64 -> 0xdbd4!] 24280+ A? asdqq.95.resolve.me. (37)
    8.8.8.8.53 > 172.18.0.4.48992: [udp sum ok] 24280 q: A? asdqq.95.resolve.me. 1/0/0 asdqq.95.resolve.me. [9m59s] A 72.52.4.119 (53)
    172.18.0.4.48992 > 8.8.8.8.53: [bad udp cksum 0xbc64 -> 0x0dd4!] 4313+ AAAA? asdqq.96.resolve.me. (37)
    8.8.8.8.53 > 172.18.0.4.48992: [udp sum ok] 4313 q: AAAA? asdqq.96.resolve.me. 0/1/0 ns: asdqq.96.resolve.me. [29m59s] SOA ns1.sedoparking.com. hostmaster.sedo.de. 2015071001 86400 10800 604800 86400 (110)
    172.18.0.4.48992 > 8.8.8.8.53: [bad udp cksum 0xbc64 -> 0xe7d8!] 21972+ A? asdqq.92.resolve.me. (37)
    8.8.8.8.53 > 172.18.0.4.48992: [udp sum ok] 21972 q: A? asdqq.92.resolve.me. 1/0/0 asdqq.92.resolve.me. [9m59s] A 72.52.4.119 (53)
    172.18.0.4.48992 > 8.8.8.8.53: [bad udp cksum 0xbc64 -> 0x8510!] 39580+ AAAA? asdqq.95.resolve.me. (37)
    8.8.8.8.53 > 172.18.0.4.48992: [udp sum ok] 39580 q: AAAA? asdqq.95.resolve.me. 0/1/0 ns: asdqq.95.resolve.me. [29m59s] SOA ns1.sedoparking.com. hostmaster.sedo.de. 2015071001 86400 10800 604800 86400 (110)
    172.18.0.4.48992 > 8.8.8.8.53: [bad udp cksum 0xbc64 -> 0xc4f6!] 31158+ A? asdqq.91.resolve.me. (37)
    8.8.8.8.53 > 172.18.0.4.48992: [udp sum ok] 31158 q: A? asdqq.91.resolve.me. 1/0/0 asdqq.91.resolve.me. [9m59s] A 72.52.4.119 (53)
```

The following errors were caught during testing:

```
asdqq.98.resolve.me { Error: getaddrinfo EAI_AGAIN
    at Object.exports._errnoException (util.js:1007:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'asdqq.98.resolve.me' }
asdqq.97.resolve.me { Error: getaddrinfo EAI_AGAIN
    at Object.exports._errnoException (util.js:1007:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'asdqq.97.resolve.me' }
asdqq.100.resolve.me { Error: getaddrinfo EAI_AGAIN
    at Object.exports._errnoException (util.js:1007:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'asdqq.100.resolve.me' }
```

`100`, `97` and `98` threw EAI_AGAIN, but they weren't in `tcpdump`'s output. I waited 10 seconds after my test ran, they never showed up.

It would appear that the failed dns requests never left the container, or left in a malformed manner (not caught by `grep asdqq`).

**Comment by justincormack** [comment]
@randunel thanks, I will remove that tag, your data seems helpful.

**Comment by randunel** [comment]
I have something else to add, adding as a separate message because i think it's pretty relevant:

During `EAI_AGAIN`, all `dig` and `drill` requests work fine, instantly. The problem appears to be exclusive to `getaddrinfo`, no packets are sent when it is called.

**Comment by randunel** [comment]
As you can see (in my edited messages above), I can do both user space and kernel space traces in a relatively controlled environment. I've done traces on both alpine linux 3.4 and ubuntu 16.04, the behaviour is the same.

I can do more tracing and debugging if you need me to. Right now I think I've reached the limit of my knowledge, so I'll need instructions or assistance for anything more complicated than ftrace/strace/tcpdump.

**Comment by randunel** [comment]
Docker's `libnetwork` has a [hard limit](https://github.com/docker/libnetwork/blob/76a9472a78a7cc393529a34c03f9b527110b61bb/resolver.go#L481) of `100` concurrent dns requests.

It would appear that this is the cause of EAI_AGAIN, docker logs even show `More than 100 concurrent queries from [...]`.

While this limit is extremely low and non-configurable, network congestion also affects how quickly that limit is reached.

It looks like we're reaching the 100-concurrent-dns-requests-limit as a consequence of heavy network usage (100+ dns requests which take >1 second) and that is cause of the errors we're seeing.

**Comment by sanimej** [comment]
@randunel The limit of 100 concurrent queries was added in 1.11 release. In your test its possible you are hitting it when the DNS resolutions are slow. But first reporters of this EAI_AGAIN issue were using pre 1.11 releases. So I am not sure if the rate limiting of concurrent queries is the main root cause here.

**Comment by blacktop** [comment]
I have a networking noob question.  Can I capture traffic inside docker as fast as outside of docker?

`docker run --net=host tcpdump`

Should I expect dropped packets and if so is there anything I can do to not?  I have an application that needs to capture as fast as possible.

Thank you.

**Comment by thaJeztah** [comment]
@blacktop please do not ask unrelated questions on the issue tracker; for questions/discussions about using docker, try forums.docker.com, or the #docker IRC channel. The GitHub issue tracker is for tracking bugs.

**Comment by blacktop** [comment]
@thaJeztah I apologize. 😞

**Comment by Serfenia** [comment]
What's the current status of this issue and are there any possibilities in fixing it?

From my own experience I started seeing these errors when I had more then 10 docker containers up and running for a while. At the moment I am seeing these messages daily and the bigger my microservice network grows, the more errors of this kind I am seeing. (Docker 1.10.3 build 20f81dd)

**Comment by randunel** [comment]
We have upgraded to `1.12.0` and still experiencing these issues.

As a workaround, we have routed all of our external connections through proxies outside the swarm, ip-based connection.

We haven't been able to use anything that requires DNS resolution ever since we've switched our infrastructure to docker.

**Comment by ozlatkov** [comment]
Great troubleshooting, @randunel . Thanks a lot - helped me figure out the situation as we're also experienced absolutely the same situation with the very same straces/tcpdump captures as shown above. 

Anyone heard about any plans for having this addressed? 
Strange thing is that there are no updates from August,2016 considering that DNS resolution is so unreliable that it cannot be trusted at all.

**Comment by sanimej** [comment]
@randunel In the latest docker master I am not able to recreate this issue.. From a ubuntu container on a bridge network `for i in $(seq 1 100); do getent hosts asdqq.$i.resolve.me; done` works just fine. I tried few different public DNS servers. 

Are you seeing the problem only for these specific names or any external query returns the same error ?

**Comment by pleerock** [comment]
Suddenly I had same problem with node and redis, restarting docker service helped me.

**Comment by ParimiDev** [comment]
had same problem with docker 1.11.2 and only workaround was to reboot the node docker service did not make any difference.

with the upgrade to 1.12.4 reduced the frequency however it still happens frequent enough not able to use it in real prod. with the upgrade there is inconsistency with the workaround some times docker restart helps sometimes it doesn't 

this issues is not seen in net=host mode though.

**Comment by HudsonAkridge** [comment]
We're also experiencing a very similar issue between the bridge network. Several large requests will go through quickly, then the next one or two requests will hang for a long while trying to establish a connection to the other docker container, then my suspicion is something in docker is restarted or refreshed, and we get 5 or 6 more large requests through quickly, then another hang until the same restart point is reached.

Very cumbersome to deal with, and not something that restarting the docker daemon is acceptable for our situation to solve.

**Comment by westsouthnight** [comment]
+1 @HudsonAkridge have same network issues if send/receive a lot of packets. We always get in unexpected places when run the tests.

Dear @aboch and @thaJeztah, please if you can join to conversation. It very bad bug, and we sense that every day.

**Comment by rbranson** [comment]
FWIW we were able to eliminate DNS issues we had on larger machines that performed a high rate of DNS resolution by running a local cache (dnsmasq). It's been a few months, but I believe this was related to some kind of port exhaustion. These would stack up in the conntrack table and once hit 65Kish things would go south.

**Comment by ut0mt8** [comment]
Wow good to see this thread. I have  a kubernetes cluster which have the same problem from time to time....

**Comment by maxingchi** [comment]
have the same problem on `Docker version 17.06.0-ce, build 02c1d87`

**Comment by jcollum-cambia** [comment]
A coworker is seeing this problem, same version

```
$ docker --version
Docker version 17.06.0-ce, build 02c1d87
```

However I can build the image fine on my machine. We are both on Win 10, running Docker for Windows, same version.

**Comment by cristhianbicca** [comment]
I also have the same problem on my servers. 
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by vania-pooh** [comment]
Not sure guys if this is a good idea, but just noticed that setting `docker0` Mac-address to `eth0` value like described [here](http://backreference.org/2010/07/28/linux-bridge-mac-addresses-and-dynamic-ports/) dramatically improves network stuff. E.g. having `eth0      Link encap:Ethernet  HWaddr 00:15:b2:a9:8f:6e` I did:
```
# ip link set docker0 address 00:15:b2:a9:8f:6e
```
My environment:
```
root@selenium-cloud-m-6:~# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
In my case LRO was turned off. Hope it helps someone.

**Comment by eduardobcastro** [comment]
I'm experiencing about 30% retransmission between containers (I'm running 20 containers in the same network)
![image](https://user-images.githubusercontent.com/163576/98324454-0d7c3c80-1fcb-11eb-9a4b-7c969cf0421d.png)
Docker version 19.03.13, build 4484c46d9d

**Comment by abiralneupane2** [comment]
Docker version 20.10.22(windows)
I am trying to use docker as alternative for VMware and I am experiencing similar issue:
```
 $ docker run -i -t -p 8082:80 ubuntu /bin/bash
 $ apt update
```
 Takes too long saying [Waiting for headers]. Also when I try to ping archive.ubuntu.com or any other domain I get either 100% packet loss or 0%.
  Tried two fixes with no improvement
 1. set the mtu size 1400 for the container's network.
 2. disable the ICS tool from windows services.
