### ISSUE TITLE
Cannot kill any container

### ISSUE THREAD

**Issue by ChristopherBiscardi** [docker/docker#12973]
Using machine on OSX, I have come across a situation in which I can not kill any containers.

I've tried `docker-compose kill`, `docker kill`, and ssh'ing in to kill:
```
docker@dev:~$ sudo kill -9 3936
docker@dev:~$ ps aux | grep 3936
 3936 root     [bash]
```

`docker-compose kill` times out:

```
Killing mycontainer_dnsmasq_1...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 144, in kill
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 182, in kill
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 110, in kill
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.container", line 127, in kill
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.client", line 605, in kill
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.client", line 79, in _post
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 425, in post
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 383, in request
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 486, in send
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.adapters", line 387, in send
requests.exceptions.Timeout: HTTPSConnectionPool(host='192.168.99.100', port=2376): Read timed out.
```

`docker kill` just hangs while the daemon logs show:

```
time="2015-05-04T21:23:40Z" level=info msg="Container 075dc10bc089 failed to exit within 10 seconds of kill - trying direct SIGKILL"
```

[daemon output](https://gist.github.com/ChristopherBiscardi/c10837a605b569d72339)

`docker version`:
```
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): darwin/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

boot2docker version:
```
Boot2Docker version 1.6.0, build master : a270c71 - Thu Apr 16 19:50:36 UTC 2015
Docker version 1.6.0, build 4749651
```

`docker exec -it con bash` works before attempting a kill. After attempting a kill (which hangs), the following error is produced by `exec`:

```
Cannot run exec command 8e10389d95011c0dba33897612a27db4aff2540d1e6cc549046dbed7537fed5c in container 6a9dfbf9d373f19ee2cf8d1c13984e5d69a45183cfc39e81fd483a5e0267d7ba: [8] System error: exit status 1
Error starting exec command in container 8e10389d95011c0dba33897612a27db4aff2540d1e6cc549046dbed7537fed5c: Cannot run exec command 8e10389d95011c0dba33897612a27db4aff2540d1e6cc549046dbed7537fed5c in container 6a9dfbf9d373f19ee2cf8d1c13984e5d69a45183cfc39e81fd483a5e0267d7ba: [8] System error: exit status 1

```

**Comment by cpuguy83** [comment]
Is this still a problem?
Can you provide some repro steps?

**Comment by thaJeztah** [comment]
looks like this has gone stale, but comment and I'll reopen
