### ISSUE TITLE
overlay backend allows rmi on in-use layers

### ISSUE THREAD

**Issue by stevenschlansker** [docker/docker#13261]
We switched to overlay yesterday and are already seeing non-deterministic problem with the filesystem backend, across multiple containers and teams. Linux 4.0.2, docker 1.6.0, ext4 filesystem.  I initially thought this might be #11012, but since that was reported against XFS originally I decided to open my own issue.

We run Docker containers for our CI builds.  Immediately after we migrated to the overlay storage driver, we started to see problems:
```
++ cut -d . -f 1
./../otpl-deploy-scripts/bin/otpl-deploy: line 218: cut: command not found
```
```
[Step 2/5] jetbrains.buildServer.agent.runner.CannotBuildCommandLineException: Unable to find java executable at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    at jetbrains.buildServer.agent.runner.JavaCommandLineBuilder.buildPath2Java(JavaCommandLineBuilder.java:155)
    at jetbrains.buildServer.agent.runner.JavaCommandLineBuilder.build(JavaCommandLineBuilder.java:107)
```

Trying to enter the container, something is clearly fucked:
```
root@mesos-slave8-qa-uswest2:~# docker exec -it 0adffe3c5da6 /bin/bash
bash-4.3# ls
bash: ls: command not found
bash-4.3# echo *
*
bash-4.3# pwd
/
bash-4.3# /bin/ls
bash: /bin/ls: No such file or directory
bash-4.3# /bin/*
bash: /bin/*: No such file or directory
bash-4.3# find .
.
bash-4.3# bash  # NOTE HOW THIS SUCCEEDS
bash-4.3# exit
bash-4.3# ps
bash-4.3# find /bin/bash
/bin/bash
bash-4.3# find /bin
/bin
```

Looking from the outside in:
```
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay# cd 0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls
lower-id  merged  upper  work
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls merged/
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls upper/
dev  etc  home  mnt  run  tmp  var
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# find work
work
work/work
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# find merged
merged
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# find merged/
merged/
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls merged/
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# find upper
upper
upper/.dockerenv
upper/.dockerinit
upper/etc
upper/etc/hosts
upper/etc/mtab
...
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls -lh merged/bin/bash
-rwxr-xr-x 0 root root 998K Oct  7  2014 merged/bin/bash
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls -lh merged/bin/
total 0
```

I looked at the mapping, and wonder if it's something related to the absence of a `root` directory:

```
root@mesos-slave8-qa-uswest2:~# cat /proc/mounts  | grep 0adf
overlay /mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83/merged overlay rw,relatime,lowerdir=/mnt/docker/overlay/914daaa4ae3ecae1966c92ef38c62835f5f81fd75ae544409d099345e958c93a/root,upperdir=/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83/upper,workdir=/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83/work 0 0

root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls
lower-id  merged  upper  work
```

```
root@mesos-slave8-qa-uswest2:/# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

root@mesos-slave8-qa-uswest2:/# docker info
Containers: 40
Images: 360
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.0.2
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 29.45 GiB
Name: mesos-slave8-qa-uswest2
ID: NMLO:YQYU:3N53:LTCK:CBGB:LYIH:GHTZ:Y5ME:UIUZ:4IKD:VUWQ:BN2L
WARNING: No swap limit support

root@mesos-slave8-qa-uswest2:~# uname -a
Linux mesos-slave8-qa-uswest2 4.0.2 #1 SMP Tue May 12 23:29:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by stevenschlansker** [comment]
I wish I had reproduction steps, believe me...

**Comment by thaJeztah** [comment]
Thanks for reporting

/cc. @jfrazelle @crosbymichael might want to have a quick look for overlay.

**Comment by jfrazelle** [comment]
pinng @vbatts we may want to add this to our list of thinngs to fix before overlay is no. 1 :)

**Comment by stevenschlansker** [comment]
I now strongly suspect this is related to a missing `root` directory.  It happened again:

```
root@mesos-slave1-qa-uswest2:/mnt/docker/overlay/ee164b56ee9a99c663e4711f9efe615c8969d0935aacd39f297a3b7f9dc81171# cat /proc/mounts | grep ee164b56ee9a
overlay /mnt/docker/overlay/ee164b56ee9a99c663e4711f9efe615c8969d0935aacd39f297a3b7f9dc81171/merged overlay rw,relatime,lowerdir=/mnt/docker/overlay/24ac989500e74c921b46ab49b2b092c96878a058100caa28072e32990c89791d/root,upperdir=/mnt/docker/overlay/ee164b56ee9a99c663e4711f9efe615c8969d0935aacd39f297a3b7f9dc81171/upper,workdir=/mnt/docker/overlay/ee164b56ee9a99c663e4711f9efe615c8969d0935aacd39f297a3b7f9dc81171/work 0 0
root@mesos-slave1-qa-uswest2:/mnt/docker/overlay/ee164b56ee9a99c663e4711f9efe615c8969d0935aacd39f297a3b7f9dc81171# ls /mnt/docker/overlay/24ac989500e74c921b46ab49b2b092c96878a058100caa28072e32990c89791d/root
ls: cannot access /mnt/docker/overlay/24ac989500e74c921b46ab49b2b092c96878a058100caa28072e32990c89791d/root: No such file or directory
root@mesos-slave1-qa-uswest2:/mnt/docker/overlay/ee164b56ee9a99c663e4711f9efe615c8969d0935aacd39f297a3b7f9dc81171# cd ../
root@mesos-slave1-qa-uswest2:/mnt/docker/overlay# cd 24ac989500e74c921b46ab49b2b092c96878a058100caa28072e32990c89791d
-su: cd: 24ac989500e74c921b46ab49b2b092c96878a058100caa28072e32990c89791d: No such file or directory
```

**Comment by stevenschlansker** [comment]
And a smoking gun: our cleanup script is deleting the layer out from under the container!
```
Untagged: docker-pp-uswest2.otenv.com/gc-featuremanager:gc-featuremanager-209
Deleted: 24ac989500e74c921b46ab49b2b092c96878a058100caa28072e32990c89791d
```
That the Docker daemon allows you to delete an in-use layer is a *huge* problem.

**Comment by vbatts** [comment]
Woah wat. This doesn't seem right or is a regression.

**Comment by stevenschlansker** [comment]
Indeed, I can now do this, which did not work before on the `btrfs` or `devicemapper` backends:

```
root@mesos-slave1-qa-uswest2:/mnt/docker/overlay# docker ps | grep feature
354eb80340af        docker-pp-uswest2.otenv.com/gc-featuremanager:gc-featuremanager-209                                        "node fm-server.js"    21 hours ago        Up 21 hours                                   mesos-626b5438-d9db-4d53-a7b0-251f1b7f1679   
ee164b56ee9a        docker-ci-uswest2.otenv.com/gc-featuremanager:gc-featuremanager-209                                        "node fm-server.js"    21 hours ago        Up 21 hours                                   mesos-b24dd8b2-9a05-4520-a8a3-78e754b49a4f   
root@mesos-slave1-qa-uswest2:/mnt/docker/overlay# docker rmi -f docker-pp-uswest2.otenv.com/gc-featuremanager:gc-featuremanager-209
Untagged: docker-pp-uswest2.otenv.com/gc-featuremanager:gc-featuremanager-209
root@mesos-slave1-qa-uswest2:/mnt/docker/overlay# docker rmi -f docker-ci-uswest2.otenv.com/gc-featuremanager:gc-featuremanager-209
Untagged: docker-ci-uswest2.otenv.com/gc-featuremanager:gc-featuremanager-209
Deleted: 24ac989500e74c921b46ab49b2b092c96878a058100caa28072e32990c89791d
Deleted: 845054e95a2e16f6a55f67fde52550b7756ec609f8e0de44dc531fc651a8da86
Deleted: b86b04419bb464fb8d824e15375b704277832318570a564b3e78d55ef88f923d
Deleted: 3523eaa06072ccbb60337270c288e70000f73bea629d280d6e593a0f867b3e4e
Deleted: 3ed5bc67cec0a6db953334ef08b46ee116d1bb148426a31145b033a977e83b5d
Deleted: 9e2e6341c4f7db48919c7e29e19ed6dfeb3029f78f302c5607b3ea85430a3df2
Deleted: a0988a11a88009da80f69f60a69779d9409b5b18024095adc8b7f3bfc8206baa
root@mesos-slave1-qa-uswest2:/mnt/docker/overlay# docker ps | grep feature
354eb80340af        docker-pp-uswest2.otenv.com/gc-featuremanager:gc-featuremanager-209                                        "node fm-server.js"    21 hours ago        Up 21 hours                                   mesos-626b5438-d9db-4d53-a7b0-251f1b7f1679   
ee164b56ee9a        docker-ci-uswest2.otenv.com/gc-featuremanager:gc-featuremanager-209                                        "node fm-server.js"    21 hours ago        Up 21 hours                                   mesos-b24dd8b2-9a05-4520-a8a3-78e754b49a4f   
```

**Comment by stevenschlansker** [comment]
This is a serious issue for people trying to reclaim disk space.  It really highlights the lack of the proposed `docker clean` command to reclaim disk space.  I bet a lot of the homegrown hacks out there will start to exhibit similar problems...

We are now back to square zero with regards to our nodes filling up their disks endlessly with CI-built images.

**Comment by cpuguy83** [comment]
Isn't the purpose of the `-f` flag here to force the removal of the image regardless if a container i using it if the container using it is stopped?

**Comment by vbatts** [comment]
I'm not seeing the same behavior
```bash

vbatts@noyee ~ (master) $ docker info
Containers: 12
Images: 172
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.0.3-300.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 7.234 GiB
Name: noyee.usersys.redhat.com
ID: VG6V:7CTR:AU4V:JIWF:4WDU:Y2WP:XHMQ:4KZG:7YIU:CBPY:3LSG:DMF6
Debug mode (server): true
Debug mode (client): false
Fds: 22
Goroutines: 44
System Time: Thu May 21 11:07:39 EDT 2015
EventsListeners: 0
Init SHA1: 61b17d8393b7181419cbc5b3fc83ad452d0a82cc
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker
Username: vbatts
Registry: [https://index.docker.io/v1/]
vbatts@noyee ~ (master) $ docker version
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 97cd073
OS/Arch (client): linux/amd64
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 97cd073
OS/Arch (server): linux/amd64
vbatts@noyee ~ (master) $ docker run -t -d busybox top
a8a5aa91aeaceb48a566c8d29abe319ffc606ee1a5ea0fc29f09ecb76283bb38
vbatts@noyee ~ (master) $ docker ps 
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS               NAMES
a8a5aa91aeac        busybox:latest           "top"               2 seconds ago       Up 2 seconds                            sick_babbage
vbatts@noyee ~ (master) $ docker rmi busybox
Error response from daemon: Conflict, cannot delete 4986bf8c1536 because the running container a8a5aa91aeac is using it, stop it and use -f to force
FATA[0000] Error: failed to remove one or more images   
vbatts@noyee ~ (master) $ docker rmi -f busybox
Error response from daemon: Conflict, cannot force delete 4986bf8c1536 because the running container a8a5aa91aeac is using it, stop it and retry
FATA[0000] Error: failed to remove one or more images 
```

even `-f` fails due to the container using it...

**Comment by cpuguy83** [comment]
Indeed for me, -f fails if the container is running, it allows the removal if the container is not running.

**Comment by stevenschlansker** [comment]
We are forced to use `-f` because of the following error message:
```
Error response from daemon: Conflict, cannot delete image 34f0138c2fbd because it is tagged in multiple repositories, use -f to force
```
Since we use regional mirrors, and docker *still* has no client side registry mirror fallback (https://github.com/docker/docker/pull/9161), we must tag all our images in each region we wish to pull from.  We are a global org and constantly pulling images from California to London seriously taxes our WAN links.

So all our images are tagged in multiple repositories.  So nothing will ever get deleted if we do not use `-f` :(

**Comment by stevenschlansker** [comment]
I upgraded to 1.6.2:
```
root@mesos-slave1-qa-uswest2:~# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```
and retried:
```
root@mesos-slave1-qa-uswest2:~# docker rmi -f docker-ci-uswest2.otenv.com/shardkeygenerator-server:shardkeygenerator-server_teamcity_37
Error response from daemon: Conflict, cannot force delete 3e17baa2fbb1 because the running container 03322bdee759 is using it, stop it and retry
```

So it seems this affects 1.6.0 but not 1.6.2

**Comment by vbatts** [comment]
so this is a non-issue now?

On Thu, May 21, 2015 at 2:29 PM, Steven Schlansker <notifications@github.com

**Comment by stevenschlansker** [comment]
Seems so.  But anyone who uses 1.6.0 is in for a surprise...

**Comment by vbatts** [comment]
fair. thanks.

On Thu, May 21, 2015 at 3:02 PM, Steven Schlansker <notifications@github.com

**Comment by stevenschlansker** [comment]
Okay, we are now reproducing the same issue on docker 1.6.2:

```
root@mesos-slave1-qa-uswest2:~# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

```
root@mesos-slave1-qa-uswest2:~# docker exec -it fe654fe63fb9 /bin/bash
exec: "/bin/bash": stat /bin/bash: no such file or directory
Cannot run exec command bee0e7367908ea56b2287540840ce4351bcd68aa966ec81966687c5524124e43 in container fe654fe63fb947d7b41fbb9a7be5a3f654b8bcca79bc08979dd4eca373c6fb3a: [8] System error: exec: "/bin/bash": stat /bin/bash: no such file or directory

root@mesos-slave1-qa-uswest2:/mnt/docker/overlay/fe654fe63fb947d7b41fbb9a7be5a3f654b8bcca79bc08979dd4eca373c6fb3a# cat /proc/mounts | grep fe654fe63fb9
overlay /mnt/docker/overlay/fe654fe63fb947d7b41fbb9a7be5a3f654b8bcca79bc08979dd4eca373c6fb3a/merged overlay rw,relatime,lowerdir=/mnt/docker/overlay/24ac989500e74c921b46ab49b2b092c96878a058100caa28072e32990c89791d/root,upperdir=/mnt/docker/overlay/fe654fe63fb947d7b41fbb9a7be5a3f654b8bcca79bc08979dd4eca373c6fb3a/upper,workdir=/mnt/docker/overlay/fe654fe63fb947d7b41fbb9a7be5a3f654b8bcca79bc08979dd4eca373c6fb3a/work 0 0

root@mesos-slave1-qa-uswest2:/mnt/docker/overlay/fe654fe63fb947d7b41fbb9a7be5a3f654b8bcca79bc08979dd4eca373c6fb3a# ls /mnt/docker/overlay/24ac989500e74c921b46ab49b2b092c96878a058100caa28072e32990c89791d
ls: cannot access /mnt/docker/overlay/24ac989500e74c921b46ab49b2b092c96878a058100caa28072e32990c89791d: No such file or directory
```

**Comment by mountkin** [comment]
It's probably a bug of the rmi API. I submitted a PR #14578
I can reproduce this problem consitently with the following script:
```bash
#!/bin/bash
# Build 2 images for testing.
echo -e "FROM busybox\nRUN echo a"|docker build -t test1 -
echo -e "FROM busybox\nRUN echo b"|docker build -t test2 -

# First let's start a long-running container.
docker run -d test1 sleep 300

# Create another container and force remove its image.
docker run --name=TEST2 test2 true
docker rmi -f test2

# At this point the images of any running containers that were created
# before TEST2 can be removed regardless of the -f flag.
docker rmi test1
```
