### ISSUE TITLE
Random network panic in 1.7

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#13436]
I'm running f83073d3eb23a3f3c22bef9401090df5da53cc2f with `docker -d -b none`.  On container start it does this.

```
INFO[0001] POST /containers/create?hostconfig=%7B%22Binds%22%3A%5B%22%2Fdev%3A%2Fhost%2Fdev%22%2C%22%2Flib%2Fmodules%3A%2Flib%2Fmodules%22%2C%22%2Flib%2Ffirmware%3A%2Flib%2Ffirmware%22%5D%2C%22Privileged%22%3Atrue%2C%22NetworkMode%22%3A%22host%22%2C%22RestartPolicy%22%3A%7B%7D%2C%22LogConfig%22%3A%7B%22Type%22%3A%22json-file%22%7D%7D&name=udev 
INFO[0001] POST /containers/3093e640d9666474febb6616b5a1d3dcd87993b04612ab685d2833079b28f274/start 
WARN[0001] IPv4 forwarding is disabled. Networking will not work 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x4c8380]

goroutine 133 [running]:
github.com/docker/docker/daemon.(*Container).ReleaseNetwork(0xc2081001e0)
	/go/src/github.com/docker/docker/daemon/container_linux.go:913 +0xc0
github.com/docker/docker/daemon.(*Container).cleanup(0xc2081001e0)
	/go/src/github.com/docker/docker/daemon/container.go:338 +0x33
github.com/docker/docker/daemon.(*containerMonitor).Close(0xc2081879d0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/monitor.go:86 +0x4a
github.com/docker/docker/daemon.func·031()
	/go/src/github.com/docker/docker/daemon/monitor.go:117 +0xbe
github.com/docker/docker/daemon.(*containerMonitor).Start(0xc2081879d0, 0x7ffad7192f40, 0xc20821dfa0)
	/go/src/github.com/docker/docker/daemon/monitor.go:145 +0x4f6
github.com/docker/docker/daemon.*containerMonitor.Start·fm(0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:703 +0x39
github.com/docker/docker/pkg/promise.func·001()
	/go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x2f
created by github.com/docker/docker/pkg/promise.Go
	/go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0xfb
```

**Comment by ibuildthecloud** [comment]
I did notice this warning `IPv4 forwarding is disabled. Networking will not work`.  Didn't docker 1.6 automatically turn on forwarding?  Is that behaviour changed now?

**Comment by ibuildthecloud** [comment]
Oh wait, I'm guess it isn't turned on because I'm running with `-b none`.  If I had bridge enable I'm assuming it will set it.

**Comment by mavenugo** [comment]
@ibuildthecloud yes. if -b is set to `none`, then the bridge driver will not be initialized. 
The ipv4 forwarding is enabled only if the bridge driver is enabled. That is expected.

**Comment by mavenugo** [comment]
@ibuildthecloud but still, the panic is unexpected. will check on this scenario with `-b=none`

**Comment by LK4D4** [comment]
I think `-b none` doesn't work at all. I fixed panic locally, but seems like execdriver still expects `NamespacePath` even with `DisabledNetwork`.

**Comment by LK4D4** [comment]
I think I've fixed it, I'll post PR tomorrow morning.

**Comment by mavenugo** [comment]
Thanks @LK4D4
