### ISSUE TITLE
--daemon --log-level=panic panic

### ISSUE THREAD

**Issue by vieux** [docker/docker#13708]
Hello,

Using  `--daemon --log-level=panic` with the last RC produce a panic.

```
$ ./docker-1.7.0-rc1  --daemon --log-level=panic
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40c1de]

goroutine 1 [running]:
main.func·002()
	/go/src/github.com/docker/docker/docker/daemon.go:103 +0xfe
main.mainDaemon()
	/go/src/github.com/docker/docker/docker/daemon.go:158 +0x1352
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:92 +0x6b4

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [runnable]:
text/template/parse.lexText(0xc208030500, 0xf38af8)
	/usr/local/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc208030500)
	/usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:191 +0x1ac

goroutine 9 [runnable]:
main.func·003()
	/go/src/github.com/docker/docker/docker/daemon.go:128
created by main.mainDaemon
	/go/src/github.com/docker/docker/docker/daemon.go:135 +0x6bc
```

**Comment by crosbymichael** [comment]
I think this is kinda expected becuase the loggers will not be hit unless they are `logrus.Panic` so any Fatals will never be executed so the exit(1)'s are not hit, and nil pointers and all kinds of fun will happen.

**Comment by icecrime** [comment]
I'm not reproducing: I get no logs when running with `--log-level=panic`, but no panic neither.

**Comment by duglin** [comment]
Don't recall seeing any logrus calls before we panic :-)

**Comment by vieux** [comment]
Ok, so thanks to @jfrazelle I understand this is expected, but think I think we should update logrus to include this commit https://github.com/Sirupsen/logrus/commit/fdae7ddaf512415df63fb429b97545928641c657 so the error will be cleaner.

**Comment by icecrime** [comment]
Thanks! Closing this one.
