### ISSUE TITLE
Failed push to registry results in panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lcwill** [docker/docker#13949]
I'm running Docker 1.4.1 on Ubuntu 12.04.5. The Docker daemon crashed with the following error stack after a failed PUT (image push) to an internal registry:
```
[1448462] rendered layer for 472161343ab3113739b457ab8b78c6c07c480ce15ca5e1e4e0ae8c13d3297de5 of [1579414528] size
[1448462] [registry] Calling PUT http://internal-registry.net/v1/images/472161343ab3113739b457ab8b78c6c07c480ce15ca5e1e4e0ae8c13d3297de5/layer
[1448462] http://internal-registry.net/v1/images/472161343ab3113739b457ab8b78c6c07c480ce15ca5e1e4e0ae8c13d3297de5/layer -- HEADERS: map[User-Agent:[docker/1.4.1 go/go1.3.3 git-commit/5bc2ff8 kernel/3.13.0-43-generic os/linux arch/amd64]]
Received HTTP code 409 while uploading layer: {"error": "Image already exists"}
[1448462] -job push(internal-registry.net/hbapi_22_tendril_scripts.setup_packages) = ERR (1)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x70645c]
 
goroutine 248636 [running]:
runtime.panic(0xbe5c40, 0x127da13)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
bufio.(*Writer).flush(0xc20a82e340, 0x0, 0x0)
        /usr/local/go/src/pkg/bufio/bufio.go:530 +0xdc
bufio.(*Writer).Flush(0xc20a82e340, 0x0, 0x0)
        /usr/local/go/src/pkg/bufio/bufio.go:519 +0x39
net/http.(*response).Flush(0xc20df7f0e0)
        /usr/local/go/src/pkg/net/http/server.go:1023 +0x4c
github.com/docker/docker/utils.(*WriteFlusher).Write(0xc20b147b30, 0xc209b46140, 0xd0, 0x13d, 0xd0, 0x0, 0x0)
        /go/src/github.com/docker/docker/utils/utils.go:265 +0x142
github.com/docker/docker/engine.(*Output).Write(0xc208e1d5c0, 0xc209b46140, 0xd0, 0x13d, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/engine/streams.go:90 +0x183
github.com/docker/docker/utils.(*WriteFlusher).Write(0xc2095f0fc0, 0xc209b46140, 0xd0, 0x13d, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/utils/utils.go:264 +0xf4
github.com/docker/docker/utils.(*WriteFlusher).Write(0xc20a1e86c0, 0xc209b46140, 0xd0, 0x13d, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/utils/utils.go:264 +0xf4
github.com/docker/docker/utils.(*WriteFlusher).Write(0xc2087f04e0, 0xc209b46140, 0xd0, 0x13d, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/utils/utils.go:264 +0xf4
github.com/docker/docker/utils.(*progressReader).Read(0xc20b1a6800, 0xc20dcd4000, 0x8000, 0x8000, 0x41eac2, 0x7f4ec3737f00, 0xc20892b9e0)
        /go/src/github.com/docker/docker/utils/progressreader.go:31 +0x2a9
github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar.(*regFileReader).Read(0xc2097687c0, 0xc20dcd4000, 0x8000, 0x8000, 0xc, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar/reader.go:748 +0xd8
github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar.(*Reader).Read(0xc2083a86c0, 0xc20dcd4000, 0x8000, 0x8000, 0x419bb4, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar/reader.go:733 +0xa4
github.com/docker/docker/pkg/tarsum.(*tarSum).Read(0xc20d3a8c30, 0xc20dccc000, 0x8000, 0x8000, 0x5dfd1f, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/tarsum/tarsum.go:152 +0x162
io.(*teeReader).Read(0xc20ad3d960, 0xc20dccc000, 0x8000, 0x8000, 0xaac3c0, 0x0, 0x0)
        /usr/local/go/src/pkg/io/io.go:486 +0x8d
io/ioutil.(*nopCloser).Read(0xc2082dd2b0, 0xc20dccc000, 0x8000, 0x8000, 0x2a16, 0x0, 0x0)
        <autogenerated>:4 +0x7b
io.Copy(0x7f4ec0278f78, 0xc2082dd930, 0x7f4ec0276b18, 0xc2082dd2b0, 0xfadc, 0x0, 0x0)
        /usr/local/go/src/pkg/io/io.go:353 +0x1f3
net/http.(*transferWriter).WriteBody(0xc20d39dc00, 0x7f4ec374c9a0, 0xc20acc5c00, 0x0, 0x0)
        /usr/local/go/src/pkg/net/http/transfer.go:202 +0x208
net/http.(*Request).write(0xc20d3a8d00, 0x7f4ec374c9a0, 0xc20acc5c00, 0xc20af68c00, 0xc2087f0a80, 0x0, 0x0)
        /usr/local/go/src/pkg/net/http/request.go:435 +0x90e
net/http.(*persistConn).writeLoop(0xc20cf37130)
        /usr/local/go/src/pkg/net/http/transport.go:891 +0x214
created by net/http.(*Transport).dialConn
        /usr/local/go/src/pkg/net/http/transport.go:601 +0x957
```

Full stack trace: http://pastebin.com/XX9UwukQ

Docker + System Info:
```
$ docker --version
Docker version 1.4.1, build 5bc2ff8

$ docker info
Containers: 67
Images: 123
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 257
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 12
Total Memory: 62.86 GiB
Name: 164.internal-host
ID: NLKS:FCRA:LEVZ:UEIE:RUKO:5ZRR:UJ76:MXFG:NBSS:YY7J:J4OX:MYJW
Debug mode (server): true
Debug mode (client): false
Fds: 480
Goroutines: 348
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker

$ uname -a
Linux 164.internal-host 3.13.0-43-generic #72~precise1-Ubuntu SMP Tue Dec 9 12:14:18 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```

This looks very similar to the issue reported in #6978, but I do not currently have a way to reliably reproduce this. If necessary though, I can try to come up with a set of steps to reproduce.

**Comment by unclejack** [comment]
Wasn't this fixed in one of the following releases? 1.4.1 is a pretty old version of Docker.

**Comment by lcwill** [comment]
@unclejack, do you know which commit(s) may have fixed this?

**Comment by ralph-tice** [comment]
I had this same problem but on a `docker pull` that was implicitly started by `docker run ... non_local_image:master` from a private registry.

```
$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
$ docker info
Containers: 148
Images: 673
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 975
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5-boot2docker
Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
CPUs: 4
Total Memory: 7.79 GiB
Name: boot2docker
ID: G7DA:LJS5:34IU:P2SA:2XK7:EA3F:IXWY:YMFV:42DO:KD6P:JR7S:7W36
Debug mode (server): true
File Descriptors: 37
Goroutines: 28
System Time: 2015-07-21T17:06:16.556581577Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
```

full stack trace here http://pastebin.com/HRJsqxcJ

**Comment by aaronlehmann** [comment]
I believe this panic was fixed by https://github.com/docker/docker/pull/15353. The issue was that some downloads would continue running after another download failed. The failure would cause the HTTP server to return a response, and then the ongoing downloads would try to write to the HTTP server's response buffer, which results in a panic.

Closing for now, please reopen if you see this in 1.8.x.
