### ISSUE TITLE
Slice bounds out of range

### ISSUE THREAD

**Issue by claubrz** [docker/docker#14007]
Hi guys,
i'm trying to run mezzanine inside a docker container and I get always that error. Any idea about what is going wrong?

Thanks.
```
goroutine 12 [running]:
bufio.(*Reader).fill(0xc082142360)
        /usr/local/go/src/bufio/bufio.go:86 +0x2e2
bufio.(*Reader).WriteTo(0xc082142360, 0x2624c8, 0xc08200a4b0, 0x18c1, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:449 +0x285
io.Copy(0x2624c8, 0xc08200a4b0, 0x264920, 0xc082142360, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:354 +0xb9
github.com/docker/docker/api/client.func┬À022(0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/hijack.go:210 +0x1e0
github.com/docker/docker/pkg/promise.func┬À001()
        /go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x36
created by github.com/docker/docker/pkg/promise.Go
        /go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x102

goroutine 1 [chan receive]:
github.com/docker/docker/api/client.(*DockerCli).CmdRun(0xc08205f220, 0xc082012090, 0x5, 0x5, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/commands.go:2469 +0xfcd
reflect.callMethod(0xc0820b51d0, 0xc082045be8)
        /usr/local/go/src/reflect/value.go:605 +0x180
reflect.methodValueCall(0xc082012090, 0x5, 0x5, 0x1, 0xc0820b51d0, 0xc08205f201, 0xc082072240, 0x5, 0xc08200a401, 0x255790, ...)
        /usr/local/go/src/reflect/asm_amd64.s:29 +0x3d
github.com/docker/docker/api/client.(*DockerCli).Cmd(0xc08205f220, 0xc082012080, 0x6, 0x6, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/cli.go:81 +0x385
main.main()
        /go/src/github.com/docker/docker/docker/docker.go:138 +0xb90

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x26
created by os/signal.init┬À1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x3c

goroutine 11 [chan receive]:
github.com/docker/docker/api/client.(*DockerCli).hijack(0xc08205f220, 0x898b90, 0x4, 0xc082140500, 0x76, 0x1, 0x262498, 0xc08200aaf0, 0x2624c8, 0xc08200a4b0, ...)
        /go/src/github.com/docker/docker/api/client/hijack.go:237 +0xd38
github.com/docker/docker/api/client.func┬À013(0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/commands.go:2437 +0x1c9
github.com/docker/docker/pkg/promise.func┬À001()
        /go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x36
created by github.com/docker/docker/pkg/promise.Go
        /go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x102

goroutine 9 [IO wait]:
net.(*pollDesc).Wait(0xc0820b6170, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082042380, 0xc0820b6060, 0x89b3f0, 0x7, 0x97d8c0, 0x91, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820b6000, 0xc0820ba000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082042398, 0xc0820ba000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xe3
crypto/tls.(*block).readFromUntil(0xc0820ca960, 0x263e68, 0xc082042398, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:454 +0xed
crypto/tls.(*Conn).readRecord(0xc08207c580, 0x17, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:539 +0x2e1
crypto/tls.(*Conn).Read(0xc08207c580, 0xc082011000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:904 +0x16d
net/http.noteEOFReader.Read(0x2646e0, 0xc08207c580, 0xc0820fc3c8, 0xc082011000, 0x1000, 0x1000, 0xc08206ea80, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x75
net/http.(*noteEOFReader).Read(0xc08202e400, 0xc082011000, 0x1000, 0x1000, 0xc082014000, 0x0, 0x0)
        <autogenerated>:125 +0xdb
bufio.(*Reader).fill(0xc082142300)
        /usr/local/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).Peek(0xc082142300, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf7
net/http.(*persistConn).readLoop(0xc0820fc370)
        /usr/local/go/src/net/http/transport.go:842 +0xab
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xca6

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc0820fc370)
        /usr/local/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcc3

goroutine 14 [sleep]:
github.com/docker/docker/api/client.func┬À025()
        /go/src/github.com/docker/docker/api/client/utils.go:286 +0x69
created by github.com/docker/docker/api/client.(*DockerCli).monitorTtySize
        /go/src/github.com/docker/docker/api/client/utils.go:295 +0x163
```

**Comment by claubrz** [comment]
Docker version:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): windows/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

Docker info:

Containers: 144
Images: 123
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 411
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 2
Total Memory: 1.957 GiB
Name: boot2docker
ID: OPAM:ZVLV:SFU3:7Q26:ULV5:THYB:XLSY:7FRS:HYIK:LODB:QKA5:KVPI
Debug mode (server): true
Debug mode (client): false
Fds: 19
Goroutines: 32
System Time: Thu Jun 18 11:20:19 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker

Uname -a :
$ uname -a
MINGW32_NT-6.1 PC-084707 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown


Steps to reproduce:
###############################################################
# Dockerfile to build mezzanine environment and run python app.
# Based on python2.7
################################################################

# Set the base image to python2.7 
FROM python:2.7

# Update the repository sources list
RUN apt-get update

#instalar dependecias mezzanine
#RUN apt-get install -y libjpeg8 libjpeg8-dev
#RUN apt-get build-dep -y python-imaging

#instalar mezzanine
RUN pip install mezzanine

EXPOSE 8000

####fin Dockerfile ########

2. After, that we build the image and launch it:
docker run -i -t python/mezz bash

3. mezzanine-project proy
4. python manage.db createdb
5. python manage.db runserver

Expected result: a python app running on localhost:8000
Received result: the error posted before.

Adittional info: 
First time I run the server it works, but if I close it and stop the cointainer, and run it againt it does'nt

**Comment by claubrz** [comment]
Plase close, same error as #13299
