### ISSUE TITLE
Overlay networking driver not working on linux kernel 3.13

### ISSUE THREAD

**Issue by jgkamat** [docker/docker#14145]
Description of problem:
I was trying out the new overlay driver on a single node, and I cant seem to get it to work, even in this minimal setting.

`docker version`:
```
Client version: 1.8.0-dev
Client API version: 1.20
Go version (client): go1.4.2
Git commit (client): f39b9a0
OS/Arch (client): linux/amd64
Experimental (client): true
Server version: 1.8.0-dev
Server API version: 1.20
Go version (server): go1.4.2
Git commit (server): f39b9a0
OS/Arch (server): linux/amd64
Experimental (server): true
```

`docker info`:
```
Containers: 6
Images: 10
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 2
Total Memory: 3.661 GiB
Name: mechjeb-1
ID: 3L3K:3ORR:P2HX:WP7B:5WK2:ZB7C:O7EL:4YHF:C3A7:RVML:RQXR:735C
WARNING: No swap limit support
Experimental: true
```

`uname -a`:
`Linux mechjeb-1 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):
AWS Instance, created with cloudcat, running ubuntu 14.04.

How reproducible:
Always

Steps to Reproduce:
1. Start consul
2. Start docker daemon requesting use of overlay driver and using consul
3. Run `docker run -ti busybox`

Actual Results:
I ran `docker run -ti busybox` twice. In the daemon logs. The stacktrace in the daemon logs seem to occur on the second run.
Consul:
```
root@mechjeb-1:~# ./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul2
==> WARNING: BootstrapExpect Mode is specified as 1; this is the same as Bootstrap mode.
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
         Node name: 'mechjeb-1'
        Datacenter: 'dc1'
            Server: true (bootstrap: true)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 172.26.19.195 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2015/06/23 16:17:59 [INFO] serf: EventMemberJoin: mechjeb-1 172.26.19.195
    2015/06/23 16:17:59 [INFO] serf: EventMemberJoin: mechjeb-1.dc1 172.26.19.195
    2015/06/23 16:17:59 [INFO] raft: Node at 172.26.19.195:8300 [Follower] entering Follower state
    2015/06/23 16:17:59 [INFO] consul: adding server mechjeb-1 (Addr: 172.26.19.195:8300) (DC: dc1)
    2015/06/23 16:17:59 [INFO] consul: adding server mechjeb-1.dc1 (Addr: 172.26.19.195:8300) (DC: dc1)
    2015/06/23 16:17:59 [ERR] agent: failed to sync remote state: No cluster leader
    2015/06/23 16:18:01 [WARN] raft: Heartbeat timeout reached, starting election
    2015/06/23 16:18:01 [INFO] raft: Node at 172.26.19.195:8300 [Candidate] entering Candidate state
    2015/06/23 16:18:01 [INFO] raft: Election won. Tally: 1
    2015/06/23 16:18:01 [INFO] raft: Node at 172.26.19.195:8300 [Leader] entering Leader state
    2015/06/23 16:18:01 [INFO] consul: cluster leadership acquired
    2015/06/23 16:18:01 [INFO] consul: New leader elected: mechjeb-1
    2015/06/23 16:18:01 [INFO] raft: Disabling EnableSingleNode (bootstrap)
    2015/06/23 16:18:01 [INFO] consul: member 'mechjeb-1' joined, marking health alive
    2015/06/23 16:18:02 [INFO] agent: Synced service 'consul'
```
Daemon:
```
root@mechjeb-1:~# docker -d --default-network overlay:multihost2 --kv-store consul:localhost:8500 
WARN[0000] Running experimental build                   
INFO[0000] [graphdriver] using prior storage driver "aufs" 
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1 
2015/06/23 16:18:06 [INFO] serf: EventMemberJoin: mechjeb-1 172.26.19.195
WARN[0000] Your kernel does not support swap memory limit. 
INFO[0000] Loading containers: start.                   
............
INFO[0000] Loading containers: done.                    
INFO[0000] Daemon has completed initialization          
INFO[0000] Docker daemon                                 commit=f39b9a0 execdriver=native-0.2 graphdriver=aufs version=1.8.0-dev
INFO[0002] GET /v1.20/containers/json                   
INFO[0005] GET /v1.20/info                              
INFO[0007] GET /v1.20/version                           
INFO[0017] POST /v1.20/containers/create                
INFO[0017] POST /v1.20/containers/d5658dc93c54fb5f055f75086ec1dbda6a247ac2c54bf269f138c9681edc7033/attach?stderr=1&stdin=1&stdout=1&stream=1 
INFO[0017] POST /v1.20/containers/d5658dc93c54fb5f055f75086ec1dbda6a247ac2c54bf269f138c9681edc7033/start 
ERRO[0017] Leave all failed for  d5658dc93c54fb5f055f75086ec1dbda6a247ac2c54bf269f138c9681edc7033: could not find sandbox for container id d5658dc93c54fb5f055f75086ec1dbda6a247ac2c54bf269f138c9681edc7033 
ERRO[0017] Handler for POST /containers/{name:.*}/start returned error: Cannot start container d5658dc93c54fb5f055f75086ec1dbda6a247ac2c54bf269f138c9681edc7033: network sandbox join failed: error creating vxlan interface: file exists 
ERRO[0017] HTTP Error                                    err=Cannot start container d5658dc93c54fb5f055f75086ec1dbda6a247ac2c54bf269f138c9681edc7033: network sandbox join failed: error creating vxlan interface: file exists statusCode=500
INFO[0021] POST /v1.20/containers/create                
INFO[0022] POST /v1.20/containers/e0933ea709135f44b6339df864338f85824481b708aeb7d1f2c4c15e9c4f8248/attach?stderr=1&stdin=1&stdout=1&stream=1 
INFO[0022] POST /v1.20/containers/e0933ea709135f44b6339df864338f85824481b708aeb7d1f2c4c15e9c4f8248/start 
2015/06/23 16:18:28 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 126 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/libnetwork/drivers/overlay.(*driver).Join(0xc208218b40, 0xc20836e4c0, 0x40, 0xc20829c380, 0x40, 0xc2082abd10, 0x22, 0x7fecca0e1bc8, 0xc208076fc0, 0xc2082abc20, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/drivers/overlay/joinleave.go:40 +0x561
github.com/docker/libnetwork.(*endpoint).Join(0xc208076fc0, 0xc208312000, 0x40, 0xc20829ce40, 0x5, 0x8, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:397 +0x786
github.com/docker/docker/daemon.(*Container).configureNetwork(0xc208113c20, 0x7fff31ce88da, 0xa, 0xc2082fb2e0, 0xc, 0x7fff31ce88d2, 0x7, 0xc2082fb201, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_linux.go:867 +0x467
github.com/docker/docker/daemon.(*Container).AllocateNetwork(0xc208113c20, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_linux.go:821 +0x4bc
github.com/docker/docker/daemon.(*Container).initializeNetworking(0xc208113c20, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_linux.go:918 +0x52c
github.com/docker/docker/daemon.(*Container).Start(0xc208113c20, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:255 +0x1cf
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc2080a47e0, 0xc2082e3197, 0x40, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/start.go:35 +0x24c
github.com/docker/docker/api/server.(*Server).postContainersStart(0xc208037140, 0xc2082e3187, 0x4, 0x7fecca0dd088, 0xc2082f72c0, 0xc2081aa4e0, 0xc208323650, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:1031 +0x162
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.postContainersStart)·fm(0xc2082e3187, 0x4, 0x7fecca0dd088, 0xc2082f72c0, 0xc2081aa4e0, 0xc208323650, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:1544 +0x7b
github.com/docker/docker/api/server.func·008(0x7fecca0dd088, 0xc2082f72c0, 0xc2081aa4e0)
	/go/src/github.com/docker/docker/api/server/server.go:1495 +0xbe5
net/http.HandlerFunc.ServeHTTP(0xc2080fbb00, 0x7fecca0dd088, 0xc2082f72c0, 0xc2081aa4e0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080ab770, 0x7fecca0dd088, 0xc2082f72c0, 0xc2081aa4e0)
	/go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2081f2fc0, 0x7fecca0dd088, 0xc2082f72c0, 0xc2081aa4e0)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2082f6a00)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
INFO[0680] GET /v1.20/containers/json
```
Client:
```
root@mechjeb-1:~# docker run -ti busybox
Error response from daemon: Cannot start container d5658dc93c54fb5f055f75086ec1dbda6a247ac2c54bf269f138c9681edc7033: network sandbox join failed: error creating vxlan interface: file exists
root@mechjeb-1:~# docker run -ti busybox
Post http:///var/run/docker.sock/v1.20/containers/e0933ea709135f44b6339df864338f85824481b708aeb7d1f2c4c15e9c4f8248/start: EOF. Are you trying to connect to a TLS-enabled daemon without TLS?
root@mechjeb-1:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

Expected Results:
Normal execution of docker run.

Additional info:
I'm running the dev build on 6-23-15. I'm not sure if I created the consul store correctly, so that could be it. I seem to have the same problem when following [the multihost swarm guide](https://github.com/docker/docker/blob/master/experimental/compose_swarm_networking.md). For that, I replaced the digitalocean driver with the generic driver, if that makes a difference.

Running the daemon without `--default-network overlay:multihost2` works fine.

I'm happy to provide any more information! =)

**Comment by mavenugo** [comment]
@jgkamat Overlay driver requires the following labels to be passed as well (as mentioned in the guide)

   on all nodes : `-label="com.docker.network.driver.overlay.bind_interface=eth0"`
   on all nodes except the first node : `-label="com.docker.network.driver.overlay.neighbor_ip=$(docker-machine ip swarm-0)"`

Can you please try this out ?

**Comment by jgkamat** [comment]
This is what i'm getting when I try running the daemon with the flag you suggested. I've been trying to get this to work on a single machine, does the overlay driver not support that currently?

Daemon:
```
root@mechjeb:~# docker -d --default-network overlay:multihost2 --kv-store 
consul:localhost:8500 
--label="com.docker.network.driver.overlay.bind_interface=eth0"
WARN[0000] Running experimental build                   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
INFO[0000] [graphdriver] using prior storage driver "aufs" 
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit 
status 1 
2015/06/23 19:50:30 [INFO] serf: EventMemberJoin: mechjeb
172.26.16.154
WARN[0000] Your kernel does not support swap memory limit. 
INFO[0000] Loading containers: start.                   

INFO[0000] Loading containers: done.                    
INFO[0000] Daemon has completed initialization          
INFO[0000] Docker daemon                                 commit=f39b9a0 
execdriver=native-0.2 graphdriver=aufs version=1.8.0-dev
INFO[0005] POST /v1.20/containers/create                
ERRO[0005] Handler for POST /containers/create returned error: No such image: 
busybox (tag: latest) 
ERRO[0005] HTTP Error                                    err=No such image: 
busybox (tag: latest) statusCode=404
INFO[0005] POST /v1.20/images/create?fromImage=busybox&tag=latest 
INFO[0010] Image manifest for busybox:latest has been verified 
INFO[0011] POST /v1.20/containers/create                
INFO[0011] POST 
/v1.20/containers/
7d3daba29ec003704b5ca332f3ecc53a0bf4318b7509b5f471b4181ff9c8d401/attach?stderr=1
&stdin=1&stdout=1&stream=1 
INFO[0011] POST 
/v1.20/containers/
7d3daba29ec003704b5ca332f3ecc53a0bf4318b7509b5f471b4181ff9c8d401/start 
ERRO[0011] Leave all failed for  
7d3daba29ec003704b5ca332f3ecc53a0bf4318b7509b5f471b4181ff9c8d401: could not find 
sandbox for container id 
7d3daba29ec003704b5ca332f3ecc53a0bf4318b7509b5f471b4181ff9c8d401 
ERRO[0011] Handler for POST /containers/{name:.*}/start returned error: Cannot 
start container 
7d3daba29ec003704b5ca332f3ecc53a0bf4318b7509b5f471b4181ff9c8d401: network 
sandbox join failed: could not add vxlan interface inside the network sandbox: 
failed in prefunc: failed to set namespace on link "vxland88a753": invalid 
argument 
ERRO[0011] HTTP Error                                    err=Cannot start 
container 7d3daba29ec003704b5ca332f3ecc53a0bf4318b7509b5f471b4181ff9c8d401: 
network sandbox join failed: could not add vxlan interface inside the network 
sandbox: failed in prefunc: failed to set namespace on link "vxland88a753": 
invalid argument statusCode=500
INFO[0143] POST /v1.20/containers/create                
INFO[0143] POST 
/v1.20/containers/
67ac787fde580e981082d0f29fcd36957ca84f8cc0e2d7b585bc9caf0a8712f9/attach?stderr=1
&stdin=1&stdout=1&stream=1 
INFO[0143] POST 
/v1.20/containers/
67ac787fde580e981082d0f29fcd36957ca84f8cc0e2d7b585bc9caf0a8712f9/start 
2015/06/23 19:52:53 http: panic serving @: runtime error: invalid memory address 
or nil pointer dereference
goroutine 197 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/libnetwork/drivers/overlay.(*driver).Join(0xc2081f61b0, 
0xc2084e38c0, 0x40, 0xc2084f9e40, 0x40, 0xc2084ddb90, 0x22, 0x7f05381ce5e0, 
0xc208564090, 0xc2084ddb60, ...)
	
/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/drivers
/overlay/joinleave.go:40 +0x561
github.com/docker/libnetwork.(*endpoint).Join(0xc208564090, 0xc2086357c0, 0x40, 
0xc2084e2a00, 0x5, 0x8, 0x0, 0x0)
	
/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/
endpoint.go:397 +0x786
github.com/docker/docker/daemon.(*Container).configureNetwork(0xc2081132c0, 
0x7fff13c5989a, 0xa, 0xc2084baee0, 0xf, 0x7fff13c59892, 0x7, 0xc2084bae01, 0x0, 
0x0)
	/go/src/github.com/docker/docker/daemon/container_linux.go:867 +0x467
github.com/docker/docker/daemon.(*Container).AllocateNetwork(0xc2081132c0, 0x0, 
0x0)
	/go/src/github.com/docker/docker/daemon/container_linux.go:821 +0x4bc
github.com/docker/docker/daemon.(*Container).initializeNetworking(0xc2081132c0, 
0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_linux.go:918 +0x52c
github.com/docker/docker/daemon.(*Container).Start(0xc2081132c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:255 +0x1cf
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc2080aea80, 
0xc2082d0947, 0x40, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/start.go:35 +0x24c
github.com/docker/docker/api/server.(*Server).postContainersStart(0xc208035140, 
0xc2082d0937, 0x4, 0x7f05381bf9a8, 0xc208458be0, 0xc208334b60, 0xc2084f46c0, 
0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:1031 +0x162
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server
.postContainersStart)·fm(0xc2082d0937, 0x4, 0x7f05381bf9a8, 0xc208458be0, 
0xc208334b60, 0xc2084f46c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:1544 +0x7b
github.com/docker/docker/api/server.func·008(0x7f05381bf9a8, 0xc208458be0, 
0xc208334b60)
	/go/src/github.com/docker/docker/api/server/server.go:1495 +0xbe5
net/http.HandlerFunc.ServeHTTP(0xc2081c80c0, 0x7f05381bf9a8, 0xc208458be0, 
0xc208334b60)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208091770, 0x7f05381bf9a8, 
0xc208458be0, 0xc208334b60)
	
/go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 
+0x297
net/http.serverHandler.ServeHTTP(0xc2081b1500, 0x7f05381bf9a8, 0xc208458be0, 
0xc208334b60)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208458640)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
```

Client:
```
root@mechjeb:~# docker run -ti busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from busybox
cf2616975b4a: Pull complete 
6ce2e90b0bc7: Pull complete 
8c2e06607696: Already exists 
busybox:latest: The image you are pulling has been verified. Important: image 
verification is a tech preview feature and should not be relied on to provide 
security.
Digest: sha256:38a203e1986cf79639cfb9b2e1d6e773de84002feea2d4eb006b52004ee8502d
Status: Downloaded newer image for busybox:latest
Error response from daemon: Cannot start container 
7d3daba29ec003704b5ca332f3ecc53a0bf4318b7509b5f471b4181ff9c8d401: network 
sandbox join failed: could not add vxlan interface inside the network sandbox: 
failed in prefunc: failed to set namespace on link "vxland88a753": invalid 
argument
root@mechjeb:~# docker run -ti busybox
Post http:///var/run/docker.sock/v1.20/containers/
67ac787fde580e981082d0f29fcd36957ca84f8cc0e2d7b585bc9caf0a8712f9/start: EOF. Are 
you trying to connect to a TLS-enabled daemon without TLS?
```

**Comment by mavenugo** [comment]
I have seen this problem with 3.13 kernel and below. Can you try the same with 3.18+

**Comment by jgkamat** [comment]
I tried upgrading my kernel to 3.19, and that works fine! However, Ubuntu 14.04 is still a supported distro with linux 3.13 (as are many other distros), and I don't think many people would be willing to upgrade their kernel on their production machines. Will support be added for older kernels eventually?

**Comment by mavenugo** [comment]
Thanks for trying. Yes, it is planned to get the support for older kernels in soon.

**Comment by jgkamat** [comment]
I also tried it on the 3.16 kernel and that seems to work as well. I'm updating this ticket's name. Thanks for helping out! :smile:

**Comment by mavenugo** [comment]
@jgkamat Thanks again for confirming. Shall we close this issue here and open it in https://github.com/docker/libnetwork/issues ?

**Comment by jgkamat** [comment]
Sure thing, I'll close this issue and reopen it in libnetwork!
