### ISSUE TITLE
Panic on invalid port syntax

### ISSUE THREAD

**Issue by icecrime** [docker/docker#14230]
A typo in a compose file (had port specification `5601;5061`) got me a daemon-side panic:

```
Jun 27 21:05:31 echoes docker[11871]: 2015/06/27 21:05:31 http: panic serving @: strconv.ParseUint: parsing "5601;5601": invalid syntax
Jun 27 21:05:31 echoes docker[11871]: goroutine 88 [running]:
Jun 27 21:05:31 echoes docker[11871]: net/http.func·011()
Jun 27 21:05:31 echoes docker[11871]: /usr/local/go/src/net/http/server.go:1130 +0xbb
Jun 27 21:05:31 echoes docker[11871]: github.com/docker/docker/nat.Port.Int(0xc2082b9670, 0xd, 0x15e1)
Jun 27 21:05:31 echoes docker[11871]: /go/src/github.com/docker/docker/nat/nat.go:60 +0x99
Jun 27 21:05:31 echoes docker[11871]: github.com/docker/docker/nat.portMapSorter.Less(0xc2081baae0, 0x2, 0x2, 0x1, 0x0, 0x7f32074f2728)
Jun 27 21:05:31 echoes docker[11871]: /go/src/github.com/docker/docker/nat/sort.go:51 +0x152
Jun 27 21:05:31 echoes docker[11871]: github.com/docker/docker/nat.(*portMapSorter).Less(0xc20823ffc0, 0x1, 0x0, 0x60)
Jun 27 21:05:31 echoes docker[11871]: <autogenerated>:6 +0xb5
Jun 27 21:05:31 echoes docker[11871]: sort.insertionSort(0x7f32074fa900, 0xc20823ffc0, 0x0, 0x2)
Jun 27 21:05:31 echoes docker[11871]: /usr/local/go/src/sort/sort.go:32 +0x72
Jun 27 21:05:31 echoes docker[11871]: sort.quickSort(0x7f32074fa900, 0xc20823ffc0, 0x0, 0x2, 0x4)
Jun 27 21:05:31 echoes docker[11871]: /usr/local/go/src/sort/sort.go:185 +0x156
Jun 27 21:05:31 echoes docker[11871]: sort.Sort(0x7f32074fa900, 0xc20823ffc0)
Jun 27 21:05:31 echoes docker[11871]: /usr/local/go/src/sort/sort.go:200 +0x7b
Jun 27 21:05:31 echoes docker[11871]: github.com/docker/docker/nat.SortPortMap(0xc20823ffa0, 0x2, 0x2, 0xc20824ae40)
Jun 27 21:05:31 echoes docker[11871]: /go/src/github.com/docker/docker/nat/sort.go:69 +0x469
Jun 27 21:05:31 echoes docker[11871]: github.com/docker/docker/daemon.(*Container).buildCreateEndpointOptions(0xc2084272c0, 0x0, 0x0, 0x0, 0x0, 0x0)
Jun 27 21:05:31 echoes docker[11871]: /go/src/github.com/docker/docker/daemon/container_linux.go:709 +0x83a
Jun 27 21:05:31 echoes docker[11871]: github.com/docker/docker/daemon.(*Container).AllocateNetwork(0xc2084272c0, 0x0, 0x0)
Jun 27 21:05:31 echoes docker[11871]: /go/src/github.com/docker/docker/daemon/container_linux.go:763 +0x2cb
Jun 27 21:05:31 echoes docker[11871]: github.com/docker/docker/daemon.(*Container).initializeNetworking(0xc2084272c0, 0x0, 0x0)
Jun 27 21:05:31 echoes docker[11871]: /go/src/github.com/docker/docker/daemon/container_linux.go:838 +0x52c
Jun 27 21:05:31 echoes docker[11871]: github.com/docker/docker/daemon.(*Container).Start(0xc2084272c0, 0x0, 0x0)
Jun 27 21:05:31 echoes docker[11871]: /go/src/github.com/docker/docker/daemon/container.go:254 +0x1cf
Jun 27 21:05:31 echoes docker[11871]: github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc20803ac40, 0xc2080e9667, 0x40, 0x0, 0x0, 0x0)
Jun 27 21:05:31 echoes docker[11871]: /go/src/github.com/docker/docker/daemon/start.go:35 +0x243
Jun 27 21:05:31 echoes docker[11871]: github.com/docker/docker/api/server.(*Server).postContainersStart(0xc20800cb00, 0xc2080e9657, 0x4, 0x7f32074f6050, 0xc2083426e0, 0xc2082e92b0, 0xc20824ac00, 0x0, 0x0)
Jun 27 21:05:31 echoes docker[11871]: /go/src/github.com/docker/docker/api/server/server.go:1028 +0x162
Jun 27 21:05:31 echoes docker[11871]: github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.postContainersStart)·fm(0xc2080e9657, 0x4, 0x7f32074f6050, 0xc2083426e0, 0xc2082e92b0, 0xc20824ac00, 0x0, 0x0)
Jun 27 21:05:31 echoes docker[11871]: /go/src/github.com/docker/docker/api/server/server.go:1538 +0x7b
Jun 27 21:05:31 echoes docker[11871]: github.com/docker/docker/api/server.func·008(0x7f32074f6050, 0xc2083426e0, 0xc2082e92b0)
Jun 27 21:05:31 echoes docker[11871]: /go/src/github.com/docker/docker/api/server/server.go:1489 +0x91d
```

**Comment by ankushagarwal** [comment]
#dibs
