### ISSUE TITLE
Docker daemon crashes during docker load

### ISSUE THREAD

**Issue by mainframe** [docker/docker#14689]
Im trying to preload some docker images (410MB gzipped tarball) as part of docker host build process  (executed inside KVM VM) - which means that Im running docker daemon in Anaconda installer kickstart post-install chroot stage with limited network setup (no docker networking - just to load images over http).

Docker daemon is run inside chroot with the following options
```bash
DOCKER_STORAGE_OPTIONS="-s devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/atomicos-docker--pool"
DOCKER_NETWORK_OPTIONS="--ip-forward=false --iptables=false"
docker -d $DOCKER_STORAGE_OPTIONS $DOCKER_NETWORK_OPTIONS &
```

Images are preloaded like this:
```bash
curl -L http://192.168.122.1:8000/docker-images.tar.gz | gzip -cd | docker load
```

If loading small tarball - like 5-10MB - it works ok. Problems start with larger tarballs (mine is 410MB).
Docker daemon crashes while trying to load larger images tarball:
```bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0INFO[0030] POST /v1.18/images/load
                                                                                                                                      INFO[0030] +job load()
 10  416M   10 45.1M    0     0  12.3M      0  0:00:33  0:00:03  0:00:30 12.3Munexpected fault address 0x651e90
fatal error: fault
[signal 0xb code=0x2 addr=0x651e90 pc=0x651e90]

goroutine 11 [running]:
runtime.gothrow(0xbf0a10, 0x5)
        /usr/lib/golang/src/runtime/panic.go:503 +0x8e fp=0xc2080f7938 sp=0xc2080f7920
runtime.sigpanic()
        /usr/lib/golang/src/runtime/sigpanic_unix.go:29 +0x265 fp=0xc2080f7988 sp=0xc2080f7938
bufio.(*Writer).Write(0xc20807c340, 0xc20807c3c0, 0x6, 0x40, 0x1, 0x1, 0xc2080ce660)
        /usr/lib/golang/src/bufio/bufio.go:556 fp=0xc2080f7990 sp=0xc2080f7988
fmt.Fprintf(0x7f179dea70a8, 0xc20807c340, 0xbd9670, 0x4, 0xc2080f7a50, 0x1, 0x1, 0x46501b, 0x0, 0x0)
        /usr/lib/golang/src/fmt/print.go:189 +0xac fp=0xc2080f79d8 sp=0xc2080f7990
net/http/internal.(*chunkedWriter).Write(0xc2080aa8f0, 0xc2080c2000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
        /usr/lib/golang/src/net/http/internal/chunked.go:166 +0x16d fp=0xc2080f7a80 sp=0xc2080f79d8
io.Copy(0x7f179dea7228, 0xc2080aa8f0, 0x7f179dea7148, 0xc2080ad680, 0x7538000, 0x0, 0x0)
        /usr/lib/golang/src/io/io.go:364 +0x278 fp=0xc2080f7b38 sp=0xc2080f7a80
net/http.(*transferWriter).WriteBody(0xc208090af0, 0x7f179dea70a8, 0xc20807c340, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transfer.go:207 +0x226 fp=0xc2080f7cc8 sp=0xc2080f7b38
net/http.(*Request).write(0xc208112000, 0x7f179dea70a8, 0xc20807c340, 0x7f179dea7000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/request.go:448 +0xada fp=0xc2080f7e70 sp=0xc2080f7cc8
net/http.(*persistConn).writeLoop(0xc2080a7810)
        /usr/lib/golang/src/net/http/transport.go:951 +0x28d fp=0xc2080f7fd8 sp=0xc2080f7e70
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080f7fe0 sp=0xc2080f7fd8
created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 1 [select]:
net/http.(*persistConn).roundTrip(0xc2080a7810, 0xc2080aa800, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1082 +0x7ad
net/http.(*Transport).RoundTrip(0xc208060360, 0xc208112000, 0xc20810d1a0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:235 +0x558
net/http.send(0xc208112000, 0x7f179dea5118, 0xc208060360, 0x2d, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc20810d170, 0xc208112000, 0x2d, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc20810d170, 0xc208112000, 0xd8a280, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:367 +0xb25
net/http.(*Client).Do(0xc20810d170, 0xc208112000, 0xc208060360, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:177 +0x192
github.com/docker/docker/api/client.(*DockerCli).clientRequest(0xc2080625a0, 0xbe4630, 0x4, 0xc0a330, 0xc, 0x7f179dea4f20, 0xc20802c000, 0x0, 0x0, 0x0, ...)
        /builddir/build/BUILD/docker-ba1f6c3a8973725dcc97298aecb367ad5498955b/_build/src/github.com/docker/docker/api/client/utils.go:81 +0x7a6
github.com/docker/docker/api/client.(*DockerCli).streamHelper(0xc2080625a0, 0xbe4630, 0x4, 0xc0a330, 0xc, 0x1, 0x7f179dea4f20, 0xc20802c000, 0x7f179dea4ea8, 0xc20802c008, ...)
        /builddir/build/BUILD/docker-ba1f6c3a8973725dcc97298aecb367ad5498955b/_build/src/github.com/docker/docker/api/client/utils.go:178 +0xa6
github.com/docker/docker/api/client.(*DockerCli).stream(0xc2080625a0, 0xbe4630, 0x4, 0xc0a330, 0xc, 0x7f179dea4f20, 0xc20802c000, 0x7f179dea4ea8, 0xc20802c008, 0x0, ...)
        /builddir/build/BUILD/docker-ba1f6c3a8973725dcc97298aecb367ad5498955b/_build/src/github.com/docker/docker/api/client/utils.go:174 +0xd1
github.com/docker/docker/api/client.(*DockerCli).CmdLoad(0xc2080625a0, 0xc20800a010, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/docker-ba1f6c3a8973725dcc97298aecb367ad5498955b/_build/src/github.com/docker/docker/api/client/commands.go:2665 +0x417
reflect.callMethod(0xc20810d050, 0xc208151b18)
        /usr/lib/golang/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a010, 0x0, 0x0, 0x1, 0xc20810d050, 0xc208062601, 0xc208060360, 0x4, 0x4, 0x7f179de98001, ...)
        /usr/lib/golang/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/api/client.(*DockerCli).Cmd(0xc2080625a0, 0xc20800a010, 0x1, 0x1, 0x0, 0x0)
        /builddir/build/BUILD/docker-ba1f6c3a8973725dcc97298aecb367ad5498955b/_build/src/github.com/docker/docker/api/client/cli.go:81 +0x37e
main.main()
        /builddir/build/BUILD/docker-ba1f6c3a8973725dcc97298aecb367ad5498955b/docker/docker.go:143 +0xec2

goroutine 5 [syscall]:
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [IO wait]:
net.(*pollDesc).Wait(0xc208090ae0, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208090ae0, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208090a80, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x7f179dea4f70, 0xc2080aa858)
        /usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c340, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f179dea7030, 0xc20802c340, 0xc2080a7868, 0xc20800f000, 0x1000, 0x1000, 0x7f179de93010, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2080ad580, 0xc20800f000, 0x1000, 0x1000, 0xc207ffd3cb, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208030720)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208030720, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080a7810)
        /usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.goUntar exit status 1 unexpected EOF
                                                                                   :660 +0xc9f
 11  416M   11 47.0M    0     0  11.5M      0  0:00:36  0:00:04  0:00:32 11.5M
curl: (23) Failed writing body (3360 != 16384)
[anaconda root@localhost /]# INFO[0034] -job load() = ERR (1)
                                                                                     ERRO[0034] Handler for POST /images/load returned error: Untar exit status 1 unexpected EOF
                                                                                                                                                                                 ERRO[0034] HTTP Error: statusCode=500 Untar exit status 1 unexpected EOF
```

Docker info:
```bash
[anaconda root@localhost /]# docker info
INFO[0558] GET /v1.18/info
INFO[0558] +job info()
INFO[0558] +job subscribers_count()
INFO[0558] -job subscribers_count() = OK (0)
INFO[0558] +job registry_config()
INFO[0558] -job registry_config() = OK (0)
INFO[0558] -job info() = OK (0)
Containers: 0
Images: 2
Storage Driver: devicemapper
 Pool Name: atomicos-docker--pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 24.05 MB
 Data Space Total: 7.181 GB
 Data Space Available: 7.157 GB
 Metadata Space Used: 81.92 kB
 Metadata Space Total: 33.55 MB
 Metadata Space Available: 33.47 MB
 Udev Sync Supported: true
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.954 GiB
Name: localhost.localdomain
ID: IPIB:YGHC:UZ5V:JVRC:PB3M:LMIM:PFQC:46G2:RLUT:YRPO:EAD4:7XUX
WARNING: No memory limit support
WARNING: No swap limit support
```

I have also successful builds using exactly the same kickstart and same approach - difference seems to be in build KVM VM vCPU count. With single virtual CPU it seems to succeed and with 2 vCPUs it seems to crash. Perhaps its some multithreading issue?

**Comment by calavera** [comment]
can you also provide the output of `docker version`?

**Comment by mainframe** [comment]
Sure - here it is:
```bash
Docker version 1.6.2, build ba1f6c3/1.6.2
```

**Comment by thaJeztah** [comment]
@mainframe are you still able to reproduce this on the current release (1.8.1)?

**Comment by mainframe** [comment]
I forgot to report back that I found a cause and a simple workaround for this issue. After more tests it seemed to be some kind of docker daemon multithreading issue inside KVM VM and anaconda chroot. I was using Fedora Imagefactory tool for OS image building and it launched VMs with vCPUs config hard-coded for 2 cores: https://github.com/projectatomic/rpm-ostree-toolbox/blob/master/src/py/rpmostreecompose/imagefactory.py#L250
It needed to be patched for single vCPU core/thread on Imagefactory build VM.

I can try 1.8.1 - but it takes time.

**Comment by thaJeztah** [comment]
@mainframe thanks! Do you want to keep this opened?

**Comment by mainframe** [comment]
I think you may close this one.

**Comment by thaJeztah** [comment]
I'll close, feel free to comment here if you have additional information. Thanks!
