### ISSUE TITLE
[attach] invalid memory address or nil pointer

### ISSUE THREAD

**Issue by noxiouz** [docker/docker#14955]
Hi,
I met an error in my production server. 
That's what I see in logs:
```
INFO[0043] POST /v1.14/images/create?fromImage=registry.ape.yandex.net/v012-karma
INFO[0044] POST /v1.14/containers/create
INFO[0045] POST /v1.14/containers/aab41d6607f035dc3a1aa4991625643ed0f32f3bf669b5104b4f4c04f6f11379/start
INFO[0046] POST /v1.14/containers/aab41d6607f035dc3a1aa4991625643ed0f32f3bf669b5104b4f4c04f6f11379/attach?logs=1&stream=1&stdout=1&stderr=1
2015/07/24 15:51:04 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 702 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/docker/daemon.(*Container).AttachWithLogs(0xc2081cf0e0, 0x0, 0x0, 0x7f41ccd2fa60, 0xc208211110, 0x7f41ccd2fa60, 0xc2082110e0, 0x101, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:844 +0xc2
github.com/docker/docker/daemon.(*Daemon).ContainerAttachWithLogs(0xc208058d20, 0xc2081cf0e0, 0xc2082110b0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/attach.go:40 +0x42f
github.com/docker/docker/api/server.(*Server).postContainersAttach(0xc208036540, 0xc2082a2877, 0x4, 0x7f41ccd24370, 0xc20839a780, 0xc20856bba0, 0xc208210ea0, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:1132 +0x614
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.postContainersAttach)·fm(0xc2082a2877, 0x4, 0x7f41ccd24370, 0xc20839a780, 0xc20856bba0, 0xc208210ea0, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:1554 +0x7b
github.com/docker/docker/api/server.func·008(0x7f41ccd24370, 0xc20839a780, 0xc20856bba0)
	/go/src/github.com/docker/docker/api/server/server.go:1501 +0xacd
net/http.HandlerFunc.ServeHTTP(0xc208093700, 0x7f41ccd24370, 0xc20839a780, 0xc20856bba0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080fb1d0, 0x7f41ccd24370, 0xc20839a780, 0xc20856bba0)
	/go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2081ddce0, 0x7f41ccd24370, 0xc20839a780, 0xc20856bba0)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20839a6e0)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
INFO[0047] POST /v1.14/containers/create
```
```
sudo docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

**Comment by borislitv** [comment]
docker info
Containers: 202
Images: 62
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: none
Kernel Version: 3.12.16-1-server
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 32
Total Memory: 62.9 GiB
Name: cocs09g.ape.yandex.net
ID: 4UDO:XCOG:USWQ:IA5A:NG5R:N5MP:ZFKC:I77J:C4HY:DPE4:2FTP:MKJO
WARNING: No swap limit support

**Comment by borislitv** [comment]
kernel 3.12.16-1-server

**Comment by noxiouz** [comment]
Seems, it's already fixed in master. We use --log-driver=none

**Comment by cpuguy83** [comment]
@noxiouz If it's fixed can you close?

**Comment by noxiouz** [comment]
Im gonna check when I reach my PC. I just looked into the code.
