### ISSUE TITLE
[1.8.0-rc1] docker-engine deadlocks under concurrent operations

### ISSUE THREAD

**Issue by burke** [docker/docker#15205]
## Summary

Under a workload that we find common on our build nodes, Docker Engine will block irrecoverably after some amount of time.

## System Info

```
$ docker info
Client:
 Version:      1.8.0-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   4f1c66a
 Built:        Sat Jul 25 05:54:28 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   4f1c66a
 Built:        Sat Jul 25 05:54:28 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ uname -r
3.18.8-031808-generic
```

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
```

```
$ ps -axo command | grep '[d]ocker daemon'
/usr/bin/docker daemon --graph='/u/lib/docker' --host='unix:///var/run/docker.sock' --restart=false --host=127.0.0.1:4445 --storage-driver='overlay' --debug --dns=172.17.42.1 --dns=8.8.8.8
```

## To reproduce

*26c8 is a Shopify image – large, on the order of 1GB, with >50k files. This may or may not be important, but it likely influences the amount of time spent in a deadlock-prone mutex region.*

```
docker run -it --entrypoint=/bin/bash --rm=false 26c8 -l
# (get back image ID of be5)
```

#### Terminal 1

```
while [ 1 ] ; do a=$(docker commit be5); docker rmi $a; done
```

#### Terminal 2

```
while [ 1 ] ; do a=$(docker commit be5); docker rmi $a; done
```

#### Terminal 3

```
while [ 1 ] ; do docker run --entrypoint=/bin/true --rm=true 26c8 -l; echo .; done
```

#### Terminal 4

```
while [ 1 ] ; do time docker inspect --format=. 26c8; done
```

## Expected Result

Everything chugs along, possibly slowing down due to heavy load.

## Actual Result

After some variable amount of time, typically on the order of 1-3 minutes, the
jobs in all terminals lock up, presumably in the daemon.  Many or most new
types of API access will not return. `docker ps` continues to work.

## Backtrace during hang

https://gist.github.com/burke/0f8f3d46166fa09d24ec

**Comment by burke** [comment]
Right, 

```
Containers: 19
Images: 181
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.18.8-031808-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 16
Total Memory: 125.9 GiB
Name: borg3.chi.shopify.com
ID: K4EY:T5Z2:ST4O:SO4J:6JYH:BD47:5RRA:XXIQ:DNSD:5QAP:2IK5:RGCP
Debug mode (server): true
File Descriptors: 31
Goroutines: 24
System Time: 2015-07-31T15:52:05.30899342Z
EventsListeners: 0
Init SHA1: 05f79f59e390d98c4c2aed5231cfda2d57ee3a07
Init Path: /usr/lib/docker/dockerinit
Docker Root Dir: /u/lib/docker
WARNING: No memory limit support
WARNING: No swap limit support
```

^ It's not hung at this particular moment.

**Comment by burke** [comment]
I'm pretty sure this is because of goroutine 451 in my trace:

```
goroutine 451 [semacquire, 3 minutes]:
github.com/docker/docker/pkg/truncindex.(*TruncIndex).Get(...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/truncindex/truncindex.go:101 +0x12b
<...snip...>
github.com/docker/docker/pkg/truncindex.(*TruncIndex).Iterate(...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/truncindex/truncindex.go:119 +0xde
<...snip...>
```

Here's the function at 101:

```go
func (idx *TruncIndex) Get(s string) (string, error) {
	if s == "" {
		return "", ErrEmptyPrefix
	}
	var (
		id string
	)
	subTreeVisitFunc := func(prefix patricia.Prefix, item patricia.Item) error {
		if id != "" {
			// we haven't found the ID if there are two or more IDs
			id = ""
			return ErrAmbiguousPrefix
		}
		id = string(prefix)
		return nil
	}

	idx.RLock() // XXXXXXXXXXXXXXX line 101 XXXXXXXXXXXXXXX
	defer idx.RUnlock()
	if err := idx.trie.VisitSubtree(patricia.Prefix(s), subTreeVisitFunc); err != nil {
		return "", err
	}
	if id != "" {
		return id, nil
	}
	return "", fmt.Errorf("no such id: %s", s)
}
``` 

...and the function on 119:

```go
func (idx *TruncIndex) Iterate(handler func(id string)) {
	idx.RLock()
	defer idx.RUnlock()
	idx.trie.Visit(func(prefix patricia.Prefix, item patricia.Item) error {
		handler(string(prefix))
		return nil
	}) // XXXXXXXXXXXXXXX line 119 XXXXXXXXXXXXXXX
}
```

Before L119, the G grabbed `idx.RLock()`, and is trying to grab it again recursively on L119. This will work most of the time, except that calling `idx.Lock()` will cause the mutex to stop accepting new read locks, granting the writer access when the current read locks are all returned. This just causes deadlock when we try to use read locks recursively.

Solution will be to prevent that recursive locking.

**Comment by phemmer** [comment]
Smells like #15195

**Comment by cpuguy83** [comment]
Being that there's potentially two reports of this, and this is on the RC I'm adding to the 1.8 milestone while we investigate.

**Comment by burke** [comment]
The braindead easy solution would be:

```diff
diff --git a/graph/graph.go b/graph/graph.go
index be911b0..e539c7d 100644
--- a/graph/graph.go
+++ b/graph/graph.go
@@ -386,7 +386,7 @@ func (graph *Graph) Map() map[string]*image.Image {
 // The walking order is undetermined.
 func (graph *Graph) walkAll(handler func(*image.Image)) {
        graph.idIndex.Iterate(func(id string) {
-               if img, err := graph.Get(id); err != nil {
+               if img, err := graph.GetLocked(id); err != nil {
                        return
                } else if handler != nil {
                        handler(img)
diff --git a/pkg/truncindex/truncindex.go b/pkg/truncindex/truncindex.go
index 8d8bee0..815e9a1 100644
--- a/pkg/truncindex/truncindex.go
+++ b/pkg/truncindex/truncindex.go
@@ -109,6 +109,32 @@ func (idx *TruncIndex) Get(s string) (string, error) {
        return "", fmt.Errorf("no such id: %s", s)
 }

+func (idx *TruncIndex) GetLocked(s string) (string, error)
+       if s == "" {
+               return "", ErrEmptyPrefix
+       }
+       var (
+               id string
+       )
+       subTreeVisitFunc := func(prefix patricia.Prefix, item patricia.Item) error {
+               if id != "" {
+                       // we haven't found the ID if there are two or more IDs
+                       id = ""
+                       return ErrAmbiguousPrefix
+               }
+               id = string(prefix)
+               return nil
+       }
+
+       if err := idx.trie.VisitSubtree(patricia.Prefix(s), subTreeVisitFunc); err != nil {
+               return "", err
+       }
+       if id != "" {
+               return id, nil
+       }
+       return "", fmt.Errorf("no such id: %s", s)
+}
+
 // Iterates over all stored IDs, and passes each of them to the given handler
 func (idx *TruncIndex) Iterate(handler func(id string)) {
        idx.RLock()
```

**Comment by burke** [comment]
...or maybe this, but there's probably a more elegant way to handle this if someone wants to plow a couple hours into it.

```diff
diff --git a/graph/graph.go b/graph/graph.go
index be911b0..e539c7d 100644
--- a/graph/graph.go
+++ b/graph/graph.go
@@ -386,7 +386,7 @@ func (graph *Graph) Map() map[string]*image.Image {
 // The walking order is undetermined.
 func (graph *Graph) walkAll(handler func(*image.Image)) {
        graph.idIndex.Iterate(func(id string) {
-               if img, err := graph.Get(id); err != nil {
+               if img, err := graph.GetLocked(id); err != nil {
                        return
                } else if handler != nil {
                        handler(img)
diff --git a/pkg/truncindex/truncindex.go b/pkg/truncindex/truncindex.go
index 8d8bee0..bf2fa92 100644
--- a/pkg/truncindex/truncindex.go
+++ b/pkg/truncindex/truncindex.go
@@ -82,6 +82,14 @@ func (idx *TruncIndex) Delete(id string) error {
 // Get retrieves an ID from the TruncIndex. If there are multiple IDs
 // with the given prefix, an error is thrown.
 func (idx *TruncIndex) Get(s string) (string, error) {
+       return idx.get(s, true)
+}
+
+func (idx *TruncIndex) GetLocked(s string) (string, error) {
+       return idx.get(s, false)
+}
+
+func (idx *TruncIndex) get(s string, mustLock bool) (string, error) {
        if s == "" {
                return "", ErrEmptyPrefix
        }
@@ -98,8 +106,10 @@ func (idx *TruncIndex) Get(s string) (string, error) {
                return nil
        }

-       idx.RLock()
-       defer idx.RUnlock()
+       if mustLock {
+               idx.RLock()
+               defer idx.RUnlock()
+       }
        if err := idx.trie.VisitSubtree(patricia.Prefix(s), subTreeVisitFunc); err != nil {
                return "", err
        }
```

**Comment by calavera** [comment]
https://github.com/docker/docker/pull/15207 should fix the issue. We never locked the index before during iteration.
