### ISSUE TITLE
docker daemon dies when pulling from a bad network with high jitter due to io problems

### ISSUE THREAD

**Issue by muayyad-alsadi** [docker/docker#15328]
Provide environment details:
my fedora laptop (physical)

```
uname -a: Linux localhost.localdomain 4.1.2-200.fc22.x86_64 #1 SMP Wed Jul 15 20:12:12 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
docker version: Docker version 1.7.1.fc22, build b6416b7/1.7.1
docker info:
Containers: 2
Images: 80
Storage Driver: devicemapper
 Pool Name: docker-253:1-2364409-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.077 GB
 Data Space Total: 107.4 GB
 Data Space Available: 41.57 GB
 Metadata Space Used: 4.112 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.2-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 8
Total Memory: 7.729 GiB
Name: localhost.localdomain
ID: IWDZ:GR2K:X4E7:3ZUE:GVHM:A4PT:FEOZ:YLQQ:66QL:72K7:DGI6:AWSV
```

List the steps to reproduce the issue:
1. connect to a very slow network or a network with high [jitter](http://www.pingtest.net/help.php#q9)
2. docker pull any large image with too many layers ex. `docker pull qnib/elk`
3. wait till docker daemon die
4. issue any command to docker like `docker rm` or `docker run` or `docker ps`

Describe the results you received:
after long enough time docker daemon die saying `read tcp 52.7.235.159:443: i/o timeout`
and no command can be sent to the daemon
```
[root@localhost ~]# docker pull qnib/elk
....
failedto pull repository docker.io/qnib/elk ...
read tcp 52.7.235.159:443: i/o timeout
[root@localhost ~]# docker pull qnib/elk
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
[root@localhost ~]# docker rm b2
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
Error: failed to remove containers: [b2]
```

How reproducible:
sometimes (other times it just failed without the daemon dying)

Describe the results you expected:
since docker daemon is the parent of my running software, we want it to be bulletproof

Provide additional info you think is important:
shouldn't `failedto` be `failed to`

**Comment by aidanhs** [comment]
Have you got any output in the docker daemon logs (possibly after adding `-D` to the daemon args)?

**Comment by muayyad-alsadi** [comment]
this is what I found on journalctl logs, please tell me if it's not helpful.
I'll add `-D` to `/etc/sysconfig/docker` but I can't guarantee that I'll get it again.


```
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.goexit()
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080b6fe0 sp=0xc2080b6fd8
Aug 05 13:10:20 localhost.localdomain docker[15616]: created by github.com/docker/docker/graph.(*TagStore).pullV2Tag
Aug 05 13:10:20 localhost.localdomain docker[15616]: /builddir/build/BUILD/docker-b6416b73f6b159bf560c118e186731e773f119c6/_build/src/github.com/docker/docker/graph/pull.go:659 +0x267b
Aug 05 13:10:20 localhost.localdomain docker[15616]: goroutine 103 [chan send]:
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.gopark(0x43ff80, 0xc208970598, 0xca78d0, 0x9)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/proc.go:130 +0x105 fp=0xc208876ea0 sp=0xc208876e70
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.goparkunlock(0xc208970598, 0xca78d0, 0x9)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/proc.go:136 +0x48 fp=0xc208876ec8 sp=0xc208876ea0
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.chansend(0xa3ca60, 0xc208970540, 0xc208876fc0, 0x1, 0x71413b, 0x0)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/chan.go:174 +0x481 fp=0xc208876f70 sp=0xc208876ec8
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.chansend1(0xa3ca60, 0xc208970540, 0xc208876fc0)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/chan.go:68 +0x43 fp=0xc208876fa8 sp=0xc208876f70
Aug 05 13:10:20 localhost.localdomain docker[15616]: github.com/docker/docker/graph.func·010(0xc20845e000)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /builddir/build/BUILD/docker-b6416b73f6b159bf560c118e186731e773f119c6/_build/src/github.com/docker/docker/graph/pull.go:658 +0x6b fp=0xc2
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.goexit()
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208876fe0 sp=0xc208876fd8
Aug 05 13:10:20 localhost.localdomain docker[15616]: created by github.com/docker/docker/graph.(*TagStore).pullV2Tag
Aug 05 13:10:20 localhost.localdomain docker[15616]: /builddir/build/BUILD/docker-b6416b73f6b159bf560c118e186731e773f119c6/_build/src/github.com/docker/docker/graph/pull.go:659 +0x267b
Aug 05 13:10:20 localhost.localdomain docker[15616]: goroutine 342 [runnable]:
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.gopark(0x422e60, 0xc2080b7f40, 0xc83b90, 0x6)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/proc.go:130 +0x105 fp=0xc2080b7c18 sp=0xc2080b7be8
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgoImpl(0xc2080b7f40, 0x0, 0x18)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:366 +0xb2c fp=0xc2080b7db0 sp=0xc2080b7c18
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgo(0xc2080b7f40)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:183 +0x12 fp=0xc2080b7dd0 sp=0xc2080b7db0
Aug 05 13:10:20 localhost.localdomain docker[15616]: net/http.(*persistConn).readLoop(0xc2080ef4a0)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:928 +0x9ce fp=0xc2080b7fd8 sp=0xc2080b7dd0
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.goexit()
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080b7fe0 sp=0xc2080b7fd8
Aug 05 13:10:20 localhost.localdomain docker[15616]: created by net/http.(*Transport).dialConn
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:660 +0xc9f
Aug 05 13:10:20 localhost.localdomain docker[15616]: goroutine 364 [select]:
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.gopark(0x422e60, 0xc2080bcf40, 0xc83b90, 0x6)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/proc.go:130 +0x105 fp=0xc2080bcc18 sp=0xc2080bcbe8
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgoImpl(0xc2080bcf40, 0x0, 0x18)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:366 +0xb2c fp=0xc2080bcdb0 sp=0xc2080bcc18
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgo(0xc2080bcf40)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:183 +0x12 fp=0xc2080bcdd0 sp=0xc2080bcdb0
Aug 05 13:10:20 localhost.localdomain docker[15616]: net/http.(*persistConn).readLoop(0xc208a68f20)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:928 +0x9ce fp=0xc2080bcfd8 sp=0xc2080bcdd0
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.goexit()
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080bcfe0 sp=0xc2080bcfd8
Aug 05 13:10:20 localhost.localdomain docker[15616]: created by net/http.(*Transport).dialConn
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:660 +0xc9f
Aug 05 13:10:20 localhost.localdomain docker[15616]: goroutine 295 [select, 2 minutes]:
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.gopark(0x422e60, 0xc208b93f40, 0xc83b90, 0x6)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/proc.go:130 +0x105 fp=0xc208b93c18 sp=0xc208b93be8
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgoImpl(0xc208b93f40, 0x0, 0x18)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:366 +0xb2c fp=0xc208b93db0 sp=0xc208b93c18
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgo(0xc208b93f40)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:183 +0x12 fp=0xc208b93dd0 sp=0xc208b93db0
Aug 05 13:10:20 localhost.localdomain docker[15616]: net/http.(*persistConn).readLoop(0xc208505810)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:928 +0x9ce fp=0xc208b93fd8 sp=0xc208b93dd0
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.goexit()
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208b93fe0 sp=0xc208b93fd8
Aug 05 13:10:20 localhost.localdomain docker[15616]: created by net/http.(*Transport).dialConn
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:660 +0xc9f
Aug 05 13:10:20 localhost.localdomain docker[15616]: goroutine 296 [select, 2 minutes]:
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.gopark(0x422e60, 0xc208878f40, 0xc83b90, 0x6)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/proc.go:130 +0x105 fp=0xc208878cb8 sp=0xc208878c88
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgoImpl(0xc208878f40, 0x0, 0x18)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:366 +0xb2c fp=0xc208878e50 sp=0xc208878cb8
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgo(0xc208878f40)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:183 +0x12 fp=0xc208878e70 sp=0xc208878e50
Aug 05 13:10:20 localhost.localdomain docker[15616]: net/http.(*persistConn).writeLoop(0xc208505810)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:945 +0x41d fp=0xc208878fd8 sp=0xc208878e70
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.goexit()
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208878fe0 sp=0xc208878fd8
Aug 05 13:10:20 localhost.localdomain docker[15616]: created by net/http.(*Transport).dialConn
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:661 +0xcbc
Aug 05 13:10:20 localhost.localdomain docker[15616]: goroutine 343 [select, 2 minutes]:
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.gopark(0x422e60, 0xc208875740, 0xc83b90, 0x6)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/proc.go:130 +0x105 fp=0xc2088754b8 sp=0xc208875488
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgoImpl(0xc208875740, 0x0, 0x18)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:366 +0xb2c fp=0xc208875650 sp=0xc2088754b8
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgo(0xc208875740)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:183 +0x12 fp=0xc208875670 sp=0xc208875650
Aug 05 13:10:20 localhost.localdomain docker[15616]: net/http.(*persistConn).writeLoop(0xc2080ef4a0)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:945 +0x41d fp=0xc2088757d8 sp=0xc208875670
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.goexit()
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2088757e0 sp=0xc2088757d8
Aug 05 13:10:20 localhost.localdomain docker[15616]: created by net/http.(*Transport).dialConn
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:661 +0xcbc
Aug 05 13:10:20 localhost.localdomain docker[15616]: goroutine 365 [select]:
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.gopark(0x422e60, 0xc208878740, 0xc83b90, 0x6)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/proc.go:130 +0x105 fp=0xc2088784b8 sp=0xc208878488
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgoImpl(0xc208878740, 0x0, 0x18)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:366 +0xb2c fp=0xc208878650 sp=0xc2088784b8
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgo(0xc208878740)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:183 +0x12 fp=0xc208878670 sp=0xc208878650
Aug 05 13:10:20 localhost.localdomain docker[15616]: net/http.(*persistConn).writeLoop(0xc208a68f20)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:945 +0x41d fp=0xc2088787d8 sp=0xc208878670
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.goexit()
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2088787e0 sp=0xc2088787d8
Aug 05 13:10:20 localhost.localdomain docker[15616]: created by net/http.(*Transport).dialConn
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:661 +0xcbc
Aug 05 13:10:21 localhost.localdomain systemd[1]: docker.service: main process exited, code=killed, status=6/ABRT
Aug 05 13:10:21 localhost.localdomain systemd[1]: Unit docker.service entered failed state.
Aug 05 13:10:21 localhost.localdomain systemd[1]: docker.service failed.


Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.goexit()
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2088757e0 sp=0xc2088757d8
Aug 05 13:10:20 localhost.localdomain docker[15616]: created by net/http.(*Transport).dialConn
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:661 +0xcbc
Aug 05 13:10:20 localhost.localdomain docker[15616]: goroutine 365 [select]:
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.gopark(0x422e60, 0xc208878740, 0xc83b90, 0x6)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/proc.go:130 +0x105 fp=0xc2088784b8 sp=0xc208878488
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgoImpl(0xc208878740, 0x0, 0x18)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:366 +0xb2c fp=0xc208878650 sp=0xc2088784b8
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.selectgo(0xc208878740)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/select.go:183 +0x12 fp=0xc208878670 sp=0xc208878650
Aug 05 13:10:20 localhost.localdomain docker[15616]: net/http.(*persistConn).writeLoop(0xc208a68f20)
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:945 +0x41d fp=0xc2088787d8 sp=0xc208878670
Aug 05 13:10:20 localhost.localdomain docker[15616]: runtime.goexit()
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2088787e0 sp=0xc2088787d8
Aug 05 13:10:20 localhost.localdomain docker[15616]: created by net/http.(*Transport).dialConn
Aug 05 13:10:20 localhost.localdomain docker[15616]: /usr/lib/golang/src/net/http/transport.go:661 +0xcbc
Aug 05 13:10:21 localhost.localdomain abrt-hook-ccpp[15974]: Failed to create core_backtrace: waitpid failed: No child processes
Aug 05 13:10:21 localhost.localdomain audit[15974]: <audit-1701> auid=4294967295 uid=0 gid=0 ses=4294967295 subj=system_u:system_r:kernel_t:s0 pid=15974 comm="abrt-hook-ccpp" exe="/usr/libex
Aug 05 13:10:21 localhost.localdomain kernel: abrt-hook-ccpp[15974]: segfault at 0 ip 00007fa1dd4f50ba sp 00007ffe574850d8 error 4 in libc-2.21.so[7fa1dd46a000+1b7000]
Aug 05 13:10:21 localhost.localdomain kernel: Process 15974(abrt-hook-ccpp) has RLIMIT_CORE set to 1
Aug 05 13:10:21 localhost.localdomain kernel: Aborting core
Aug 05 13:10:21 localhost.localdomain systemd[1]: docker.service: main process exited, code=killed, status=6/ABRT
Aug 05 13:10:21 localhost.localdomain systemd[1]: Unit docker.service entered failed state.
Aug 05 13:10:21 localhost.localdomain systemd[1]: docker.service failed.

```

**Comment by LK4D4** [comment]
I think this was fixed. There was no reports again, so closing.
