### ISSUE TITLE
docker ps --format panic

### ISSUE THREAD

**Issue by vieux** [docker/docker#15600]
`docker  ps -l --format "table {{.Label ''}}"` or even `docker  ps -l --format "table {{.Label 'com.docker.test'}}"`

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x8eb892]

goroutine 1 [running]:
text/template.errRecover(0xc2081373c8)
	/usr/local/go/src/text/template/exec.go:100 +0xbc
text/template.(*Template).Execute(0x0, 0x7f9be741d3b0, 0xc208118a80, 0x1057c00, 0xc2081440c0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:137 +0x242
github.com/docker/docker/api/client/ps.customFormat(0x7f9be741a218, 0xc20803a008, 0x7fff03b467de, 0x13, 0x10000, 0xc2080cac80, 0x1, 0x4)
	/go/src/github.com/docker/docker/api/client/ps/custom.go:183 +0x6ae
github.com/docker/docker/api/client/ps.Format(0x7f9be741a218, 0xc20803a008, 0x7fff03b467de, 0x13, 0x10000, 0xc2080cac80, 0x1, 0x4)
	/go/src/github.com/docker/docker/api/client/ps/formatter.go:40 +0x170
github.com/docker/docker/api/client.(*DockerCli).CmdPs(0xc208144000, 0xc20800a020, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/ps.go:113 +0x1859
reflect.callMethod(0xc208146330, 0xc208137ce0)
	/usr/local/go/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a020, 0x3, 0x3, 0x1, 0xc208146330, 0x0, 0x0, 0xc208146330, 0x0, 0x45343f, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc208146030, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cli.go:89 +0x38e
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:69 +0x428

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0xc2081188b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081188b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208118850, 0xc208152000, 0x1000, 0x1000, 0x0, 0x7f9be741a340, 0xc208101d60)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20803a498, 0xc208152000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f9be741d0b0, 0xc20803a498, 0xc2080fec08, 0xc208152000, 0x1000, 0x1000, 0xea9700, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2081427a0, 0xc208152000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208042ba0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208042ba0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080febb0)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc2080febb0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 14 [runnable]:
text/template/parse.lexChar(0xc208091080, 0x1317608)
	/usr/local/go/src/text/template/parse/lex.go:453 +0x125
text/template/parse.(*lexer).run(0xc208091080)
	/usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:191 +0x1ac
```

**Comment by thaJeztah** [comment]
ping @estesp could you have a look? do you need more info (version etc?)

**Comment by thaJeztah** [comment]
tentatively adding this to the 1.8.2 milestone

**Comment by duglin** [comment]
until the panic is fixed....try with double-quotes instead of single quotes

**Comment by duglin** [comment]
btw, when I try it on master I see:
```
docker ps -l --format "table {{.Label ''}}"
Template parsing error: template: :1: invalid syntax
```

**Comment by duglin** [comment]
@vieux what version of docker and which OS were you using? I just tried with v1.8.0 and I get the same non-panic error message.

**Comment by vieux** [comment]
my bad, it was for a old version

**Comment by thaJeztah** [comment]
LOL, should've listened to @GordonTheTurtle ;-)
