### ISSUE TITLE
docker1.8.1 arm64 static run error

### ISSUE THREAD

**Issue by jefby** [docker/docker#16129]
Hi, everyone , i have compile static docker 1.8.1 for arm64, but it may failed sometimes.error log like below:
docker version :

>#./docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   devel +d3ffc97 Wed Jul 29 23:50:20 2015 +0000
 Git commit:   73045d9
 Built:        Tue Sep  8 16:20:43 UTC 2015
 OS/Arch:      linux/arm64

uname -a 
 >3.19.8
 
docker info

>#./docker info
Containers: 86
Images: 17
Storage Driver: devicemapper
 Pool Name: docker-8:3-2625852-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.785 GB
 Data Space Total: 107.4 GB
 Data Space Available: 26.63 GB
 Metadata Space Used: 6.717 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.97-git (2015-05-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.8.fc21.aarch64
Operating System: Fedora 21 aarch64
CPUs: 32
Total Memory: 125.9 GiB
Name: localhost
ID: IZ7A:OLLC:2UIM:WQIX:SHIG:6SVO:24TV:ZA22:N7KS:4C2U:YALQ:WEOK
Username: jefby
Registry: https://index.docker.io/v1/

>Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   devel +d3ffc97 Wed Jul 29 23:50:20 2015 +0000
 Git commit:   73045d9
 Built:        Tue Sep  8 16:20:43 UTC 2015
 OS/Arch:      linux/arm64

error log 
```
#./docker -d
Warning: '-d' is deprecated, it will be removed soon. See usage.
WARN[0000] please use 'docker daemon' instead.
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
WARN[0000] Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x11e0d60, 0x2a)
	/media/jefby/docker-work/go-github/src/runtime/panic.go:527 +0x80
runtime.sigpanic()
	/media/jefby/docker-work/go-github/src/runtime/sigpanic_unix.go:12 +0x50

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x406e04, 0x4820764528, 0x4800000000)
	/media/jefby/docker-work/go-github/src/runtime/cgocall.go:120 +0x150 fp=0x48207644e0 sp=0x48207644b0
github.com/docker/docker/pkg/devicemapper._Cfunc_dm_udev_wait(0x4800000000, 0x0)
	??:0 +0x44 fp=0x4820764520 sp=0x48207644e0
github.com/docker/docker/pkg/devicemapper.dmUdevWaitFct(0x0, 0x43bcfc)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper_wrapper.go:249 +0x28 fp=0x4820764540 sp=0x4820764520
github.com/docker/docker/pkg/devicemapper.UdevWait(0x4820415050, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:300 +0x3c fp=0x48207645b0 sp=0x4820764540
github.com/docker/docker/pkg/devicemapper.activateDevice(0x482030fc80, 0x23, 0x482040c1e0, 0x17, 0x1, 0x280000000, 0x0, 0x0, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:751 +0x6d8 fp=0x4820764730 sp=0x48207645b0
github.com/docker/docker/pkg/devicemapper.ActivateDevice(0x482030fc80, 0x23, 0x482040c1e0, 0x17, 0x1, 0x280000000, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:714 +0x58 fp=0x4820764790 sp=0x4820764730
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).activateDeviceIfNeeded(0x482041dcc0, 0x48203afd40, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:459 +0x340 fp=0x48207648a0 sp=0x4820764790
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).verifyBaseDeviceUUID(0x482041dcc0, 0x48203afd40, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:697 +0xa8 fp=0x4820764990 sp=0x48207648a0
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).setupBaseImage(0x482041dcc0, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:747 +0x168 fp=0x4820764ac0 sp=0x4820764990
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).initDevmapper(0x482041dcc0, 0x482041dc01, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:1383 +0x13e4 fp=0x4820764dc0 sp=0x4820764ac0
github.com/docker/docker/daemon/graphdriver/devmapper.NewDeviceSet(0x482049a560, 0x1c, 0x480000ef01, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:2016 +0xfcc fp=0x4820764fe0 sp=0x4820764dc0
github.com/docker/docker/daemon/graphdriver/devmapper.Init(0x482049a560, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/driver.go:44 +0x134 fp=0x48207650b0 sp=0x4820764fe0
github.com/docker/docker/daemon/graphdriver.GetDriver(0x10a6200, 0xc, 0x4820429630, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/driver.go:103 +0x150 fp=0x48207651c0 sp=0x48207650b0
github.com/docker/docker/daemon/graphdriver.New(0x4820429630, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/driver.go:128 +0x408 fp=0x48207653f0 sp=0x48207651c0
github.com/docker/docker/daemon.NewDaemon(0x48202ac400, 0x4820284938, 0x0, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:610 +0x6cc fp=0x48207658a0 sp=0x48207653f0
main.(*DaemonCli).CmdDaemon(0x4820281d50, 0x482000a190, 0x0, 0x0, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/docker/daemon.go:256 +0xba4 fp=0x4820765c40 sp=0x48207658a0
main.handleGlobalDaemonFlag()
	/media/jefby/docker-work/go-github.bak/docker/docker/daemon.go:65 +0x224 fp=0x4820765d00 sp=0x4820765c40
main.main()
	/media/jefby/docker-work/go-github.bak/docker/docker/docker.go:59 +0x304 fp=0x4820765f00 sp=0x4820765d00
runtime.main()
	/media/jefby/docker-work/go-github/src/runtime/proc.go:111 +0x330 fp=0x4820765f50 sp=0x4820765f00
runtime.goexit()
	/media/jefby/docker-work/go-github/src/runtime/asm_arm64.s:1012 +0x4 fp=0x4820765f50 sp=0x4820765f50

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/media/jefby/docker-work/go-github/src/runtime/asm_arm64.s:1012 +0x4

goroutine 34 [chan receive]:
github.com/docker/docker/api/server.(*Server).ServeApi(0x482027ac80, 0x48202c4020, 0x1, 0x1, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/api/server/server.go:111 +0x590
main.(*DaemonCli).CmdDaemon.func2(0x482027ac80, 0x48203f5aa0)
	/media/jefby/docker-work/go-github.bak/docker/docker/daemon.go:242 +0x64
created by main.(*DaemonCli).CmdDaemon
	/media/jefby/docker-work/go-github.bak/docker/docker/daemon.go:248 +0xa9c

goroutine 19 [chan receive]:
github.com/docker/docker/pkg/listenbuffer.(*defaultListener).Accept(0x482026cde0, 0x0, 0x0, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/pkg/listenbuffer/buffer.go:73 +0x98
net/http.(*Server).Serve(0x48201a2a20, 0x7fb05301a0, 0x482026cde0, 0x0, 0x0)
	/media/jefby/docker-work/go-github/src/net/http/server.go:1852 +0x88
github.com/docker/docker/api/server.(*HttpServer).Serve(0x482026cf40, 0x0, 0x0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/api/server/server.go:126 +0x54
github.com/docker/docker/api/server.(*Server).ServeApi.func1(0x0, 0x0, 0x48201a29c0, 0x7fb0530228, 0x482026cf40)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/api/server/server.go:102 +0x28
created by github.com/docker/docker/api/server.(*Server).ServeApi
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/api/server/server.go:106 +0x4d8

goroutine 7 [syscall]:
os/signal.loop()
	/media/jefby/docker-work/go-github/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/media/jefby/docker-work/go-github/src/os/signal/signal_unix.go:28 +0x3c

goroutine 35 [select, locked to thread]:
runtime.gopark(0x12980f0, 0x482005ff10, 0x108dcd8, 0x6, 0x18, 0x2)
	/media/jefby/docker-work/go-github/src/runtime/proc.go:185 +0x178
runtime.selectgoImpl(0x482005ff10, 0x18, 0x2)
	/media/jefby/docker-work/go-github/src/runtime/select.go:392 +0x1298
runtime.selectgo(0x482005ff10)
	/media/jefby/docker-work/go-github/src/runtime/select.go:212 +0x10
runtime.ensureSigM.func1()
	/media/jefby/docker-work/go-github/src/runtime/signal1_unix.go:227 +0x4cc
runtime.goexit()
	/media/jefby/docker-work/go-github/src/runtime/asm_arm64.s:1012 +0x4

goroutine 36 [chan receive]:
github.com/docker/docker/daemon.setupDumpStackTrap.func1(0x48203f5bc0)
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:17 +0x44
created by github.com/docker/docker/daemon.setupDumpStackTrap
	/media/jefby/docker-work/go-github.bak/docker/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:20 +0x110
```

Does anyone know why? how to fix?

**Comment by Pensu** [comment]
How did you compile static binary? Looks like daemon is not able to find a suitable storage driver.

**Comment by jefby** [comment]
Hi, @Pensu ,cd docker source code,and run command " hack/make.sh binary"

**Comment by cpuguy83** [comment]
This really looks like some issues communicating to udev, which it does warn against, though I've never seen it fail like this.
To use devicemapper you would need to use a dyn binary, not a static one.

**Comment by hqhq** [comment]
@cpuguy83 was right, using devicemapper with udev sync unsupported is really bad idea, try dynamic build and see if that still fail?

**Comment by thaJeztah** [comment]
@jefby I'm going to close this, because you have some suggestions how to fix this, but feel free to comment here after I've closed.

Let us know if you managed to solve it :+1:

**Comment by jefby** [comment]
@cpuguy83 @hqhq yes , the dynamic version can work good. Thanks very much.

**Comment by thaJeztah** [comment]
Thanks for reporting back @jefby, good to hear it helped you!
