### ISSUE TITLE
Docker-compose crash by a commit 

### ISSUE THREAD

**Issue by HuKeping** [docker/docker#16296]
docker version: the master branch

docker-compose version: 1.4.0

docker-compose.yml:
```
proa:
        build: .
```

When I use `docker-compose build` and then `docker-compose up`, these error happen:
```
$ docker-compose up

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 39, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 495, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 251, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 446, in remove_duplicate_containers
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 453, in duplicate_containers
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 110, in containers
TypeError: 'NoneType' object is not iterable
```

But if I use a earlier docker version(I choose `docker1.7`), it works fine. Then I do the `git bisect`, it shows me commit `06699f73fb6d779894a875f9177afc5a1f3bc5b3` upstream is the key.

When I revert this commit  from the master branch, it works fine again. I haven't found what cause this problem, but it seems all in that commit.

**Comment by runcom** [comment]
@HuKeping thanks for the report, there's also an open issue on compose repo about newer docker not being able to use compare (something about one_off label iirc) I'll look into this

**Comment by calavera** [comment]
Thanks @HuKeping. Closing since this should be tracked in compose. Feel free to follow up in docker/compose#2009.
