### ISSUE TITLE
The network ls --help sub command is crashing

### ISSUE THREAD

**Issue by achanda** [docker/docker#17048]
Here is what I see on the experimental repo
```
Abhishek@dev:~$ docker network ls --help
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/docker/docker/pkg/mflag.(*FlagSet).FlagCountUndeprecated(0xc208078b00, 0xc208163660)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/mflag/flag.go:606 +0xc6
github.com/docker/docker/cli.func·002()
	/usr/src/docker/.gopath/src/github.com/docker/docker/cli/cli.go:163 +0x70
github.com/docker/docker/cli.func·001()
	/usr/src/docker/.gopath/src/github.com/docker/docker/cli/cli.go:157 +0x2f
github.com/docker/docker/pkg/mflag.(*FlagSet).ParseFlags(0xc208078b00, 0xc20800a030, 0x1, 0x1, 0xffffffffffffff01, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/mflag/flag.go:1128 +0x1f6
github.com/docker/docker/api/client.(*DockerCli).CmdNetworkLs(0xc2080ea000, 0xc20800a030, 0x1, 0x1, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/client/network.go:112 +0x3b4
reflect.callMethod(0xc208119ec0, 0xc208163ce8)
	/usr/local/go/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a030, 0x1, 0x1, 0x3, 0xc208119ec0, 0x0, 0x0, 0x0, 0xc208119ec0, 0x4e1e8f, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc208119cb0, 0xc20800a010, 0x3, 0x3, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/cli/cli.go:80 +0x175
main.main()
	/usr/src/docker/docker/docker.go:65 +0x418

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 9 [runnable]:
text/template/parse.lexText(0xc208078480, 0x13c1d70)
	/usr/local/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc208078480)
	/usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:191 +0x1ac
```

Fix coming

**Comment by duglin** [comment]
This we can close this one on due to #17049 being closed.
