### ISSUE TITLE
docker registry crashed and can't start it anymore

### ISSUE THREAD

**Issue by ttux** [docker/docker#17307]
I have a private docker registry, I was pushing an image and it crashed. Now when I try to start it, the following happens:
[ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/lib/python2.7/site-packages/docker_registry/wsgi.py", line 27, in <module>
    from .search import *  # noqa
  File "/usr/lib/python2.7/site-packages/docker_registry/search.py", line 14, in <module>
    INDEX = index.load(cfg.search_backend.lower())
  File "/usr/lib/python2.7/site-packages/docker_registry/lib/index/__init__.py", line 82, in load
    return db.SQLAlchemyIndex()
  File "/usr/lib/python2.7/site-packages/docker_registry/lib/index/db.py", line 86, in __init__
    self._setup_database()
  File "/usr/lib/python2.7/site-packages/docker_registry/toolkit.py", line 323, in wrapper
    raise Exception('Timedout waiting for db init')

And it dies.

I am running the private docker registry with the following command:
gunicorn --access-logfile /var/log/docker-registry/access.log --error-logfile /var/log/docker-registry/server.log -k gevent --max-requests 100 --graceful-timeout 3600 -t 3600 -b 0.0.0.0:5000 -w 8 docker_registry.wsgi:application

I run on an AWS instance and the docker registry runs as a docker container.

`docker version`:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2/1.6.2
OS/Arch (server): linux/amd64

`docker info`:
Containers: 33
Images: 201
Storage Driver: devicemapper
 Pool Name: docker-202:1-263382-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: 
 Metadata file: 
 Data Space Used: 11.42 GB
 Data Space Total: 107.4 GB
 Data Space Available: 95.95 GB
 Metadata Space Used: 16.09 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.131 GB
 Udev Sync Supported: true
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 3.14.27-25.47.amzn1.x86_64
Operating System: Amazon Linux AMI 2014.09
CPUs: 1
Total Memory: 996.3 MiB

gunicorn (version 19.1.1)

`uname -a`:
Linux 6c60a338a4d7 3.14.27-25.47.amzn1.x86_64 #1 SMP Wed Dec 17 18:36:15 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ttux** [comment]
It also starts with a lot of this:
ct/2015:10:49:16 +0000 WARNING: Another process is creating the search database
23/Oct/2015:10:49:16 +0000 WARNING: Another process is creating the search database
23/Oct/2015:10:49:16 +0000 WARNING: Another process is creating the search database
23/Oct/2015:10:49:16 +0000 WARNING: Another process is creating the search database
23/Oct/2015:10:49:16 +0000 WARNING: Another process is creating the search database
23/Oct/2015:10:49:16 +0000 WARNING: Another process is creating the search database

**Comment by phemmer** [comment]
The docker registry is maintained in a different repo ([here](https://github.com/docker/distribution)). This repo is for the docker daemon & client.

**Comment by thaJeztah** [comment]
@ttux could you open this issue in the https://github.com/docker/distribution issue tracker? Thanks!
