### ISSUE TITLE
Test timed out on Google cloud instance

### ISSUE THREAD

**Issue by azmifarih** [docker/docker#17640]
Description of problem: 
First at all, I'm new with Docker. I only follow step by step to contribute in Docker. I run `make test ` and see errors like this:

```````
PASS: docker_cli_events_test.go:354: DockerSuite.TestEventsFilterImageName	0.809s
PASS: docker_cli_events_test.go:387: DockerSuite.TestEventsFilterLabels	0.677s
PASS: docker_cli_events_test.go:323: DockerSuite.TestEventsFilters	0.842s
PASS: docker_cli_events_test.go:274: DockerSuite.TestEventsImageImport	0.563s
PASS: docker_cli_events_test.go:254: DockerSuite.TestEventsImagePull	6.558s
PASS: docker_cli_events_test.go:230: DockerSuite.TestEventsImageTag	1.065s
PASS: docker_cli_events_test.go:200: DockerSuite.TestEventsImageUntagDelete	0.269s
PASS: docker_cli_events_test.go:102: DockerSuite.TestEventsLimit	6.910s
PASS: docker_cli_events_unix_test.go:57: DockerSuite.TestEventsOOMDisableFalse	0.910s
panic: test timed out after 1h0m0s

goroutine 3048 [running]:
testing.func·008()
	/usr/local/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive, 60 minutes]:
testing.RunTests(0xd35ca8, 0x112a9d0, 0x1, 0x1, 0xc208136101)
	/usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20804b400, 0x115d6c0)
	/usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
	github.com/docker/docker/integration-cli/_test/_testmain.go:120 +0x291

goroutine 5 [syscall, 60 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 8 [chan receive, 49 minutes]:
github.com/go-check/check.(*suiteRunner).runTest(0xc208074d00, 0xc208151dc0, 0xc209d23b30)
	/go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:801 +0x5e
github.com/go-check/check.(*suiteRunner).run(0xc208074d00, 0x115eac8)
	/go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:606 +0x27a
github.com/go-check/check.Run(0xb8d3a0, 0x115eac8, 0xc2080c5e00, 0xc208019db8)
	/go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/run.go:92 +0x4a
github.com/go-check/check.RunAll(0xc2080c5e00, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/run.go:84 +0xc2
github.com/go-check/check.TestingT(0xc208044fc0)
	/go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/run.go:72 +0x1fd
github.com/docker/docker/integration-cli.Test(0xc208044fc0)
	/go/src/github.com/docker/docker/integration-cli/check_test.go:20 +0xfd
testing.tRunner(0xc208044fc0, 0x112a9d0)
	/usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 9 [select, 49 minutes]:
github.com/go-check/check.(*resultTracker)._loopRoutine(0xc208045050)
	/go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:452 +0x395
created by github.com/go-check/check.(*resultTracker).start
	/go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:432 +0x32

goroutine 3042 [syscall, 49 minutes]:
syscall.Syscall6(0x3d, 0x30d3, 0xc209e513ac, 0x0, 0xc209e64bd0, 0x0, 0x0, 0xc209e66c00, 0x404811, 0xc209e66c20)
	/usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x30d3, 0xc209e513ac, 0x0, 0xc209e64bd0, 0x90, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x30d3, 0xc209e513f4, 0x0, 0xc209e64bd0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc209e5fba0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc209e5fba0, 0xc209e76690, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc209ddbb80, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:364 +0x23c
os/exec.(*Cmd).Run(0xc209ddbb80, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:246 +0x71
os/exec.(*Cmd).CombinedOutput(0xc209ddbb80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:408 +0x354
github.com/docker/docker/pkg/integration.RunCommandWithOutput(0xc209ddbb80, 0x0, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/integration/utils.go:66 +0x4c
github.com/docker/docker/pkg/integration.DockerCmd(0xc20800a4e0, 0x58, 0xc209d23ef0, 0xc209e51970, 0x2, 0x2, 0x0, 0x0, 0xc209b14e00)
	/go/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:34 +0x94
github.com/docker/docker/integration-cli.dockerCmd(0xc209d23ef0, 0xc209e51970, 0x2, 0x2, 0x0, 0x0, 0x4)
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:964 +0x7a
github.com/docker/docker/integration-cli.(*DockerSuite).TestEventsOOMDisableTrue(0x115eac8, 0xc209d23ef0)
	/go/src/github.com/docker/docker/integration-cli/docker_cli_events_unix_test.go:153 +0x435
reflect.Value.call(0xb8d3a0, 0x115eac8, 0x31313, 0xb9c790, 0x4, 0xc209e51f78, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xb8d3a0, 0x115eac8, 0x31313, 0xc209e51f78, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
github.com/go-check/check.func·003(0xc209d23ef0)
	/go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:763 +0x401
github.com/go-check/check.func·001()
	/go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:657 +0x92
created by github.com/go-check/check.(*suiteRunner).forkCall
	/go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:658 +0x3fd

goroutine 2827 [chan send, 49 minutes]:
github.com/docker/docker/integration-cli.func·035()
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:182 +0x8c
created by github.com/docker/docker/integration-cli.(*Daemon).Start
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:185 +0x17f0

goroutine 2818 [chan send, 49 minutes]:
github.com/docker/docker/integration-cli.func·035()
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:182 +0x8c
created by github.com/docker/docker/integration-cli.(*Daemon).Start
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:185 +0x17f0

goroutine 33 [syscall, 59 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 2816 [chan send, 49 minutes]:
github.com/docker/docker/integration-cli.func·035()
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:182 +0x8c
created by github.com/docker/docker/integration-cli.(*Daemon).Start
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:185 +0x17f0

goroutine 2828 [chan send, 49 minutes]:
github.com/docker/docker/integration-cli.func·035()
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:182 +0x8c
created by github.com/docker/docker/integration-cli.(*Daemon).Start
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:185 +0x17f0

goroutine 2817 [chan send, 49 minutes]:
github.com/docker/docker/integration-cli.func·035()
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:182 +0x8c
created by github.com/docker/docker/integration-cli.(*Daemon).Start
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:185 +0x17f0

goroutine 2829 [chan send, 49 minutes]:
github.com/docker/docker/integration-cli.func·035()
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:182 +0x8c
created by github.com/docker/docker/integration-cli.(*Daemon).Start
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:185 +0x17f0

goroutine 2830 [chan send, 49 minutes]:
github.com/docker/docker/integration-cli.func·035()
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:182 +0x8c
created by github.com/docker/docker/integration-cli.(*Daemon).Start
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:185 +0x17f0

goroutine 3047 [syscall, 49 minutes]:
syscall.Syscall(0x0, 0xf, 0xc209de1e00, 0x200, 0x0, 0x5f8, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0xf, 0xc209de1e00, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0xf, 0xc209de1e00, 0x200, 0x200, 0xc209b5a5a0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc209db2a38, 0xc209de1e00, 0x200, 0x200, 0xc209de1e00, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc209db2a38, 0xc209de1e00, 0x200, 0x200, 0x1, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
bytes.(*Buffer).ReadFrom(0xc209b15110, 0x7f9c87bb5020, 0xc209db2a38, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:169 +0x25a
io.Copy(0x7f9c87bb5b10, 0xc209b15110, 0x7f9c87bb5020, 0xc209db2a38, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:358 +0x13d
os/exec.func·003(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc209e5fa40)
	/usr/local/go/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:329 +0xb6d

goroutine 3043 [syscall, 49 minutes]:
syscall.Syscall6(0x3d, 0x30bb, 0xc208145aec, 0x0, 0xc209e64a20, 0x0, 0x0, 0xc209e66720, 0xc209e2a380, 0xc209e66740)
	/usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x30bb, 0xc208145aec, 0x0, 0xc209e64a20, 0x90, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x30bb, 0xc208145b34, 0x0, 0xc209e64a20, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc209e5f640, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc209e5f640, 0xc209d53600, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc209ddb7c0, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:364 +0x23c
os/exec.(*Cmd).Run(0xc209ddb7c0, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:246 +0x71
os/exec.(*Cmd).CombinedOutput(0xc209ddb7c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:408 +0x354
github.com/docker/docker/pkg/integration.RunCommandWithOutput(0xc209ddb7c0, 0x0, 0x0, 0xa, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/integration/utils.go:66 +0x4c
github.com/docker/docker/pkg/integration.DockerCmdWithError(0xc20800a4e0, 0x58, 0xc208145f38, 0xa, 0xa, 0x0, 0x0, 0xc2082dd880, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:17 +0x8c
github.com/docker/docker/integration-cli.dockerCmdWithError(0xc208145f38, 0xa, 0xa, 0x0, 0x0, 0x1, 0x0, 0x0)
	github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:954 +0x88
github.com/docker/docker/integration-cli.func·104()
	/go/src/github.com/docker/docker/integration-cli/docker_cli_events_unix_test.go:113 +0xac
created by github.com/docker/docker/integration-cli.(*DockerSuite).TestEventsOOMDisableTrue
	/go/src/github.com/docker/docker/integration-cli/docker_cli_events_unix_test.go:117 +0x311

goroutine 3044 [syscall, 49 minutes]:
syscall.Syscall(0x0, 0xe, 0xc209de1800, 0x200, 0x0, 0x3f1, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0xe, 0xc209de1800, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0xe, 0xc209de1800, 0x200, 0x200, 0xc209b59da0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc209db2978, 0xc209de1800, 0x200, 0x200, 0xc209de1800, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc209db2978, 0xc209de1800, 0x200, 0x200, 0x1, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
bytes.(*Buffer).ReadFrom(0xc209b14cb0, 0x7f9c87bb5020, 0xc209db2978, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:169 +0x25a
io.Copy(0x7f9c87bb5b10, 0xc209b14cb0, 0x7f9c87bb5020, 0xc209db2978, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:358 +0x13d
os/exec.func·003(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc209e5f4e0)
	/usr/local/go/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:329 +0xb6d
exit status 2
FAIL	github.com/docker/docker/integration-cli	3600.060s
---> Making bundle: .integration-daemon-stop (in bundles/1.9.0-dev/test-integration-cli)
+++++ cat bundles/1.9.0-dev/test-integration-cli/docker.pid
++++ kill 12629
```````

`docker version`:
```````
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64
```````

`docker info`:
```````
Containers: 1
Images: 50
Storage Driver: devicemapper
 Pool Name: docker-8:1-50341675-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.974 GB
 Data Space Total: 107.4 GB
 Data Space Available: 5.248 GB
 Metadata Space Used: 5.018 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 3.614 GiB
Name: docker-node
ID: O4US:IYST:SOPM:XDLQ:FDSC:FVMX:EQY6:NAZA:NZCR:LRD7:SQU5:FX4E
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```````

`uname -a`:
```````
Linux docker-node 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```````

Environment details (AWS, VirtualBox, physical, etc.): Google Cloud instances

**Comment by thaJeztah** [comment]
@azmifarih I don't have experience with working on Google Cloud Instances, but since this is about developing docker, perhaps you could join the #docker-dev IRC channel on freenode to ask if there are other developers able to help you out here?

**Comment by azmifarih** [comment]
thank you @thaJeztah for your advice.

**Comment by unclejack** [comment]
It seems that system is slow or there might be another issue. Either way, support for developing Docker isn't provided via the issue tracker. As @thaJeztah has pointed out above, this is something to discuss on IRC.
