### ISSUE TITLE
[1.9.1-rc1] docker ps goes to the interwebs

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#18003]
I noticed a massive slow down in `docker ps` and narrowed it down to this goroutine

```
goroutine 4876 [chan receive]:
net.goLookupIP(0xc2088f7320, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/dnsclient_unix.go:392 +0x492
net.lookupIP(0xc2088f7320, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup_unix.go:66 +0xad
net.func\ufffd\ufffd025(0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup.go:41 +0x55
net.(*singleflight).doCall(0x1da5ef0, 0xc20927d0e0, 0xc2088f7320, 0x6, 0xc208a86a90)
    /usr/local/go/src/net/singleflight.go:91 +0x2f
net.(*singleflight).Do(0x1da5ef0, 0xc2088f7320, 0x6, 0xc208a86a90, 0x0, 0x0, 0x0, 0x0, 0xc2080445a0)
    /usr/local/go/src/net/singleflight.go:61 +0x280
net.lookupIPMerge(0xc2088f7320, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup.go:42 +0xae
net.LookupIP(0xc2088f7320, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup.go:31 +0x5f
github.com/docker/docker/registry.(*ServiceConfig).isSecureIndex(0xc2080a8840, 0xc2088f7320, 0x6, 0x0)
    /go/src/github.com/docker/docker/registry/config.go:163 +0x127
github.com/docker/docker/registry.(*ServiceConfig).NewIndexInfo(0xc2080a8840, 0xc2088f7320, 0x6, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/registry/config.go:272 +0x236
github.com/docker/docker/registry.(*ServiceConfig).NewRepositoryInfo(0xc2080a8840, 0xc2088f7320, 0x1e, 0xc2088f7300, 0x5, 0x0, 0x0)
    /go/src/github.com/docker/docker/registry/config.go:321 +0x1ec
github.com/docker/docker/registry.ParseRepositoryInfo(0xc2088f7320, 0x1e, 0xc20886f180, 0x0, 0x0)
    /go/src/github.com/docker/docker/registry/config.go:365 +0x55
github.com/docker/docker/registry.NormalizeLocalName(0xc2088f7320, 0x1e, 0x0, 0x0)
    /go/src/github.com/docker/docker/registry/config.go:382 +0x44
github.com/docker/docker/graph.(*TagStore).GetID(0xc208587aa0, 0xc2088f7320, 0x24, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/graph/tags.go:178 +0x117
github.com/docker/docker/daemon.getImage(0xc208587aa0, 0xc2088f7320, 0x24, 0xc208760640, 0x40, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/daemon/list.go:294 +0x13a
github.com/docker/docker/daemon.(*Daemon).transformContainer(0xc208077040, 0xc2086ec600, 0xc208a04660, 0xc20886f180, 0x0, 0x0)
    /go/src/github.com/docker/docker/daemon/list.go:319 +0x28f
github.com/docker/docker/daemon.*Daemon.(github.com/docker/docker/daemon.transformContainer)\ufffd\ufffdfm(0xc2086ec600, 0xc208a04660, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/daemon/list.go:84 +0x4d
github.com/docker/docker/daemon.(*Daemon).reducePsContainer(0xc208077040, 0xc2086ec600, 0xc208a04660, 0xc208a874b0, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/daemon/list.go:127 +0x11c
github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc208077040, 0xc20884b0e0, 0xc208a874b0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/daemon/list.go:97 +0x1bc
github.com/docker/docker/daemon.(*Daemon).Containers(0xc208077040, 0xc20884b0e0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/daemon/list.go:84 +0xa5
github.com/docker/docker/api/server/router/local.(*router).getContainersJSON(0xc20874f520, 0x7f49e5cde008, 0xc208efd4a0, 0x7f49e5cddf58, 0xc208b21e00, 0xc208caf860, 0xc208efd380, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/router/local/container.go:47 +0x3ba
github.com/docker/docker/api/server/router/local.*router.(github.com/docker/docker/api/server/router/local.getContainersJSON)\ufffd\ufffdfm(0x7f49e5cde008, 0xc208efd4a0, 0x7f49e5cddf58, 0xc208b21e00, 0xc208caf860, 0xc208efd380, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/router/local/local.go:109 +0x7b
github.com/docker/docker/api/server.func\ufffd\ufffd004(0x7f49e5cde008, 0xc208efd4a0, 0x7f49e5cddf58, 0xc208b21e00, 0xc208caf860, 0xc208efd380, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/middleware.go:87 +0x7c7
```

Basically what I figured out was that I had a container that was spun up from an image from gcr.io and I had very crappy wifi.  While listing the containers and parsing the image tag it appears that it has to go out to the internet to validate something....  Obviously that is bad and slow.

**Comment by ibuildthecloud** [comment]
@LK4D4 @tiborvass

**Comment by tiborvass** [comment]
Thanks @ibuildthecloud will look into it

**Comment by tiborvass** [comment]
@ibuildthecloud can you try with cherrypicking #17087 ?

**Comment by ibuildthecloud** [comment]
@tiborvass I believe that commit is in rc1 already, right?

**Comment by tiborvass** [comment]
@ibuildthecloud damn you're right ... :( tired

**Comment by calavera** [comment]
Fixing
