### ISSUE TITLE
v1.9.1: cannot create container due to missing cgroup.procs file

### ISSUE THREAD

**Issue by yoanisgil** [docker/docker#18128]
We have this internal tool for deploying our containers, the main script looks like this:

https://gist.github.com/yoanisgil/6277a17e1766b533b70d

We have been using it for some months now with Docker 1.8.x. Recently we decided to upgrade to Docker 1.9. However I hit this bug from time to time and on what it seems to be a very random manner:

```
2015-11-20 10:08:07,180 - roll.single.deploy - INFO - Starting container 2b0e5d7e34402e145d73385b2711e11efa3ef945c561d90ff732f0bec27fea04
None None
Traceback (most recent call last):
  File "./single-roll", line 44, in <module>
    deploy.run()
  File "/home/ygil/dev/docker-roll/roll/single/deploy.py", line 111, in run
    self.client.start(new_container.get('Id'))
  File "/home/ygil/.envs/docker-roll/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ygil/.envs/docker-roll/lib/python2.7/site-packages/docker/api/container.py", line 344, in start
    self._raise_for_status(res)
  File "/home/ygil/.envs/docker-roll/lib/python2.7/site-packages/docker/client.py", line 142, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot start container 2b0e5d7e34402e145d73385b2711e11efa3ef945c561d90ff732f0bec27fea04: [8] System error: open /sys/fs/cgroup/devices/system.slice/docker-2b0e5d7e34402e145d73385b2711e11efa3ef945c561d90ff732f0bec27fea04.scope/cgroup.procs: no such file or directory")
```

We run the script like this:

```bash
SLEEP=0 DOCKER_HOST='tcp://aws038:2375' ./single-roll docker-roll-config.yml crakmedia/crakrevenue-affiliate:5.10.1
```
Here is some context information (providing this since our deployment script uses docker-py):

Pip
============

```bash
pip list
coverage (3.7.1)
docker-py (1.5.0)
docker-roll (0.0.5)
nose (1.3.7)
pip (7.1.2)
pyaml (15.6.3)
python-consul (0.4.2)
PyYAML (3.11)
requests (2.8.1)
setuptools (18.0.1)
six (1.10.0)
websocket-client (0.32.0)
wheel (0.24.0)
```

```bash
$ docker version
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64
```

OS Information
===========

```
OS: CentOS 7
Kernel version: uname -a
Linux aws074.crakmedia.lan 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Docker was installed from CentOS's official repo:

```bash
$yum info docker-engine
Installed Packages
Name        : docker-engine
Arch        : x86_64
Version     : 1.9.1
Release     : 1.el7.centos
Size        : 36 M
Repo        : installed
From repo   : docker-main-repo
Summary     : The open-source application container engine
URL         : https://dockerproject.org
License     : ASL 2.0
Description : Docker is an open source project to build, ship and run any application as a
            : lightweight container.
            :
            : Docker containers are both hardware-agnostic and platform-agnostic. This means
            : they can run anywhere, from your laptop to the largest EC2 compute instance and
            : everything in between - and they don't require you to use a particular
            : language, framework or packaging system. That makes them great building blocks
            : for deploying and scaling web apps, databases, and backend services without
            : depending on a particular stack or provider.
```

**Comment by yoanisgil** [comment]
I must say I cannot consistently reproduce this. In the beginning I thought it was related to either Swarm or the fact that it takes two API calls to run a container using docker-py (see here https://github.com/docker/docker-py/issues/857). However after further testing, I hit the same bug when not using Swarm.

**Comment by crosbymichael** [comment]
This is a dup of #17653

Please see this comment for a workaround, this is a systemd issue.

https://github.com/docker/docker/issues/17653#issuecomment-155609224

**Comment by yoanisgil** [comment]
@crosbymichael thanks for the quick reply. Will look into mentioned ticket.
