### ISSUE TITLE
 Running GUI :: works on Debian, not Fedora

### ISSUE THREAD

**Issue by auzias** [docker/docker#18361]
Hi everyone.
I'm trying to run arduino IDE from within a Docker. It starts on a Debian machine but not on a Fedora.

_Note that this was partly reported, **before I checked whether it works on Debian or not**, on [forums.docker.com](https://forums.docker.com/t/running-gui-in-docker/4721) and [stackoverflow.com](https://stackoverflow.com/questions/34017038/running-gui-in-docker-no-ssh-no-vnc)._

---

#### Dockerfile
    FROM ubuntu:14.04
    MAINTAINER Mael Auzias <docker@mael.auzias.net>
    
    ENV HOME /home/arduino
    ENV USER arduino

    RUN apt-get update && apt-get install -y \
       libx11-6 libxext-dev libxrender-dev libxtst-dev \
        --no-install-recommends \
        && useradd --create-home --home-dir $HOME $USER \
        && chown -R $USER:$USER $HOME

    ADD arduino-1.6.6-linux64.tar.xz $HOME

    WORKDIR $HOME/arduino-1.6.6
    USER $USER

    ENTRYPOINT ["/bin/bash"]

---

#### Docker-run command
I spent time to understand how does [Jessica Frazelle usually starts her graphical containers](https://github.com/jfrazelle/dotfiles/blob/master/.dockerfunc) to rightly start mine with the command:

    $docker run --name arduino --rm -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix 25af73b6cb3c ./arduino

#### On Debian
On debian wheezy it starts, I can see the loading screen, but a Java error occurs though, but not related to Docker IMO:
````bash
Picked up JAVA_TOOL_OPTIONS: 
java.lang.Error: Cannot load com.sun.java.swing.plaf.gtk.GTKLookAndFeel
        at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1351)
        at javax.swing.UIManager.initialize(UIManager.java:1459)
        at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)
        at javax.swing.UIManager.getLookAndFeel(UIManager.java:492)
        at processing.app.linux.GTKLookAndFeelFixer.installGtkPopupBugWorkaround(GTKLookAndFeelFixer.java:79)
        at processing.app.linux.Platform.setLookAndFeel(Platform.java:48)
        at processing.app.Base.guardedMain(Base.java:210)
        at processing.app.Base.main(Base.java:135)
````

#### On Fedora
    No protocol specified
    Picked up JAVA_TOOL_OPTIONS: 
    No protocol specified
    Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.

I installed `strace` and check with `xeyes` what was wrong, and I get the following error:

    connect(3, {sa_family=AF_LOCAL, sun_path=@"/tmp/.X11-unix/X0"}, 20) = -1 ECONNREFUSED (Connection refused)

---

##### Debian
**`docker version`**
````
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:37:20 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:37:20 UTC 2015
 OS/Arch:      linux/amd64
````
**`docker info`**
````
Containers: 223
Images: 138
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 588
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 4
Total Memory: 7.694 GiB
Name: pc-mna-139
ID: DCVR:5T6Y:56LZ:SYPQ:KTAE:TUWE:VUPV:X3BJ:6AIH:EHK4:VNT2:BAZD
WARNING: No memory limit support
WARNING: No swap limit support
````
**`uname -a`**
````
Linux pc-mna-139 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u4~bpo70+1 (2015-09-22) x86_64 GNU/Linux
````

##### Fedora
**`docker version`**
````
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:39:26 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:39:26 UTC 2015
 OS/Arch:      linux/amd64
````
**`docker info`**
````
Containers: 5
Images: 39
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:2-921840-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.825 GB
 Data Space Total: 107.4 GB
 Data Space Available: 48.68 GB
 Metadata Space Used: 3.187 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.6-301.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
CPUs: 4
Total Memory: 15.64 GiB
Name: fire
ID: K5ZP:GRSC:G22J:TRWR:YC5Z:AVH6:GWOJ:CSHM:YMGM:KWOT:OU33:JJ7H
````
**`uname -a`**
````
Linux fire 4.2.6-301.fc23.x86_64 #1 SMP Fri Nov 20 22:22:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
````

**Comment by thaJeztah** [comment]
I wonder if this could be a SELinux issue, i.e., SELinux blocking access. But I'm not really good at that :smile:

**Comment by auzias** [comment]
Me neither, not at all. I just install Fedora two weeks ago, still new for me.

**Comment by thaJeztah** [comment]
Might be worth checking https://wiki.gentoo.org/wiki/SELinux/Tutorials/Where_to_find_SELinux_permission_denial_details and http://selinuxproject.org/page/NB_AL (just a quick google)

**Comment by cpuguy83** [comment]
On Fedora you probably need `--privileged` to bypass selinux and gain access to the socket.

**Comment by auzias** [comment]
_Environment updated in the first post_

@cpuguy83 I tried with `--privileged` but it does not work either.
###### With `--privileged`
````
type=ANOM_PROMISCUOUS msg=audit(1449087305.287:730): dev=vethfcc72de prom=256 old_prom=0 auid=4294967295 uid=0 gid=0 ses=4294967295
type=NETFILTER_CFG msg=audit(1449087305.305:731): table=filter family=2 entries=0
type=NETFILTER_CFG msg=audit(1449087305.305:732): table=raw family=2 entries=0
type=NETFILTER_CFG msg=audit(1449087305.305:733): table=security family=2 entries=0
type=NETFILTER_CFG msg=audit(1449087305.305:734): table=nat family=2 entries=0
type=NETFILTER_CFG msg=audit(1449087305.305:735): table=mangle family=2 entries=0
type=NETFILTER_CFG msg=audit(1449087305.305:736): table=filter family=10 entries=0
type=NETFILTER_CFG msg=audit(1449087305.305:737): table=raw family=10 entries=0
type=NETFILTER_CFG msg=audit(1449087305.306:738): table=security family=10 entries=0
type=NETFILTER_CFG msg=audit(1449087305.306:739): table=nat family=10 entries=0
type=NETFILTER_CFG msg=audit(1449087305.306:740): table=mangle family=10 entries=0
type=USER_AVC msg=audit(1449087305.308:741): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='Unknown permission start for class system exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
type=USER_AVC msg=audit(1449087305.606:742): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='Unknown permission stop for class system exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
type=USER_AVC msg=audit(1449087305.608:743): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='Unknown permission stop for class system exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
type=ANOM_PROMISCUOUS msg=audit(1449087305.643:744): dev=vethfcc72de prom=0 old_prom=256 auid=4294967295 uid=0 gid=0 ses=4294967295
````


###### Without `--privileged`
````
type=ANOM_PROMISCUOUS msg=audit(1449087436.000:760): dev=vethb0609ac prom=256 old_prom=0 auid=4294967295 uid=0 gid=0 ses=4294967295
type=NETFILTER_CFG msg=audit(1449087436.013:761): table=filter family=2 entries=0
type=NETFILTER_CFG msg=audit(1449087436.013:762): table=raw family=2 entries=0
type=NETFILTER_CFG msg=audit(1449087436.013:763): table=security family=2 entries=0
type=NETFILTER_CFG msg=audit(1449087436.013:764): table=nat family=2 entries=0
type=NETFILTER_CFG msg=audit(1449087436.013:765): table=mangle family=2 entries=0
type=NETFILTER_CFG msg=audit(1449087436.013:766): table=filter family=10 entries=0
type=NETFILTER_CFG msg=audit(1449087436.013:767): table=raw family=10 entries=0
type=NETFILTER_CFG msg=audit(1449087436.013:768): table=security family=10 entries=0
type=NETFILTER_CFG msg=audit(1449087436.013:769): table=nat family=10 entries=0
type=NETFILTER_CFG msg=audit(1449087436.013:770): table=mangle family=10 entries=0
type=USER_AVC msg=audit(1449087436.016:771): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='Unknown permission start for class system exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
type=USER_AVC msg=audit(1449087436.311:772): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='Unknown permission stop for class system exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
type=USER_AVC msg=audit(1449087436.311:773): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='Unknown permission stop for class system exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
type=ANOM_PROMISCUOUS msg=audit(1449087436.353:774): dev=vethb0609ac prom=0 old_prom=256 auid=4294967295 uid=0 gid=0 ses=4294967295
````


I don't have more time for now, but I'll dig it up later on.

**Comment by infoslack** [comment]
The  xhost is  used to add and delete host names or user names to the list allowed to make connections to the X server.  In this case I believe it is disabled.

You can try to activate with the `xhost +` instruction before creating the container.

**Comment by auzias** [comment]
Got some news...

As the user root I cannot start graphical application. When I `su regular-user` and start `xterm` or `xeyes` it works. I don't really understand why though :/

**Comment by auzias** [comment]
This issue is resolved and can be closed.

**Comment by thaJeztah** [comment]
Thanks @auzias! Feel free to continue the discussion if needed; I don't think this is a docker bug, but it may help people trying this :+1:

**Comment by timthelion** [comment]
FYI, the [subuser](http://subuser.org) project deals with this issue. If you want to copy scripts from us, you can find the xauth setup code here: https://github.com/subuser-security/subuser/blob/b175efadbaaeceabe2e693666a458ff2cebf66e7/logic/subuserlib/classes/subuserSubmodules/run/runtime.py#L220

````python
  def setupXauth(self):
    try:
      self.getUser().getEndUser().makedirs(self.getXautorityDirPath())
    except OSError: #Already exists
      pass
    try:
      os.remove(self.getXautorityFilePath())
    except OSError:
      pass
    subuserlib.subprocessExtras.call(self.getUser().getEndUser().getSudoArgs()+["xauth","extract",".Xauthority",self.getEnvironment()["DISPLAY"]],cwd=self.getXautorityDirPath())
    with open(self.getXautorityFilePath(),"rb") as xauthFile:
      # The extracted Xauthority file has the following format(bytewise):
      # 1 0 0 [len(hostname)] [hostname-in-ascii] 0 1 [display-number-in-ascii] 0 22 ["MIT-MAGIC-COOKIE-1"-in-ascii] 0 20 [Magic number]
      # The goal here, is to change the hostname...
      # BTW, either I am doing this totally wrong,
      # or python is terrible at dealing with binary files...
      start=xauthFile.read(3)
      lengthOfHostname = struct.unpack("b",xauthFile.read(1))[0]
      hostnameOfHost = xauthFile.read(lengthOfHostname)
      rest = xauthFile.read()
    with open(self.getXautorityFilePath(),"wb") as xauthFile:
      xauthFile.write(start)
      hostname = self.getHostname()
      xauthFile.write(struct.pack("b",len(hostname)))
      xauthFile.write(hostname)
      xauthFile.write(rest)
````

What this code does is it runs `xauth extract` on the host to get a valid xauth cookie file for the current display. It then fiddles that cookie file to configure it to be accepted by the docker container, and then it inserts that modified cookie file into the docker container.

**Comment by auzias** [comment]
Explanation on [root and GUI issue](http://unix.stackexchange.com/questions/118811/why-cant-i-run-gui-apps-from-root-no-protocol-specified#answer-118826)
