### ISSUE TITLE
'docker logs' does not update when there is an infinite loop

### ISSUE THREAD

**Issue by eliothxchan** [docker/docker#18573]
Hey guys. Perhaps this issue is really niche and not useful to fix, or perhaps I'm just not correctly understanding the way the logs are updated, but I'm trying to write a python container that has a long-running script that I can use to generate some reports on a database once a week.

As such, there's an infinite loop in the code, and when I attempted to test it using docker logs, the logs are empty. Here's a simplified version of my code:

```
#Email sending
from postmark import PMMail

#Scheduler
import schedule
import time

def testSchedule():
    print 'Testeroni'
    message = PMMail(api_key = os.environ['KEY_POSTMARK'],
                    subject = 'Swoopity Schedule',
                    sender = 'TEST@test.test',
                    to = 'myemail@test.test',
                    text_body = 'Moocaroon'
                    )
    message.send()

schedule.every(1).minutes.do(testSchedule)

while True:
    schedule.run_pending()
    time.sleep(1)

```

and my Dockerfile:

```
FROM python:2.7.10-onbuild
RUN mkdir /report-generator/
ADD . /report-generator/
CMD cd /report-generator && python generateReports.py
```

I've also got a requirements.txt for the container, but I highly doubt that's relevant to the issue. The container performs its functions correctly - I get the emails, but the console just doesn't update.

Steps to Reproduce:

```
docker build -t report-generator
docker stop report-generator
docker rm report-generator
docker run -d \
    --name report-generator \
    -e KEY_POSTMARK=MYKEYHERE \
    echan/report-generator
#Wait for a few minutes
docker logs report-generator
```

I expect it to log 'Testeroni' a couple of times, but I get no output instead.

docker version: 

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

docker info:

```
Containers: 23
Images: 528
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 574
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: HZUP:4FTM:4ITH:JC4T:KPEV:WZBP:UXXY:RZGL:EHAK:ZJPH:LKC4:RCYG
Debug mode (server): true
File Descriptors: 41
Goroutines: 67
System Time: 2015-12-10T15:55:54.475316374Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

uname -a:

```
Darwin Eliots-MacBook-Pro-2.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

**Comment by eliothxchan** [comment]
docker version: 

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

docker info:

```
Containers: 23
Images: 528
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 574
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: HZUP:4FTM:4ITH:JC4T:KPEV:WZBP:UXXY:RZGL:EHAK:ZJPH:LKC4:RCYG
Debug mode (server): true
File Descriptors: 41
Goroutines: 67
System Time: 2015-12-10T15:55:54.475316374Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

uname -a:

```
Darwin Eliots-MacBook-Pro-2.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

**Comment by MHBauer** [comment]
You need to allocate a terminal with `-t`. Otherwise there is no stdout to print to.

**Comment by eliothxchan** [comment]
Yeah, I do so when I build the container. I'll update the OP with my build command as well.

**Comment by MHBauer** [comment]
I do mean with `run`. Gotta have a tty to have somewhere to print to, as I understand it.

**Comment by duglin** [comment]
try running the container w/o the -d so the output goes to the screen and see if that works.

**Comment by MHBauer** [comment]
I'm gonna go with python output buffering until I see a counterexample.

```
λ docker run -d python:2.7.10 python -c "exec(\"print 'test' \\nwhile True: pass\")"
188f56a2edeb305636591ca2b2190f7cf4d545d252cadd224c1e9e2dc672d165

λ docker run -d python:2.7.10 python -u -c "exec(\"print 'test' \\nwhile True: pass\")"
1e4bcb8dbf876561f1a6a0c0db4f6973378cf168aa8f8737e7272be8ff7da91a

λ docker ps
CONTAINER ID        IMAGE               COMMAND                   CREATED             STATUS              PORTS               NAMES
188f56a2edeb        python:2.7.10       "python -c 'exec(\"pri"   2 seconds ago       Up 1 seconds                            silly_bose
1e4bcb8dbf87        python:2.7.10       "python -u -c 'exec(\""   27 seconds ago      Up 26 seconds                           tiny_bhabha


λ docker logs 1e4bcb8dbf876561f1a6a0c0db4f6973378cf168aa8f8737e7272be8ff7da91a
test

λ docker logs 188f56a2edeb305636591ca2b2190f7cf4d545d252cadd224c1e9e2dc672d165
[mhb@morgans-mbp:~/src/testing/report-gen] 2015-12-10 17:27:30


λ docker run python:2.7.10 python -c "exec(\"print 'test' \\nwhile True: pass\")"
^Ctest
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 2, in <module>
KeyboardInterrupt

λ docker run python:2.7.10 python -u -c "exec(\"print 'test' \\nwhile True: pass\")"
test
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 2, in <module>
λ
```

Notice when the 'C-c' appears in the printed output.

**Comment by eliothxchan** [comment]
Tried running it with the -t flag and it seems like it works. Thanks!

But it's odd, if I 

1) Have the loop without the -t flag -> docker logs has no output
2) Have the loop with the -t flag -> docker logs has output
3) Don't have the loop without the -t -> docker logs has output

I'm not sure I quite understand why this happens, do you mind explaining?

**Comment by MHBauer** [comment]
My guess is python sees stdout attached to a pipe and not a tty, so the output gets buffered. (probably a 4k page, so your output will *eventually* show up, but not for a while). Leave it go for a while.

A while = about seven and a half hours
"testeroni" is nine chars
9/4096 = ~455 
455/60 = 7.58

**Comment by eliothxchan** [comment]
Jesus.

I see, that makes much more sense now - thanks a lot for your help!

**Comment by MHBauer** [comment]
Just, to be clear, the first example ran python with `-u` for unbuffered output. I have no idea if that has any performance implications for your case, but it might be nice for testing.
