### ISSUE TITLE
Dockerfile fails to build on overlay but works on aufs

### ISSUE THREAD

**Issue by grahamc** [docker/docker#19262]
The following Dockerfile fails to build on Overlay, but works on AUFS. I replicated this on two machines, docker-machine built and one running ubuntu trusty with linux kernel 4.2.

```Dockerfile
FROM python:3.4
RUN pip install flake8==2.5.1
RUN pip install flake8==2.5.0
```

Note it also fails with `python:3.5`, however changing it to the following works fine:

```Dockerfile
FROM python:3.4
RUN pip install flake8==2.5.1 && pip install flake8==2.5.0
```

**Note:** I know installing flake8 then installing a lesser version isn't great, but that doesn't change the fact that this is a bug. The problem is only exhibited on overlay, and not any other storage driver I've tried.

Build output on overlay:

```
➜  overlaybug  docker build --pull --no-cache  -t overlaybug .
Sending build context to Docker daemon 8.704 kB
Step 1 : FROM python:3.4
3.4: Pulling from library/python
523ef1d23f22: Pull complete
140f9bdfeb97: Pull complete
5c63804eac90: Pull complete
ce2b29af7753: Pull complete
5c2bdca41b86: Pull complete
b48f4076b06d: Pull complete
d6788afe8670: Pull complete
a81a1086b672: Pull complete
15b1f796b9f0: Pull complete
1efcb21adee7: Pull complete
d1dcef8ab76f: Pull complete
dd40266492e1: Pull complete
285252a442bf: Pull complete
Digest: sha256:19e0ba3b85f69233ab0d06954a58afa2672f659c6cb9bf86807d292c417a8dea
Status: Downloaded newer image for python:3.4
 ---> 285252a442bf
Step 2 : RUN pip install flake8==2.5.1
 ---> Running in 945cdf613f1c
Collecting flake8==2.5.1
  Downloading flake8-2.5.1-py2.py3-none-any.whl
Collecting pyflakes<1.1,>=0.8.1 (from flake8==2.5.1)
  Downloading pyflakes-1.0.0-py2.py3-none-any.whl (152kB)
Collecting pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7 (from flake8==2.5.1)
  Downloading pep8-1.5.7-py2.py3-none-any.whl
Collecting mccabe<0.4,>=0.2.1 (from flake8==2.5.1)
  Downloading mccabe-0.3.1-py2.py3-none-any.whl
Installing collected packages: pyflakes, pep8, mccabe, flake8
Successfully installed flake8-2.5.1 mccabe-0.3.1 pep8-1.5.7 pyflakes-1.0.0
 ---> 25d407bf5a85
Removing intermediate container 945cdf613f1c
Step 3 : RUN pip install flake8==2.5.0
 ---> Running in 228cd950e051
Collecting flake8==2.5.0
  Downloading flake8-2.5.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): mccabe<0.4,>=0.2.1 in /usr/local/lib/python3.4/site-packages (from flake8==2.5.0)
Requirement already satisfied (use --upgrade to upgrade): pyflakes<1.1,>=0.8.1 in /usr/local/lib/python3.4/site-packages (from flake8==2.5.0)
Requirement already satisfied (use --upgrade to upgrade): pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7 in /usr/local/lib/python3.4/site-packages (from flake8==2.5.0)
Installing collected packages: flake8
  Found existing installation: flake8 2.5.1
    Uninstalling flake8-2.5.1:
      Successfully uninstalled flake8-2.5.1
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/shutil.py", line 424, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'flake8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.4/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/local/lib/python3.4/site-packages/pip/req/req_set.py", line 657, in install
    requirement.commit_uninstall()
  File "/usr/local/lib/python3.4/site-packages/pip/req/req_install.py", line 729, in commit_uninstall
    self.uninstalled.commit()
  File "/usr/local/lib/python3.4/site-packages/pip/req/req_uninstall.py", line 152, in commit
    rmtree(self.save_dir)
  File "/usr/local/lib/python3.4/site-packages/pip/_vendor/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.4/site-packages/pip/_vendor/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.4/site-packages/pip/_vendor/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.4/site-packages/pip/_vendor/six.py", line 659, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/pip/_vendor/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.4/site-packages/pip/utils/__init__.py", line 90, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/local/lib/python3.4/shutil.py", line 468, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/lib/python3.4/shutil.py", line 406, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/lib/python3.4/shutil.py", line 406, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/lib/python3.4/shutil.py", line 406, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/lib/python3.4/shutil.py", line 426, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/lib/python3.4/site-packages/pip/utils/__init__.py", line 98, in rmtree_errorhandler
    if os.stat(path).st_mode & stat.S_IREAD:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-7imwu3vj-uninstall/usr/local/bin/flake8'
The command '/bin/sh -c pip install flake8==2.5.0' returned a non-zero code: 2
```

docker info:
```
➜  overlaybug  docker info
Containers: 16
Images: 37
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: overlaytest
ID: 4WVC:34GK:NLWL:3LFL:QIGK:J6LD:YZL5:DQ47:WL2J:XJRX:6MCZ:DQ6Z
Debug mode (server): true
 File Descriptors: 15
 Goroutines: 20
 System Time: 2016-01-12T16:47:52.96032768Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

docker version:

```
➜  overlaybug  docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Sat Nov 21 00:49:19 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

created via:
```
docker-machine create --driver virtualbox --virtualbox-disk-size 5000 --engine-storage-driver overlay overlaytest
```

No interesting dmesg or docker.log output was found.

**Comment by grahamc** [comment]
Closing as dup of #12327.
