### ISSUE TITLE
panic on NewStoreFromGraphdriver

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#19449]
Reported by @justincormack 

```
time="2016-01-19T14:51:15.264108533Z" level=info msg="Layer sha256:4e0e182967f847e292d3b8c8ebff2cf567c6a38713ddbad9f40e8dad2e603ff4 cleaned up" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x815856]

goroutine 1 [running]:
github.com/docker/docker/layer.NewStoreFromGraphDriver(0x7fd78c5eee38, 0xc820616d80, 0x7fd78c5eed38, 0xc820357220, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/layer/layer_store.go:90 +0x446
github.com/docker/docker/layer.NewStoreFromOptions(0xc820611800, 0xf, 0xc820258140, 0x20, 0x7ffd15737edb, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/layer/layer_store.go:66 +0x496
github.com/docker/docker/daemon.NewDaemon(0xc82032f080, 0xc8203580e0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:707 +0xe36
main.(*DaemonCli).CmdDaemon(0xc820329540, 0xc82000a1a0, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/docker/docker/docker/daemon.go:252 +0x16e6
reflect.callMethod(0xc82027d530, 0xc8206b1c48)
	/usr/local/go/src/reflect/value.go:628 +0x1fc
reflect.methodValueCall(0xc82000a1a0, 0x4, 0x4, 0x1, 0xc82027d530, 0x0, 0x0, 0xc82027d530, 0x0, 0x474114, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc82027d4a0, 0xc82000a190, 0x5, 0x5, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cli.go:89 +0x383
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:63 +0x43c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 51 [chan receive]:
github.com/docker/docker/daemon.setupDumpStackTrap.func1(0xc82013eb40)
	/go/src/github.com/docker/docker/daemon/debugtrap_unix.go:17 +0x4d
created by github.com/docker/docker/daemon.setupDumpStackTrap
	/go/src/github.com/docker/docker/daemon/debugtrap_unix.go:20 +0x12a

goroutine 18 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 50 [select, locked to thread]:
runtime.gopark(0x19ea8c8, 0xc820021f28, 0x16ebe38, 0x6, 0x41c018, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820021f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820021f28)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x815856]

goroutine 1 [running]:
github.com/docker/docker/layer.NewStoreFromGraphDriver(0x7f8e3873eb38, 0xc8205a7bf0, 0x7f8e3873ea38, 0xc820079b80, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/layer/layer_store.go:90 +0x446
github.com/docker/docker/layer.NewStoreFromOptions(0xc8206a3840, 0xf, 0xc8202958e0, 0x20, 0x7ffe86ce0ed6, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/layer/layer_store.go:66 +0x496
github.com/docker/docker/daemon.NewDaemon(0xc82007a840, 0xc8203180c0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:707 +0xe36
main.(*DaemonCli).CmdDaemon(0xc820294f00, 0xc82000a1a0, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/docker/docker/docker/daemon.go:252 +0x16e6
reflect.callMethod(0xc8206accf0, 0xc8206bfc48)
	/usr/local/go/src/reflect/value.go:628 +0x1fc
reflect.methodValueCall(0xc82000a1a0, 0x4, 0x4, 0x1, 0xc8206accf0, 0x0, 0x0, 0xc8206accf0, 0x0, 0x474114, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc8206acc60, 0xc82000a190, 0x5, 0x5, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cli.go:89 +0x383
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:63 +0x43c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 36 [select, locked to thread]:
runtime.gopark(0x19ea8c8, 0xc8205a5728, 0x16ebe38, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc8205a5728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc8205a5728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 37 [chan receive]:
github.com/docker/docker/daemon.setupDumpStackTrap.func1(0xc82036a600)
	/go/src/github.com/docker/docker/daemon/debugtrap_unix.go:17 +0x4d
created by github.com/docker/docker/daemon.setupDumpStackTrap
	/go/src/github.com/docker/docker/daemon/debugtrap_unix.go:20 +0x12a
```

**Comment by cpuguy83** [comment]
Looks like a bug in the store, as there should never be a nil where it's reported in the stack trace.

**Comment by justincormack** [comment]
```
Client:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:17:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:17:17 2016
 OS/Arch:      linux/amd64
```

This is the official build of 1.10.1-rc1

**Comment by dmcgowan** [comment]
Adding a continue when loading a failed layer should prevent this panic. If there is an issue with a referenced layer there still may be a failure. I would be curious to know what the debug line `DEBU[0000] Failed to load layer ...` says.
