### ISSUE TITLE
iptables commands intermittently failing inside of a container 

### ISSUE THREAD

**Issue by aaronjwood** [docker/docker#19808]
I have an application that gets unit tested a lot by Jenkins. Basically Jenkins starts a privileged container to execute these unit tests as some of them trigger changes to netfilter using iptables. I want this code to be executed and tested with what I have but I don't want to actually make any changes to the system's firewall which is why I am running the tests inside of a privileged container.

Every so often, these unit tests fail with the message `route ip+net: netlinkrib: invalid argument`. For example, this morning I saw that one of the unit tests that triggers the application to run `iptables -n -t nat -L -v` failed with the message above. In case it's relevant to know, it's possible that this application will be unit tested and built concurrently as our current CI setup allows for up to 8 parallel jobs. Other people are allowed to trigger this application to get tested and built so I'm sure at times it's running concurrently. Still, I do not think this is the issue as it usually works fine when building concurrently as well as when it's the only job running.

Normally things go fine, it's maybe only once every other day this happens.

Here's my environment:

CoreOS 723.3.0
Docker 1.9.1
Storage diver: overlay
Backing filesystem: extfs
Execution Driver: native-0.2
Kernel: 4.0.5
24 cores/128GB RAM

Here's a good chunk of the failing output from Jenkins:

```
Host 57987cd0274d has triggered a firewall change: iptables-v -I INPUT -i lo -p tcp --dport 10 -j ACCEPT
Host 57987cd0274d has triggered a firewall change: iptables-v -D INPUT -i lo -p tcp --dport 10 -j ACCEPT
Host 57987cd0274d has triggered a firewall change: iptables-v -t nat -I PREROUTING -i lo -p tcp --dport 10 -j DNAT --to-destination 127.0.0.1:11
Host 57987cd0274d has triggered a firewall change: iptables-v -t nat -D PREROUTING -i lo -p tcp --dport 10 -j DNAT --to-destination 127.0.0.1:11
Host 57987cd0274d has triggered a firewall change: iptables-n -t nat -L -v
route ip+net: netlinkrib: invalid argument
--- FAIL: TestSanitize (0.00s)
	sanitize_test.go:219: Failed sanitizing user input for a filter rule
Host 57987cd0274d has triggered a firewall change: iptables-n -t raw -L -v
Host 57987cd0274d has triggered a firewall change: iptables-n -L -v
Host 57987cd0274d has triggered a firewall change: iptables-n -t mangle -L -v
Host 57987cd0274d has triggered a firewall change: ls-l -a
SIGQUIT: quit
PC=0x45f409 m=0

goroutine 0 [idle]:
runtime.epollwait(0x7ffc00000004, 0x7ffcd7bf9770, 0xffffffff00000080, 0x1, 0x1ffffffff, 0x0, 0x0, 0x350faa380000201d, 0x2b6e, 0x0, ...)
	/go/src/runtime/sys_linux_amd64.s:420 +0x19
runtime.netpoll(0xa30901, 0x0)
	/go/src/runtime/netpoll_epoll.go:68 +0x94
runtime.findrunnable(0xc820016000, 0x0)
	/go/src/runtime/proc1.go:1512 +0x598
runtime.schedule()
	/go/src/runtime/proc1.go:1639 +0x267
runtime.park_m(0xc8201b6d80)
	/go/src/runtime/proc1.go:1698 +0x18b
runtime.mcall(0x7ffcd7bf9e80)
	/go/src/runtime/asm_amd64.s:204 +0x5b

goroutine 1 [chan receive]:
testing.RunTests(0x8de8d8, 0xa298c0, 0xd, 0xd, 0x2b6e34f45000)
	/go/src/testing/testing.go:582 +0x558
testing.(*M).Run(0xc8200f9ed8, 0x30)
	/go/src/testing/testing.go:494 +0x70
cloud-platform/services/networking/firewall/src.TestMain(0xc8200f9ed8)
	/gopath/src/cloud-platform/services/networking/firewall/src/server_test.go:14 +0x21
main.main()
	cloud-platform/services/networking/firewall/src/_test/_testmain.go:76 +0x113

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 25 [syscall]:
syscall.Syscall6(0x2d, 0x5, 0xc820270000, 0x1000, 0x0, 0xc820228710, 0xc82022870c, 0xc8201b6600, 0xc8201b66b0, 0x433b4f)
	/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.recvfrom(0x5, 0xc820270000, 0x1000, 0x1000, 0x0, 0xc820228710, 0xc82022870c, 0x40faf9, 0x0, 0x0)
	/go/src/syscall/zsyscall_linux_amd64.go:1712 +0x91
syscall.Recvfrom(0x5, 0xc820270000, 0x1000, 0x1000, 0x0, 0x1000, 0x0, 0x0, 0x0, 0x0)
	/go/src/syscall/syscall_unix.go:244 +0xb8
syscall.NetlinkRIB(0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/syscall/netlink_linux.go:71 +0x3b0
net.interfaceTable(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/net/interface_linux.go:17 +0x64
net.Interfaces(0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/net/interface.go:89 +0x47
cloud-platform/services/networking/firewall/src.AllInterfaces(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/cloud-platform/services/networking/firewall/src/networking.go:14 +0x7f
cloud-platform/services/networking/firewall/src.Whitelist.ValidateInterface(0x0, 0x82ec38, 0x4, 0x10082d780)
	/gopath/src/cloud-platform/services/networking/firewall/src/sanitize.go:22 +0x27
cloud-platform/services/networking/firewall/src.TestValidateInterface(0xc8201c8120)
	/gopath/src/cloud-platform/services/networking/firewall/src/sanitize_test.go:17 +0x4d
testing.tRunner(0xc8201c8120, 0xa299b0)
	/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/go/src/testing/testing.go:561 +0x86d

goroutine 26 [chan receive]:
testing.RunTests.func1(0xc820011020, 0xc8201c8120)
	/go/src/testing/testing.go:565 +0x47
created by testing.RunTests
	/go/src/testing/testing.go:566 +0x90e

rax    0xfffffffffffffffc
rbx    0xffffffff
rcx    0x45f409
rdx    0x80
rdi    0x4
rsi    0x7ffcd7bf9770
rbp    0x2b6e350faa38
rsp    0x7ffcd7bf9730
r8     0xa31140
r9     0x0
r10    0xffffffff
r11    0x246
r12    0x8
r13    0x8db464
r14    0x1
r15    0x8
rip    0x45f409
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
```

Here's the unit test that triggers eventually causes the issue:

```
//Tests returning a list of all the rules in the NAT table
func TestAllNatRules(t *testing.T) {
	t.Parallel()

	output, err := AllNatRules()

	if err != nil {
		t.Fatal("Listing NAT rules failed: " + err.Error())
	}

	if output == "" {
		t.Fatal("No output from listing NAT rules")
	}
}
```

Here's what the `AllNatRules()` function looks like that the test calls:

```
//Returns a verbose listing of all rules in the NAT table
func AllNatRules() (string, error) {
	return Run("iptables", "-n", "-t", "nat", "-L", "-v")
}
```

And here's what `Run()` looks like:

```
//Runs an iptables command with a variable amount of arguments
func Run(command string, args ...string) (string, error) {
	out, err := exec.Command(command, args...).CombinedOutput()
	if err != nil {
		log.Println(err.Error())
	}

	hostname, err := os.Hostname()
	if err != nil {
		log.Println(err.Error())
	} else {
		log.Println("Host "+hostname+" has triggered a firewall change: "+command+strings.Join(args, " "))
	}

	return string(out), err
}
```

**Comment by aaronjwood** [comment]
Looking into this more, this seems like it could be caused by my tests running in parallel. I found a few things relating to iptables failures when people were using it or testing against it concurrently. I'm going to run a bunch of tests for this today. I'll report back with what I find.

FWIW here's what I found on the subject:
https://bugzilla.kernel.org/show_bug.cgi?id=36422
https://github.com/ClusterHQ/flocker/issues/97

**Comment by aaronjwood** [comment]
Okay, so what I did was run my unit tests in a tight loop. Even though most of the tests execute concurrently I ran this loop in multiple shells just to increase the amount of parallelism. I was unable to reproduce any errors by just running `while true; do go test; done` inside of a container.

What I tried next was to run exactly what Jenkins runs when testing and building my stuff but in a tight loop like I did above. It looks something like this (with a few things masked out) `while true; do docker run -it --rm  "--privileged" -v /usr/local/bin/docker:/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v /lib/libdevmapper.so.1.02:/lib/libdevmapper.so.1.02 -v <MY LOCAL GOPATH>:/gopath/src <CONTAINER NAME>:<CONTAINER VERSION> bash -c  "cd <PATH TO MY STUFF>; make test"; done`. What I found when running this was that every so often different commands would exit with the status code 4:

```
Host 9264780868fa has triggered a firewall change: iptables-v -I INPUT -i lo -p tcp --dport 10 -j ACCEPT
Host 9264780868fa has triggered a firewall change: iptables-v -D INPUT -i lo -p tcp --dport 10 -j ACCEPT
Host 9264780868fa has triggered a firewall change: iptables-v -t nat -I PREROUTING -i lo -p tcp --dport 10 -j DNAT --to-destination 127.0.0.1:11
Host 9264780868fa has triggered a firewall change: iptables-v -t nat -D PREROUTING -i lo -p tcp --dport 10 -j DNAT --to-destination 127.0.0.1:11
Host 9264780868fa has triggered a firewall change: iptables-n -t nat -L -v
Host 9264780868fa has triggered a firewall change: iptables-n -L -v
Host 9264780868fa has triggered a firewall change: iptables-n -t raw -L -v
exit status 4
Host 9264780868fa has triggered a firewall change: iptables-n -t mangle -L -v
Host 9264780868fa has triggered a firewall change: ls-l -a
```

```
Host 8ca640d36068 has triggered a firewall change: iptables-v -I INPUT -i lo -p tcp --dport 10 -j ACCEPT
Host 8ca640d36068 has triggered a firewall change: iptables-v -D INPUT -i lo -p tcp --dport 10 -j ACCEPT
Host 8ca640d36068 has triggered a firewall change: iptables-v -t nat -I PREROUTING -i lo -p tcp --dport 10 -j DNAT --to-destination 127.0.0.1:11
Host 8ca640d36068 has triggered a firewall change: iptables-v -t nat -D PREROUTING -i lo -p tcp --dport 10 -j DNAT --to-destination 127.0.0.1:11
Host 8ca640d36068 has triggered a firewall change: iptables-n -L -v
Host 8ca640d36068 has triggered a firewall change: iptables-n -t nat -L -v
exit status 4
Host 8ca640d36068 has triggered a firewall change: iptables-n -t raw -L -v
Host 8ca640d36068 has triggered a firewall change: iptables-n -t mangle -L -v
Host 8ca640d36068 has triggered a firewall change: ls-l -a
```

```
Host 1f8151d66ebc has triggered a firewall change: iptables-v -I INPUT -i lo -p tcp --dport 10 -j ACCEPT
Host 1f8151d66ebc has triggered a firewall change: iptables-v -D INPUT -i lo -p tcp --dport 10 -j ACCEPT
Host 1f8151d66ebc has triggered a firewall change: iptables-v -t nat -I PREROUTING -i lo -p tcp --dport 10 -j DNAT --to-destination 127.0.0.1:11
Host 1f8151d66ebc has triggered a firewall change: iptables-v -t nat -D PREROUTING -i lo -p tcp --dport 10 -j DNAT --to-destination 127.0.0.1:11
exit status 4
Host 1f8151d66ebc has triggered a firewall change: iptables-n -t nat -L -v
Host 1f8151d66ebc has triggered a firewall change: iptables-n -L -v
Host 1f8151d66ebc has triggered a firewall change: iptables-n -t mangle -L -v
Host 1f8151d66ebc has triggered a firewall change: iptables-n -t raw -L -v
Host 1f8151d66ebc has triggered a firewall change: ls-l -a
```

```
Host 046ae872931c has triggered a firewall change: iptables-v -I INPUT -i lo -p tcp --dport 10 -j ACCEPT
Host 046ae872931c has triggered a firewall change: iptables-v -D INPUT -i lo -p tcp --dport 10 -j ACCEPT
Host 046ae872931c has triggered a firewall change: iptables-v -t nat -I PREROUTING -i lo -p tcp --dport 10 -j DNAT --to-destination 127.0.0.1:11
Host 046ae872931c has triggered a firewall change: iptables-v -t nat -D PREROUTING -i lo -p tcp --dport 10 -j DNAT --to-destination 127.0.0.1:11
Host 046ae872931c has triggered a firewall change: iptables-n -t nat -L -v
Host 046ae872931c has triggered a firewall change: iptables-n -L -v
exit status 4
Host 046ae872931c has triggered a firewall change: iptables-n -t raw -L -v
Host 046ae872931c has triggered a firewall change: iptables-n -t mangle -L -v
Host 046ae872931c has triggered a firewall change: ls-l -a
```

It looks like iptables can exit with status 4 if two or more processes tries to update the same table again and again.

I removed `t.Parallel()` from all of my tests that eventually it iptables underneath and it seems to have solved the issue. Definitely seemed like a race condition. Nasty nasty!

My fault for opening this issue against Docker :)
