### ISSUE TITLE
[1.10.1] PANIC!!!!  json-file file poller writing to closed channel

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#20449]
```
^[[33mWARN^[[0m[122022] falling back to file poller                   ^[[33mlogger^[[0m=json-file
^[[33mWARN^[[0m[122022] falling back to file poller                   ^[[33mlogger^[[0m=json-file
panic: send on closed channel

goroutine 826 [running]:
github.com/docker/docker/pkg/filenotify.(*filePoller).sendEvent(0xc82067f4d0, 0xc8212185dc, 0x49, 0x2, 0xc821206fc0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/filenotify/poller.go:128 +0x164
github.com/docker/docker/pkg/filenotify.(*filePoller).watch(0xc82067f4d0, 0xc8208cef58, 0x7f9e927b4648, 0xc822146cd0, 0xc821206fc0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/filenotify/poller.go:198 +0x676
created by github.com/docker/docker/pkg/filenotify.(*filePoller).Add
        /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/filenotify/poller.go:69 +0x37e
```

```
docker version; docker info
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 211
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 229
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.16.0-60-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.614 GiB
Name: latest-ubuntu-10acre-master-0
ID: CTQE:ZJYW:32GS:VW7F:GR2C:FRPM:5KZI:6X4L:EBDT:ZOXX:JFE5:P3KP
WARNING: No swap limit support
````

**Comment by cpuguy83** [comment]
Thanks, this is already fixed on master.

**Comment by ibuildthecloud** [comment]
@cpuguy83 Is there going to be a 1.10.2?  Docker 1.10.1 is completely unstable on Ubuntu 14.04

**Comment by cpuguy83** [comment]
I'm not sure. But keep in mind the poller is only used as a fallback when inotify is not available.
How come it's falling back?

**Comment by ibuildthecloud** [comment]
@cpuguy83 I have no clue.  I don't believe it prints the error why it falls back.
