### ISSUE TITLE
`An error occurred trying to connect: Post ... EOF` upon a `docker pull`

### ISSUE THREAD

**Issue by netvl** [docker/docker#21213]
**Output of `docker version`:**

```
% docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Sat Mar 12 04:07:39 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
% docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: vdocker
ID: XHZF:YJ53:FYDP:LQXB:76JF:6ODQ:FXXR:JX3C:B76F:EPOV:47FW:WOAM
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 24
 System Time: 2016-03-15T10:38:52.938565211Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: netvl
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm using docker-machine with the latest boot2docker image on VirtualBox on OS X 10.10. Recreating the machine didn't help.

**Steps to reproduce the issue:**
1. Run `docker pull qubell/scratch`

**Describe the results you received:**

Got the following error:
```
% docker pull qubell/scratch
Using default tag: latest
An error occurred trying to connect: Post https://192.168.99.100:2376/v1.22/images/create?fromImage=qubell%2Fscratch%3Alatest: EOF
```

**Describe the results you expected:**

Expected the image to be downloaded correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

This looks like a regression, because it worked in Docker 1.9. Other images that I've tried are pulled just fine.

I think that the fact that `qubell/scratch` is basically just `scratch` may be important. I also see the following message in the daemon log:

```
time="2016-03-15T10:40:11.095837171Z" level=debug msg="Calling POST /v1.22/images/create"
time="2016-03-15T10:40:11.095856985Z" level=debug msg="POST /v1.22/images/create?fromImage=qubell%2Fscratch%3Alatest"
time="2016-03-15T10:40:11.095926245Z" level=debug msg="Trying to pull qubell/scratch from https://registry-1.docker.io v2"
time="2016-03-15T10:40:12.930265152Z" level=debug msg="Increasing token expiration to: 0 seconds"
time="2016-03-15T10:40:14.185832576Z" level=debug msg="Pulling ref from V2 registry: qubell/scratch:latest"
2016/03/15 10:40:14 http: panic serving 192.168.99.1:60234: runtime error: invalid memory address or nil pointer dereference
goroutine 390 [running]:
net/http.(*conn).serve.func1(0xc820071130, 0x7fa2d8312a78, 0xc82011b600)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/docker/docker/layer.(*layerStore).Release(0xc820188f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/layer/layer_store.go:404 +0xc0
github.com/docker/docker/layer.ReleaseAndLog(0x7fa2d8362158, 0xc820188f00, 0x0, 0x0)
	/go/src/github.com/docker/docker/layer/layer.go:243 +0x75
github.com/docker/docker/distribution/xfer.(*LayerDownloadManager).Download.func1()
	/go/src/github.com/docker/docker/distribution/xfer/download.go:145 +0x4b
github.com/docker/docker/distribution.(*v2Puller).pullSchema1(0xc820874480, 0x7fa2d831ba40, 0xc820fa1140, 0x7fa2d831b9a0, 0xc820e08570, 0xc8215eb550, 0xc820c33540, 0x47, 0xc820c33590, 0x47, ...)
	/go/src/github.com/docker/docker/distribution/pull_v2.go:376 +0xa60
github.com/docker/docker/distribution.(*v2Puller).pullV2Tag(0xc820874480, 0x7fa2d831ba40, 0xc820fa1140, 0x7fa2d831b9a0, 0xc820e08570, 0xc820e08680, 0x0, 0x0)
	/go/src/github.com/docker/docker/distribution/pull_v2.go:262 +0x83c
github.com/docker/docker/distribution.(*v2Puller).pullV2Repository(0xc820874480, 0x7fa2d831ba40, 0xc820fa1140, 0x7fa2d831b9a0, 0xc820e08570, 0x0, 0x0)
	/go/src/github.com/docker/docker/distribution/pull_v2.go:69 +0xdb
github.com/docker/docker/distribution.(*v2Puller).Pull(0xc820874480, 0x7fa2d831ba40, 0xc820fa1140, 0x7fa2d831b9a0, 0xc820e08570, 0x0, 0x0)
	/go/src/github.com/docker/docker/distribution/pull_v2.go:54 +0x332
github.com/docker/docker/distribution.Pull(0x7fa2d831ba40, 0xc820fa1140, 0x7fa2d831b9a0, 0xc820e08570, 0xc8208baee0, 0x0, 0x0)
	/go/src/github.com/docker/docker/distribution/pull.go:127 +0x8d8
github.com/docker/docker/daemon.(*Daemon).PullImage(0xc820001c80, 0x7fa2d831b9a0, 0xc820e08570, 0xc820e7cc00, 0xc820874060, 0x7fa2d831b9e8, 0xc820fa1080, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:1025 +0x3b4
github.com/docker/docker/api/server/router/local.(*router).postImagesCreate(0xc82071dd20, 0x7fa2d83170e8, 0xc820e7cae0, 0x7fa2d8312fb8, 0xc8215ea420, 0xc820dc5880, 0xc820e7c840, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/router/local/image.go:139 +0xd33
github.com/docker/docker/api/server/router/local.(*router).(github.com/docker/docker/api/server/router/local.postImagesCreate)-fm(0x7fa2d83170e8, 0xc820e7cae0, 0x7fa2d8312fb8, 0xc8215ea420, 0xc820dc5880, 0xc820e7c840, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/router/local/local.go:100 +0x74
github.com/docker/docker/api/server.versionMiddleware.func1(0x7fa2d83170e8, 0xc820e7cae0, 0x7fa2d8312fb8, 0xc8215ea420, 0xc820dc5880, 0xc820e7c840, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a
github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7fa2d8360068, 0xc82000f720, 0x7fa2d8312fb8, 0xc8215ea420, 0xc820dc5880, 0xc820e7c840, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa
github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7fa2d8360068, 0xc82000f720, 0x7fa2d8312fb8, 0xc8215ea420, 0xc820dc5880, 0xc820e7c840, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be
github.com/docker/docker/api/server.debugRequestMiddleware.func1(0x7fa2d8360068, 0xc82000f720, 0x7fa2d8312fb8, 0xc8215ea420, 0xc820dc5880, 0xc820e7c840, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware.go:35 +0x2bf
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fa2d8312fb8, 0xc8215ea420, 0xc820dc5880)
	/go/src/github.com/docker/docker/api/server/server.go:169 +0x2ad
net/http.HandlerFunc.ServeHTTP(0xc82088bb00, 0x7fa2d8312fb8, 0xc8215ea420, 0xc820dc5880)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82071bea0, 0x7fa2d8312fb8, 0xc8215ea420, 0xc820dc5880)
	/go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820940680, 0x7fa2d8312fb8, 0xc8215ea420, 0xc820dc5880)
	/go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc820653200, 0x7fa2d8312fb8, 0xc8215ea420, 0xc820dc5880)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820071130)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
time="2016-03-15T10:40:14.187481059Z" level=error msg="error writing progress to client: writeflusher: closed"
```

**Comment by thaJeztah** [comment]
ping @aaronlehmann I was able to reproduce this
