### ISSUE TITLE
Docker core dumps when remove network with special characters

### ISSUE THREAD

**Issue by cookieisaac** [docker/docker#21401]
**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-34779823-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 474.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 16.39 GB
 Metadata Space Used: 1.167 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.462 GiB
Name: <MyHostName>
ID: 2PYA:ZOO2:WVKX:PMZQ:C5M5:PYWH:NXSA:ZT5E:L44F:KOUM:RS5Y:WS7D
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

**Steps to reproduce the issue:**
1. Create network with name `test@#$`
2. Create network with name `kiwl$%^`
3. Remove network `test@#$`
**_Current Result_**: Cannot find network test@, see below for details
**_Expected Result_**: Network removed
4. Remove network `kiwl$%^`
**_Current Result_**: Core dump, see below for details
**_Expected Result_**: Network removed

**Describe the results you received:**
```
[testBox]# docker network create test@#$
3bdb5afda32ade309138f8db2bd6ade5ce29ed8990c768ce493d475846c4ea64
[testBox]# docker network create kiwl$%^
db781fadc900962bfd1994b61b9f9659561a80a435c7df43a54fd3231702462e
[testBox]# docker network ls
NETWORK ID          NAME                DRIVER
773566b2314c        bridge              bridge
e9694fbb6005        none                null
d444a95f8939        host                host
3bdb5afda32a        test@#$             bridge
db781fadc900        kiwl$%^             bridge
[testBox]# docker network rm test@#$
Error response from daemon: network test@ not found
[testBox]# docker network rm kiwl$%^
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0xa387e5]

goroutine 1 [running]:
github.com/docker/engine-api/client.(*Client).sendClientRequest(0xc820381420, 0x1640748, 0x6, 0xc8202e2360, 0x11, 0x0, 0x7f92b08d0e80, 0xc820381490, 0x0, 0x5, ...)
        /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/engine-api/client/request.go:84 +0x2c5
github.com/docker/engine-api/client.(*Client).sendRequest(0xc820381420, 0x1640748, 0x6, 0xc8202e2360, 0x11, 0x0, 0x0, 0x0, 0x0, 0xc820673960, ...)
        /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/engine-api/client/request.go:69 +0x296
github.com/docker/engine-api/client.(*Client).delete(0xc820381420, 0xc8202e2360, 0x11, 0x0, 0x0, 0xc8202e2360, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/engine-api/client/request.go:53 +0x86
github.com/docker/engine-api/client.(*Client).NetworkRemove(0xc820381420, 0x7fffa4910840, 0x7, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/engine-api/client/network.go:28 +0x91
github.com/docker/docker/api/client.(*DockerCli).CmdNetworkRm(0xc820148700, 0xc82000a1f0, 0x1, 0x1, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/client/network.go:102 +0x2b4
reflect.callMethod(0xc8205f2fc0, 0xc820673c48)
        /usr/local/go/src/reflect/value.go:628 +0x1fc
reflect.methodValueCall(0xc82000a1f0, 0x1, 0x1, 0x3, 0xc8205f2fc0, 0x0, 0x0, 0x0, 0xc8205f2fc0, 0x0, ...)
        /usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc8205f2e10, 0xc82000a1d0, 0x3, 0x3, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/cli/cli.go:80 +0x175
main.main()
        /root/rpmbuild/BUILD/docker-engine/docker/docker.go:63 +0x43c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 18 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

**Describe the results you expected:**
Network should be successfully removed, or network with special characters are prohibited to create in the first place

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Comment by cookieisaac** [comment]
This only happens with CLI, and if I use Rest API, network can be removed successfully.

**Comment by yongtang** [comment]
The problem seems to be that in https://github.com/docker/docker/blob/master/vendor/src/github.com/docker/engine-api/client/network_remove.go:
```
	resp, err := cli.delete(ctx, "/networks/"+networkID, nil, nil)
```
the `networkID` is not escaped. I can provide a pull request to see if it could be fixed.

**Comment by yongtang** [comment]
#dibs
