### ISSUE TITLE
Docker crash due to: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by eobeidamadeus** [docker/docker#21440]
**Output of `docker version`:**

```
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-115.el7.x86_64
Go version (client): go1.4.2
Git commit (client): 446ad9b/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Package Version (server): docker-1.7.1-115.el7.x86_64
Go version (server): go1.4.2
Git commit (server): 446ad9b/1.7.1
OS/Arch (server): linux/amd64
```

**Output of `docker info`:**

```
Containers: 39
Images: 225
Storage Driver: overlay
 Backing Filesystem: xfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.4.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 16
Total Memory: 14.09 GiB
Name: tec-openshift-node-d0ba.figaro.amadeus.net
ID: AV3E:ADCE:UY2B:LZNW:55SH:WSGR:EEWF:5MMI:4IKL:5O6F:FNZL:S5TD
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual Machine spawned on GCE

**Beginning of the logs:**
```
Mar 23 11:01:28 tec-openshift-node-d0ba docker: panic: runtime error: invalid memory address or nil pointer dereference
Mar 23 11:01:28 tec-openshift-node-d0ba docker: [signal 0xb code=0x1 addr=0x20 pc=0x6386fa]
Mar 23 11:01:28 tec-openshift-node-d0ba docker: goroutine 521 [running]:
Mar 23 11:01:28 tec-openshift-node-d0ba docker: runtime.gopanic(0xb9a440, 0xc20802a050)
Mar 23 11:01:28 tec-openshift-node-d0ba docker: /usr/lib/golang/src/runtime/panic.go:425 +0x2a3 fp=0xc2082c18f8 sp=0xc2082c1890
Mar 23 11:01:28 tec-openshift-node-d0ba docker: runtime.panicmem()
Mar 23 11:01:28 tec-openshift-node-d0ba docker: /usr/lib/golang/src/runtime/panic.go:42 +0x4e fp=0xc2082c1920 sp=0xc2082c18f8
Mar 23 11:01:28 tec-openshift-node-d0ba docker: runtime.sigpanic()
Mar 23 11:01:28 tec-openshift-node-d0ba docker: /usr/lib/golang/src/runtime/sigpanic_unix.go:26 +0x274 fp=0xc2082c1970 sp=0xc2082c1920
Mar 23 11:01:28 tec-openshift-node-d0ba docker: bufio.(*Writer).flush(0xc208190940, 0x0, 0x0)
Mar 23 11:01:28 tec-openshift-node-d0ba docker: /usr/lib/golang/src/bufio/bufio.go:530 +0xda fp=0xc2082c1a08 sp=0xc2082c1970
Mar 23 11:01:28 tec-openshift-node-d0ba docker: bufio.(*Writer).Flush(0xc208190940, 0x0, 0x0)
Mar 23 11:01:28 tec-openshift-node-d0ba docker: /usr/lib/golang/src/bufio/bufio.go:519 +0x3a fp=0xc2082c1a28 sp=0xc2082c1a08
Mar 23 11:01:28 tec-openshift-node-d0ba docker: net/http.(*response).Flush(0xc2085cee60)
Mar 23 11:01:28 tec-openshift-node-d0ba docker: /usr/lib/golang/src/net/http/server.go:1047 +0x4c fp=0xc2082c1a48 sp=0xc2082c1a28
Mar 23 11:01:28 tec-openshift-node-d0ba docker: github.com/docker/docker/pkg/ioutils.(*WriteFlusher).Write(0xc2086bd3e0, 0xc208079600, 0xbd, 0x149, 0xbd, 0x0, 0x0)
Mar 23 11:01:28 tec-openshift-node-d0ba docker: /builddir/build/BUILD/docker-446ad9bd9e8ec218aff5b22529c0bdc6df69d0e2/_build/src/github.com/docker/docker/pkg/ioutils/writeflusher.go:21 +0x145 fp=0xc2082c1aa8 sp=0xc2082c1a48
Mar 23 11:01:28 tec-openshift-node-d0ba docker: github.com/docker/docker/pkg/progressreader.(*Config).Read(0xc208146e70, 0xc20841a000, 0x8000, 0x8000, 0x4000, 0x7fb42a8ed470, 0xc2084f7ec0)
Mar 23 11:01:28 tec-openshift-node-d0ba docker: /builddir/build/BUILD/docker-446ad9bd9e8ec218aff5b22529c0bdc6df69d0e2/_build/src/github.com/docker/docker/pkg/progressreader/progressreader.go:37 +0x2e5 fp=0xc2082c1b48 sp=0xc2082c1aa8
Mar 23 11:01:28 tec-openshift-node-d0ba docker: io.Copy(0x7fb42a8d12a8, 0xc20856c890, 0x7fb42a8db510, 0xc208146e70, 0xa0fcad, 0x0, 0x0)
Mar 23 11:01:28 tec-openshift-node-d0ba docker: /usr/lib/golang/src/io/io.go:362 +0x1f6 fp=0xc2082c1c00 sp=0xc2082c1b48
Mar 23 11:01:28 tec-openshift-node-d0ba docker: github.com/docker/docker/graph.func·010(0xc20834b430, 0x0, 0x0)
Mar 23 11:01:28 tec-openshift-node-d0ba docker: /builddir/build/BUILD/docker-446ad9bd9e8ec218aff5b22529c0bdc6df69d0e2/_build/src/github.com/docker/docker/graph/pull.go:634 +0xd42 fp=0xc2082c1fa8 sp=0xc2082c1c00
Mar 23 11:01:28 tec-openshift-node-d0ba docker: github.com/docker/docker/graph.func·011(0xc20834b430)
Mar 23 11:01:28 tec-openshift-node-d0ba docker: /builddir/build/BUILD/docker-446ad9bd9e8ec218aff5b22529c0bdc6df69d0e2/_build/src/github.com/docker/docker/graph/pull.go:658 +0x2f fp=0xc2082c1fd8 sp=0xc2082c1fa8
Mar 23 11:01:28 tec-openshift-node-d0ba docker: runtime.goexit()
```

The rest is attached

**Output of `uname -a`:**

```
Linux tec-openshift-node-d0ba.figaro.amadeus.net 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happened on 4 machines of the same cluster, and out of the blue..

**Comment by eobeidamadeus** [comment]
[dockerCrash.txt](https://github.com/docker/docker/files/186666/dockerCrash.txt)

**Comment by cpuguy83** [comment]
Closing this is fixed for a long time.

**Comment by eobeidamadeus** [comment]
Ah is it? and do you have a PR link?

**Comment by cpuguy83** [comment]
I'd be happy to provide it, but this has been completely rewritten (in addition to fixing the panic even before the re-write).

**Comment by thaJeztah** [comment]
It looks like you're running a Red Hat build of Docker 1.7.1, so the best option for support on those builds is to report through https://bugzilla.redhat.com. Those versions contain quite some modifications, so it's possible that some bugs are related to those changes. https://github.com/projectatomic/docker/compare/v1.7.1...446ad9b
