### ISSUE TITLE
[not critical] `http: panic serving @: reflect: slice index out of range` under `docker stats` stress testing

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker#22030]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 56
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 49
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.6 GiB
Name: suda-PC2
ID: 42B5:4E7P:VILK:75VX:TKMU:7PC7:QYS3:CZHX:R6SR:3VWI:E75Y:G4L6
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 39
 Goroutines: 88
 System Time: 2016-04-14T20:01:36.596918829+09:00
 EventsListeners: 7
Username: akihirosuda
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical (4 CPUs)

**Steps to reproduce the issue:**
1. Open many terminals and run containers repeatedly and simultaneously.
When I hit the issue, I was running `cd DOCKER_SRC_DIR; make shell` and `docker run -it --rm busybox true`.
2. Open many terminals and do `docker stats --all --no-stream` repeatedly and simultaneously.
3. Watch the daemon log after a few minutes.

**Describe the results you received:**
```
2016/04/14 19:56:43 http: panic serving @: reflect: slice index out of range
```
Note that the panic is recovered and the daemon can continue serving.
So this issue is not critical.

**Describe the results you expected:**
Even though it is not critical, we should not see any panic.

**Additional information you deem important (e.g. issue happens only occasionally):**

I can reproduce the issue multiple times under a heavy stress.
I'll try to add `logrus.Debugf` for `stats.go` later.

daemon log:
```
DEBU[1067] attach: stdout: end                          
DEBU[1067] attach: stdin: end                           
DEBU[1067] attach: stderr: end                          
DEBU[1067] Revoking external connectivity on endpoint jolly_murdock (c9768641b7e880bf47bb0bc123dc601e566a37aeb4b5c9bb5047f5dbc4cdf7d2) 
DEBU[1067] Calling POST /v1.23/containers/d4949a07e503f7334610d52d66ac367aac42017012e6a27a5b477685d3fb2a72/wait 
DEBU[1067] Releasing addresses for endpoint jolly_murdock's interface on network bridge 
DEBU[1067] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.3) 
2016/04/14 19:56:43 http: panic serving @: reflect: slice index out of range
goroutine 18170 [running]:
net/http.(*conn).serve.func1(0xc821abdce0, 0x7f6cd0b8e080, 0xc8205cab90)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
encoding/json.(*encodeState).marshal.func1(0xc820db2e40)
        /usr/local/go/src/encoding/json/encode.go:265 +0x11f
reflect.Value.Index(0x11e6300, 0xc820dc6e20, 0xd7, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:847 +0x151
encoding/json.(*arrayEncoder).encode(0xc82043cad8, 0xc820f1a000, 0x11e6300, 0xc820dc6e20, 0xd7, 0x0)
        /usr/local/go/src/encoding/json/encode.go:685 +0xd2
encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc820f1a000, 0x11e6300, 0xc820dc6e20, 0xd7, 0x0)
        /usr/local/go/src/encoding/json/encode.go:692 +0x51
encoding/json.(*sliceEncoder).encode(0xc82043cae0, 0xc820f1a000, 0x11e6300, 0xc820dc6e20, 0xd7, 0x0)
        /usr/local/go/src/encoding/json/encode.go:662 +0xb0
encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc820f1a000, 0x11e6300, 0xc820dc6e20, 0xd7, 0x0)
        /usr/local/go/src/encoding/json/encode.go:671 +0x51
encoding/json.(*structEncoder).encode(0xc8208fb410, 0xc820f1a000, 0x1572ea0, 0xc820dc6e18, 0xd9, 0x0)
        /usr/local/go/src/encoding/json/encode.go:582 +0x2c0
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc820f1a000, 0x1572ea0, 0xc820dc6e18, 0xd9, 0x0)
        /usr/local/go/src/encoding/json/encode.go:596 +0x51
encoding/json.(*structEncoder).encode(0xc8208fb260, 0xc820f1a000, 0x15176e0, 0xc820dc6e18, 0xd9, 0x0)
        /usr/local/go/src/encoding/json/encode.go:582 +0x2c0
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc820f1a000, 0x15176e0, 0xc820dc6e18, 0xd9, 0x0)
        /usr/local/go/src/encoding/json/encode.go:596 +0x51
encoding/json.(*structEncoder).encode(0xc820c26ea0, 0xc820f1a000, 0x14ee5c0, 0xc820dc6e00, 0xd9, 0x0)
        /usr/local/go/src/encoding/json/encode.go:582 +0x2c0
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc820f1a000, 0x14ee5c0, 0xc820dc6e00, 0xd9, 0xc820dc6e00)
        /usr/local/go/src/encoding/json/encode.go:596 +0x51
encoding/json.(*ptrEncoder).encode(0xc8205ca3a0, 0xc820f1a000, 0x1197940, 0xc820dc6e00, 0x16, 0x0)
        /usr/local/go/src/encoding/json/encode.go:704 +0xea
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc820f1a000, 0x1197940, 0xc820dc6e00, 0x16, 0xc820dc6e00)
        /usr/local/go/src/encoding/json/encode.go:709 +0x51
encoding/json.(*encodeState).reflectValue(0xc820f1a000, 0x1197940, 0xc820dc6e00, 0x16)
        /usr/local/go/src/encoding/json/encode.go:297 +0x6b
encoding/json.(*encodeState).marshal(0xc820f1a000, 0x1197940, 0xc820dc6e00, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:270 +0xa9
encoding/json.(*Encoder).Encode(0xc820db3118, 0x1197940, 0xc820dc6e00, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:188 +0x94
github.com/docker/docker/daemon.(*Daemon).ContainerStats(0xc82032db00, 0xc821748e56, 0xc, 0xc820d2c9c0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/stats.go:110 +0x9e5
github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersStats(0xc8208a2540, 0x7f6cd0b8fb38, 0xc820d2c8d0, 0x7f6ccc49c698, 0xc820ec4210, 0xc820c25420, 0xc820d83bf0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:82 +0x34d
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersStats)-fm(0x7f6cd0b8fb38, 0xc820d2c8d0, 0x7f6ccc49c698, 0xc820ec4210, 0xc820c25420, 0xc820d83bf0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:37 +0x74
github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7f6cd0b8fb38, 0xc820d2c8d0, 0x7f6ccc49c698, 0xc820ec4210, 0xc820c25420, 0xc820d83bf0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43
github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7f6cd0b8fb38, 0xc820d2c7e0, 0x7f6ccc49c698, 0xc820ec4210, 0xc820c25420, 0xc820d83bf0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:34 +0x6b8
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x7f6cd0b88f58, 0xc820011040, 0x7f6ccc49c698, 0xc820ec4210, 0xc820c25420, 0xc820d83bf0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/debug.go:21 +0xd57
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f6ccc49c698, 0xc820ec4210, 0xc820c25420)
        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:132 +0x138
net/http.HandlerFunc.ServeHTTP(0xc8204445e0, 0x7f6ccc49c698, 0xc820ec4210, 0xc820c25420)
        /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82051aaf0, 0x7f6ccc49c698, 0xc820ec4210, 0xc820c25420)
        /usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820a1f040, 0x7f6ccc49c698, 0xc820ec4210, 0xc820c25420)
        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc82038a240, 0x7f6ccc49c698, 0xc820ec4210, 0xc820c25420)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc821abdce0)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6
DEBU[1067] Calling GET /v1.23/containers/d4949a07e503f7334610d52d66ac367aac42017012e6a27a5b477685d3fb2a72/json 
DEBU[1067] Calling DELETE /v1.23/containers/d4949a07e503f7334610d52d66ac367aac42017012e6a27a5b477685d3fb2a72?v=1 
DEBU[1067] Closing buffered stdin pipe                  
DEBU[1067] Calling POST /v1.23/containers/create
```

**Comment by AkihiroSuda** [comment]
https://github.com/docker/docker/issues/21616 is also JSON-related panic issue, but it should have been fixed in 1.11.0

**Comment by crosbymichael** [comment]
Can anyone else try to reproduce this.  I have an idea what the fix should be but I have not been able to reproduce on my machine yet.

**Comment by tonistiigi** [comment]
@crosbymichael We should probably make a copy here https://github.com/docker/docker/blob/ac7e011ec90b110e62aafd3a1b2963634c9976a3/daemon/stats.go#L46 . The same pointer is sent to multiple goroutines in https://github.com/docker/docker/blob/ac7e011ec90b110e62aafd3a1b2963634c9976a3/pkg/pubsub/publisher.go#L75

**Comment by crosbymichael** [comment]
@tonistiigi ya, that was the func I was looking at as well.
