### ISSUE TITLE
Docker fails to activate libnetwork plugin

### ISSUE THREAD

**Issue by fkautz** [docker/docker#22175]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:40:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:40:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-396886-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 35.91 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.703 GiB
Name: localhost.localdomain
ID: 6KFB:6USV:ZVQZ:6QD2:EJLA:XDO7:RR5D:DCUA:RIC5:TVRE:WVGQ:P3YC
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Cluster store: etcd://localhost:4001
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
docker -H tcp://0.0.0.0:2375 network create --driver=kuryr phoenix

**Describe the results you received:**

```
2016/04/19 18:19:57 http: panic serving 127.0.0.1:58713: runtime error: invalid memory address or nil pointer dereference
goroutine 124 [running]:
net/http.(*conn).serve.func1(0xc820372000, 0x7effcae96898, 0xc820024020)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/docker/docker/pkg/plugins.(*Plugin).activate(0xc820076000, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:86 +0x191
github.com/docker/docker/pkg/plugins.loadWithRetry(0xc8209e2520, 0x5, 0xc81ffb3d01, 0x0, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:175 +0x3bd
github.com/docker/docker/pkg/plugins.load(0xc8209e2520, 0x5, 0xc8209e2520, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:146 +0x3c
github.com/docker/docker/pkg/plugins.get(0xc8209e2520, 0x5, 0x184dd40, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:194 +0xe3
github.com/docker/docker/pkg/plugins.Get(0xc8209e2520, 0x5, 0x1720c90, 0xd, 0xc8209851f4, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:199 +0x4f
github.com/docker/libnetwork.(*controller).loadDriver(0xc8200d2b00, 0xc8209e2520, 0x5, 0x0, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/controller.go:751 +0x68
github.com/docker/libnetwork.(*network).driver(0xc8209850e0, 0xc820354f01, 0x0, 0x0, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/network.go:653 +0x13c
github.com/docker/libnetwork.(*controller).NewNetwork(0xc8200d2b00, 0xc8209e2520, 0x5, 0xc8209e2510, 0x7, 0xc820354f40, 0x4, 0x4, 0x0, 0x0, ...)
        /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/controller.go:457 +0x38c
github.com/docker/docker/daemon.(*Daemon).CreateNetwork(0xc820371b00, 0xc8209e2510, 0x7, 0xc8209e2520, 0x5, 0xc8209e2600, 0x7, 0xc820966d50, 0x21ca9d0, 0x0, ...)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/network.go:114 +0x3e1
github.com/docker/docker/api/server/router/network.(*networkRouter).postNetworkCreate(0xc82095fb60, 0x7effcae90fd8, 0xc820966150, 0x7effcadce3b0, 0xc820372420, 0xc820086000, 0xc820983e90, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/router/network/network_routes.go:94 +0x945
github.com/docker/docker/api/server/router/network.(*networkRouter).(github.com/docker/docker/api/server/router/network.postNetworkCreate)-fm(0x7effcae90fd8, 0xc820966150, 0x7effcadce3b0, 0xc820372420, 0xc820086000, 0xc820983e90, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/router/network/network.go:31 +0x74
github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7effcae90fd8, 0xc820966150, 0x7effcadce3b0, 0xc820372420, 0xc820086000, 0xc820983e90, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43
github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7effcae90fd8, 0xc820983f50, 0x7effcadce3b0, 0xc820372420, 0xc820086000, 0xc820983e90, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:34 +0x6b8
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7effcadce3b0, 0xc820372420, 0xc820086000)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/server.go:132 +0x138
net/http.HandlerFunc.ServeHTTP(0xc8209ce320, 0x7effcadce3b0, 0xc820372420, 0xc820086000)
        /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8203859f0, 0x7effcadce3b0, 0xc820372420, 0xc820086000)
        /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8209fa010, 0x7effcadce3b0, 0xc820372420, 0xc820086000)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc820374420, 0x7effcadce3b0, 0xc820372420, 0xc820086000)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820372000)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Describe the results you expected:**
Plugin properly activates

**Additional information you deem important (e.g. issue happens only occasionally):**
I have a vagrant environment where this should be reproducible. I'll set up a branch on github and share soon.

**Comment by fkautz** [comment]
This is also using a less recent version of kuryr. Has there been a backwards incompatible change in how plugins are activated? I think this error is occurring before it contacts kuryr, but want to ask for completeness.

**Comment by fkautz** [comment]
This takes a while to load, but I uploaded the current workflow here:

https://github.com/fkautz/vagrant-devstack/tree/docker-22175

We should be able to reproduce the problem with less infrastructure if the problem isn't immediately apparent.

**Comment by mavenugo** [comment]
@fkautz how is the plugin activated ? I see a potential bug in the plugin activation code when the plugin is loaded via SpecPaths with JSON format.

**Comment by fkautz** [comment]
```sh
$ cat /usr/lib/docker/plugins/kuryr/kuryr.json
{
    "Name": "kuryr",
    "Addr": "http://127.0.0.1:2377"
}
```

**Comment by fkautz** [comment]
Here is what the docker client is sending to the docker server:

```json
{"Name":"phoenix","CheckDuplicate":true,"Driver":"kuryr","EnableIPv6":false,"IPAM":{"Driver":"default","Options":{},"Config":[]},"Internal":false,"Options":{},"Labels":{}}
```

pretty:
```json
{  
  "Name":"phoenix",
  "CheckDuplicate":true,
  "Driver":"kuryr",
  "EnableIPv6":false,
  "IPAM":{  
    "Driver":"default",
    "Options":{  

    },
    "Config":[  

    ]
  },
  "Internal":false,
  "Options":{  

  },
  "Labels":{  

  }
}
```

Response:

```sh
An error occurred trying to connect: Post http://0.0.0.0:2375/v1.23/networks/create: EOF
```

**Comment by mavenugo** [comment]
@fkautz could you try using the `.spec` file format instead of the `.json` ?
The bug that I see in the plugin discovery code is specific to the `.json` format which we will get it resolved shortly.

As mentioned https://github.com/docker/docker/blob/master/docs/extend/plugin_api.md, just write a file named kuryr.spec and add `http://127.0.0.1:2377` in the file.

**Comment by fkautz** [comment]
That worked, I was able to start the plugin with a .spec file.

**Comment by LipingMao** [comment]
Hello , I see this bug is closed, but till now, only spec can work, json still can't work, will we support json? Thanks.
