### ISSUE TITLE
docker http panics

### ISSUE THREAD

**Issue by pcarrier** [docker/docker#22210]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 252
 Running: 73
 Paused: 0
 Stopped: 179
Images: 4
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: journald
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-15-generic
Operating System: Ubuntu 16.04
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.9 GiB
Name: ip-10-0-1-115
ID: 3FQR:PLJG:D4NS:TGV2:7DQY:IAKT:R2V7:2NQJ:O2XS:MT43:BEVE:CHF7
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS, m4.4xlarge.

**Steps to reproduce the issue:** Unknown. We're running `amazon-ecs-agent` 1.8.2 and scheduling a bunch of tasks.

**Describe the results you received:** Some container deletions fail. We can see panics in logs. They are remarkably consistent.

```
$ journalctl -u docker _TRANSPORT=stdout | grep -A33 'panic serving'
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: 2016/04/20 19:40:11 http: panic serving @: runtime error: index out of range
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: goroutine 55903667 [running]:
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve.func1(0xc8263442c0, 0x7f5df2aa2218, 0xc821608e10)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1287 +0xb5
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetByName(0xc820157800, 0xc825e63057, 0x0, 0x0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:529 +0x3fb
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetContainer(0xc820157800, 0xc825e63057, 0x0, 0x0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:149 +0xd2
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).ContainerRm(0xc820157800, 0xc825e63057, 0x0, 0xc8210c94c0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/delete.go:22 +0x6e
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).deleteContainers(0xc820754c60, 0x7f5df2aefb08, 0xc825e631d0, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380, 0xc825e630e0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container_routes.go:401 +0x1de
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.deleteContainers)-fm(0x7f5df2aefb08, 0xc825e631d0, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380, 0xc825e630e0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container.go:64 +0x74
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.versionMiddleware.func1(0x7f5df2aefb08, 0xc825e631d0, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380, 0xc825e630e0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380, 0xc825e630e0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380, 0xc825e630e0, 0x0, 0x0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/server.go:169 +0x2ad
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: net/http.HandlerFunc.ServeHTTP(0xc8208f6740, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1422 +0x3a
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc8207febe0, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8209fe4d0, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: net/http.serverHandler.ServeHTTP(0xc82016e9c0, 0x7f5df2aef800, 0xc8263444d0, 0xc824aaa380)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1862 +0x19e
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve(0xc8263442c0)
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1361 +0xbee
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]: created by net/http.(*Server).Serve
Apr 20 19:40:11 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1910 +0x3f6
--
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: 2016/04/20 19:52:48 http: panic serving @: runtime error: index out of range
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: goroutine 56017683 [running]:
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve.func1(0xc820e540b0, 0x7f5df2aa2218, 0xc820d42360)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1287 +0xb5
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetByName(0xc820157800, 0xc826caa667, 0x0, 0x0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:529 +0x3fb
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetContainer(0xc820157800, 0xc826caa667, 0x0, 0x0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:149 +0xd2
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).ContainerRm(0xc820157800, 0xc826caa667, 0x0, 0xc827350f20, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/delete.go:22 +0x6e
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).deleteContainers(0xc820754c60, 0x7f5df2aefb08, 0xc826caa7b0, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000, 0xc826caa6f0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container_routes.go:401 +0x1de
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.deleteContainers)-fm(0x7f5df2aefb08, 0xc826caa7b0, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000, 0xc826caa6f0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container.go:64 +0x74
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.versionMiddleware.func1(0x7f5df2aefb08, 0xc826caa7b0, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000, 0xc826caa6f0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000, 0xc826caa6f0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000, 0xc826caa6f0, 0x0, 0x0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5df2aef800, 0xc820e54160, 0xc824b28000)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/server.go:169 +0x2ad
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: net/http.HandlerFunc.ServeHTTP(0xc8208f6740, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1422 +0x3a
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc8207febe0, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8209fe4d0, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: net/http.serverHandler.ServeHTTP(0xc82016e9c0, 0x7f5df2aef800, 0xc820e54160, 0xc824b28000)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1862 +0x19e
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve(0xc820e540b0)
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1361 +0xbee
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]: created by net/http.(*Server).Serve
Apr 20 19:52:48 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1910 +0x3f6
--
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: 2016/04/20 20:04:12 http: panic serving @: runtime error: index out of range
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: goroutine 56121551 [running]:
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve.func1(0xc8263442c0, 0x7f5df2aa2218, 0xc826a4f5c0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1287 +0xb5
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetByName(0xc820157800, 0xc82692c4e7, 0x0, 0x0, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:529 +0x3fb
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetContainer(0xc820157800, 0xc82692c4e7, 0x0, 0x0, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:149 +0xd2
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).ContainerRm(0xc820157800, 0xc82692c4e7, 0x0, 0xc820d753d0, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/delete.go:22 +0x6e
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).deleteContainers(0xc820754c60, 0x7f5df2aefb08, 0xc82692c630, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460, 0xc82692c570, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container_routes.go:401 +0x1de
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.deleteContainers)-fm(0x7f5df2aefb08, 0xc82692c630, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460, 0xc82692c570, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container.go:64 +0x74
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.versionMiddleware.func1(0x7f5df2aefb08, 0xc82692c630, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460, 0xc82692c570, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460, 0xc82692c570, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460, 0xc82692c570, 0x0, 0x0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5df2aef800, 0xc826344370, 0xc826dbc460)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/server.go:169 +0x2ad
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: net/http.HandlerFunc.ServeHTTP(0xc8208f6740, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1422 +0x3a
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc8207febe0, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8209fe4d0, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: net/http.serverHandler.ServeHTTP(0xc82016e9c0, 0x7f5df2aef800, 0xc826344370, 0xc826dbc460)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1862 +0x19e
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve(0xc8263442c0)
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1361 +0xbee
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]: created by net/http.(*Server).Serve
Apr 20 20:04:12 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1910 +0x3f6
--
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: 2016/04/20 23:01:52 http: panic serving @: runtime error: index out of range
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: goroutine 57686309 [running]:
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve.func1(0xc822c16d10, 0x7f5df2aa2218, 0xc8212f4ed8)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1287 +0xb5
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetByName(0xc820157800, 0xc82284ba77, 0x0, 0x0, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:529 +0x3fb
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).GetContainer(0xc820157800, 0xc82284ba77, 0x0, 0x0, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/daemon.go:149 +0xd2
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/daemon.(*Daemon).ContainerRm(0xc820157800, 0xc82284ba77, 0x0, 0xc8253ca890, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/daemon/delete.go:22 +0x6e
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).deleteContainers(0xc820754c60, 0x7f5df2aefb08, 0xc82284bbc0, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0, 0xc82284bb00, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container_routes.go:401 +0x1de
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.deleteContainers)-fm(0x7f5df2aefb08, 0xc82284bbc0, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0, 0xc82284bb00, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router/container/container.go:64 +0x74
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.versionMiddleware.func1(0x7f5df2aefb08, 0xc82284bbc0, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0, 0xc82284bb00, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0, 0xc82284bb00, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7f5df2aa1c28, 0xc820075440, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0, 0xc82284bb00, 0x0, 0x0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/server.go:169 +0x2ad
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: net/http.HandlerFunc.ServeHTTP(0xc8208f6740, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1422 +0x3a
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc8207febe0, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8209fe4d0, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: net/http.serverHandler.ServeHTTP(0xc82016e9c0, 0x7f5df2aef800, 0xc822c16dc0, 0xc8253f29a0)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1862 +0x19e
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: net/http.(*conn).serve(0xc822c16d10)
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1361 +0xbee
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]: created by net/http.(*Server).Serve
Apr 20 23:01:52 ip-10-0-1-115 docker[1359]:         /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Describe the results you expected:** No panics.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens on a small subset of our production hosts.

systemd unit file for Docker:
```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Restart=always
Type=notify
ExecStart=/usr/bin/docker daemon --default-ulimit nofile=64000:64000 \
  --storage-driver=overlay \
  --log-driver=journald \
  --log-opt env=GALAXY_APP_ID,[shortened by pcarrier...]
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
OOMScoreAdjust=-1000
TasksMax=infinity
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
```

**Comment by cpuguy83** [comment]
Do you know what action you are performing when this occurs?

**Comment by pcarrier** [comment]
It's ecs agent. Based on the stack I'd say container removal?

Pierre Carrier

**Comment by cpuguy83** [comment]
lol, yes.

The only thing I can see that would be causing this is if the name given to docker is an empty string (which we should fix, b/c it shouldn't ever panic).
May be an indicator of a bug elsewhere (either in docker or in the ecs-agent) since it seems docker is getting an empty string.

**Comment by yongtang** [comment]
The issue could be reproduced by using an empty container name for deletion in remote API:
```sh
curl -i http://127.0.0.1:2375/containers/ -XDELETE -H 'Content-Type: application/json'
```
I created a pull request #22213 to try to address this issue.
