### ISSUE TITLE
Docker runtime has unexpected fatal error and panic

### ISSUE THREAD

**Issue by stayclassychicago** [docker/docker#22473]
---
## BUG REPORT INFORMATION

**Output of `docker version`:**

```
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-6.git6ec29ef.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      7206621
 Built:           Mon Jan 25 20:52:22 UTC 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-6.git6ec29ef.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      7206621
 Built:           Mon Jan 25 20:52:22 UTC 2016
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
Images: 221
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: vg_root-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 5.453 GB
 Data Space Total: 46.08 GB
 Data Space Available: 40.63 GB
 Metadata Space Used: 4.493 MB
 Metadata Space Total: 599.8 MB
 Metadata Space Available: 595.3 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: journald
Kernel Version: 4.3.5-300.fc23.x86_64
Operating System: Fedora 23 (Twenty Three)
CPUs: 40
Total Memory: 125.8 GiB
Name: njl3s090.trading.imc.intra
ID: V6WW:PK2K:GQCQ:HW2O:72E3:T2Z5:SYFO:2AN7:M6H5:MJJM:VKON:GMKI
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical host - Fedora 23

```
Linux njl3sXXX.domain 4.3.5-300.fc23.x86_64 #1 SMP Mon Feb 1 03:18:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Steps to reproduce the issue:**
We've had a spurious/recurring issue on our Fedora 23 hosts.  These are the events which consistently happen leading up to this Docker daemon fatal exit
1.  Docker service (systemd managed) running 
2.  Docker container "myapp" (java application, systemd managed) running
3.  Systemd command to stop Docker container service  (example: systemctl stop myapp)

**Describe the results you received:**

Logs (journalctl) shows 
1. Systemd stops the Docker container service (java application) 
2. Immediately followed by Docker service unexpectedly/fatally exits
3. Docker Panic stacktrace (abridged output below)
4. systemd-coredump[144821]: Process 141742 (docker) of user 0 dumped core.

```
-- Logs begin at Fri 2016-05-02 21:13:07 CDT --


[journald_docker_log_2016-05-02_21.13.08.txt](https://github.com/docker/docker/files/247197/journald_docker_log_2016-05-02_21.13.08.txt)
# End of stopping the Docker container service (java application) 
May 02 21:13:07  docker[141742]: 2016.05.02-21:13:07 killed process 193
May 02 21:13:07  docker[141742]: 2016.05.02-21:13:07 remove pid file
May 02 21:13:07  docker[141742]: 2016.05.02-21:13:07 stop - end -

# Start of Docker panic stacktrace, followed by coredump
   Terminated
   fatal error: unexpected signal during runtime execution
   [signal 0xb code=0x1 addr=0x7fb5ca149fc8 pc=0x7fb736f9c692]
   runtime stack:
   runtime.throw(0x1643720, 0x2a)
   /usr/lib/golang/src/runtime/panic.go:527 +0x90 fp=0x7fb6fe7fb990 sp=0x7fb6fe7fb978
   runtime.sigpanic()
   /usr/lib/golang/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x7fb6fe7fb9e0 sp=0x7fb6fe7fb990
   goroutine 21475 [syscall, locked to thread]:
   runtime.cgocall(0xf24e40, 0xc820070d88, 0x0)
   /usr/lib/golang/src/runtime/cgocall.go:120 +0x11b fp=0xc820070d58 sp=0xc820070d28
   github.com/docker/docker/daemon/logger/journald._Cfunc_sd_journal_next(0x7fb6180008c0, 0xc800000000)
   github.com/docker/docker/daemon/logger/journald/_obj/_cgo_gotypes.go:191 +0x35 fp=0xc820070d88 sp=0xc820070d58
   github.com/docker/docker/daemon/logger/journald.(*journald).drainJournal(0xc821e61e00, 0xc8213a6e20, 0x0, 0xc800000000, 0x0, 0xffffffffffffffff, 0xc8224d3b01, 0x7fb6180008c0, 0xc821fae880, 0x7f, ...)
   /builddir/build/BUILD/docker-6ec29ef9a2d48a6ccd716a2bbb00a1ed07412d6a/_build/src/github.com/docker/docker/daemon/logger/journald/read.go:164 +0x615 fp=0xc820070ee0 sp=0xc820070d88
   github.com/docker/docker/daemon/logger/journald.(*journald).followJournal.func1(0x7fb6180008c0, 0xf0000000ef, 0xc820bb2060, 0xc821e61e00, 0xc8213a6e20, 0x0, 0xc800000000, 0x0, 0xffffffffffffffff, 0xc8205aa601)
   /builddir/build/BUILD/docker-6ec29ef9a2d48a6ccd716a2bbb00a1ed07412d6a/_build/src/github.com/docker/docker/daemon/logger/journald/read.go:180 +0xc4 fp=0xc820070f60 sp=0xc820070ee0
   runtime.goexit()
   /usr/lib/golang/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820070f68 sp=0xc820070f60
   created by github.com/docker/docker/daemon/logger/journald.(*journald).followJournal
   /builddir/build/BUILD/docker-6ec29ef9a2d48a6ccd716a2bbb00a1ed07412d6a/_build/src/github.com/docker/docker/daemon/logger/journald/read.go:187 +0xf0
   goroutine 1 [chan receive, 4653 minutes]:
   runtime.gopark(0x174c928, 0xc82119a5f8, 0x14ac5f0, 0xc, 0x17, 0x3)
   /usr/lib/golang/src/runtime/proc.go:185 +0x163 fp=0xc821c9d4c8 sp=0xc821c9d4a0
   runtime.goparkunlock(0xc82119a5f8, 0x14ac5f0, 0xc, 0x41fd17, 0x3)
   /usr/lib/golang/src/runtime/proc.go:191 +0x54 fp=0xc821c9d500 sp=0xc821c9d4c8
   runtime.chanrecv(0x101e2a0, 0xc82119a5a0, 0xc821c9d980, 0xc820c6bb01, 0xc8212e0000)
   /usr/lib/golang/src/runtime/chan.go:448 +0x472 fp=0xc821c9d5c0 sp=0xc821c9d500
   runtime.chanrecv1(0x101e2a0, 0xc82119a5a0, 0xc821c9d980)
   /usr/lib/golang/src/runtime/chan.go:349 +0x2b fp=0xc821c9d5f0 sp=0xc821c9d5c0
   main.(*DaemonCli).CmdDaemon(0xc82016be70, 0xc82000a140, 0x10, 0x10, 0x0, 0x0)
   /builddir/build/BUILD/docker-6ec29ef9a2d48a6ccd716a2bbb00a1ed07412d6a/docker/daemon.go:329 +0x2168 fp=0xc821c9daa0 sp=0xc821c9d5f0

...
<SNIP:  full stacktrace attached>
...

systemd[1]: docker.service: Main process exited, code=killed, status=6/ABRT
systemd[1]: docker.service: Unit entered failed state.
systemd[1]: docker.service: Failed with result 'signal'.
systemd-coredump[144821]: Process 141742 (docker) of user 0 dumped core.

                                                                     Stack trace of thread 141950:
                                                                     #0  0x0000000000472004 runtime.raise (docker)
-- Subject: Process 141742 (docker) dumped core
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
--
-- Process 141742 (docker) crashed and dumped core.
--
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.

```

**Describe the results you expected:**
Docker service should continue running

**Additional information you deem important (e.g. issue happens only occasionally):**
This happened about 6-8 times over the past two (2) weeks.  While we haven't been able to root-cause or reproduce consistently, we've seen this panic and coredump on our hosts (physical) running

**Comment by stayclassychicago** [comment]
Full panic stacktrace here: https://github.com/docker/docker/files/247204/journald_docker_log_2016-05-02_21.13.08.txt

**Comment by justincormack** [comment]
Hmm, this looks like a SEGV in the linked journalctl C code that is called from Go, but not in a way that is at all obvious how it could take place. This is also not a docker build, it is a patched Fedora build, so I am not sure if this code is patched. Can you replicate this with a more recent, official build of Docker?

**Comment by mickep76** [comment]
You would need a dynamically linked version of Docker, since it's using a device-mapper thinpool device.

**Comment by thaJeztah** [comment]
This is a very old version by now, could you try on the current official version? Since we're no longer doing patch releases for docker 1.9, upgrading is the best option here
