### ISSUE TITLE
Test integration cli daemon sometimes dies while running tests

### ISSUE THREAD

**Issue by tophj-ibm** [docker/docker#22612]
Opening this because it may not be a power specific issue, but on ppc64le sometimes the docker daemon gets killed while running the integration tests. As seen here :

https://jenkins.dockerproject.org/job/Docker%20Master%20(powerpc)/136/console

```sh
PASS: docker_cli_run_test.go:2021: DockerSuite.TestRunSetMacAddress	0.573s
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Cannot connect to the Docker daemon. Is the docker daemon running on this host?


----------------------------------------------------------------------
FAIL: docker_cli_run_test.go:2285: DockerSuite.TestRunSlowStdoutConsumer

docker_cli_run_test.go:2306:
     c.Fatalf("Expected %d, got %d", expected, n)
 ... Error: Expected 4096000, got 1179648

Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
and it continues like this until the end.

It only fails during TestRunSlowStdoutConsumer, and furthermore only during a full integration-cli run. It passes if running the specific suite or test. 

Some interesting info from the docker.log:
```sh
time="2016-05-09T15:49:27.971217000Z" level=debug msg="received containerd event: &types.Event{Type:\"start-container\", Id:\"7b7864c0e7998c1585eb0d85b17dfb06c5641badbf6be618e60fab70c717d944\", Status:0x0, Pid:\"\", Timestamp:0x5730b187}"
fatal error: concurrent map read and map write
```

**Comment by tophj-ibm** [comment]
update: definitely being thrown just by this test (only 1/10 of the time). The first goroutine suggests it was copying to the attached stream when the panic happened.
```sh
goroutine 241 [running]:
runtime.throw(0x113c3900, 0x21)
        /usr/src/go/src/runtime/panic.go:547 +0x8c fp=0xc820c92ba0 sp=0xc820c92b70
runtime.mapaccess1_fast64(0x10d9b780, 0xc82001b0e0, 0x400, 0xc820a2d768)
        /usr/src/go/src/runtime/hashmap_fast.go:112 +0x78 fp=0xc820c92bd8 sp=0xc820c92ba0
github.com/docker/docker/pkg/ioutils.returnBuffer(0xc8212673b0)
        /go/src/github.com/docker/docker/pkg/ioutils/bytespipe.go:167 +0x60 fp=0xc820c92c28 sp=0xc820c92bd8
github.com/docker/docker/pkg/ioutils.(*BytesPipe).Read(0xc8209b0ac0, 0xc820bf63c0, 0x7c40, 0x7c40, 0x7c0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/ioutils/bytespipe.go:148 +0x2ac fp=0xc820c92d08 sp=0xc820c92c28
io.copyBuffer(0x3fff901cbda0, 0xc82022cea0, 0x3fff9030aa08, 0xc8209b0ac0, 0xc820bf6000, 0x8000, 0x8000, 0x70000, 0x0, 0x0)
        /usr/src/go/src/io/io.go:380 +0x1dc fp=0xc820c92de0 sp=0xc820c92d08
io.Copy(0x3fff901cbda0, 0xc82022cea0, 0x3fff9030aa08, 0xc8209b0ac0, 0xc8209b0ac0, 0x0, 0x0)
        /usr/src/go/src/io/io.go:350 +0x5c fp=0xc820c92e50 sp=0xc820c92de0
github.com/docker/docker/container.AttachStreams.func2(0x1125b878, 0x6, 0x3fff901cbda0, 0xc82022cea0, 0x3fff9030a9d8, 0xc8209b0ac0)
        /go/src/github.com/docker/docker/container/container.go:425 +0x178 fp=0xc820c92f60 sp=0xc820c92e50
runtime.goexit()
        /usr/src/go/src/runtime/asm_ppc64x.s:1049 +0x4 fp=0xc820c92f60 sp=0xc820c92f60
created by github.com/docker/docker/container.AttachStreams
        /go/src/github.com/docker/docker/container/container.go:442 +0x2b8
```

**Comment by cpuguy83** [comment]
Thanks, I see the issue.

**Comment by cpuguy83** [comment]
#22698
