### ISSUE TITLE
Flaky test TestHelpTextVerify (gccgo)?

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#22879]
First time I've seen this failing, but lets create an issue, just in case

seen failing on gccgo; https://jenkins.dockerproject.org/job/Docker-PRs-gccgo/5559/console

```
16:44:36 ----------------------------------------------------------------------
16:44:36 FAIL: docker_cli_help_test.go:15: TestHelpTextVerify.pN52_github_com_docker_docker_integration_cli.DockerSuite
16:44:36 
16:44:36 docker_cli_help_test.go:137:
16:44:36     c.Fatal(err)
16:44:36 ... Error: Error on "top" help. non-empty stderr:"Aborted\n\npanic during panic\n\ngoroutine 16 [syscall]:\n\tgoroutine in C code; stack unavailable\ncreated by main\n\t/usr/src/gcc/libgo/runtime/go-main.c:48\n\ngoroutine 18 [finalizer wait]:\nstack trace unavailable\n"
16:44:36 
```

**Comment by vdemeester** [comment]
Didn't see that one in a while, closing for now
