### ISSUE TITLE
docker attach hangs 1.11.1 release (experimental)

### ISSUE THREAD

**Issue by kunalkushwaha** [docker/docker#22895]
`docker attach` operation hangs if, docker daemon in killed and started again.
Rest of operations like `docker exec` and `docker ps` works fine.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   e3079b4-unsupported
 Built:        Sun May 22 10:18:12 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   e3079b4-unsupported
 Built:        Sun May 22 10:18:12 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
$ docker info
Containers: 18
 Running: 1
 Paused: 0
 Stopped: 17
Images: 68
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 130
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: dev
ID: 7DLO:3SES:XAM2:QKUY:B5IJ:QABX:3TFB:UE65:6OAE:4CAJ:Y6TG:ML5M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Working environment in Virtualbox**

**Steps to reproduce the issue:**
1. Create container in background `docker run -itd --name nyan supertest2014/nyan`
2. Check attach operations `docker attach nyan`
3. detach from container **Ctrl+p + Crtl+q**
4. kill docker daemon using `kill -9 $DockerDaemonPID`
5. restart docker daemon `systemctl start docker`
6. Try `docker ps` - successfull
7. Try `docker exec nyan ps`
8. Try `docker attach nyan` - Hang!!

This issue is always reproducable with 1.11.1 main release and experimental release both.

**Comment by AkihiroSuda** [comment]
I cannot locally reproduce the issue on B2D v1.11.1 (`docker-machine create -d virtualbox`).
```
docker@dm1:~$ docker attach nyan
You cannot attach to a stopped container, start it first
```

@kunalkushwaha Could you provide the stack trace? (send `SIGUSR1` to the daemon)
Is it new to v1.11.1?

**Comment by kunalkushwaha** [comment]
#### Background of issue:

This bug I came across while understanding new features and changes in binaries in 1.11.

Since, the docker binaries are divided into 4 binaries and ``docker-runc`` and ``docker-containerd-shim`` should not be affected by killing docker-daemon and docker-containerd.  

### Issue
- For nayn image, maybe it may not work properly with docker-machine based docker-host. I am using simple virtualbox based dev machine.

Please see the stack trace below of daemon kill and start , operations on docker
```
May 23 10:25:53 mac-dev systemd[1]: Started Docker Application Container Engine.
May 23 10:25:53 mac-dev dockerd[5162]: time="2016-05-23T10:25:53.491059671+09:00" level=info msg="API listen on /var/run/docker.sock"
May 23 10:28:32 mac-dev dockerd[5162]: time="2016-05-23T10:28:32.402792662+09:00" level=error msg="Handler for POST /v1.23/containers/f97986964edd/resize retu
May 23 10:28:32 mac-dev dockerd[5162]: time="2016-05-23T10:28:32.403862801+09:00" level=error msg="Handler for POST /v1.23/containers/f97986964edd/resize retu
May 23 10:28:58 mac-dev dockerd[5162]: time="2016-05-23T10:28:58.812868680+09:00" level=error msg="Handler for POST /v1.23/containers/f97986964edd/resize retu
May 23 10:28:58 mac-dev dockerd[5162]: time="2016-05-23T10:28:58.813876174+09:00" level=error msg="Handler for POST /v1.23/containers/f97986964edd/resize retu
May 23 11:03:12 mac-dev dockerd[5162]: time="2016-05-23T11:03:12.077542574+09:00" level=error msg="attach: stdout: write unix /var/run/docker.sock->@: write:
May 23 11:03:49 mac-dev dockerd[5162]: time="2016-05-23T11:03:49.553359674+09:00" level=error msg="Handler for POST /v1.23/containers/f97986964edd/start retur
May 23 11:04:58 mac-dev dockerd[5162]: time="2016-05-23T11:04:58.412501787+09:00" level=error msg="Handler for POST /v1.23/containers/f97986964edd/resize retu
May 23 11:04:58 mac-dev dockerd[5162]: time="2016-05-23T11:04:58.413501626+09:00" level=error msg="Handler for POST /v1.23/containers/f97986964edd/resize retu
May 23 11:09:07 mac-dev dockerd[5162]: time="2016-05-23T11:09:07.472668364+09:00" level=error msg="Handler for POST /v1.23/containers/create returned error: N
May 23 11:11:44 mac-dev systemd[1]: docker.service: Main process exited, code=killed, status=9/KILL
May 23 11:13:14 mac-dev systemd[1]: docker.service: State 'stop-sigterm' timed out. Killing.
May 23 11:13:14 mac-dev systemd[1]: docker.service: Unit entered failed state.
May 23 11:13:14 mac-dev systemd[1]: docker.service: Failed with result 'timeout'.
May 23 11:13:14 mac-dev systemd[1]: Starting Docker Application Container Engine...
May 23 11:13:14 mac-dev dockerd[16599]: time="2016-05-23T11:13:14+09:00" level=warning msg="Running experimental build"
May 23 11:13:14 mac-dev dockerd[16599]: time="2016-05-23T11:13:14.971601981+09:00" level=info msg="New containerd process, pid: 16606"
May 23 11:13:14 mac-dev dockerd[16599]: time="2016-05-23T11:13:14.982099999+09:00" level=error msg="containerd: get exit status" error="containerd: process ha
May 23 11:13:16 mac-dev dockerd[16599]: time="2016-05-23T11:13:16.017681371+09:00" level=info msg="[graphdriver] using prior storage driver \"aufs\""
May 23 11:13:16 mac-dev dockerd[16599]: time="2016-05-23T11:13:16.064292627+09:00" level=info msg="Graph migration to content-addressability took 0.00 seconds
May 23 11:13:16 mac-dev dockerd[16599]: time="2016-05-23T11:13:16.087968452+09:00" level=info msg="Firewalld running: false"
May 23 11:13:16 mac-dev dockerd[16599]: time="2016-05-23T11:13:16.119566277+09:00" level=info msg="Removing stale sandbox a369c3f84bc59ea7d7edc5a48b0a94f65fc3
May 23 11:13:16 mac-dev dockerd[16599]: time="2016-05-23T11:13:16.144701035+09:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172
May 23 11:13:16 mac-dev dockerd[16599]: time="2016-05-23T11:13:16.175394370+09:00" level=warning msg="Your kernel does not support swap memory limit."
May 23 11:13:16 mac-dev dockerd[16599]: time="2016-05-23T11:13:16.176020901+09:00" level=info msg="Loading containers: start."
May 23 11:13:16 mac-dev dockerd[16599]: .......time="2016-05-23T11:13:16.189406592+09:00" level=warning msg="unexpected backlog event: &types.Event{Type:\"exi
May 23 11:13:16 mac-dev dockerd[16599]: time="2016-05-23T11:13:16.209852720+09:00" level=info msg="Loading containers: done."
May 23 11:13:16 mac-dev dockerd[16599]: time="2016-05-23T11:13:16.210146327+09:00" level=info msg="Daemon has completed initialization"
May 23 11:13:16 mac-dev dockerd[16599]: time="2016-05-23T11:13:16.210307705+09:00" level=info msg="Docker daemon" commit=cbc404a-unsupported graphdriver=aufs
May 23 11:13:16 mac-dev systemd[1]: Started Docker Application Container Engine.
May 23 11:13:16 mac-dev dockerd[16599]: time="2016-05-23T11:13:16.232768854+09:00" level=info msg="API listen on /var/run/docker.sock"
May 23 11:13:43 mac-dev dockerd[16599]: time="2016-05-23T11:13:43.322234708+09:00" level=error msg="Handler for POST /v1.23/containers/972fbf08d7b8/resize ret
May 23 11:13:43 mac-dev dockerd[16599]: time="2016-05-23T11:13:43.323206771+09:00" level=error msg="Handler for POST /v1.23/containers/972fbf08d7b8/resize ret
May 23 11:16:05 mac-dev dockerd[16599]: time="2016-05-23T11:16:05.126519454+09:00" level=info msg="Container 972fbf08d7b8495310f449aff3a8bf51ca304cc91809449d4
```

**Comment by AkihiroSuda** [comment]
@kunalkushwaha Thank you for the information, but the log does not seem to contain the stack trace (it should contain `=== BEGIN goroutine stack dump ===...`)

I could not reproduce the issue even on Ubuntu 16.04 with the default systemd configuration file. (although `docker ps` takes a while)

**Comment by kunalkushwaha** [comment]
Log with stack trace.

After docker daemon restart following operations were performed.
``
$ docker ps
$ docker exec nyan ps
$ docker attach nyan
``


```
May 23 15:58:40 mac-dev dockerd[23533]: time="2016-05-23T15:58:40.255278195+09:00" level=info msg="API listen on /var/run/docker.sock"
May 23 16:01:06 mac-dev dockerd[23533]: time="2016-05-23T16:01:06.064658880+09:00" level=error msg="Handler for POST /v1.23/containers/create returned error:
May 23 16:01:46 mac-dev systemd[1]: docker.service: Main process exited, code=killed, status=9/KILL
May 23 16:03:16 mac-dev systemd[1]: docker.service: State 'stop-sigterm' timed out. Killing.
May 23 16:03:16 mac-dev systemd[1]: docker.service: Unit entered failed state.
May 23 16:03:16 mac-dev systemd[1]: docker.service: Failed with result 'timeout'.
May 23 16:03:16 mac-dev systemd[1]: Starting Docker Application Container Engine...
May 23 16:03:16 mac-dev dockerd[28018]: time="2016-05-23T16:03:16+09:00" level=warning msg="Running experimental build"
May 23 16:03:16 mac-dev dockerd[28018]: time="2016-05-23T16:03:16.307290757+09:00" level=info msg="New containerd process, pid: 28024"
May 23 16:03:16 mac-dev dockerd[28018]: time="2016-05-23T16:03:16.355600233+09:00" level=info msg="[graphdriver] using prior storage driver \"aufs\""
May 23 16:03:16 mac-dev dockerd[28018]: time="2016-05-23T16:03:16.417215343+09:00" level=info msg="Graph migration to content-addressability took 0.00 seconds
May 23 16:03:16 mac-dev dockerd[28018]: time="2016-05-23T16:03:16.440954227+09:00" level=info msg="Firewalld running: false"
May 23 16:03:16 mac-dev dockerd[28018]: time="2016-05-23T16:03:16.472930784+09:00" level=info msg="Removing stale sandbox f73e8dc7fb1b670826c933d7a6a0bf5e2350
May 23 16:03:16 mac-dev dockerd[28018]: time="2016-05-23T16:03:16.497684426+09:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172
May 23 16:03:16 mac-dev dockerd[28018]: time="2016-05-23T16:03:16.526527305+09:00" level=warning msg="Your kernel does not support swap memory limit."
May 23 16:03:16 mac-dev dockerd[28018]: time="2016-05-23T16:03:16.527171911+09:00" level=info msg="Loading containers: start."
May 23 16:03:16 mac-dev dockerd[28018]: ........
May 23 16:03:16 mac-dev dockerd[28018]: time="2016-05-23T16:03:16.551970834+09:00" level=info msg="Loading containers: done."
May 23 16:03:16 mac-dev dockerd[28018]: time="2016-05-23T16:03:16.552159211+09:00" level=info msg="Daemon has completed initialization"
May 23 16:03:16 mac-dev dockerd[28018]: time="2016-05-23T16:03:16.552311320+09:00" level=info msg="Docker daemon" commit=cbc404a-unsupported graphdriver=aufs
May 23 16:03:16 mac-dev systemd[1]: Started Docker Application Container Engine.
May 23 16:03:16 mac-dev dockerd[28018]: time="2016-05-23T16:03:16.578290266+09:00" level=info msg="API listen on /var/run/docker.sock"
May 23 16:03:45 mac-dev dockerd[28018]: time="2016-05-23T16:03:45.457086137+09:00" level=error msg="Handler for POST /v1.23/containers/nyan/resize returned er
May 23 16:03:45 mac-dev dockerd[28018]: time="2016-05-23T16:03:45.458140137+09:00" level=error msg="Handler for POST /v1.23/containers/nyan/resize returned er
May 23 16:05:02 mac-dev dockerd[28018]: time="2016-05-23T16:05:02.519292829+09:00" level=info msg="=== BEGIN goroutine stack dump ===\ngoroutine 19 [running]:
May 23 16:05:02 mac-dev dockerd[28018]: usr/local/go/src/os/doc.go:45 +0x2d\nos/exec.(*Cmd).Wait(0xc820360c80, 0x0, 0x0)\n\t/usr/local/go/src/os/exec/exec.go:
May 23 16:05:02 mac-dev dockerd[28018]:  0x0, 0x0)\n\t/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a\nnet.(*pollDesc).WaitRead(0xc82036c920, 0x0, 0x0)\n\t/
May 23 16:05:02 mac-dev dockerd[28018]: lang.org/grpc.NewClientStream\n\t/usr/src/docker/vendor/src/google.golang.org/grpc/stream.go:138 +0x869\n\ngoroutine 1
May 23 16:05:02 mac-dev dockerd[28018]: ime.selectgoImpl(0xc82001e728, 0x0, 0x18)\n\t/usr/local/go/src/runtime/select.go:392 +0xa64\nruntime.selectgo(0xc82001
May 23 16:05:02 mac-dev dockerd[28018]: r/src/docker/vendor/src/github.com/docker/libnetwork/sandbox_externalkey_unix.go:122 +0x28a\n\ngoroutine 71 [chan rece
May 23 16:05:02 mac-dev dockerd[28018]: , 0x7f5d32fc4990, 0xc8208aee78, 0x7f5d32fc4990, 0xc8208aee78, 0xc820a60100, 0x2055df8, ...)\n\t/usr/src/docker/.gopath
May 23 16:05:02 mac-dev dockerd[28018]:  0xc820085ea0)\n\t/usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e\ngithub.com/docker/docker/api/ser
May 23 16:05:02 mac-dev dockerd[28018]: 0x0, 0x0)\n\t/usr/local/go/src/io/pipe.go:52 +0x2d2\nio.(*PipeReader).Read(0xc8200256a8, 0xc82088c000, 0x8000, 0x8000,
May 23 16:05:02 mac-dev dockerd[28018]: time_Syncsemacquire(0xc8201fead0)\n\t/usr/local/go/src/runtime/sema.go:237 +0x201\nsync.(*Cond).Wait(0xc8201feac0)\n\t
May 23 16:05:02 mac-dev dockerd[28018]: ollWait(0x7f5d32fc4170, 0x72, 0xc82000e180)\n\t/usr/local/go/src/runtime/netpoll.go:157 +0x60\nnet.(*pollDesc).Wait(0x
May 23 16:05:02 mac-dev dockerd[28018]: nio.(*LimitedReader).Read(0xc820528540, 0xc820838000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\t/usr/local/go/src/io/io.go:427
May 23 16:05:02 mac-dev dockerd[28018]: spipe.go:134 +0xf7\nio.copyBuffer(0x7f5d32fc4990, 0xc8208aee78, 0x7f5d32f3a848, 0xc82019fb80, 0xc820aee000, 0x8000, 0x
May 23 16:05:02 mac-dev dockerd[28018]: n\t/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36\nnet.(*netFD).Read(0xc820aa0690, 0xc820ade000, 0x8000, 0x8000, 0x
May 23 16:05:02 mac-dev dockerd[28018]: r/src/docker/.gopath/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x5d\n\n=== END goroutine stack dump ==="
```

**Comment by thaJeztah** [comment]
Killing the daemon and restarting it on "experimental" will try to re-attach to the container, and there's still some issues with that (also see https://github.com/docker/docker/issues/21933). For me the container is showing up again after restarting, but attaching hangs indeed;

```
May 23 05:07:16 digitalocean dockerd[13561]: time="2016-05-23T05:07:16.452890056-04:00" level=error msg="Handler for POST /v1.24/containers/nyan/resize returned error: rpc error: code = 3 desc = \"invalid argument\""
May 23 05:07:16 digitalocean dockerd[13561]: time="2016-05-23T05:07:16.455129519-04:00" level=error msg="Handler for POST /v1.24/containers/nyan/resize returned error: rpc error: code = 3 desc = \"invalid argument\""
```

Exec-ing in the container works for me though;
```
docker exec -it nyan bash
root@9de81d12173f:/#
```

On non-experimental, there's a slightly different issue; after killing `docker daemon` and starting again, `docker ps` shows that the container is exited;

```
CONTAINER ID        IMAGE                COMMAND                CREATED             STATUS                      PORTS               NAMES
eb8eaa41b8b3        supertest2014/nyan   "/bin/sh -c nyancat"   18 minutes ago      Exited (0) 15 minutes ago                       nan

```
However, starting the container doesn't work, looks like the state of `docker-containerd` and `docker daemon` are out of sync in that case;

```
May 23 05:56:46 digitalocean docker[16723]: time="2016-05-23T05:56:46.201963383-04:00" level=error msg="Handler for POST /v1.23/containers/nyan/start returned error: Container eb8eaa41b8b36a56b34502458f4bf44c64e9a8a28c5bb815533525862e4e2210 is aleady active"
```

stopping and starting again doesn't work either;

```
docker stop nyan
nyan
docker start nyan
Error response from daemon: Container eb8eaa41b8b36a56b34502458f4bf44c64e9a8a28c5bb815533525862e4e2210 is aleady active
Error: failed to start containers: nyan
```

(and logs:)
```
May 23 05:59:06 digitalocean docker[16723]: time="2016-05-23T05:59:06.947435285-04:00" level=error msg="Handler for POST /v1.23/containers/nyan/stop returned error: Container nyan is already stopped"
May 23 05:59:20 digitalocean kernel: [ 4099.466155] aufs au_opts_verify:1597:docker[16740]: dirperm1 breaks the protection by the permission bits on the lower branch
May 23 05:59:20 digitalocean kernel: [ 4099.471178] device vethdfa5ed8 entered promiscuous mode
May 23 05:59:20 digitalocean kernel: [ 4099.471302] IPv6: ADDRCONF(NETDEV_UP): vethdfa5ed8: link is not ready
May 23 05:59:20 digitalocean systemd-udevd[16880]: Could not generate persistent MAC address for vethdfa5ed8: No such file or directory
May 23 05:59:20 digitalocean systemd-udevd[16879]: Could not generate persistent MAC address for veth7f497e4: No such file or directory
May 23 05:59:20 digitalocean kernel: [ 4099.488728] docker0: port 1(vethdfa5ed8) entered disabled state
May 23 05:59:20 digitalocean kernel: [ 4099.489824] device vethdfa5ed8 left promiscuous mode
May 23 05:59:20 digitalocean kernel: [ 4099.489828] docker0: port 1(vethdfa5ed8) entered disabled state
May 23 05:59:20 digitalocean docker[16723]: time="2016-05-23T05:59:20.346948775-04:00" level=error msg="Handler for POST /v1.23/containers/nyan/start returned error: Container eb8eaa41b8b36a56b34502458f4bf44c64e9a8a28c5bb815533525862e4e2210 is aleady active"
```

To resolve this, doing a "clean" restart of the daemon;

```
systemctl restart docker
docker start nyan
nyan
docker ps
CONTAINER ID        IMAGE                COMMAND                CREATED             STATUS              PORTS               NAMES
eb8eaa41b8b3        supertest2014/nyan   "/bin/sh -c nyancat"   22 minutes ago      Up 8 seconds
```


So, for experimental, I think this is still something that's being worked on. For the 1.11.1 issue, I seem to recall there's a PR in `containerd` that resolves the "state getting out of sync" if the daemon is not shut-down cleanly.

**Comment by thaJeztah** [comment]
For the "already active" issue on 1.11.1, see https://github.com/docker/docker/issues/22851 (and the PR in containerd https://github.com/docker/containerd/pull/129)

**Comment by thaJeztah** [comment]
ping @mlaventure @tonistiigi do you know if the "already active" issue was resolved?

**Comment by thaJeztah** [comment]
I created a separate issue for the "already active" issue on docker 1.11.1 (non-experimental) https://github.com/docker/docker/issues/22913

**Comment by krasi-georgiev** [comment]
@thaJeztah  do you know if this is fixed?  
I can try to work on it

**Comment by thaJeztah** [comment]
@krasi-georgiev not sure, may be worth checking if the issue is reproducible on 1.13.1

**Comment by krasi-georgiev** [comment]
@kunalkushwaha , @thaJeztah  just tried it against 1.3.x and no problem

**Comment by thaJeztah** [comment]
@kunalkushwaha can you confirm this issue is fixed on 1.13.1? I suggest closing this issue then

**Comment by kunalkushwaha** [comment]
Its strange, but now container gets killed on restart of docker daemon.

-- Create container in background docker run -itd --name nyan supertest2014/nyan
- Check attach operations docker attach nyan
- detach from container Ctrl+p + Crtl+q
- kill docker daemon using kill -9 $DockerDaemonPID
- restart docker daemon systemctl start docker
- Try docker ps -  container is killed (``Exited (137) ``)


I tried with experimental and without experimental flag.

```
$ docker version               
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ docker-containerd --version
containerd version 0.2.3 commit: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1


$ docker-runc --version
runc version 1.0.0-rc2
commit: 9df8b306d01f59d3a8029be411de015b7304dd8f
spec: 1.0.0-rc2-dev

```

**Comment by krasi-georgiev** [comment]
@kunalkushwaha this is by design , you need to set --restart=always 

https://docs.docker.com/engine/reference/commandline/run/#/restart-policies---restart

**Comment by thaJeztah** [comment]
thanks for your help with triaging issues, @krasi-georgiev! Really appreciated ❤️

**Comment by kunalkushwaha** [comment]
@krasi-georgiev  No, this scenario  is different then you mentioned.

From docker v1.12, docker containers run independently of docker-daemon & docker-daemon can be restarted without affecting container lifecycle. 

ref:
- https://github.com/docker/docker/pull/23213
- https://docs.docker.com/engine/admin/live-restore/


Interestingly, now while verifying, I forgot to add ``--live-restore`` flag to docker-daemon, which enable daemon to reconnect to running containers after restart.




So this bug is fixed :), Closing.
