### ISSUE TITLE
pkg/jsonmessage.TestProgress fails depending on TIOCGWINSZ

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker#23112]
**Steps to reproduce the issue:**

The test fails if COLUMNS <= 110.

```
$ echo $COLUMNS
$ go test -c ./pkg/jsonmessage
$ go test -v ./jsonmessage.test
```

Docker: ef42e2f214dd528e3520d394d2d648de92f703cd
Go: 1.6.1

**Describe the results you received:**
```
=== RUN   TestProgress
--- FAIL: TestProgress (0.00s)
panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 7 [running]:
panic(0x586a80, 0xc8200100b0)
        /usr/lib/go-1.6/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc820094090)
        /usr/lib/go-1.6/src/testing/testing.go:467 +0x192
panic(0x586a80, 0xc8200100b0)
        /usr/lib/go-1.6/src/runtime/panic.go:426 +0x4e9
_/mnt/disk2/WORK/docker/pkg/jsonmessage.TestProgress(0xc820094090)
        /mnt/disk2/WORK/docker/pkg/jsonmessage/jsonmessage_test.go:37 +0xa80
testing.tRunner(0xc820094090, 0x893a98)
        /usr/lib/go-1.6/src/testing/testing.go:473 +0x98
created by testing.RunTests
        /usr/lib/go-1.6/src/testing/testing.go:582 +0x892
```

**Describe the results you expected:**
The test should not fail.

**Additional information you deem important (e.g. issue happens only occasionally):**

 * `go test -v ./pkg/jsonmessage` (without `-c`) succeeds because `ioctl` for `TIOCGWINSZ` returns `ENOTTY`
 * Found in PR https://github.com/docker/docker/pull/22930, which is an attempt to simplify `go test` in `hack/*`

 * the panic occured at https://github.com/docker/docker/blob/ef42e2f214dd528e3520d394d2d648de92f703cd/pkg/jsonmessage/jsonmessage_test.go#L37 . `jp3.String()` returns `"    20 B/100 B 0"` (len=16) in this case.

**Comment by AkihiroSuda** [comment]
opened PR #23113
