### ISSUE TITLE
java.rmi.server.ExportException: Listen failed on port: 1098; nested exception is: java.net.SocketException: Operation not permitted

### ISSUE THREAD

**Issue by mlecar** [docker/docker#23181]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 58
 Running: 1
 Paused: 0
 Stopped: 57
Images: 137
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 242
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.63 GiB
Name: TOQUELAU
ID: DSMI:554H:O6A7:KYIW:BDBR:MMUL:PRZB:QQEU:3BZQ:DWJZ:V77U:I3EZ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS, VirtualBox

**Steps to reproduce the issue:**
1. Using image centos:7
2. Install jboss 4.2.3-jdk6
3. Install suport 32 bit lib with "yum install glibc.i686"
4. Install jdk1.8.0_51 64bit
5. Configure JAVA_HOME and PATH with JAVA_HOME/bin
6. Run command /jboss-4.2.3.GA/bin/run.sh -b 0.0.0.0 -c minimal

**Describe the results you received:**
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /jboss-4.2.3.GA

  JAVA: /jdk1.8.0_51/bin/java

  JAVA_OPTS: -Dprogram.name=run.sh -server -Xms128m -Xmx512m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djava.net.preferIPv4Stack=true

  CLASSPATH: /jboss-4.2.3.GA/bin/run.jar:/jdk1.8.0_51/lib/tools.jar

=========================================================================

23:38:21,476 INFO  [Server] Starting JBoss (MX MicroKernel)...
23:38:21,477 INFO  [Server] Release ID: JBoss [Trinity] 4.2.3.GA (build: SVNTag=JBoss_4_2_3_GA date=200807181439)
23:38:21,477 INFO  [Server] Home Dir: /jboss-4.2.3.GA
23:38:21,477 INFO  [Server] Home URL: file:/jboss-4.2.3.GA/
23:38:21,478 INFO  [Server] Patch URL: null
23:38:21,478 INFO  [Server] Server Name: minimal
23:38:21,478 INFO  [Server] Server Home Dir: /jboss-4.2.3.GA/server/minimal
23:38:21,478 INFO  [Server] Server Home URL: file:/jboss-4.2.3.GA/server/minimal/
23:38:21,478 INFO  [Server] Server Log Dir: /jboss-4.2.3.GA/server/minimal/log
23:38:21,478 INFO  [Server] Server Temp Dir: /jboss-4.2.3.GA/server/minimal/tmp
23:38:21,478 INFO  [Server] Root Deployment Filename: jboss-service.xml
23:38:21,595 INFO  [ServerInfo] Java version: 1.8.0_51,Oracle Corporation
23:38:21,596 INFO  [ServerInfo] Java VM: Java HotSpot(TM) Server VM 25.51-b03,Oracle Corporation
23:38:21,596 INFO  [ServerInfo] OS-System: Linux 4.4.0-22-generic,i386
23:38:21,676 INFO  [Server] Core system initialized
23:38:21,834 INFO  [Log4jService$URLWatchTimerTask] Configuring from URL: resource:jboss-log4j.xml
23:38:21,890 WARN  [ServiceController] Problem starting service jboss:service=Naming
java.rmi.server.ExportException: Listen failed on port: 1098; nested exception is: 
	java.net.SocketException: Operation not permitted
	at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:343)
	at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:249)
	at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:411)
	at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
	at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:208)
	at java.rmi.server.UnicastRemoteObject.exportObject(UnicastRemoteObject.java:383)
	at java.rmi.server.UnicastRemoteObject.exportObject(UnicastRemoteObject.java:346)
	at org.jnp.server.Main.initJnpInvoker(Main.java:354)
	at org.jnp.server.Main.start(Main.java:316)
	at org.jboss.naming.NamingService.startService(NamingService.java:284)
	at org.jboss.system.ServiceMBeanSupport.jbossInternalStart(ServiceMBeanSupport.java:289)
	at org.jboss.system.ServiceMBeanSupport.jbossInternalLifecycle(ServiceMBeanSupport.java:245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:155)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:94)
	at org.jboss.mx.interceptor.AbstractInterceptor.invoke(AbstractInterceptor.java:133)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88)
	at org.jboss.mx.interceptor.ModelMBeanOperationInterceptor.invoke(ModelMBeanOperationInterceptor.java:142)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
	at org.jboss.system.ServiceController$ServiceProxy.invoke(ServiceController.java:978)
	at com.sun.proxy.$Proxy0.start(Unknown Source)
	at org.jboss.system.ServiceController.start(ServiceController.java:417)
	at org.jboss.system.ServiceController.start(ServiceController.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:155)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:94)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:86)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
	at org.jboss.mx.util.MBeanProxyExt.invoke(MBeanProxyExt.java:210)
	at com.sun.proxy.$Proxy4.start(Unknown Source)
	at org.jboss.deployment.SARDeployer.start(SARDeployer.java:304)
	at org.jboss.deployment.MainDeployer.start(MainDeployer.java:1025)
	at org.jboss.deployment.MainDeployer.deploy(MainDeployer.java:819)
	at org.jboss.deployment.MainDeployer.deploy(MainDeployer.java:782)
	at org.jboss.deployment.MainDeployer.deploy(MainDeployer.java:766)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:155)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:94)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:86)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
	at org.jboss.mx.util.MBeanProxyExt.invoke(MBeanProxyExt.java:210)
	at com.sun.proxy.$Proxy5.deploy(Unknown Source)
	at org.jboss.system.server.ServerImpl.doStart(ServerImpl.java:482)
	at org.jboss.system.server.ServerImpl.start(ServerImpl.java:362)
	at org.jboss.Main.boot(Main.java:200)
	at org.jboss.Main$1.run(Main.java:508)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Operation not permitted
	at java.net.ServerSocket.createImpl(ServerSocket.java:307)
	at java.net.ServerSocket.getImpl(ServerSocket.java:257)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at org.jboss.net.sockets.DefaultSocketFactory.createServerSocket(DefaultSocketFactory.java:120)
	at org.jboss.net.sockets.DefaultSocketFactory.createServerSocket(DefaultSocketFactory.java:95)
	at sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:666)
	at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:330)
	... 59 more
23:38:21,892 ERROR [Server] Root deployment has missing dependencies; continuing
Incomplete Deployment listing:

--- MBeans waiting for other MBeans ---
ObjectName: jboss:service=Naming
  State: FAILED
  Reason: java.rmi.server.ExportException: Listen failed on port: 1098; nested exception is: 
	java.net.SocketException: Operation not permitted
  I Depend On:
    jboss.system:service=ThreadPool
    jboss:service=NamingBeanImpl

--- MBEANS THAT ARE THE ROOT CAUSE OF THE PROBLEM ---
ObjectName: jboss:service=Naming
  State: FAILED
  Reason: java.rmi.server.ExportException: Listen failed on port: 1098; nested exception is: 
	java.net.SocketException: Operation not permitted
  I Depend On:
    jboss.system:service=ThreadPool
    jboss:service=NamingBeanImpl

	at org.jboss.deployment.MainDeployer.checkIncompleteDeployments(MainDeployer.java:1385)
	at org.jboss.deployment.MainDeployer.deploy(MainDeployer.java:785)
	at org.jboss.deployment.MainDeployer.deploy(MainDeployer.java:766)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:155)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:94)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:86)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:659)
	at org.jboss.mx.util.MBeanProxyExt.invoke(MBeanProxyExt.java:210)
	at com.sun.proxy.$Proxy5.deploy(Unknown Source)
	at org.jboss.system.server.ServerImpl.doStart(ServerImpl.java:482)
	at org.jboss.system.server.ServerImpl.start(ServerImpl.java:362)
	at org.jboss.Main.boot(Main.java:200)
	at org.jboss.Main$1.run(Main.java:508)
	at java.lang.Thread.run(Thread.java:745)
23:38:21,894 INFO  [Server] JBoss (MX MicroKernel) [4.2.3.GA (build: SVNTag=JBoss_4_2_3_GA date=200807181439)] Started in 415ms

**Describe the results you expected:**
Not happen:
23:38:21,890 WARN  [ServiceController] Problem starting service jboss:service=Naming
java.rmi.server.ExportException: Listen failed on port: 1098; nested exception is: 
	java.net.SocketException: Operation not permitted

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by HackToday** [comment]
Did you run above reproduce steps in container or not ?

What container options do you use to kick that container run ?

**Comment by justincormack** [comment]
Can you provide a container (a standalone Dockerfile or a container pushed to docker hub) that reproduces this?

**Comment by justincormack** [comment]
Also can you try with 1.11.2, there is a fix that might be related?

**Comment by mlecar** [comment]
Hi guys,
I did some other tests and realized that architecture 64-bit of jdk works, but 32-bit doesn't. My host is 64-bit (as docker info and docker version previously added) and I installed the 32-bit support for centos on image too.

The Dockerfile with jdk 32-bit that doesn't work is:
`FROM centos:7

RUN yum update

RUN yum install -y unzip
RUN yum install -y curl
RUN yum install -y libstdc++.i686
RUN yum install -y less

#download jboss 4.2.3 jdk6
RUN curl -v -O http://pilotfiber.dl.sourceforge.net/project/jboss/JBoss/JBoss-4.2.3.GA/jboss-4.2.3.GA-jdk6.zip
RUN unzip -q jboss-4.2.3.GA-jdk6.zip

#download jdk-8u51-linux-i586.rpm
RUN curl -v -j -k -O -L -H "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u51-b16/jdk-8u51-linux-i586.rpm > jdk-8u51-linux-i586.rpm
RUN yum install -y jdk-8u51-linux-i586.rpm

ENTRYPOINT ["/jboss-4.2.3.GA/bin/run.sh", "-b", "0.0.0.0", "-c", "minimal"]
`
build command: docker build --tag jdk8u51-jboss423-minimal-32bit .
run command: docker run -it jdk8u51-jboss423-minimal-32bit bash

But, as I said, with 64-bit works and the Dockerfile is:
`FROM centos:7

RUN yum update

RUN yum install -y unzip
RUN yum install -y curl
RUN yum install -y libstdc++.i686
RUN yum install -y less

#download jboss 4.2.3 jdk6
RUN curl -v -O http://pilotfiber.dl.sourceforge.net/project/jboss/JBoss/JBoss-4.2.3.GA/jboss-4.2.3.GA-jdk6.zip
RUN unzip -q jboss-4.2.3.GA-jdk6.zip

#download jdk-8u51-linux-x64.rpm
RUN curl -v -j -k -O -L -H "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u51-b16/jdk-8u51-linux-x64.rpm > jdk-8u51-linux-x64.rpm
RUN yum install -y jdk-8u51-linux-x64.rpm

ENTRYPOINT ["/jboss-4.2.3.GA/bin/run.sh", "-b", "0.0.0.0", "-c", "minimal"]
`

build command: docker build --tag jdk8u51-jboss423-minimal-64bit .
run command: docker run -it jdk8u51-jboss423-minimal-64bit bash

So I decided to go for 64-bit jdk. But I think it's up to you to tell if this is really an issue or not.

Thank you for support!

**Comment by thaJeztah** [comment]
@mlecar have you tried the 1.11.2 release as well? 32-bit support may be fixed there.

**Comment by mlecar** [comment]
No, I didn't. Let me try to do that.

**Comment by mlecar** [comment]
Yes, both architectures of jdk (64-bit and 32-bit), are working on 1.11.2 release. 

Thank you guys!

**Comment by thaJeztah** [comment]
Cool, thanks for testing! Happy that it's resolved 👍
