### ISSUE TITLE
Windows - Running .NET app in docker w/ perf counters

### ISSUE THREAD

**Issue by volak** [docker/docker#23225]
I was pointed here from the Microsoft forums - hope its the right place.  I have discovered an issue with windows containers concerning performance counters specifically the System.Diagnostics library.

I've reproduced this issue in a solution here: https://github.com/volak/PerformanceCounterBug
Simply build this app and run inside a container like so:

docker run windowsservercore PerformanceCounterBug.exe

The app uses Metrics.Net to read and create system performance counters.  In tech preview 4 this functionality worked fine - in TP 5 I'm getting the following exception:

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.Win32.Win32Native.RegQueryValueEx(SafeRegistryHandle hKey, String lpValueName, Int32[] lpReserved, Int32& lpType, Byte[] lpData, Int32& lpcbData)
   at Microsoft.Win32.RegistryKey.InternalGetValue(String name, Object defaultValue, Boolean doNotExpand, Boolean checkSecurity)
   at Microsoft.Win32.RegistryKey.GetValue(String name)
   at System.Diagnostics.PerformanceMonitor.GetData(String item)
   at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item)
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CategoryExists(String machine, String category)
   at System.Diagnostics.PerformanceCounterCategory.Exists(String categoryName, String machineName)
   at System.Diagnostics.PerformanceCounterCategory.Exists(String categoryName)
   at Metrics.PerfCounters.PerformanceCounters.WrappedRegister(MetricsContext context, String name, Unit unit, String category, String counter, String instance, Func`2 deriv
ate, MetricTags tags) in C:\Work\Metrics.NET\Src\Metrics\PerfCounters\PerformanceCounters.cs:line 131
   at Metrics.PerfCounters.PerformanceCounters.Register(MetricsContext context, String name, Unit unit, String category, String counter, String instance, Func`2 derivate, Me
tricTags tags) in C:\Work\Metrics.NET\Src\Metrics\PerfCounters\PerformanceCounters.cs:line 98
   at Metrics.PerfCounters.PerformanceCounters.RegisterAppCounters(MetricsContext context) in C:\Work\Metrics.NET\Src\Metrics\PerfCounters\PerformanceCounters.cs:line 56
   at Metrics.PerformanceCountersConfigExtensions.<>c__DisplayClass4_0.<WithAppCounters>b__0(MetricsContext ctx, Func`1 hs) in C:\Work\Metrics.NET\Src\Metrics\PerfCounters\P
erformanceCountersConfigExtensions.cs:line 37
   at Metrics.MetricsConfig.<>c__DisplayClass17_0.<WithConfigExtension>b__0(MetricsContext m, Func`1 h) in C:\Work\Metrics.NET\Src\Metrics\MetricsConfig.cs:line 176
   at Metrics.MetricsConfig.WithConfigExtension[T](Func`3 extension) in C:\Work\Metrics.NET\Src\Metrics\MetricsConfig.cs:line 190
   at Metrics.MetricsConfig.WithConfigExtension(Action`2 extension) in C:\Work\Metrics.NET\Src\Metrics\MetricsConfig.cs:line 176
   at Metrics.PerformanceCountersConfigExtensions.WithAppCounters(MetricsConfig config, String context) in C:\Work\Metrics.NET\Src\Metrics\PerfCounters\PerformanceCountersCo
nfigExtensions.cs:line 37
   at PerformanceCounterBug.Program.Main(String[] args) in c:\users\charl\Projects\PerformanceCounterBug\PerformanceCounterBug\Program.cs:line 17
```

@PaulParau @jhowardmsft

**Comment by volak** [comment]
Forgot the docker info

```
PS C:\Users\Administrator> docker info
Containers: 172
 Running: 9
 Paused: 0
 Stopped: 163
Images: 4
Server Version: 1.12.0-dev
Storage Driver: Windows filter storage driver
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: transparent nat null
Kernel Version: 10.0 14300 (14300.1016.amd64fre.rs1_release_svc.160428-1819)
Operating System: Windows Server 2016 Standard Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 63.89 GiB
Name: HOME
ID: ZICW:54EJ:5H7E:J2EC:GYGR:SI4B:BXES:PQZY:IQ2P:F75F:ZDDO:5GGP
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
PS C:\Users\Administrator> docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64
```

**Comment by volak** [comment]
Seems this issue was fixed at some point - closing

**Comment by thaJeztah** [comment]
Thanks @volak
