### ISSUE TITLE
Dockerd(Swarm): panic serving  After create user defined network 

### ISSUE THREAD

**Issue by sqleejan** [docker/docker#23655]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   74873f1-unsupported
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   74873f1-unsupported
 Built:        
 OS/Arch:      linux/amd64
```

**Steps to reproduce the issue:**
1.I make the node as manager role in Docker Swarm(docker swarm init )
2.Start Calico Network Plugin  ("/run/docker/plugins/calico.sock")
3.Docker network create -d calico --subnet=10.1.2.0/24 calico1
4.the Output of "Docker network ls" is “An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/networks: EOF ”

**Output of Dockerd:**
```
ERRO[0006] failed allocating network 6hr82hpafwlyl2jv2b9yx8fzj during init: failed during network allocation for network 6hr82hpafwlyl2jv2b9yx8fzj: failed while allocating driver state for network 6hr82hpafwlyl2jv2b9yx8fzj: could not resolve network driver calico 
INFO[0006] Daemon has completed initialization          
INFO[0006] Docker daemon                                 commit=74873f1-unsupported graphdriver=devicemapper version=1.12.0-dev
INFO[0006] Initial encryption keys: [(key: 2d022, tag: 0x1) (key: 86db0, tag: 0x2)] 
INFO[0006] API listen on /var/run/docker.sock           
WARN[0006] task updates not yet supported                module=taskmanager task.id=97lzimxjitx4l1ggh1f5wmta6
ERRO[0007] Failed joining ingress sandbox to ingress endpoint: subnet sandbox join failed for "10.255.0.0/16": vxlan interface creation failed for subnet "10.255.0.0/16": failed to set link up: transport endpoint is not connected 
WARN[0011] task updates not yet supported                module=taskmanager task.id=0sf4qoxznn0ndq2fqjorc8hnb
2016-06-16 23:53:45.711924 I | http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 389 [running]:
net/http.(*conn).serve.func1(0xc8214e0b00)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x19d15e0, 0xc82000a0e0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/docker/docker/daemon/cluster/convert.BasicNetworkFromGRPC(0xc821009fa0, 0x19, 0x63, 0xc820b5b8b0, 0xc820b5b8c0, 0xc820b5b898, 0x7, 0x0, 0xc821009fc0, 0x0, ...)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/cluster/convert/network.go:155 +0x35b
github.com/docker/docker/daemon/cluster.(*Cluster).GetNetworks(0xc820a23bc0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/cluster/cluster.go:874 +0x292
github.com/docker/docker/api/server/router/network.(*networkRouter).getNetworksList(0xc820ac6330, 0x7f3535aa24f8, 0xc820c19140, 0x7f3535a89760, 0xc8202d6dd0, 0xc82116f0a0, 0xc820c18ff0, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/router/network/network_routes.go:29 +0x190
github.com/docker/docker/api/server/router/network.(*networkRouter).(github.com/docker/docker/api/server/router/network.getNetworksList)-fm(0x7f3535aa24f8, 0xc820c19140, 0x7f3535a89760, 0xc8202d6dd0, 0xc82116f0a0, 0xc820c18ff0, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/router/network/network.go:33 +0x74
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f3535aa24f8, 0xc820c19140, 0x7f3535a89760, 0xc8202d6dd0, 0xc82116f0a0, 0xc820c18ff0, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x7f3535aa24f8, 0xc820c19050, 0x7f3535a89760, 0xc8202d6dd0, 0xc82116f0a0, 0xc820c18ff0, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x68e
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f3535a89760, 0xc8202d6dd0, 0xc82116f0a0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x138
net/http.HandlerFunc.ServeHTTP(0xc820a62900, 0x7f3535a89760, 0xc8202d6dd0, 0xc82116f0a0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8209b8190, 0x7f3535a89760, 0xc8202d6dd0, 0xc82116f0a0)
	/root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8207640e0, 0x7f3535a89760, 0xc8202d6dd0, 0xc82116f0a0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc8203ea080, 0x7f3535a89760, 0xc8202d6dd0, 0xc82116f0a0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8214e0b00)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

**Describe the results you expected:**
I see that dockerd should not happen  "panic serving" anyway

I have some Questions:
  1.In docker Swarm cluster ,Can I use "docker run " command to create container with user defined network  ?
  2.Will docker service support VIP  in version 1.12?

**Comment by icecrime** [comment]
Cc @aboch @mrjana @mavenugo!

**Comment by icecrime** [comment]
Cc @vieux @dnephin!

**Comment by mavenugo** [comment]
@sqleejan there are couple of issues here -

1. Network plugins are not currently supported in `swarmkit` and hence `docker network create -d {plugin}` will not work if the plugin is a GLOBAL_SCOPED driver in `swarm-mode`.
2. Networks created in `swarm-mode` will work only with `docker service` and cannot be used with `docker run`.

We have to fix the panic certainly ( I will push a PR shortly ). But the functionality that you are trying to achieve won't work till the above 2 issues are resolved.
