### ISSUE TITLE
docker inspect stopped working after upgrade of Docker for Windows

### ISSUE THREAD

**Issue by provegard** [docker/docker#23745]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 366
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 252
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.854 GiB
Name: moby
ID: NLEM:6W2R:YS2K:C43R:BBWZ:L2V6:CP2N:AEQS:WIWA:WUNV:L2HA:O6KJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 10.

**Steps to reproduce the issue:**
1. docker run hello-world
2. docker inspect hello-world

**Describe the results you received:**

```
[]
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/hello-world/json: EOF
```

**Describe the results you expected:**

Normal `docker inspect` output.

**Additional information you deem important (e.g. issue happens only occasionally):**

Prior to today's upgrade, the inspect command worked as expected.

Full diagnostics uploaded and reported in this forum thread: https://forums.docker.com/t/docker-inspect-stopped-working-after-upgrade/15842

From the log:

```
[13:38:07.072][ProxyProcess   ][Info   ] proxy >> GET /v1.24/containers/hello-world/json
[13:38:07.075][ProxyProcess   ][Info   ] Dial Hyper-V socket a5f8deb1-05c8-4df1-8eb0-5230b5727d4e:23a432c2-537a-4291-bcb5-d62504644739
[13:38:07.075][ProxyProcess   ][Info   ] http: panic serving //./pipe/docker_engine: runtime error: invalid memory address or nil pointer dereference
[13:38:07.081][ProxyProcess   ][Info   ] goroutine 62 [running]:
[13:38:07.084][ProxyProcess   ][Info   ] net/http.(*conn).serve.func1(0xc082143500)
[13:38:07.086][ProxyProcess   ][Info   ]    C:/go/src/net/http/server.go:1389 +0xc8
[13:38:07.089][ProxyProcess   ][Info   ] panic(0x8e40e0, 0xc082006060)
[13:38:07.092][ProxyProcess   ][Info   ]    C:/go/src/runtime/panic.go:443 +0x4f7
[13:38:07.095][ProxyProcess   ][Info   ] github.com/docker/pinata/v1/docker_proxy.(*inspectRewriter).Rewrite(0xc082104e20, 0x1aa4878, 0xc08210b640, 0x0, 0x0, 0x0)
[13:38:07.098][ProxyProcess   ][Info   ]    c:/gopath/src/github.com/docker/pinata/v1/docker_proxy/inspect.go:88 +0x5f0
[13:38:07.100][ProxyProcess   ][Info   ] github.com/docker/pinata/v1/docker_proxy.(*passthru).HandleHTTP(0xc082108a60, 0x1aa4348, 0xc0821121a0, 0xc08215c8c0, 0x0, 0x0)
[13:38:07.103][ProxyProcess   ][Info   ]    c:/gopath/src/github.com/docker/pinata/v1/docker_proxy/passthru.go:88 +0xb99
[13:38:07.105][ProxyProcess   ][Info   ] github.com/docker/pinata/v1/docker_proxy.addRoute.func1(0x1aa4348, 0xc0821121a0, 0xc08215c8c0)
[13:38:07.109][ProxyProcess   ][Info   ]    c:/gopath/src/github.com/docker/pinata/v1/docker_proxy/proxy.go:77 +0x6c
[13:38:07.112][ProxyProcess   ][Info   ] net/http.HandlerFunc.ServeHTTP(0xc082108a80, 0x1aa4348, 0xc0821121a0, 0xc08215c8c0)
[13:38:07.114][ProxyProcess   ][Info   ]    C:/go/src/net/http/server.go:1618 +0x41
[13:38:07.118][ProxyProcess   ][Info   ] github.com/docker/pinata/v1/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc082134000, 0x1aa4348, 0xc0821121a0, 0xc08215c8c0)
[13:38:07.120][ProxyProcess   ][Info   ]    c:/gopath/src/github.com/docker/pinata/v1/vendor/github.com/gorilla/mux/mux.go:107 +0x29e
[13:38:07.122][ProxyProcess   ][Info   ] net/http.serverHandler.ServeHTTP(0xc082142e80, 0x1aa4348, 0xc0821121a0, 0xc08215c8c0)
[13:38:07.125][ProxyProcess   ][Info   ]    C:/go/src/net/http/server.go:2081 +0x1a5
[13:38:07.128][ProxyProcess   ][Info   ] net/http.(*conn).serve(0xc082143500)
[13:38:07.130][ProxyProcess   ][Info   ]    C:/go/src/net/http/server.go:1472 +0xf35
[13:38:07.132][ProxyProcess   ][Info   ] created by net/http.(*Server).Serve
[13:38:07.135][ProxyProcess   ][Info   ]    C:/go/src/net/http/server.go:2137 +0x455
```

**Comment by thaJeztah** [comment]
One thing I noticed is that `docker run hello-world` starts a container using the `hello-world` image, but the container may have a different name, so `docker inspect hello-world` is inspecting the *image*, not the *container*.

The "panic" in the logs doesn't look good though. Let me ping someone from the Docker for Windows team, because development for that isn't done in this repository

ping @dgageot PTAL

**Comment by dgageot** [comment]
@thaJeztah @provegard this is fixed in Docker for Windows master. Will be released soon

**Comment by provegard** [comment]
@thaJeztah My use case is actually image inspection.

@dgageot great to hear, thanks! :-)

**Comment by thaJeztah** [comment]
@provegard ah, right! I was confused because you first did a `docker run ...`.

I'll close this issue, because it will be fixed in the next beta of Docker for Windows (which has its own repository)
