### ISSUE TITLE
Docker daemon crashed at start

### ISSUE THREAD

**Issue by panter-dsd** [docker/docker#23975]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
Daemon crashed at start.

**Describe the results you received:**
```
ERRO[0002] could not create netlink handle on initial namespace: protocol not supported
ERRO[0002] could not create netlink handle on initial namespace: protocol not supported
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0xef399e]

goroutine 1 [running]:
panic(0x1a27e80, 0xc82000e120)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/vishvananda/netlink.(*Handle).LinkByName(0x0, 0x1cfdc28, 0x7, 0x0, 0x0, 0x0, 0x0)
	/var/tmp/portage/portage/app-emulation/docker-1.12.0_rc2/work/docker-1.12.0_rc2/src/github.com/docker/docker/vendor/src/github.com/vishvananda/netlink/link_linux.go:759 +0x4e
github.com/docker/libnetwork/netutils.ElectInterfaceAddresses(0x1cfdc28, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/tmp/portage/portage/app-emulation/docker-1.12.0_rc2/work/docker-1.12.0_rc2/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/netutils/utils_linux.go:78 +0xde
github.com/docker/docker/daemon.initBridgeDriver(0x7f455df2ac48, 0xc82045ab40, 0xc8203c6700, 0x0, 0x0)
	/var/tmp/portage/portage/app-emulation/docker-1.12.0_rc2/work/docker-1.12.0_rc2/src/github.com/docker/docker/daemon/daemon_unix.go:712 +0x6c4
github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc8204721a0, 0xc8203c6700, 0xc8203bad80, 0x0, 0x0, 0x0, 0x0)
	/var/tmp/portage/portage/app-emulation/docker-1.12.0_rc2/work/docker-1.12.0_rc2/src/github.com/docker/docker/daemon/daemon_unix.go:661 +0x7b4
github.com/docker/docker/daemon.(*Daemon).restore(0xc8204721a0, 0x0, 0x0)
	/var/tmp/portage/portage/app-emulation/docker-1.12.0_rc2/work/docker-1.12.0_rc2/src/github.com/docker/docker/daemon/daemon.go:223 +0xa70
github.com/docker/docker/daemon.NewDaemon(0xc8203c6700, 0x7f455df4a3c0, 0xc820024610, 0x7f455e01c308, 0xc8203b71e0, 0x0, 0x0, 0x0)
	/var/tmp/portage/portage/app-emulation/docker-1.12.0_rc2/work/docker-1.12.0_rc2/src/github.com/docker/docker/daemon/daemon.go:596 +0x3337
main.(*DaemonCli).start(0xc8203bb0b0, 0x0, 0x0)
	/var/tmp/portage/portage/app-emulation/docker-1.12.0_rc2/work/docker-1.12.0_rc2/src/github.com/docker/docker/cmd/dockerd/daemon.go:269 +0x1a0e
main.main()
	/var/tmp/portage/portage/app-emulation/docker-1.12.0_rc2/work/docker-1.12.0_rc2/src/github.com/docker/docker/cmd/dockerd/docker.go:68 +0x491
```

**Comment by sanimej** [comment]
This is fixed in docker master by https://github.com/docker/docker/pull/23859 and will be available in 1.12-RC3. For now to avoid this panic make sure the kernel modules xrfm_user and xrmf_algo are loaded.

**Comment by panter-dsd** [comment]
I'm not found linux kernel modules named xrfm_user or xrmf_algo.

**Comment by sanimej** [comment]
Sorry, there were typos. module names are xfrm_user xfrm_algo.

It may not be available in some distros though. The PR I referred to earlier handles it gracefully and avoids the panic.

**Comment by panter-dsd** [comment]
Tank you. I'll wait for an update .
