### ISSUE TITLE
Networking: Panic on Manager(s) after scaling and getting `too many open files` errors

### ISSUE THREAD

**Issue by abronan** [docker/docker#24014]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   cccfe63
 Built:        Mon Jun 27 17:46:02 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   cccfe63
 Built:        Mon Jun 27 17:46:02 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 241
 Running: 5
 Paused: 0
 Stopped: 236
Images: 1
Server Version: 1.12.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: bnpa9guxfqznkkp6g9qmtbiim
 IsManager: No
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.6 MiB
Name: node05
ID: VPNA:RUIV:3HML:CTPL:2ZHA:7FXL:IPY7:JZTK:FJYX:KM77:MHZ2:W22H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Digital Ocean VMs:

3 Managers:
Specs: 2 GB Memory / 40 GB Disk / SFO1 - Ubuntu 16.04 x64

3 Agents:
Specs: 1 GB Memory / 30 GB Disk / SFO1 - Ubuntu 16.04 x64

**Steps to reproduce the issue:**
1. Create the cluster
2. Create a few services (in my case using redis)
3. Scale to a ridiculously huge amount of containers for such a tiny cluster (for this example: 3000)

**Describe the results you received:**

Getting `too many files open` errors on network and other operations, and then the Manager daemons are starting to crash in order. Agents are still running.

**Describe the results you expected:**

While creating that amount of containers should certainly lead to issues, the panic leaves the cluster in such a bad state that it can hardly be restarted, especially using multiple managers. I would expect the ability to scale down the number of containers without the daemon crashing to mitigate the issue and get back to a stable state for the cluster.

**Additional information you deem important (e.g. issue happens only occasionally):**

Excerpt of the stacktrace:

```
ERRO[16337] containerd: start container                   error=oci runtime error: process_linux.go:334: running prestart hook 0 caused "exit status 1: time=\"2016-06-27T18:24:35-04:00\" level=fatal msg=\"open /var/run/docker/netns/9c896b940b61: too many open files\" \n" id=2ddc47cc54bd3f3ee9b156768dd19b44d36a697fb8e3443d10bc3fb04c0fc957
ERRO[16337] Not continuing with pull after error: Error while pulling image: Get https://index.docker.io/v1/repositories/library/redis/images: dial tcp: lookup index.docker.io on 8.8.8.8:53: no such host 
ERRO[16337] pulling image failed                          error=Error while pulling image: Get https://index.docker.io/v1/repositories/library/redis/images: dial tcp: lookup index.docker.io on 8.8.8.8:53: no such host module=taskmanager task.id=4rtdvt923l2abp9qpjqc88zgw
ERRO[16337] fatal task error                              error=open /var/lib/docker/containers/3843381fd1a65078e1fcd374f340a761e79d70c5be4d2c0d51d0196efa1da163/resolv.conf: too many open files
github.com/docker/docker/daemon/cluster/executor/container.(*controller).Start
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/controller.go:141: starting container failed module=taskmanager task.id=c9tfqw1rdbyf6358zz7vah1sr
ERRO[16337] no state for container: "invalid container: 546c8aee796d001e2f41278bbfec3b68cc9d1e9f74fb27444dc1b245177b8d32" 
ERRO[16337] container status unavailable                  error=open /var/lib/docker/overlay/56537778fcb697e7d5f30e09e07c02f10e26fc791450e8d8d3640f2bc1a93319/lower-id: too many open files module=taskmanager task.id=c9tfqw1rdbyf6358zz7vah1sr
ERRO[16337] Error saving dying container to disk: open /var/lib/docker/containers/a93487cb2904501a21f7c682abf3c830c7b0a349f32f830399d7e878290c6d18/.tmp-config.v2.json267942762: too many open files 
ERRO[16337] fatal task error                              error=open /var/lib/docker/overlay/ee1a92e6d8e291d88f61fbb91eac6fc00fb6298fe474b5d5ae0251eb853ee0ee-init/lower-id: too many open files module=taskmanager task.id=4rtdvt923l2abp9qpjqc88zgw
WARN[16337] Failed to remove bridge endpoint 955331e from store: open /var/lib/docker/network/files/local-kv.db: too many open files 
WARN[16337] Could not rollback container connection to network bridge 
WARN[16337] Failed to parse cgroup information: Failed to parse cgroup information: open /proc/self/cgroup: too many open files 
WARN[16337] Error getting v2 registry: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 8.8.4.4:53: dial udp 8.8.4.4:53: socket: too many open files 
ERRO[16337] Attempting next endpoint for pull after error: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 8.8.4.4:53: dial udp 8.8.4.4:53: socket: too many open files 
ERRO[16337] Not continuing with pull after error: open /etc/docker/certs.d/docker.io: too many open files 
ERRO[16337] pulling image failed                          error=open /etc/docker/certs.d/docker.io: too many open files module=taskmanager task.id=bw9stxgorom9ftvf2rii1klx5
WARN[16337] Failed to parse cgroup information: Failed to parse cgroup information: open /proc/self/mountinfo: too many open files 
WARN[16337] IPv4 forwarding is disabled. Networking will not work 
ERRO[16337] fatal task error                              error=open /var/lib/docker/image/overlay/imagedb/content/sha256/4465e4bcad80b5b43cef0bace96a8ef0a55c0050be439c1fb0ecd64bc0b8cce4: too many open files module=taskmanager task.id=bw9stxgorom9ftvf2rii1klx5
ERRO[16337] Error saving dying container to disk: open /var/lib/docker/containers/c5dd3b290721c53f0bc25322283eb122512195d26ce6883e12535f9b86437f12/.tmp-config.v2.json860875838: too many open files 
ERRO[16337] fatal task error                              error=open /var/lib/docker/overlay/0199afc81f4a50560ba35dd40843915f73f3c56f6d8cc4e36764a7dd2a46f042-init/merged/.dockerenv: too many open files module=taskmanager task.id=3vwqh88hpcvrms128l9733ix2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x9c2316]

goroutine 47470 [running]:
panic(0x1acd500, 0xc82000a0d0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/libnetwork/drivers/bridge.(*driver).CreateEndpoint(0xc820158000, 0xc8202c8b40, 0x40, 0xc822f5e4c0, 0x40, 0x7fed5e3a1d20, 0xc8218b0e60, 0xc821f96e40, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go:1023 +0x22d6
github.com/docker/libnetwork.(*network).addEndpoint(0xc82148c640, 0xc8216c5600, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/network.go:806 +0x21b
github.com/docker/libnetwork.(*network).CreateEndpoint(0xc82148c640, 0xc820e706c1, 0x23, 0xc8220f2f40, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/network.go:876 +0xd31
github.com/docker/docker/daemon.(*Daemon).connectToNetwork(0xc8201636c0, 0xc8275ed860, 0x1da57e8, 0x6, 0xc821a16fc0, 0x4d5600, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_operations.go:572 +0x3b6
github.com/docker/docker/daemon.(*Daemon).allocateNetwork(0xc8201636c0, 0xc8275ed860, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_operations.go:417 +0x39b
github.com/docker/docker/daemon.(*Daemon).initializeNetworking(0xc8201636c0, 0xc8275ed860, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_operations.go:703 +0x42a
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc8201636c0, 0xc8275ed860, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/start.go:126 +0x1fe
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc8201636c0, 0xc821f96540, 0x23, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/start.go:80 +0x5dd
github.com/docker/docker/daemon/cluster/executor/container.(*containerAdapter).start(0xc82135dce0, 0x7fed625b8b78, 0xc826df9340, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/adapter.go:149 +0x82
github.com/docker/docker/daemon/cluster/executor/container.(*controller).Start(0xc820a0bd00, 0x7fed625b8b78, 0xc826df9340, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/controller.go:140 +0x1b6
github.com/docker/swarmkit/agent/exec.Do(0x7fed625b8b78, 0xc826df9340, 0xc827510d80, 0x7fed5e3f8120, 0xc820a0bd00, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/agent/exec/controller.go:253 +0x699
github.com/docker/swarmkit/agent.(*taskManager).run.func2(0x7fed625b8b08, 0xc821018900, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/agent/task.go:123 +0x2f0
github.com/docker/swarmkit/agent.runctx(0x7fed625b8b08, 0xc821018900, 0xc8246410e0, 0xc824641f80, 0xc826df9540)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/agent/helpers.go:9 +0x55
created by github.com/docker/swarmkit/agent.(*taskManager).run
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/agent/task.go:139 +0x7c0
```

/cc @mrjana @aluzzardi

**Comment by sanimej** [comment]
@abronan This panic should be addressed by https://github.com/docker/libnetwork/pull/1300. Its not in docker yet. Its a one liner. Can you try with this change and see if the handling is more graceful in this case ?

**Comment by abronan** [comment]
Thanks for the answer, going to test by vendoring the change and update.

**Comment by abronan** [comment]
I can confirm the panic is fixed vendoring the change, but I still obviously get to the cluster being unstable. I'll close as a duplicate of #23971 and re-open with more specific issues related to the scenario described above. Thanks @sanimej.
