### ISSUE TITLE
the log bug in swarm mode

### ISSUE THREAD

**Issue by zuhouhu** [docker/docker#24167]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-rc2
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 362.3 MB
 Data Space Total: 5.096 GB
 Data Space Available: 4.734 GB
 Metadata Space Used: 143.4 kB
 Metadata Space Total: 50.33 MB
 Metadata Space Available: 50.19 MB
 Thin Pool Minimum Free Space: 509.6 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: fluentd
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: active
 NodeID: 8h3ffel5nvqyuc0lrtu34xqm1
 IsManager: Yes
 Managers: 3
 Nodes: 3
 CACertHash: sha256:d720d776bd2f5acbf39ff3145363c51e4cb7a2ff3cc0fd1902aa481489b6223d
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993 MiB
Name: master
ID: FPJG:VDCD:K3R5:S3C3:T7WB:WHVY:47PL:XNPC:RONI:PYM7:MOGF:TPTQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

virtualbox

**Steps to reproduce the issue:**
1. stop docker daemon and add --log-driver syslog --log-opt syslog-address=tcp://10.0.2.15:514，then start daemon，no errors
2.'docker swarm join  manage ip'，and 'docker service create --name redis --replicas=3 redis'，then
   'docker service ls'  get result but very slow,so i run "ps aux|grep docker",and blank,the docker daemon  down
3.i remove  syslog-address=tcp://10.0.2.15:514 ，the container can start and run normal，so this wrong just happen when docker start with the --log-opt argument and use ‘docker swarm service’ create service
   when use ‘docker run’ a contaner ，the container can run normal。

**Describe the results you received:**
```
Jun 30 04:02:44 master NetworkManager[532]: <info>  (veth9998010): enslaved to docker_gwbridge
Jun 30 04:02:44 master avahi-daemon[531]: Withdrawing workstation service for veth21f385a.
Jun 30 04:02:44 master kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth9998010: link becomes ready
Jun 30 04:02:44 master NetworkManager[532]: <warn>  (veth21f385a): failed to disable userspace IPv6LL address handling
Jun 30 04:02:44 master NetworkManager[532]: <info>  (veth9998010): link connected
Jun 30 04:02:45 master avahi-daemon[531]: Registering new address record for fe80::c4c1:61ff:fefb:284f on veth9998010.*.
Jun 30 04:02:46 master dockerd: time="2016-06-30T04:02:46.172995176-04:00" level=info msg="raft.node: 3a6d1ce18104dc32 elected leader 1dc613a9b2f07d9e at term 3"
Jun 30 04:02:48 master dockerd: panic: assignment to entry in nil map
Jun 30 04:02:48 master dockerd: goroutine 173 [running]:
Jun 30 04:02:48 master dockerd: panic(0x169c160, 0xc820b7a910)
Jun 30 04:02:48 master dockerd: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Jun 30 04:02:48 master dockerd: github.com/docker/docker/daemon.(*Daemon).mergeAndVerifyLogConfig(0xc820313a00, 0xc8216f3528, 0x0, 0x0)
Jun 30 04:02:48 master dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/logs.go:149 +0x240
Jun 30 04:02:48 master dockerd: github.com/docker/docker/daemon.(*Daemon).create(0xc820313a00, 0xc820a2e4b0, 0x21, 0xc821284c80, 0xc8216f3500, 0xc820efb290, 0x0, 0x1, 0x0, 0x0, ...)
Jun 30 04:02:48 master dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/create.go:84 +0x1ef
Jun 30 04:02:48 master dockerd: github.com/docker/docker/daemon.(*Daemon).containerCreate(0xc820313a00, 0xc820a2e4b0, 0x21, 0xc821284c80, 0xc8216f3500, 0xc820efb290, 0xc820a2e500, 0xc820a2e501, 0x0, 0x0, ...)
Jun 30 04:02:48 master dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/create.go:55 +0x4b7
Jun 30 04:02:48 master dockerd: github.com/docker/docker/daemon.(*Daemon).CreateManagedContainer(0xc820313a00, 0xc820a2e4b0, 0x21, 0xc821284c80, 0xc8216f3500, 0xc820efb290, 0x7f3c2ab3e600, 0x0, 0x0, 0x0, ...)
Jun 30 04:02:48 master dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/create.go:24 +0xb6
Jun 30 04:02:48 master dockerd: github.com/docker/docker/daemon/cluster/executor/container.(*containerAdapter).create(0xc820acb2c0, 0x7f3c2ac108e8, 0xc820390c80, 0x7f3c2ab9cce8, 0xc820313a00, 0x0, 0x0)
Jun 30 04:02:48 master dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/cluster/executor/container/adapter.go:119 +0x179
Jun 30 04:02:48 master dockerd: github.com/docker/docker/daemon/cluster/executor/container.(*controller).Prepare(0xc820ab2f00, 0x7f3c2ac108e8, 0xc820390c80, 0x0, 0x0)
Jun 30 04:02:48 master dockerd: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/cluster/executor/container/controller.go:102 +0x33e
Jun 30 04:02:48 master dockerd: github.com/docker/swarmkit/agent/exec.Do(0x7f3c2ac108e8, 0xc820390c80, 0xc820921680, 0x7f3c2ab3e710, 0xc820ab2f00, 0x0, 0x0, 0x0)
Jun 30 04:02:48 master dockerd: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/swarmkit/agent/exec/controller.go:247 +0x546
Jun 30 04:02:48 master dockerd: github.com/docker/swarmkit/agent.(*taskManager).run.func2(0x7f3c2ac10878, 0xc82090d0e0, 0x0, 0x0)
Jun 30 04:02:48 master dockerd: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/swarmkit/agent/task.go:123 +0x2f0
Jun 30 04:02:48 master dockerd: github.com/docker/swarmkit/agent.runctx(0x7f3c2ac10878, 0xc82090d0e0, 0xc820b1e7e0, 0xc8209f18c0, 0xc820390d00)
Jun 30 04:02:48 master dockerd: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/swarmkit/agent/helpers.go:9 +0x55
Jun 30 04:02:48 master dockerd: created by github.com/docker/swarmkit/agent.(*taskManager).run
Jun 30 04:02:48 master dockerd: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/swarmkit/agent/task.go:139 +0x7c0
Jun 30 04:02:48 master systemd: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 30 04:02:48 master systemd: Unit docker.service entered failed state.
Jun 30 04:02:48 master systemd: docker.service failed.
```

**Describe the results you expected:**
i hope the docker container can run 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
#dibs

**Comment by zuhouhu** [comment]
when slove the bug？

**Comment by zuhouhu** [comment]
not just rsyslog，later i try add with --log-drive fluentd --log-opt tcp://localhost:22,same as above

**Comment by dnephin** [comment]
@cpuguy83 I had assigned myself, I had a fix for it here (https://github.com/dnephin/docker/commit/0b2f576eb7c18acdb8f393d4daeb8f943249d149#diff-b56258ecab11f7b797306907327cc904R264) but was still working on a unit test

**Comment by cpuguy83** [comment]
@dnephin 
```go
package daemon

import (
	"testing"

	containertypes "github.com/docker/engine-api/types/container"
)

func TestMergeAndVerifyLogConfig(t *testing.T) {
	d := &Daemon{defaultLogConfig: containertypes.LogConfig{Type: "json-file", Config: map[string]string{"max-file": "1"}}}
	cfg := containertypes.LogConfig{Type: d.defaultLogConfig.Type}
	if err := d.mergeAndVerifyLogConfig(&cfg); err != nil {
		t.Fatal(err)
	}
}
```

**Comment by dnephin** [comment]
Thanks. I had implemented this somewhere else, and was trying to write a test to cover all of `daemon.CreateContainer()`, but maybe that's a mistake.

Do you think it's better to fix this at the immediate site where it's read, or in a function that deals with setting other defaults?

**Comment by cpuguy83** [comment]
@dnephin I was creating a new map in `mergeAndVerifyLogConfig` and copying everything into it rather than modfying everything in place.

**Comment by dnephin** [comment]
Oh , that sounds good. I'll abandon my approach and take a look at your PR, since it sounds like it's ready.

**Comment by tiborvass** [comment]
@cpuguy83 @dnephin if there's a pr can we link it to issue?

**Comment by cpuguy83** [comment]
#24548
