### ISSUE TITLE
daemon crash when removing a node from swarm (v1.12-rc3)

### ISSUE THREAD

**Issue by alontorres** [docker/docker#24491]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:28:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:28:53 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 9
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: active
 NodeID: 0sg4bj6srnek9wffadbkz6yso
 IsManager: Yes
 Managers: 1
 Nodes: 2
 CACertHash: sha256:9e61945c68a01a5e077dfcf8e25359e71978a8c708c0789df33288d2a01a5179
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 3.13.0-91-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: swarm-manager-test-16891
ID: RWSQ:LBI5:RSVN:UUHJ:BQL4:YOYR:MY4C:KJMN:KD4U:4VCG:YFPJ:6XIC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on AWS EC2, and using AWS ECR.

**Steps to reproduce the issue:**
1. Create a swarm with multiple nodes
2. `docker service create --name sumologic --registry-auth --mode global --network mynet -m type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock,writable=false account_id.dkr.ecr.us-east-1.amazonaws.com/sumologic args`
3. terminate one of the worker nodes
4. docker node rm worker_node_name

**Describe the results you received:**
Docker daemon on all swarm nodes crashes, and then starts an infinite daemon restart loop. Any docker command gives the following output:
`An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/nodes: read unix @->/var/run/docker.sock: read: connection reset by peer`

docker log shows the following, repeating itself:
```
time="2016-07-10T14:05:24.111258141Z" level=info msg="16e6650232844435 is starting a new election at term 14"
time="2016-07-10T14:05:24.111613019Z" level=info msg="16e6650232844435 became candidate at term 15"
time="2016-07-10T14:05:24.111736443Z" level=info msg="16e6650232844435 received vote from 16e6650232844435 at term 15"
time="2016-07-10T14:05:24.111862195Z" level=info msg="16e6650232844435 became leader at term 15"
time="2016-07-10T14:05:24.111972278Z" level=info msg="raft.node: 16e6650232844435 elected leader 16e6650232844435 at term 15"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x58 pc=0x124d1d8]

goroutine 238 [running]:
panic(0x1a2b780, 0xc820010070)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/swarmkit/manager/scheduler.(*ReadyFilter).Check(0x2a3d8d0, 0xc821084d40, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/swarmkit/manager/scheduler/filter.go:32 +0x8
github.com/docker/swarmkit/manager/scheduler.(*Pipeline).Process(0xc821085440, 0xc821084d40, 0xc821723910)
	/usr/src/docker/vendor/src/github.com/docker/swarmkit/manager/scheduler/pipeline.go:40 +0xc7
github.com/docker/swarmkit/manager/scheduler.(*Scheduler).taskFitNode(0xc8217e5bc0, 0x7fad414c9858, 0xc8209bb9c0, 0xc820b15320, 0xc82100e540, 0x19, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/swarmkit/manager/scheduler/scheduler.go:373 +0x1af
github.com/docker/swarmkit/manager/scheduler.(*Scheduler).processPreassignedTasks(0xc8217e5bc0, 0x7fad414c9858, 0xc8209bb9c0)
	/usr/src/docker/vendor/src/github.com/docker/swarmkit/manager/scheduler/scheduler.go:264 +0x1a2
github.com/docker/swarmkit/manager/scheduler.(*Scheduler).Run(0xc8217e5bc0, 0x7fad414c9858, 0xc8209bb9c0, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/swarmkit/manager/scheduler/scheduler.go:107 +0x1ef
github.com/docker/swarmkit/manager.(*Manager).Run.func2.6(0x7fad414c9858, 0xc8209bb9c0, 0xc8217e5bc0)
	/usr/src/docker/vendor/src/github.com/docker/swarmkit/manager/manager.go:380 +0x4a
created by github.com/docker/swarmkit/manager.(*Manager).Run.func2
	/usr/src/docker/vendor/src/github.com/docker/swarmkit/manager/manager.go:383 +0x159f
/var/run/docker.sock is up
time="2016-07-10T14:05:24.230698835Z" level=info msg="New containerd process, pid: 20433"
time="2016-07-10T14:05:25.287328278Z" level=info msg="[graphdriver] using prior storage driver \"aufs\""
time="2016-07-10T14:05:25.295120948Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-07-10T14:05:25.295479412Z" level=warning msg="Your kernel does not support swap memory limit."
time="2016-07-10T14:05:25.295775075Z" level=warning msg="mountpoint for pids not found"
time="2016-07-10T14:05:25.296220775Z" level=info msg="Loading containers: start."
..........time="2016-07-10T14:05:25.325523225Z" level=info msg="Firewalld running: false"
time="2016-07-10T14:05:25.404196907Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"

time="2016-07-10T14:05:25.470850992Z" level=info msg="Loading containers: done."
time="2016-07-10T14:05:25.738011049Z" level=info msg="16e6650232844435 became follower at term 15"
time="2016-07-10T14:05:25.738376511Z" level=info msg="newRaft 16e6650232844435 [peers: [], term: 15, commit: 735, applied: 0, lastindex: 735, lastterm: 15]"
time="2016-07-10T14:05:25.738539616Z" level=info msg="16e6650232844435 became follower at term 15"
time="2016-07-10T14:05:25.738687260Z" level=info msg="newRaft 16e6650232844435 [peers: [], term: 15, commit: 735, applied: 0, lastindex: 735, lastterm: 15]"
time="2016-07-10T14:05:25.741120198Z" level=info msg="Listening for connections" addr="[::]:2377" proto=tcp
time="2016-07-10T14:05:25.741425568Z" level=info msg="Listening for local connections" addr="/var/lib/docker/swarm/control.sock" proto=unix
```

**Describe the results you expected:**
the terminated node should be removed from the swarm.

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue only happens when we try using the sumologic image, which needs access to docker.sock to function properly. Everything works fine until we try to remove the terminated node. This is 100% reproducible on our end.

**Comment by aaronlehmann** [comment]
Thanks for the report. This was fixed in https://github.com/docker/swarmkit/pull/1115 and the fix will be included in the next -rc release.
