### ISSUE TITLE
Several docker commands are hanging

### ISSUE THREAD

**Issue by nbars** [docker/docker#24608]
Hello,

I am using `debian 8.5` and `docker 1.11.2, build b9f10c9`.
I am unable to run several commands like images, info, ps.

Here is a strace snippet that was created while I executed `docker images`
(as you can see, the process is blocking on a futex call):

```
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 6
setsockopt(6, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
connect(6, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, 23) = 0
epoll_ctl(5, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=885611896, u64=140192913120632}}) = 0
getsockname(6, {sa_family=AF_LOCAL, NULL}, [2]) = 0
getpeername(6, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, [23]) = 0
futex(0xc820062110, FUTEX_WAKE, 1)      = 1
read(6, 0xc8203ea000, 4096)             = -1 EAGAIN (Resource temporarily unavailable)
futex(0x21eac90, FUTEX_WAIT, 0, NULL^CProcess 4012 detached
 <detached ...>
```

This is the debug output while running `docker images`:
```
docker daemon -D                                                                                                                              :(
DEBU[0000] docker group found. gid: 995                 
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] previous instance of containerd still alive (4632) 
DEBU[0000] containerd connection state change: CONNECTING 
DEBU[0000] containerd connection state change: READY    
DEBU[0000] Using default logging driver json-file       
DEBU[0000] Golang's threads limit set to 27000          
INFO[0000] [graphdriver] using prior storage driver "aufs" 
DEBU[0000] Using graph driver aufs                      
DEBU[0000] received past containerd event: &types.Event{Type:"live", Id:"", Status:0x0, Pid:"", Timestamp:0x5786cce9} 
```

Thanks in advance!

**Comment by mpalmer** [comment]
I'm hitting something similar on 1.11.1, and I've noticed that if I `strace` the `docker daemon` process (`strace -p <XXX> -f`) everything comes good a couple of seconds later (all my hung `docker ps` calls return).  I know it's not a *solution*, but it'd be an interesting data point if you were seeing the same behaviour from the daemon.

**Comment by mpalmer** [comment]
Also, I've found #13885 which seems to apply to my situation; does it match up with what you're seeing?

**Comment by nbars** [comment]
Running `strace -p <XXX> -f` doesn't help. I also can't replicate #13885 because I'am unable to start or stop any container.

Any idea how to further debug this problem?

**Comment by cpuguy83** [comment]
@nbars Unfortunately running strace on the docker client doesn't give us what we need.
If you could send `SIGUSR1` to the stuck daemon and then grab the stack trace from the daemon logs that would be extremely helpful, along with what commands may have been run that led up to the hang.

Thanks!

**Comment by nbars** [comment]
I solved the issue by running `rm -rf /var/lib/docker ` and purging and reinstalling docker.
The removing process took several minutes, so it looks like docker created a huge amount of files.

**Comment by cpuguy83** [comment]
@nbars Closing this issue then. If you run into the problem again please feel free to comment and please provide the output from the daemon.
Thanks!

**Comment by nbars** [comment]
Hello,

I just ran into the same problem again. So here is the stacktrace after
calling ```kill -SIGUSR1``` on the daemon process.

I am now on ```Docker version 1.12.0, build 8eab29e```.

```
DEBU[0000] docker group found. gid: 995                 
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] libcontainerd: new containerd process, pid: 11459 
DEBU[0000] libcontainerd: containerd connection state change: CONNECTING 
DEBU[0000] libcontainerd: containerd connection state change: TRANSIENT_FAILURE 
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=4 memory=3837 runtime=docker-runc runtimeArgs=[] stateDir=/var/run/docker/libcontainerd/containerd
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
DEBU[0001] Using default logging driver json-file       
DEBU[0001] Golang's threads limit set to 27000          
INFO[0001] [graphdriver] using prior storage driver "aufs" 
DEBU[0001] Using graph driver aufs                      
DEBU[0003] libcontainerd: containerd connection state change: READY 
INFO[0781] === BEGIN goroutine stack dump ===
goroutine 29 [running]:
github.com/docker/docker/pkg/signal.DumpStacks()
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:74 +0x98
github.com/docker/docker/daemon.setupDumpStackTrap.func1(0xc82035bec0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:18 +0x5e
created by github.com/docker/docker/daemon.setupDumpStackTrap
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:20 +0x13f

goroutine 1 [syscall]:
syscall.Syscall(0x0, 0x8, 0xc82195f180, 0x245, 0x0, 0x0, 0x4)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x8, 0xc82195f180, 0x245, 0x245, 0xc82195f400, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0x8, 0xc82195f180, 0x245, 0x245, 0xc82195f180, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:161 +0x4d
os.(*File).read(0xc821dc9b38, 0xc82195f180, 0x245, 0x245, 0x7, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:228 +0x53
os.(*File).Read(0xc821dc9b38, 0xc82195f180, 0x245, 0x245, 0x280, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x8a
bytes.(*Buffer).ReadFrom(0xc8221b8b90, 0x7f124815b270, 0xc821dc9b38, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:176 +0x23f
io/ioutil.readAll(0x7f124815b270, 0xc821dc9b38, 0x245, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:33 +0x156
io/ioutil.ReadFile(0xc821956e00, 0x72, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:70 +0x19f
github.com/docker/docker/layer.(*fileMetadataStore).GetInitID(0xc820460260, 0xc8230596ea, 0x40, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/layer/filestore.go:274 +0xab
github.com/docker/docker/layer.(*layerStore).loadMount(0xc82046a500, 0xc8230596ea, 0x40, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/layer/layer_store.go:170 +0x186
github.com/docker/docker/layer.NewStoreFromGraphDriver(0x7f12480993c0, 0xc820460260, 0x7f1248128da8, 0xc8204bc000, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/layer/layer_store.go:98 +0x508
github.com/docker/docker/layer.NewStoreFromOptions(0xc820419130, 0xf, 0xc8204156a0, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/layer/layer_store.go:67 +0x496
github.com/docker/docker/daemon.NewDaemon(0xc820412700, 0x7f1248128d20, 0xc8203321f0, 0x7f1248124a60, 0xc8203f9ad0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:493 +0x11da
main.(*DaemonCli).start(0xc8203f7e00, 0x0, 0x0)
	/usr/src/docker/cmd/dockerd/daemon.go:269 +0x1a0e
main.main()
	/usr/src/docker/cmd/dockerd/docker.go:68 +0x491

goroutine 17 [syscall, 13 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 34 [IO wait, 13 minutes]:
net.runtime_pollWait(0x7f124811ece8, 0x72, 0xc820476000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8204680d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204680d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820468070, 0xc820476000, 0x8000, 0x8000, 0x0, 0x7f1248157168, 0xc820010250)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820472000, 0xc820476000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc8204740c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8204740c0, 0xc820488038, 0x9, 0x9, 0x9, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f124815fa10, 0xc8204740c0, 0xc820488038, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f124815fa10, 0xc8204740c0, 0xc820488038, 0x9, 0x9, 0x1073642d784a1b01, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc820488038, 0x9, 0x9, 0x7f124815fa10, 0xc8204740c0, 0x48000000, 0xc800000000, 0x0, 0x0)
	/usr/src/docker/vendor/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc820488000, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/vendor/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc820486000, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/vendor/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc82048a000)
	/usr/src/docker/vendor/src/google.golang.org/grpc/transport/http2_client.go:788 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/usr/src/docker/vendor/src/google.golang.org/grpc/transport/http2_client.go:174 +0xd21

goroutine 6 [syscall]:
os/signal.signal_recv(0x7f1248157190)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 24 [syscall, 13 minutes]:
syscall.Syscall6(0x3d, 0x2cc3, 0xc820024ddc, 0x0, 0xc820434000, 0x0, 0x0, 0x4453d1, 0x4453d1, 0x467510)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.wait4(0x2cc3, 0xc820024ddc, 0x0, 0xc820434000, 0x90, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:172 +0x7f
syscall.Wait4(0x2cc3, 0xc820024e24, 0x0, 0xc820434000, 0x419053, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_linux.go:256 +0x55
os.(*Process).wait(0xc8204151e0, 0xc820052040, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:22 +0x105
os.(*Process).Wait(0xc8204151e0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:49 +0x2d
os/exec.(*Cmd).Wait(0xc820405540, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:396 +0x211
github.com/docker/docker/libcontainerd.(*remote).runContainerdDaemon.func1(0xc820405540, 0xc8203f9ad0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/remote_linux.go:418 +0x21
created by github.com/docker/docker/libcontainerd.(*remote).runContainerdDaemon
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/remote_linux.go:420 +0x12eb

goroutine 25 [select, 13 minutes]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc8204000f0)
	/usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:544 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc8204000f0)
	/usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:355 +0x1b5
created by google.golang.org/grpc.NewConn
	/usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:356 +0x4e3

goroutine 26 [semacquire, 12 minutes]:
sync.runtime_Syncsemacquire(0xc820429bd0)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc820429bc0)
	/usr/local/go/src/sync/cond.go:63 +0x9b
google.golang.org/grpc.(*Conn).WaitForStateChange(0xc8204000f0, 0x7f124815b940, 0xc8200108e0, 0x2, 0x0, 0x0, 0x0)
	/usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:405 +0x19f
google.golang.org/grpc.(*unicastPicker).WaitForStateChange(0xc8204152a0, 0x7f124815b940, 0xc8200108e0, 0x2, 0x1ff71a0, 0x0, 0x0)
	/usr/src/docker/vendor/src/google.golang.org/grpc/picker.go:96 +0x4f
google.golang.org/grpc.(*ClientConn).WaitForStateChange(0xc8203bf6b0, 0x7f124815b940, 0xc8200108e0, 0x2, 0x1, 0x0, 0x0)
	/usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:283 +0x6b
github.com/docker/docker/libcontainerd.(*remote).handleConnectionChange(0xc8203f9ad0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/remote_linux.go:139 +0xb4
created by github.com/docker/docker/libcontainerd.New
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/remote_linux.go:117 +0xb42

goroutine 35 [select, 13 minutes]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc82048a000)
	/usr/src/docker/vendor/src/google.golang.org/grpc/transport/http2_client.go:866 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/usr/src/docker/vendor/src/google.golang.org/grpc/transport/http2_client.go:201 +0x15c2

goroutine 28 [chan receive, 13 minutes]:
github.com/docker/docker/pkg/signal.Trap.func1(0xc820474360, 0xc82045e2a0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:32 +0x71
created by github.com/docker/docker/pkg/signal.Trap
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:62 +0x2be

goroutine 37 [select, 13 minutes]:
google.golang.org/grpc.NewClientStream.func1(0x7f1248097078, 0xc82048a000, 0xc820498000, 0xc8204660a0)
	/usr/src/docker/vendor/src/google.golang.org/grpc/stream.go:151 +0x258
created by google.golang.org/grpc.NewClientStream
	/usr/src/docker/vendor/src/google.golang.org/grpc/stream.go:159 +0xab2

goroutine 38 [select, 13 minutes]:
google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc820486150, 0xc82045e1f0, 0x5, 0x5, 0x0, 0x0, 0x0)
	/usr/src/docker/vendor/src/google.golang.org/grpc/transport/transport.go:141 +0x7e6
google.golang.org/grpc/transport.(*Stream).Read(0xc820498000, 0xc82045e1f0, 0x5, 0x5, 0x0, 0x0, 0x0)
	/usr/src/docker/vendor/src/google.golang.org/grpc/transport/transport.go:294 +0x71
io.ReadAtLeast(0x7f1248097218, 0xc820498000, 0xc82045e1f0, 0x5, 0x5, 0x5, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f1248097218, 0xc820498000, 0xc82045e1f0, 0x5, 0x5, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
google.golang.org/grpc.(*parser).recvMsg(0xc82045e1e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/vendor/src/google.golang.org/grpc/rpc_util.go:216 +0xb9
google.golang.org/grpc.recv(0xc82045e1e0, 0x7f1248124ac0, 0x2a77640, 0xc820498000, 0x0, 0x0, 0x1b68b60, 0xc8203187c0, 0x0, 0x0)
	/usr/src/docker/vendor/src/google.golang.org/grpc/rpc_util.go:300 +0x45
google.golang.org/grpc.(*clientStream).RecvMsg(0xc8204660a0, 0x1b68b60, 0xc8203187c0, 0x0, 0x0)
	/usr/src/docker/vendor/src/google.golang.org/grpc/stream.go:234 +0xac
github.com/docker/containerd/api/grpc/types.(*aPIEventsClient).Recv(0xc820460120, 0x0, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/containerd/api/grpc/types/api.pb.go:1032 +0x7e
github.com/docker/docker/libcontainerd.(*remote).handleEventStream(0xc8203f9ad0, 0x7f1248097368, 0xc820460120)
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/remote_linux.go:286 +0x64
created by github.com/docker/docker/libcontainerd.(*remote).startEventsMonitor
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/remote_linux.go:280 +0x2db

goroutine 39 [select, 13 minutes, locked to thread]:
runtime.gopark(0x214b9f0, 0xc820494728, 0x1d367c8, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820494728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820494728)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 9 [select, 12 minutes]:
google.golang.org/grpc.(*Conn).WaitForStateChange.func1(0x7f124815b940, 0xc8200108e0, 0xc8204000f0, 0xc8200105f0, 0xc823c62000)
	/usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:394 +0x1b1
created by google.golang.org/grpc.(*Conn).WaitForStateChange
	/usr/src/docker/vendor/src/google.golang.org/grpc/clientconn.go:402 +0x14e

=== END goroutine stack dump === 

```

**Comment by thaJeztah** [comment]
let me reopen the issue

ping @cpuguy83 ptal ^^

**Comment by cpuguy83** [comment]
@nbars It looks like you are stuck on daemon startup... specifically while docker is trying to read a file from disk for the layer store (nothing fancy, just a simple file). Seems like there is something very wrong on your node.

**Comment by nbars** [comment]
I just checked the content of ```/var/lib/docker/containers```.
There are 146182 files in the folder (no recursive listing), that a way to much, right?

**Comment by nbars** [comment]
Well, it looks like the docker jenkins plugin isn't working correctly. Thanks for you're help!

**Comment by cpuguy83** [comment]
@nbars Yep, that's a *lot*. That means there are 146,182 containers (or something is putting random stuff in there that shouldn't be).
