### ISSUE TITLE
docker start with invalid graphdriver cause daemon panic

### ISSUE THREAD

**Issue by coolljt0725** [docker/docker#24674]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   87f15fa
 Built:        Fri Jul 15 08:12:59 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. `dockerd -s over -D --live-restore`
2.
3.

**Describe the results you received:**

````
WARN[0004] Unable to locate plugin: over, retrying in 4s
WARN[0008] Unable to locate plugin: over, retrying in 8s
ERRO[0016] Failed to GetDriver graph over /var/lib/docker
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x9bc5f7]

goroutine 1 [running]:
panic(0x1b217c0, 0xc82000e160)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/docker/pkg/registrar.(*Registrar).GetAll(0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/registrar/registrar.go:120 +0x1e7
github.com/docker/docker/daemon.(*Daemon).foldFilter(0xc8203669c0, 0xc820312bc0, 0xc81ffe62a9, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/list.go:283 +0x51c
github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc8203669c0, 0xc820312bc0, 0xc8204fb040, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/list.go:159 +0xa8
github.com/docker/docker/daemon.(*Daemon).Containers(0xc8203669c0, 0xc820312bc0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/list.go:91 +0x76
github.com/docker/docker/daemon.(*Daemon).Shutdown(0xc8203669c0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/daemon.go:656 +0xb6
github.com/docker/docker/daemon.NewDaemon.func1(0xc8204fb958, 0xc8203669c0)
        /go/src/github.com/docker/docker/daemon/daemon.go:461 +0x37
github.com/docker/docker/daemon.NewDaemon(0xc820437180, 0x7eff64975180, 0xc820032560, 0x7eff669bf1d0, 0xc820440ea0, 0x0, 0x7eff669b5028, 0xc82033aac0)
        /go/src/github.com/docker/docker/daemon/daemon.go:497 +0x125f
main.(*DaemonCli).start(0xc82043ce70, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:269 +0x1a06
main.main()
        /go/src/github.com/docker/docker/cmd/dockerd/docker.go:68 +0x49
````
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by runcom** [comment]
luckily 1.12-rc4 isn't affected by this

**Comment by coolljt0725** [comment]
@runcom  1.12-rc4 is also affected by this.
````
DEBU[0001] [graphdriver] trying provided driver "over"
ERRO[0001] Failed to GetDriver graph over /var/lib/docker
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x9ab9b7]

goroutine 1 [running]:
panic(0x1af0ac0, 0xc82000e170)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/docker/pkg/registrar.(*Registrar).GetAll(0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/registrar/registrar.go:120 +0x1e7
github.com/docker/docker/daemon.(*Daemon).foldFilter(0xc820422340, 0xc820012300, 0xc81ffd7df5, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/list.go:283 +0x51c
github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc820422340, 0xc820012300, 0xc82054afe0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/list.go:159 +0xa8
github.com/docker/docker/daemon.(*Daemon).Containers(0xc820422340, 0xc820012300, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/list.go:91 +0x76
github.com/docker/docker/daemon.(*Daemon).Shutdown(0xc820422340, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/daemon.go:654 +0xb6

[root@fedora ~]# docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:39:43 2016
 OS/Arch:      linux/amd64

````
