### ISSUE TITLE
libnetwork: panic in restore code

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#25109]
```
Jul 26 19:25:57 deathstar systemd[1]: Starting docker...
Jul 26 19:25:57 deathstar systemd[1]: Started docker.
Jul 26 19:25:57 deathstar docker[24013]: time="2016-07-26T19:25:57.089163560-07:00" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DO
Jul 26 19:25:57 deathstar docker[24013]: time="2016-07-26T19:25:57.089871702-07:00" level=info msg="libcontainerd: new containerd process, pid: 24027"
Jul 26 19:25:57 deathstar docker[24013]: time="2016-07-26T19:25:57.098125588-07:00" level=warning msg="containerd: low RLIMIT_NOFILE changing to max" current=1024 max=4096
Jul 26 19:25:58 deathstar docker[24013]: time="2016-07-26T19:25:58.288050675-07:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul 26 19:25:58 deathstar docker[24013]: time="2016-07-26T19:25:58.288728923-07:00" level=info msg="Loading containers: start."
Jul 26 19:25:58 deathstar docker[24013]: .time="2016-07-26T19:25:58.288810308-07:00" level=error msg="Failed to load container 689687a7cf7a900bbd7652ccb515264ba2c123b713e4b
Jul 26 19:25:58 deathstar docker[24013]: .time="2016-07-26T19:25:58.289900841-07:00" level=warning msg="libcontainerd: restore was called on a fully synced container (6a889
Jul 26 19:25:58 deathstar docker[24013]: time="2016-07-26T19:25:58.294715331-07:00" level=info msg="Firewalld running: false"
Jul 26 19:25:58 deathstar docker[24013]: time="2016-07-26T19:25:58.343434041-07:00" level=error msg="getEndpointFromStore for eid 1c0c0f29aa21249d36655fec12eabd97e5ab713075
Jul 26 19:25:58 deathstar docker[24013]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 26 19:25:58 deathstar docker[24013]: [signal 0xb code=0x1 addr=0x18 pc=0x8b5c9f]
Jul 26 19:25:58 deathstar docker[24013]: goroutine 1 [running]:
Jul 26 19:25:58 deathstar docker[24013]: panic(0x1b1b820, 0xc82000e070)
Jul 26 19:25:58 deathstar docker[24013]:         /usr/local/go/src/runtime/panic.go:481 +0x3e6
Jul 26 19:25:58 deathstar docker[24013]: github.com/docker/libnetwork.(*sandbox).restoreOslSandbox(0xc820257860, 0x0, 0x0)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/sandbox.go:729 +0x1cf
Jul 26 19:25:58 deathstar docker[24013]: github.com/docker/libnetwork.(*controller).sandboxCleanup(0xc82020e000, 0xc8201cb050)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/sandbox_store.go:261 +0x1645
Jul 26 19:25:58 deathstar docker[24013]: github.com/docker/libnetwork.New(0xc82037cd00, 0x7, 0x8, 0x0, 0x0, 0x0, 0x0)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/controller.go:219 +0xa26
Jul 26 19:25:58 deathstar docker[24013]: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc820426820, 0xc820162380, 0xc8201cb050, 0x0, 0x0, 0x0, 0x0)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/daemon/daemon_unix.go:638 +0xf5
Jul 26 19:25:58 deathstar docker[24013]: github.com/docker/docker/daemon.(*Daemon).restore(0xc820426820, 0x0, 0x0)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/daemon/daemon.go:225 +0xa8f
Jul 26 19:25:58 deathstar docker[24013]: github.com/docker/docker/daemon.NewDaemon(0xc820162380, 0x7fdae2cdf730, 0xc820402098, 0x7fdae2cdf178, 0xc82037ac30, 0x0, 0x0, 0x0)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/daemon/daemon.go:603 +0x329c
Jul 26 19:25:58 deathstar docker[24013]: main.(*DaemonCli).start(0xc82045d680, 0x0, 0x0)
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:270 +0x1a0e
Jul 26 19:25:58 deathstar docker[24013]: main.main()
Jul 26 19:25:58 deathstar docker[24013]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:68 +0x491
Jul 26 19:25:58 deathstar systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 26 19:25:58 deathstar systemd[1]: docker.service: Unit entered failed state.
```

**Comment by mavenugo** [comment]
@crosbymichael the error `Jul 26 19:25:58 deathstar docker[24013]: time="2016-07-26T19:25:58.343434041-07:00" level=error msg="getEndpointFromStore for eid 1c0c0f29aa21249d36655fec12eabd97e5ab713075` is truncated :( ... but it indicates that endpoint is not stored in the store.

We can certainly add protection code in sandbox restore to avoid including the endpoint restore if it is not seen in the store. But, am  curious now to understand how this can happen. Are we trying to restore containers created by swarm ? It will fail because endpoints and networks are not persisted in the store.

**Comment by crosbymichael** [comment]
@mavenugo no not swarm containers, just regular ones.

**Comment by mavenugo** [comment]
thanks @crosbymichael. it is not clear exactly what could cause this. But adding a defensive check to prevent panics : https://github.com/docker/docker/pull/25131

**Comment by crosbymichael** [comment]
I had a left over sandbox not attached to anything

```
root@deathstar:/run/docker# cd ..
root@deathstar:/run# rm -r docker
rm: cannot remove 'docker/netns/ed7244e5a58b': Device or resource busy
rm: cannot remove 'docker/netns/default': Device or resource busy
root@deathstar:/run# umount docker/netns/ed7244e5a58b
root@deathstar:/run# umount docker/netns/default
root@deathstar:/run# rm -r docker                                                                                                                                           
root@deathstar:/run# exit
exit
```

after doing that it starts fine

**Comment by mavenugo** [comment]
@crosbymichael aha. that answers. it is a stale sandbox causing this mayhem. my fix above should help.

**Comment by mavenugo** [comment]
@crosbymichael i take that (comment on stale sandbox) back. the panic happens only in the restore code-path. Restore codepath is taken only if the daemon explicitly requests for restoring a sandbox. That essentially means the container was running in its previous life. Maybe it was in the process of going down and the daemon restart happened. Never-the-less, I don't think it is right to call this a stale sandbox. wdyt ?

**Comment by crosbymichael** [comment]
@mavenugo true. your fix solved the panic.  i'm looking into why its reporting a running container when its not after a crash
