### ISSUE TITLE
s390x: CI broken by "bump go-patricia to 2.2.4"?

### ISSUE THREAD

**Issue by michael-holzheu** [docker/docker#25360]
Looks like PR #25283 (commit  3d714b5ed58cfdfd5872ddd3654d171b09bb02d3) introduced a problem for s390x. See Jenkins run: https://jenkins.dockerproject.org/job/Docker%20Master%20(z)/132

```
FAIL: docker_cli_build_test.go:4318: TestBuildEntrypointInheritance.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_build_test.go:507: TestBuildOnBuildCmdEntrypointJSON.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_api_containers_test.go:1225: TestContainerApiGetContainersJSONEmpty.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_api_containers_test.go:88: TestContainerApiPsOmitFields.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_health_test.go:53: TestHealth.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_import_test.go:16: TestImportDisplay.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_import_test.go:45: TestImportFile.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_import_test.go:92: TestImportFileWithMessage.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_import_test.go:67: TestImportGzipped.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_info_test.go:125: TestInfoDisplaysPausedContainers.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_info_test.go:114: TestInfoDisplaysRunningContainers.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_info_test.go:140: TestInfoDisplaysStoppedContainers.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_links_test.go:32: TestLinksPingLinkedContainers.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_port_test.go:275: TestPortExposeHostBinding.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_port_test.go:253: TestPortHostBinding.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_port_test.go:14: TestPortList.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_ps_test.go:19: TestPsListContainersBase.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_ps_test.go:263: TestPsListContainersFilterAncestorImage.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_ps_test.go:403: TestPsListContainersFilterExited.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_rm_test.go:52: TestRmContainerOrphaning.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_run_test.go:4352: TestRunAttachFailedNoLeak.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_run_test.go:2988: TestRunContainerWithRmFlagCannotStartContainer.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_run_test.go:2971: TestRunContainerWithRmFlagExitCodeNotEqualToZero.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_run_test.go:4319: TestRunNamedVolumeNotRemoved.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_run_test.go:4336: TestRunNamedVolumesFromNotRemoved.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_run_test.go:2958: TestRunVolumesFromRestartAfterRemoved.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_port_test.go:180: TestUnpublishedPortsInPsOutput.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_update_unix_test.go:132: TestUpdateKernelMemoryUninitialized.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_volume_test.go:240: TestVolumeCliCreateWithOpts.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_volume_test.go:66: TestVolumeCliLs.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_volume_test.go:98: TestVolumeCliLsFilterDangling.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_volume_test.go:173: TestVolumeCliRm.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_api_volumes_test.go:66: TestVolumesApiInspect.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_api_volumes_test.go:13: TestVolumesApiList.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_api_volumes_test.go:42: TestVolumesApiRemove.pN52_github_com_docker_docker_integration_cli.DockerSuite
FAIL: docker_cli_daemon_test.go:797: TestDaemonBridgeFixedCidr2.pN58_github_com_docker_docker_integration_cli.DockerDaemonSuite
FAIL: docker_cli_daemon_test.go:2048: TestDaemonRestartWithNames.pN58_github_com_docker_docker_integration_cli.DockerDaemonSuite
FAIL: docker_cli_daemon_test.go:81: TestDaemonRestartWithVolumesRefs.pN58_github_com_docker_docker_integration_cli.DockerDaemonSuite
FAIL: docker_cli_daemon_test.go:2257: TestRunLinksChanged.pN58_github_com_docker_docker_integration_cli.DockerDaemonSuite
FAIL: docker_api_swarm_test.go:601: TestApiSwarmLeaveRemovesContainer.pN57_github_com_docker_docker_integration_cli.DockerSwarmSuite
FAIL: docker_api_swarm_test.go:907: TestApiSwarmRestartCluster.pN57_github_com_docker_docker_integration_cli.DockerSwarmSuite
FAIL: docker_api_swarm_test.go:207: TestApiSwarmServicesCreate.pN57_github_com_docker_docker_integration_cli.DockerSwarmSuite
FAIL: docker_cli_external_volume_driver_unix_test.go:411: TestExternalVolumeDriverBindExternalVolume.pN66_github_com_docker_docker_integration_cli.DockerExternalVolumeSuite
FAIL: docker_cli_external_volume_driver_unix_test.go:440: TestExternalVolumeDriverGet.pN66_github_com_docker_docker_integration_cli.DockerExternalVolumeSuite
FAIL: docker_cli_external_volume_driver_unix_test.go:426: TestExternalVolumeDriverList.pN66_github_com_docker_docker_integration_cli.DockerExternalVolumeSuite
FAIL: docker_cli_external_volume_driver_unix_test.go:294: TestExternalVolumeDriverVolumesFrom.pN66_github_com_docker_docker_integration_cli.DockerExternalVolumeSuite
```

Investigating...

**Comment by michael-holzheu** [comment]
Looks like 3d714b5ed58cfdfd5872ddd3654d171b09bb02d3 is indeed the reason for the failures on s390x. I did the following experiment (twice):

1) Checkout commit 3d714b5ed58cfdfd5872ddd3654d171b09bb02d3 and run test:
```
root@04afededd74a:/go/src/github.com/docker/docker# git checkout 3d714b5ed58cfdfd5872ddd3654d171b09bb02d3
root@04afededd74a:/go/src/github.com/docker/docker# TESTFLAGS='-check.f DockerSuite.TestImportFile' DOCKER_GRAPHDRIVER=vfs DOCKER_EXECDRIVER=native TIMEOUT="120m" hack/make.sh gccgo test-integration-cli
FAIL: docker_cli_import_test.go:45: TestImportFile.pN52_github_com_docker_docker_integration_cli.DockerSuite

docker_cli_import_test.go:64:
    c.Assert(out, checker.Equals, "", check.Commentf("command output should've been nothing."))
... obtained string = "An error occurred trying to connect: EOF\n"
... expected string = ""
... command output should've been nothing.


----------------------------------------------------------------------
PASS: docker_cli_import_test.go:124: TestImportFileNonExistentFile.pN52_github_com_docker_docker_integration_cli.DockerSuite    0.098s

----------------------------------------------------------------------
FAIL: docker_cli_import_test.go:92: TestImportFileWithMessage.pN52_github_com_docker_docker_integration_cli.DockerSuite

docker_cli_import_test.go:121:
    c.Assert(out, checker.Equals, "", check.Commentf("command output should've been nothing"))
... obtained string = "An error occurred trying to connect: EOF\n"
... expected string = ""
... command output should've been nothing

OOPS: 1 passed, 2 FAILED
```

2) Revert commit and re-run Test:
```
root@04afededd74a:/go/src/github.com/docker/docker#  # git show | patch -p1 -R
patching file hack/vendor.sh
patching file vendor/src/github.com/tchap/go-patricia/patricia/children.go
patching file vendor/src/github.com/tchap/go-patricia/patricia/patricia.go

root@04afededd74a:/go/src/github.com/docker/docker# TESTFLAGS='-check.f DockerSuite.TestImportFile' DOCKER_GRAPHDRIVER=vfs DOCKER_EXECDRIVER=native TIMEOUT="120m" hack/make.sh gccgo test-integration-cli
PASS: docker_cli_import_test.go:45: TestImportFile.pN52_github_com_docker_docker_integration_cli.DockerSuite    5.860s
PASS: docker_cli_import_test.go:124: TestImportFileNonExistentFile.pN52_github_com_docker_docker_integration_cli.DockerSuite    0.099s
PASS: docker_cli_import_test.go:92: TestImportFileWithMessage.pN52_github_com_docker_docker_integration_cli.DockerSuite 4.065s
OK: 3 passed
```

The commit does not look not architecture specific. So perhaps a gccgo issue?

**Comment by justincormack** [comment]
We currently don't have tests enabled on gccgo so could have missed this.
Can you test on amd64 gccgo?

BTW is s390x moving to normal Go in 1.7?

**Comment by michael-holzheu** [comment]
> Can you test on amd64 gccgo?

I tried the following on my laptop (Ubuntu 14.04):

```
# docker build --rm --force-rm -t docker:build -f Dockerfile.gccgo .
# docker run --rm -ti --privileged docker:build bash
# TESTFLAGS='-check.f DockerSuite.TestImportFile' DOCKER_GRAPHDRIVER=vfs DOCKER_EXECDRIVER=native TIMEOUT="120m" hack/make.sh gccgo test-integration-cli
```

Looks like it hangs in .ensure-httpserver in the step "docker build -t httpserver":

```
++++ tar -cC bundles/1.13.0-dev/test-integration-cli/frozen-images .
++++ docker load
++++ set +x
Untagged: hello-world:latest
---> Making bundle: .ensure-httpserver (in bundles/1.13.0-dev/test-integration-cli)
```

**Comment by michael-holzheu** [comment]
> BTW is s390x moving to normal Go in 1.7?

Our current plan is to use golang 1.7 for Dockerfile.s390x when it is released in the next weeks.
Would you agree?

**Comment by michael-holzheu** [comment]
BTW with go1.7rc5 the tests work fine also on s390x:

```
# go version
go version go1.7rc5 linux/s390x
# git checkout 3d714b5ed58cfdfd5872ddd3654d171b09bb02d3
# TESTFLAGS='-check.f DockerSuite.TestImportFile' DOCKER_GRAPHDRIVER=vfs DOCKER_EXECDRIVER=native TIMEOUT="120m" hack/make.sh dynbinary test-integration-cli
INFO: Testing against a local daemon
PASS: docker_cli_import_test.go:45: DockerSuite.TestImportFile  1.713s
PASS: docker_cli_import_test.go:124: DockerSuite.TestImportFileNonExistentFile  0.009s
PASS: docker_cli_import_test.go:92: DockerSuite.TestImportFileWithMessage       1.487s
OK: 3 passed
```

**Comment by michael-holzheu** [comment]
@unclejack : I now tried the "go-patricia" testsuite on my laptop (amd64) with gccgo 6.1. It works with version v2.1.0 and fails with version v2.2.4. So it seems to be an architecture independent gccgo related problem.

Here the steps to reproduce:

1) Start gcc:6.1 image and get go-patricia code
```
$ docker run -ti --rm gcc:6.1 bash
root@a0f013b0c10a:~# mkdir -p /root/go/src
root@a0f013b0c10a:~# cd /root/go/src
root@a0f013b0c10a:~/go/src# export GOPATH=/root/go
root@a0f013b0c10a:~/go/src# go get github.com/satori/go.uuid
root@a0f013b0c10a:~/go/src# git clone https://github.com/tchap/go-patricia.git github.com/tchap/go-patricia
```

2) Try with version 2.1.0 (works):
```
root@a0f013b0c10a:~/go/src# cd github.com/tchap/go-patricia/patricia && git checkout v2.1.0 && cd -
Previous HEAD position was 0d76659... Fix Delete memory leak and other bugs found
HEAD is now at d87fea6... Merge pull request #14 from ishidawataru/fix_walk
root@a0f013b0c10a:~/go/src# go test github.com/tchap/go-patricia/patricia
ok      github.com/tchap/go-patricia/patricia   4.646s
```

2) Try with version 2.2.4 (fails):
```
root@a0f013b0c10a:~/go/src# cd github.com/tchap/go-patricia/patricia && git checkout v2.2.4 && cd -
HEAD is now at 0d76659... Fix Delete memory leak and other bugs found
root@a0f013b0c10a:~# go test github.com/tchap/go-patricia/patricia

--- FAIL: TestTrie_DeleteLeakageDense (0.00s)
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range


        :0

        :0

github_com_tchap_go_patricia_patricia.remove.pN53_github_com_tchap_go_patricia_patricia.sparseChildList
        /root/go/src/github.com/tchap/go-patricia/patricia/children.go:73
github_com_tchap_go_patricia_patricia.Delete.pN42_github_com_tchap_go_patricia_patricia.Trie
        /root/go/src/github.com/tchap/go-patricia/patricia/patricia.go:302
github_com_tchap_go_patricia_patricia.TestTrie_DeleteLeakageDense
        /root/go/src/github.com/tchap/go-patricia/patricia/patricia_dense_test.go:196

        :0

goroutine 16 [chan receive]:

        :0


created by main
        /usr/src/gcc/libgo/runtime/go-main.c:54

        :0

        :0

goroutine 17 [syscall]:
        goroutine in C code; stack unavailable

goroutine 18 [finalizer wait]:

goroutine 19 [GC sweep wait]:
        :0

        :0
FAIL    github.com/tchap/go-patricia/patricia   0.044s
```

**Comment by justincormack** [comment]
Yes, I was just thinking no one will care about gccgo after this...

**Comment by michael-holzheu** [comment]
> So it seems to be an architecture independent gccgo related problem.

Or it is a off-by-one problem with patricia that is discovered by gccgo ;-)

**Comment by michael-holzheu** [comment]
I opended issue tchap/go-patricia#26 to clarify the root cause of the problem

**Comment by unclejack** [comment]
@michael-holzheu This issue seems to have nothing to do with Go itself or with the go-patricia code. If it works with Go and it breaks with gccgo, that means it's quite likely gccgo itself is broken in some way.

It might be a really bad idea to go after every individual package to fix it to make it work with gccgo (except for the architecture specific fixes, constants and quirks). This seems to imply that valid code needs to be modified in order to work around a certain compiler's bugs. A better course of action would be to address the underlying causes of those gccgo problems.

When Go 1.7 drops, the s390 Dockerfile should use Go 1.7. gccgo support shouldn't be removed from the Docker repository because that would allow us to help make gccgo better in the future.

**Comment by michael-holzheu** [comment]
> it works with Go and it breaks with gccgo, that means it's quite likely gccgo itself is broken in some way.

@unclejack it's likely, but it can also be that gccgo detected a bug that golang did not. I just wanted to make sure that this is not the case before I open a gccgo bug.

> It might be a really bad idea to go after every individual package to fix it to make it work with gccgo 

That never was my intention.

**Comment by justincormack** [comment]
Ok, this has been fixed upstream in patricia 2.2.5.

**Comment by justincormack** [comment]
Should be fixed by https://github.com/docker/docker/pull/25510

**Comment by michael-holzheu** [comment]
> Should be fixed by #25510

At least this one looks good now, thanks:
```
# git checkout 34877a41a8a6660a31ff3770566cc1341759b16c
# TESTFLAGS='-check.f DockerSuite.TestImportFile' DOCKER_GRAPHDRIVER=vfs DOCKER_EXECDRIVER=native TIMEOUT="120m" hack/make.sh gccgo test-integration-cli

PASS: docker_cli_import_test.go:45: TestImportFile.pN52_github_com_docker_docker_integration_cli.DockerSuite    4.781s
PASS: docker_cli_import_test.go:124: TestImportFileNonExistentFile.pN52_github_com_docker_docker_integration_cli.DockerSuite    0.128s
PASS: docker_cli_import_test.go:92: TestImportFileWithMessage.pN52_github_com_docker_docker_integration_cli.DockerSuite 4.218s
OK: 3 passed
```

But with https://jenkins.dockerproject.org/job/Docker%20Master%20(z)/197 we have another problem.

Investigating...

**Comment by michael-holzheu** [comment]
> But with https://jenkins.dockerproject.org/job/Docker%20Master%20(z)/197 we have another problem.
>
> Investigating...

I opened issue #25533 for the new problem

**Comment by michael-holzheu** [comment]
@unclejack : FYI: Perhaps we should consider updating to go-patricia version v2.2.6, because of commit tchap/go-patricia@666120de432aea38ab06bd5c818f04f4129882c9? See also comment https://github.com/tchap/go-patricia/issues/26#issuecomment-239687539.

**Comment by justincormack** [comment]
@michael-holzheu see https://github.com/docker/docker/pull/25809

**Comment by michael-holzheu** [comment]
>  @michael-holzheu see #25809

Thanks!
