### ISSUE TITLE
Non-SOCKS ALL_PROXY results in proxy: unknown scheme: http

### ISSUE THREAD

**Issue by bbodenmiller** [docker/docker#25740]
If the `ALL_PROXY` environment variable is set to a non-SOCKS address it results in the `proxy: unknown scheme: http` when it instead should ignore it. Also filed at https://github.com/golang/go/issues/16715.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 1
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.16-boot2docker
Operating System: Boot2Docker 1.12.0 (TCL 7.2); HEAD : e030bab - Fri Jul 29 00:2
9:14 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: 3RVV:2FO4:HFHV:2X6L:M7YC:WRHP:BCG7:ARR7:HPNA:J2OY:YCAX:RG5P
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 24
 System Time: 2016-08-16T02:41:52.016303815Z
 EventsListeners: 0
Http Proxy: http://www-proxy.company.com:31060
Https Proxy: http://www-proxy.company.com:31060
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Using Docker Toolbox

**Steps to reproduce the issue:**
1. On Windows 8.1, set ALL_PROXY to http://www-proxy.company.com:31060
2. Run Docker Quickstart Terminal
3. Run `docker run hello-world` - see `proxy: unknown scheme: http` error

**Describe the results you received:**
Get `proxy: unknown scheme: http` error

**Describe the results you expected:**
I expect docker to run without an error

**Additional information you deem important (e.g. issue happens only occasionally):**
If I run `unset ALL_PROXY` Docker runs fine.

**Comment by thaJeztah** [comment]
ping @dave-tucker PTAL

**Comment by dave-tucker** [comment]
TIL there is a variable called `ALL_PROXY` 😁 
At [a cursory glance](https://github.com/kennethreitz/requests/issues/3183) it looks like it's a SOCKS-only thing so I don't think it's unreasonable to error out if it's set to a non-socks address as it's clearly not going to work as expected. None of my standard sources of proxy documentation (`curl` and `wget`) claim to have any support for it at all.

If the intention was indeed to use an HTTP_PROXY, there are environment variables already in place to allow that

**Comment by bbodenmiller** [comment]
While `ALL_PROXY` may be intended for SOCKS usage in some cases [users use it for non-SOCKS usage](https://www.bonusbits.com/wiki/HowTo:Setup_HTTP_Proxy_Settings_for_Bash_Profile_on_Linux). When they have that setup docker pulls fail. Just because a user or their system admin does something silly like use `ALL_PROXY` for a different purpose does not mean that docker should fail. There is at least a few users facing this issue as I see it reported on GitHub in a few locations and [SO](https://stackoverflow.com/questions/37573476/docker-complaining-about-all-proxy-environment-variable-with-proxy-unknown-sch). How about docker just does a simple check and if it starts with anything other than `socks` ignores the value?

**Comment by dave-tucker** [comment]
I stand corrected. `man curl` states
```
ALL_PROXY [protocol://]<host>[:port]
       Sets the proxy server to use if no  protocol-specific  proxy  is
       set.
```

As I read it, we shouldn't raise an error... instead we should use the value of `ALL_PROXY` assuming a protocol specific proxy hasn't been set.

**Comment by nathairtras** [comment]
Posting the error output in hopes that it might save someone else the couple of hours I wasted. Apologies if this is creating clutter.

Tried setting up Docker / Docker Machine on a mac running inside corporate network after doing the same on a personal machine.  Got a **SIGSEGV** and no obvious indication that this was a proxy issue.  (Not a go dev, maybe obvious if so?)

Running the same command on the docker-machine VM worked fine - was not passing in the `ALL_PROXY` variable.  From the host Mac, able to create containers and remove containers, using `run` caused the issue.

Clear `ALL_PROXY` and everything works.  (Assuming that the docker-machine IP is in `NO_PROXY`...)

**Output of `docker run --rm -it ubuntu bash`**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1054f08]

goroutine 1 [running]:
github.com/docker/cli/cli/command/container.runContainer(0xc4201d7a40, 0xc4203b8120, 0xc42039d400, 0xc42046c160, 0x1f256e0, 0xc4200f2180)
        /private/tmp/docker-20170709-24447-pqqft6/src/github.com/docker/cli/cli/command/container/run.go:171 +0xa62
github.com/docker/cli/cli/command/container.runRun(0xc4201d7a40, 0xc42008f4d0, 0xc4203b8120, 0xc42039d400, 0x0, 0x0)
        /private/tmp/docker-20170709-24447-pqqft6/src/github.com/docker/cli/cli/command/container/run.go:94 +0x141
github.com/docker/cli/cli/command/container.NewRunCommand.func1(0xc4203b1b00, 0xc4202eb940, 0x2, 0x4, 0x0, 0x0)
        /private/tmp/docker-20170709-24447-pqqft6/src/github.com/docker/cli/cli/command/container/run.go:48 +0x109
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203b1b00, 0xc4200100e0, 0x4, 0x4, 0xc4203b1b00, 0xc4200100e0)
        /private/tmp/docker-20170709-24447-pqqft6/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:646 +0x44e
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42039a240, 0xc42039a6c0, 0xc4203a0170, 0xc42000e4b8)
        /private/tmp/docker-20170709-24447-pqqft6/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:742 +0x349
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42039a240, 0xc42039a240, 0x1f276e0)
        /private/tmp/docker-20170709-24447-pqqft6/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
        /private/tmp/docker-20170709-24447-pqqft6/src/github.com/docker/cli/cmd/docker/docker.go:168 +0xc3```

**Comment by thaJeztah** [comment]
@nathairtras can you open a new issue with that information in the https://github.com/docker/cli/issues issue tracker?

**Comment by bastiaanb** [comment]
@thaJeztah : the segfault has been logged in https://github.com/docker/cli/issues/505 and already has been fixed.
