### ISSUE TITLE
Docker daemon panics in DNS resolution

### ISSUE THREAD

**Issue by xytis** [docker/docker#25802]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd6
```

**Output of `docker info`:**

```
Containers: 61
 Running: 0
 Paused: 0
 Stopped: 61
Images: 31
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: dnet bridge null host
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 157.2 GiB
Name: docker-07
ID: I253:KPRT:TQQN:CTBX:NIIO:UCTL:FOOO:GTMX:SDM6:SIR2:ODPH:6RMK
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Cluster store: consul://127.0.0.1:8500
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical servers, containers linked to `docker network create network-1` network.

**Steps to reproduce the issue:**
Observable in production with containers performing lots of DNS requests

**Describe the results you received:**
```
Aug 17 15:14:26 docker-07 docker[27936]: panic: sync: unlock of unlocked mutex
Aug 17 15:14:26 docker-07 docker[27936]: goroutine 11703956 [running]:
Aug 17 15:14:26 docker-07 docker[27936]: sync.(*Mutex).Unlock(0xc82263da58)
Aug 17 15:14:26 docker-07 docker[27936]: /usr/local/go/src/sync/mutex.go:108 +0x9f
Aug 17 15:14:26 docker-07 docker[27936]: sync.(*Once).Do(0xc82263da58, 0xc8233e1d18)
Aug 17 15:14:26 docker-07 docker[27936]: /usr/local/go/src/sync/once.go:46 +0xe5
Aug 17 15:14:26 docker-07 docker[27936]: github.com/docker/libnetwork.(*resolver).ServeDNS(0xc82263da00, 0x7f65a87be938, 0xc82371afc0, 0xc82230ce10)
Aug 17 15:14:26 docker-07 docker[27936]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/resolver.go:355 +0x812
Aug 17 15:14:26 docker-07 docker[27936]: github.com/miekg/dns.(*Server).serve(0xc820bd7520, 0x7f65b02bb988, 0xc821be9440, 0x7f65b0238948, 0xc82263da00, 0xc822
Aug 17 15:14:26 docker-07 docker[27936]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/server.go:535 +0x7c1
Aug 17 15:14:26 docker-07 docker[27936]: created by github.com/miekg/dns.(*Server).serveUDP
Aug 17 15:14:26 docker-07 docker[27936]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/server.go:489 +0x3d5
Aug 17 15:14:26 docker-07 docker[27936]: goroutine 1 [chan receive, 2996 minutes]:
Aug 17 15:14:26 docker-07 docker[27936]: main.(*DaemonCli).CmdDaemon(0xc8204258c0, 0xc82000a0c0, 0x8, 0x8, 0x0, 0x0)
Aug 17 15:14:26 docker-07 docker[27936]: /root/rpmbuild/BUILD/docker-engine/docker/daemon.go:337 +0x23e1
Aug 17 15:14:26 docker-07 docker[27936]: reflect.callMethod(0xc8204177a0, 0xc821703c78)
Aug 17 15:14:26 docker-07 docker[27936]: /usr/local/go/src/reflect/value.go:628 +0x1fc
Aug 17 15:14:26 docker-07 docker[27936]: reflect.methodValueCall(0xc82000a0c0, 0x8, 0x8, 0x1, 0xc8204177a0, 0x0, 0x0, 0xc8204177a0, 0x0, 0x47ccb4, ...)
Aug 17 15:14:26 docker-07 docker[27936]: /usr/local/go/src/reflect/asm_amd64.s:29 +0x36
Aug 17 15:14:26 docker-07 docker[27936]: github.com/docker/docker/cli.(*Cli).Run(0xc820417710, 0xc82000a0b0, 0x9, 0x9, 0x0, 0x0)
Aug 17 15:14:26 docker-07 docker[27936]: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/cli/cli.go:89 +0x383
Aug 17 15:14:26 docker-07 docker[27936]: main.main()
Aug 17 15:14:26 docker-07 docker[27936]: /root/rpmbuild/BUILD/docker-engine/docker/docker.go:63 +0x43c
```

**Describe the results you expected:**
Docker daemon should not crash (duh)

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens only occasionally.

**Comment by cpuguy83** [comment]
Thanks for the report, this is not possible in 1.12 so closing...

However I am really concerned that this was even possible as it is panicking in go's `sync.Once`

**Comment by mrjana** [comment]
@cpuguy83 It's a forced panic from go stdlib because we are trying to unlock an already unlocked mutex.

**Comment by cpuguy83** [comment]
@mrjana Yes, but it's happening when `sync.Once` is doing it's unlock... so the panic is likely from a race in sync.Mutex.

**Comment by mrjana** [comment]
Ahh.  Missed that little bit of information. That is strange indeed.

**Comment by cpuguy83** [comment]
Opened golang/go#16762
