### ISSUE TITLE
Panic: invalid memory address or nil pointer dereference at reducePsContainer

### ISSUE THREAD

**Issue by fernandoacorreia** [docker/docker#25991]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 12
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /REDACTED/docker/aufs
 Backing Filesystem: extfs
 Dirs: 181
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-93-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 29.44 GiB
Name: prod-exec-d-xlarge-79
ID: WW6Z:LOLJ:4MKX:ETKV:LNLQ:X7CC:ZZ6D:RZT5:XJ76:44XY:LJGV:WXSI
Docker Root Dir: /REDACTED/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

EC2 VM running Ubuntu 14.04.

**Steps to reproduce the issue:**

It is an intermittent issue. It happened 5 times over the last 24 hours on different VMs after we upgraded from Docker 1.7.1 to Docker 1.12.1.

* Run `docker run` e.g. like this:

```
/usr/bin/docker run -i -d --cidfile /REDACTED/REDACTED/server/tmp/cid6129368768428711423.tmp --name REDACTED-REDACTED-57bdae46489465196851ccab -e REDACTED_USER_ID=12345 -e REDACTED_GROUP_ID=12345 -u root -w /mnt --device /dev/nvidiactl:/dev/nvidiactl -v /REDACTED/REDACTED/server/REDACTED/57bdae46489465196851ccab:/mnt -v /REDACTED/REDACTED/server/tmp/1472048791057-0/launch:/tmp/launch -p 0.0.0.0::8888 REDACTED:TAG bash -e /tmp/launch/REDACTED
```

* Run `docker ps`, e.g.:

```
docker ps -a -f name=REDACTED-REDACTED-57bdae46489465196851ccab --no-trunc
```

**Describe the results you received:**

```
2016-08-24 14:26:31.184337 I | http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 194 [running]:
net/http.(*conn).serve.func1(0xc820c02b80)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x1a619a0, 0xc82000e0b0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/docker/docker/daemon.(*Daemon).reducePsContainer(0xc8204b0000, 0x0, 0xc820810f60, 0xc820b953d0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:202 +0x31
github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc8204b0000, 0xc820516340, 0xc820b953d0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:185 +0x1a5
```

(see complete log attached)

[log.txt](https://github.com/docker/docker/files/435617/log.txt)

**Describe the results you expected:**

No panic.

**Additional information you deem important (e.g. issue happens only occasionally):**

The logs don't show exactly when `docker ps` was called, but it is supposed to be executed shortly after `docker run`. The panic message seems to indicate that it was caused by `docker ps` but I may be reading it wrong. I know that it happened after `docker run`.

It's likely that several `docker ps` attempts were made after that, which may explain the several panic messages in the log.

**Comment by crosbymichael** [comment]
@fernandoacorreia thanks for the report, sorry you hit this.  I have a fix for this in #26049.

**Comment by fernandoacorreia** [comment]
Thanks for the quick fix. Looking forward to the next release. Historically we've been cautious to upgrade Docker because although it usually fixes important bugs, it tends to introduce others.

**Comment by thaJeztah** [comment]
@crosbymichael @vieux added this to 1.12.2 as it fixes a panic
