### ISSUE TITLE
crash on upgrade to 1.12.1

### ISSUE THREAD

**Issue by Flow86** [docker/docker#26075]
Hi,
I use "docker-engine" via the debian repository on a debian jessie machine (with backports kernel for overlayfs). My latest version was 1.11.2.

I updated to 1.12.1-0~jessie and the docker service crashes on startup:

```
time="2016-08-27T17:25:15.604714017+02:00" level=debug msg="Listener created for HTTP on fd ()"
time="2016-08-27T17:25:15.605454930+02:00" level=info msg="libcontainerd: new containerd process, pid: 22949"
time="2016-08-27T17:25:15.605873239+02:00" level=debug msg="libcontainerd: containerd connection state change: TRANSIENT_FAILURE"
time="2016-08-27T17:25:15.612449809+02:00" level=debug msg="containerd: read past events" count=0
time="2016-08-27T17:25:15.612549204+02:00" level=debug msg="containerd: supervisor running" cpus=8 memory=32092 runtime=docker-runc runtimeArgs=[] stateDir="/var/run/docker/libcontainerd/containerd"
time="2016-08-27T17:25:15.612694147+02:00" level=debug msg="containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock"
time="2016-08-27T17:25:16.606722865+02:00" level=debug msg="Using default logging driver journald"
time="2016-08-27T17:25:16.606774356+02:00" level=debug msg="Golang's threads limit set to 229590"
time="2016-08-27T17:25:16.606814753+02:00" level=debug msg="[graphdriver] trying provided driver \"overlay\""
time="2016-08-27T17:25:16.610430550+02:00" level=debug msg="Using graph driver overlay"
time="2016-08-27T17:25:16.612234994+02:00" level=debug msg="Max Concurrent Downloads: 3"
time="2016-08-27T17:25:16.612271133+02:00" level=debug msg="Max Concurrent Uploads: 5"
time="2016-08-27T17:25:16.632630752+02:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-08-27T17:25:16.632865483+02:00" level=warning msg="Your kernel does not support cgroup memory limit"
time="2016-08-27T17:25:16.634277710+02:00" level=debug msg="Loaded container xxx"
time="2016-08-27T17:25:16.634803008+02:00" level=debug msg="Loaded container xxx"
time="2016-08-27T17:25:16.635287787+02:00" level=debug msg="Loaded container xxx"
time="2016-08-27T17:25:16.635424478+02:00" level=debug msg="Option DefaultDriver: bridge"
time="2016-08-27T17:25:16.635442947+02:00" level=debug msg="Option DefaultNetwork: bridge"
time="2016-08-27T17:25:16.641689586+02:00" level=info msg="Firewalld running: false"
time="2016-08-27T17:25:16.644035596+02:00" level=debug msg="/sbin/iptables, [--wait --version]"
time="2016-08-27T17:25:16.645383917+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]"
time="2016-08-27T17:25:16.646974646+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER]"
time="2016-08-27T17:25:16.648517544+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER]"
time="2016-08-27T17:25:16.650037107+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -D PREROUTING]"
time="2016-08-27T17:25:16.651562001+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -D OUTPUT]"
time="2016-08-27T17:25:16.652956863+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -F DOCKER]"
time="2016-08-27T17:25:16.654331503+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -X DOCKER]"
time="2016-08-27T17:25:16.655639127+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -F DOCKER]"
time="2016-08-27T17:25:16.657315940+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -X DOCKER]"
time="2016-08-27T17:25:16.658696226+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION]"
time="2016-08-27T17:25:16.660462050+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION]"
time="2016-08-27T17:25:16.661756831+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -n -L DOCKER]"
time="2016-08-27T17:25:16.663072827+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -N DOCKER]"
time="2016-08-27T17:25:16.664353544+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -n -L DOCKER]"
time="2016-08-27T17:25:16.665610657+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -n -L DOCKER-ISOLATION]"
time="2016-08-27T17:25:16.666958347+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION -j RETURN]"
time="2016-08-27T17:25:16.668245145+02:00" level=debug msg="/sbin/iptables, [--wait -I DOCKER-ISOLATION -j RETURN]"
panic: runtime error: index out of range
goroutine 1 [running]:
panic(0x1a521e0, 0xc82000e040)
/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/libnetwork.(*controller).reservePools(0xc820204b40)
/usr/src/docker/vendor/src/github.com/docker/libnetwork/controller.go:691 +0x1453
github.com/docker/libnetwork.New(0xc82045e280, 0x6, 0x8, 0x0, 0x0, 0x0, 0x0)
/usr/src/docker/vendor/src/github.com/docker/libnetwork/controller.go:216 +0xa08
github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc820478000, 0xc8203d8380, 0xc820194cf0, 0x0, 0x0, 0x0, 0x0)
/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon_unix.go:640 +0xf5
github.com/docker/docker/daemon.(*Daemon).restore(0xc820478000, 0x0, 0x0)
/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:223 +0xa70
github.com/docker/docker/daemon.NewDaemon(0xc8203d8380, 0x7fddac496b68, 0xc820026638, 0x7fddac496588, 0xc8203caea0, 0x0, 0x0, 0x0)
/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:605 +0x34aa
main.(*DaemonCli).start(0xc8203c15c0, 0x0, 0x0)
/usr/src/docker/cmd/dockerd/daemon.go:269 +0x1a0e
main.main()
/usr/src/docker/cmd/dockerd/docker.go:68 +0x491
Aug 27 17:25:16 ma systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```

I currently start the docker daemon via
```
/usr/bin/docker daemon -H fd:// --storage-driver=overlay --cgroup-parent --ipv6=true --fixed-cidr-v6="2a01:1x:x:x::/64" --log-driver=journald -D
```
I changed it for 1.12 to 
```
/usr/bin/dockerd -H fd:// ...
```
but same error. 

I also tried to start with standard service arguments (removed all my custom additions) but same error.

can somebody tell me whats going wrong?

**Comment by coolljt0725** [comment]
ping @aboch

**Comment by aboch** [comment]
looking at it

**Comment by Flow86** [comment]
sorry for the late reply.

(re)moving local-kv.db worked ("buggy" version attached
[local-kv.db.zip](https://github.com/docker/docker/files/475183/local-kv.db.zip) )

theres another thing I've found:

````
docker network inspect 9f2a4029b299
[
    {
        "Name": "bridge",
        "Id": "....",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                },
                {
                    "Subnet": "xxxx:xxxx:xxxx:1::/64"
                }
            ]
        },
```

EnableIPv6 is still stated as "off", even if it has added the ipv6 subnet I wanted docker to use?

**Comment by aboch** [comment]
@Flow86  Thanks for providing the file

> EnableIPv6 is still stated as "off", even if it has added the ipv6 subnet I wanted docker to use?

That's correct, if `--ipv6` was not specified, that ipv6 subnet config is not operational, libnetwork does not request its reservation to the ipam driver. And when container is connected to the network, libnetwork will not program an IPv6 address.

**Comment by aboch** [comment]
I think that was it @Flow86, a misconfigured ipv6 network in the datastore.
Thanks for providing the extra info, will take care of this.

**Comment by Flow86** [comment]
> That's correct, if --ipv6 was not specified
yes the strange thing is: i had specified it?

**Comment by aboch** [comment]
> yes the strange thing is: i had specified it?

I do not think you specified it. From your local store file:
```
docker/network/v1.0/network/26f158e9fa8f875f473b93f59ee4e0adc45404599af7420ee4f8e43c32d31313/
{
"addrSpace":"LocalDefault",
"enableIPv6":false,   <----  <-----
"generic":{ <snip>},
"id":"26f158e9fa8f875f473b93f59ee4e0adc45404599af7420ee4f8e43c32d31313",
"inDelete":false,
"internal":false,
"ipamOptions":null,
"ipamType":"default",
"ipamV4Config":"[
    {  
        \"PreferredPool\":\"172.17.0.0/16\",
         \"SubPool\":\"\",
         \"Gateway\":\"172.17.0.1\", 
         \"AuxAddresses\":{}
    }
]",
"ipamV4Info":"[ <snip>]
"ipamV6Config":"[
    {
       \"PreferredPool\":\"2a01:198:283:1::/64\",
       \"SubPool\":\"\",
       \"Gateway\":\"\",
       \"AuxAddresses\":{}
    }
]",
"labels":null,
"name":"bridge",
"networkType":"bridge",
"persist":true,
"postIPv6":true,
"scope":"local"
}
```

**Comment by Flow86** [comment]
well, then it seems that that an additional bug here?

```
docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─local.conf
   Active: active (running) since Do 2016-09-15 18:50:03 CEST; 2h 9min ago
     Docs: https://docs.docker.com
 Main PID: 11043 (dockerd)
   CGroup: /system.slice/docker.service
           ├─11043 /usr/bin/dockerd -H fd:// --storage-driver=overlay --cgroup-parent **--ipv6** --fixed-cidr-v6="2a01:198:283:1::/64" --log-driver=journald
```

**Comment by aboch** [comment]
@Flow86 Looks like... Thanks.

**Comment by aboch** [comment]
@Flow86  Ok, I found something funny and the reason why the flag is false.

Things are fine if you start the daemon with:
`sudo dockerd --ipv6=true --fixed-cidr-v6="2001:db8:abcd::/64"`

But if you add the `--cgroup-parent` option, then it breaks, in the sense the "EnableIPv6" is false...
`sudo dockerd --cgroup-parent --ipv6=true --fixed-cidr-v6="2001:db8:abcd::/64"`

This is true on 1.11.2 and also on 1.12.1.

**Comment by aboch** [comment]
@Flow86 

Ok, it looks like that is not the correct way to use that option, you need to specify a value

`--cgroup-parent string    Optional parent cgroup for the container`

**Comment by Flow86** [comment]
ah! thank you. its a bit confusing that it still accepts "--ipv6" as an argument for the option.

I added a cgroup-parent name - I had to delete local-kv.db again afterwards to start docker, but now it "EnableIPv6" is true

```
Sep 16 07:40:16 ma dockerd[9146]: panic: runtime error: index out of range
Sep 16 07:40:16 ma dockerd[9146]: goroutine 1 [running]:
Sep 16 07:40:16 ma dockerd[9146]: panic(0x1a61640, 0xc82000e040)
Sep 16 07:40:16 ma dockerd[9146]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Sep 16 07:40:16 ma dockerd[9146]: github.com/docker/libnetwork.(*controller).reservePools(0xc820152b40)
Sep 16 07:40:16 ma dockerd[9146]: /usr/src/docker/vendor/src/github.com/docker/libnetwork/controller.go:703 +0x1453
Sep 16 07:40:16 ma dockerd[9146]: github.com/docker/libnetwork.New(0xc82048a740, 0x6, 0x8, 0x0, 0x0, 0x0, 0x0)
Sep 16 07:40:16 ma dockerd[9146]: /usr/src/docker/vendor/src/github.com/docker/libnetwork/controller.go:216 +0xa08
Sep 16 07:40:16 ma dockerd[9146]: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc8204a6000, 0xc82041c700, 0xc82014ea50, 0x0, 0x0, 0x0, 0x0)
Sep 16 07:40:16 ma dockerd[9146]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon_unix.go:640 +0xf5
Sep 16 07:40:16 ma dockerd[9146]: github.com/docker/docker/daemon.(*Daemon).restore(0xc8204a6000, 0x0, 0x0)
Sep 16 07:40:16 ma dockerd[9146]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:223 +0xa70
Sep 16 07:40:16 ma dockerd[9146]: github.com/docker/docker/daemon.NewDaemon(0xc82041c700, 0x7f1d000a1470, 0xc8203361f8, 0x7f1d000a0d78, 0xc8203fbc70, 0x0, 0x0, 0x0)
Sep 16 07:40:16 ma dockerd[9146]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:605 +0x34aa
Sep 16 07:40:16 ma dockerd[9146]: main.(*DaemonCli).start(0xc820428180, 0x0, 0x0)
Sep 16 07:40:16 ma dockerd[9146]: /usr/src/docker/cmd/dockerd/daemon.go:265 +0x1951
Sep 16 07:40:16 ma dockerd[9146]: main.main()
Sep 16 07:40:16 ma dockerd[9146]: /usr/src/docker/cmd/dockerd/docker.go:68 +0x491
```

**Comment by thaJeztah** [comment]
@aboch I can consistently reproduce the panic if the daemon is started with the invalid option once, basically:

```
# run with invalid option:
dockerd --debug --cgroup-parent --ipv6=true --fixed-cidr-v6="2001:db8:abcd::/64"

# stop daemon, and start without options
dockerd --debug
```

produces the panic:

<details>
```
DEBU[0000] docker group found. gid: 999
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock)
INFO[0000] libcontainerd: new containerd process, pid: 4568
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=4 memory=1999 runtime=docker-runc runtimeArgs=[] stateDir=/var/run/docker/libcontainerd/containerd
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock
DEBU[0001] Using default logging driver json-file
DEBU[0001] Golang's threads limit set to 13950
INFO[0001] [graphdriver] using prior storage driver: aufs
DEBU[0001] Using graph driver aufs
DEBU[0001] Max Concurrent Downloads: 3
DEBU[0001] Max Concurrent Uploads: 5
INFO[0001] Graph migration to content-addressability took 0.00 seconds
DEBU[0001] Loaded container 962ba68bcbcdb14c91de5b32a3d7cc6f71f0e02b1d10f313c4dc478877661c20
DEBU[0001] Loaded container dccfc61b41dc836bbbb625bdb1e4f34cecd09149beeb0448b364e3f1fa9b4802
DEBU[0001] Option DefaultDriver: bridge
DEBU[0001] Option DefaultNetwork: bridge
WARN[0001] Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.20-moby/modules.dep.bin'
modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.20-moby/modules.dep.bin'
, error: exit status 1
WARN[0001] Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.20-moby/modules.dep.bin'`, error: exit status 1
WARN[0001] Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.20-moby/modules.dep.bin'`, error: exit status 1
DEBU[0001] Fail to initialize firewalld: Failed to connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory, using raw iptables instead
DEBU[0001] /sbin/iptables, [--wait --version]
DEBU[0001] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t nat -D PREROUTING]
DEBU[0001] /sbin/iptables, [--wait -t nat -D OUTPUT]
DEBU[0001] /sbin/iptables, [--wait -t nat -F DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t nat -X DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t filter -F DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t filter -X DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION]
DEBU[0001] /sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION]
DEBU[0001] /sbin/iptables, [--wait -t nat -n -L DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t nat -N DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t filter -n -L DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t filter -n -L DOCKER-ISOLATION]
DEBU[0001] /sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION -j RETURN]
DEBU[0001] /sbin/iptables, [--wait -I DOCKER-ISOLATION -j RETURN]
WARN[0001] Could not load necessary modules for IPSEC rules: Running modprobe xfrm_user failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.20-moby/modules.dep.bin'`, error: exit status 1
DEBU[0001] /sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.18.0.0/16 ! -o docker0 -j MASQUERADE]
DEBU[0001] /sbin/iptables, [--wait -t nat -C DOCKER -i docker0 -j RETURN]
DEBU[0001] /sbin/iptables, [--wait -t nat -I DOCKER -i docker0 -j RETURN]
DEBU[0001] /sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP]
DEBU[0001] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT]
DEBU[0001] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT]
DEBU[0001] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]
DEBU[0001] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
DEBU[0001] /sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
DEBU[0001] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER]
DEBU[0001] /sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION]
DEBU[0001] /sbin/iptables, [--wait -D FORWARD -j DOCKER-ISOLATION]
DEBU[0001] /sbin/iptables, [--wait -I FORWARD -j DOCKER-ISOLATION]
DEBU[0001] Network (301be39) restored
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x15c5380, 0xc4200100d0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/libnetwork.(*controller).reservePools(0xc4200d8690)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/controller.go:757 +0xa16
github.com/docker/libnetwork.New(0xc420207dc0, 0x6, 0x8, 0xc420207dc0, 0x6, 0x8, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/controller.go:219 +0x70d
github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc42034d520, 0xc42043f180, 0xc42047ea20, 0xc42034d520, 0xc420209198, 0xc42047ea20, 0xc42047e9f0)
	/go/src/github.com/docker/docker/daemon/daemon_unix.go:617 +0x8f
github.com/docker/docker/daemon.(*Daemon).restore(0xc42034d520, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:248 +0xc97
github.com/docker/docker/daemon.NewDaemon(0xc42043f180, 0x21ed1e0, 0xc42002a6d8, 0x21e0960, 0xc42043d450, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:671 +0x218b
main.(*DaemonCli).start(0xc420448f60, 0x0, 0x17d1201, 0x17, 0xc42043f180, 0xc42024f400, 0xc42008cea0, 0x0, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/daemon.go:246 +0xffd
main.runDaemon(0x0, 0x17d1201, 0x17, 0xc42043f180, 0xc42024f400, 0xc42008cea0, 0x1, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:75 +0xb2
main.newDaemonCommand.func1(0xc42033d200, 0xc420441510, 0x0, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:41 +0x71
github.com/spf13/cobra.(*Command).execute(0xc42033d200, 0xc42000c1d0, 0x1, 0x1, 0xc42033d200, 0xc42000c1d0)
	/go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:643 +0x26d
github.com/spf13/cobra.(*Command).ExecuteC(0xc42033d200, 0x15e78c0, 0xc42024f401, 0xc4204414b0)
	/go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:739 +0x377
github.com/spf13/cobra.(*Command).Execute(0xc42033d200, 0xc4204414b0, 0xc42006e058)
	/go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:692 +0x2b
main.main()
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:99 +0xe2
```
</details>

Running on current master (inside a container);

```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   76ee0e8
 Built:        Fri Sep 16 12:36:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   76ee0e8
 Built:        Fri Sep 16 12:36:48 2016
 OS/Arch:      linux/amd64
```

**Comment by aboch** [comment]
@thaJeztah Yes, I am aware of that.
