### ISSUE TITLE
connect docker host from remote host using docker-py 

### ISSUE THREAD

**Issue by lamhaison** [docker/docker#26100]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
root@hd1-stag-docker01:~# docker info
Containers: 21
 Running: 7
 Paused: 0
 Stopped: 14
Images: 3
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: active
 NodeID: 9wdo0x0vez8c7zhh7kccizmpt
 Is Manager: true
 ClusterID: 6u3vsu40okshjvp376bvon7mu
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.10.11.254
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: hd1-stag-docker01
ID: LZKF:MSXX:7FX5:WDBK:XXYQ:VBZ3:2KKA:GCWI:4NLO:UC2L:S55E:VWRU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
root@hd1-stag-docker01:~# 
root@hd1-stag-docker01:~# 
root@hd1-stag-docker01:~# 
root@hd1-stag-docker01:~# 
root@hd1-stag-docker01:~# 
root@hd1-stag-docker01:~# docker info
Containers: 21
 Running: 7
 Paused: 0
 Stopped: 14
Images: 3
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: active
 NodeID: 9wdo0x0vez8c7zhh7kccizmpt
 Is Manager: true
 ClusterID: 6u3vsu40okshjvp376bvon7mu
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.10.11.254
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: hd1-stag-docker01
ID: LZKF:MSXX:7FX5:WDBK:XXYQ:VBZ3:2KKA:GCWI:4NLO:UC2L:S55E:VWRU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**nestat command:**

netstat -ntpl
tcp6       0      0 :::2377                 :::*                    LISTEN      3084/dockerd 

**Steps to reproduce the issue:**
1. I want to connect docker swarm manager from remote host using docker-py
2. I using code above to get image list
````
from docker import Client
cli = Client(base_url='tcp://%s' % '10.10.11.254:2377')
cli.images()
````

**Describe the results you received:**
```
Error
Traceback (most recent call last):
  File "/home/lamhaison/PycharmProjects/cdfimplus/tests/dockerclientest/dockerclienttest.py", line 195, in test_get_all_image
    result = self.cli.images()
  File "/home/lamhaison/env/cdfimplus/lib/python2.7/site-packages/docker/api/image.py", line 39, in images
    res = self._result(self._get(self._url("/images/json"), params=params),
  File "/home/lamhaison/env/cdfimplus/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/home/lamhaison/env/cdfimplus/lib/python2.7/site-packages/docker/client.py", line 145, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/lamhaison/env/cdfimplus/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/home/lamhaison/env/cdfimplus/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lamhaison/env/cdfimplus/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/lamhaison/env/cdfimplus/lib/python2.7/site-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\n',))
**Describe the results you expected:**
List json include list images
```

**How to connect to remote docker swarm host using python?. Thanks**

**Comment by lamhaison** [comment]
After a long time debug, i see this message "Are you trying to connect to a TLS-enabled daemon without TLS". Default docker is using tls on docker swarm 1.12?
How to resolve it (i do not where is key pem file)

**Comment by cpuguy83** [comment]
Indeed you are connecting to a TLS enabled daemon without telling docker-py about it, so docker-py is connecting over plain HTTP and not understanding the response.

Can you point to the docs you followed?

**Comment by lamhaison** [comment]
I follow this tutorial https://docs.docker.com/engine/swarm/swarm-tutorial/.
I don't setup any step for TLS, I don't understand why it require TLS when connect docker swarm manager?

**Comment by cpuguy83** [comment]
I see now...
It looks like you are trying to connect to the swarm control socket which is used for node-to-node communication. This is only used for communication between nodes, not API access.

To connect to "the swarm" just use the normal docker API.
There are new endpoints for management of services, tasks, and nodes.

Closing since this is a non-issue.
Thanks!
