### ISSUE TITLE
dockerd: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by JamesJJ** [docker/docker#26356]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

*... after `systemctl restart  docker.service`*

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker_lvm_vg-docker_lvm
 Pool Blocksize: 524.3 kB
 Base Device Size: 8.59 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 4.733 GB
 Data Space Total: 52.94 GB
 Data Space Available: 48.2 GB
 Metadata Space Used: 1.913 MB
 Metadata Space Total: 209.7 MB
 Metadata Space Available: 207.8 MB
 Thin Pool Minimum Free Space: 3.705 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.389 GiB
Name: ip-10-12-15-126.domain.name
ID: 62CV:56GM:HC7A:HS6X:PVII:5HMY:HQNW:Q3PL:7L3D:SRFF:EUDH:BPNX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS / Centos 7, fully updated / Docker from Docker's Yum repo

**Steps to reproduce the issue:**
1. [unknown if relevant] Start some containers
2. [unknown if relevant] One container includes `HEALTHCHECK ...` directive
3. Wait for /time/ (in this case the machine and containers had been running for about 3 days)
4. Docker and containers all dead. `/var/log/messages` shows below panic message

**Describe the results you received:**

*From /var/log/messages*

```
Sep  6 20:48:54 ip-10-12-15-126 dockerd: time="2016-09-06T20:48:54.855732287Z" level=warning msg="Health check error: rpc error: code = 2 desc = oci runtime error: exec failed: process_linux.go:75: starting setns process caused \"fork/exec /proc/self/exe: no such file or directory\""
Sep  6 20:48:58 ip-10-12-15-126 dockerd: time="2016-09-06T20:48:58.875034743Z" level=warning msg="Health check error: rpc error: code = 2 desc = oci runtime error: exec failed: process_linux.go:75: starting setns process caused \"fork/exec /proc/self/exe: no such file or directory\""
Sep  6 20:49:02 ip-10-12-15-126 dockerd: time="2016-09-06T20:49:02.894231701Z" level=warning msg="Health check error: rpc error: code = 2 desc = oci runtime error: exec failed: process_linux.go:75: starting setns process caused \"fork/exec /proc/self/exe: no such file or directory\""
Sep  6 20:49:06 ip-10-12-15-126 dockerd: time="2016-09-06T20:49:06.913581331Z" level=warning msg="Health check error: rpc error: code = 2 desc = oci runtime error: exec failed: process_linux.go:75: starting setns process caused \"fork/exec /proc/self/exe: no such file or directory\""
Sep  6 20:49:10 ip-10-12-15-126 dockerd: time="2016-09-06T20:49:10.933518882Z" level=warning msg="Health check error: rpc error: code = 2 desc = oci runtime error: exec failed: process_linux.go:75: starting setns process caused \"fork/exec /proc/self/exe: no such file or directory\""
Sep  6 20:49:14 ip-10-12-15-126 dockerd: time="2016-09-06T20:49:14.952690867Z" level=warning msg="Health check error: rpc error: code = 2 desc = oci runtime error: exec failed: process_linux.go:75: starting setns process caused \"fork/exec /proc/self/exe: no such file or directory\""
Sep  6 20:49:18 ip-10-12-15-126 dockerd: time="2016-09-06T20:49:18.971882492Z" level=warning msg="Health check error: rpc error: code = 2 desc = oci runtime error: exec failed: process_linux.go:75: starting setns process caused \"fork/exec /proc/self/exe: no such file or directory\""
Sep  6 20:49:19 ip-10-12-15-126 dockerd: panic: runtime error: invalid memory address or nil pointer dereference
Sep  6 20:49:19 ip-10-12-15-126 dockerd: [signal 0xb code=0x1 addr=0x28 pc=0x8b6fa0]
Sep  6 20:49:19 ip-10-12-15-126 dockerd: goroutine 583379 [running]:
Sep  6 20:49:19 ip-10-12-15-126 dockerd: panic(0x1a7edc0, 0xc82000a080)
Sep  6 20:49:19 ip-10-12-15-126 dockerd: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Sep  6 20:49:19 ip-10-12-15-126 dockerd: github.com/docker/libnetwork.(*resolver).ServeDNS(0xc8200882d0, 0x7f7a522a7898, 0xc82649ea10, 0xc8a2b88360)
Sep  6 20:49:19 ip-10-12-15-126 dockerd: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/resolver.go:363 +0x7b0
Sep  6 20:49:19 ip-10-12-15-126 dockerd: github.com/miekg/dns.(*Server).serve(0xc820e944e0, 0x7f7a522a3508, 0xc8adfb9050, 0x7f7a522a3580, 0xc8200882d0, 0xc8981df800, 0x23, 0x200, 0xc82001c0d0, 0xc8a76f6940, ...)
Sep  6 20:49:19 ip-10-12-15-126 dockerd: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/server.go:535 +0x7c8
Sep  6 20:49:19 ip-10-12-15-126 dockerd: created by github.com/miekg/dns.(*Server).serveUDP
Sep  6 20:49:19 ip-10-12-15-126 dockerd: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/server.go:489 +0x3d5
Sep  6 20:49:19 ip-10-12-15-126 systemd: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Sep  6 20:49:19 ip-10-12-15-126 systemd: Unit docker.service entered failed state.
Sep  6 20:49:19 ip-10-12-15-126 systemd: docker.service failed.

```
**Describe the results you expected:**

No panic / service uninterrupted 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
ping @sanimej

**Comment by sanimej** [comment]
@JamesJJ Were there lot of DNS activity happening from the containers ? Panic happened on a nil pointer dereference. But there are error checks. When the containers were running did you notice any issues with name resolution ?

**Comment by JamesJJ** [comment]
@sanimej  Monitoring did not highlight any issues before the panic. At the time this machine was not "in-service", so although the containers were running, they were just idle ... 1 app request every 8 seconds for the loadbalancer's health check. The compose stack is nginx in front of a backend container. If the DNS TTL had been reached, Nginx would have done 1 DNS request to find the IP of the backend container.

**Comment by JamesJJ** [comment]
As a sanity, I ran `tcpdump` inside each container, and on the bridge interface on the host `br-e9f8414dce88 172.18.0.1/16` .... I did not see any DNS traffic, apart from when I specifically did DNS lookups using `dig` ... So I'm reasonable certain the above is correct: DNS activity very low.

**Comment by thaJeztah** [comment]
ping @sanimej any progress here?

**Comment by vieux** [comment]
ping @sanimej any progress here?

**Comment by JamesJJ** [comment]
Another `panic: runtime error: invalid memory address or nil pointer dereference
` ... the trace is slightly different though:

```
Sep 16 06:17:53 ip-10-10-44-248 dockerd[5037]: time="2016-09-16T06:17:53Z" level=info msg="Firewalld running: false"
Sep 16 06:20:09 ip-10-10-44-248 dockerd[5037]: time="2016-09-16T06:20:08Z" level=info msg="Firewalld running: false"
Sep 16 06:22:21 ip-10-10-44-248 dockerd[5037]: time="2016-09-16T06:22:21Z" level=info msg="Firewalld running: false"
Sep 16 06:24:36 ip-10-10-44-248 dockerd[5037]: time="2016-09-16T06:24:36Z" level=info msg="Firewalld running: false"
Sep 16 06:26:46 ip-10-10-44-248 dockerd[5037]: time="2016-09-16T06:26:46Z" level=info msg="Firewalld running: false"
Sep 16 06:33:26 ip-10-10-44-248 dockerd[5037]: time="2016-09-16T06:32:49.228009422Z" level=error msg="containerd: start container" error="containerd: container did not start before the specified timeout" id=bc3941ec25eb832aa1df7961f16f4b015f55ed94febc104b5d67a29714456362
Sep 16 06:37:07 ip-10-10-44-248 dockerd[5037]: time="2016-09-16T06:37:06.040399719Z" level=error msg="libcontainerd: error restarting rpc error: code = 2 desc = containerd: container did not start before the specified timeout"
Sep 16 06:37:07 ip-10-10-44-248 dockerd[5037]: time="2016-09-16T06:37:06.330255193Z" level=error msg="libcontainerd: rpc error: code = 2 desc = containerd: container did not start before the specified timeout"
Sep 16 06:37:54 ip-10-10-44-248 dockerd[5037]: time="2016-09-16T06:37:51Z" level=info msg="Firewalld running: false"
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: [signal 0xb code=0x1 addr=0x0 pc=0xdd404e]
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: goroutine 764162 [running]:
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: panic(0x1a7edc0, 0xc82000a080)
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: github.com/miekg/dns.getUDPSocketName(0x0, 0x0, 0x0, 0x0, 0x0)
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/udp_linux.go:68 +0xce
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: github.com/miekg/dns.setUDPSocketOptions(0x0, 0x0, 0x0)
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/udp.go:23 +0x37
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: github.com/miekg/dns.(*Server).ActivateAndServe(0xc822f39c70, 0x0, 0x0)
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/server.go:349 +0x1b7
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: github.com/docker/libnetwork.(*resolver).Start.func1(0xc822f39c70)
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/resolver.go:122 +0x21
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: created by github.com/docker/libnetwork.(*resolver).Start
Sep 16 06:38:05 ip-10-10-44-248 dockerd[5037]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/resolver.go:123 +0x2b1
Sep 16 06:38:06 ip-10-10-44-248 systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 16 06:38:06 ip-10-10-44-248 systemd[1]: Unit docker.service entered failed state.
Sep 16 06:38:06 ip-10-10-44-248 systemd[1]: docker.service failed.
```

**Comment by sanimej** [comment]
@JamesJJ From this log it looks like there is some failure in running the healthcheck command 

`Sep  6 20:49:18 ip-10-12-15-126 dockerd: time="2016-09-06T20:49:18.971882492Z" level=warning msg="Health check error: rpc error: code = 2 desc = oci runtime error: exec failed: process_linux.go:75: starting setns process caused \"fork/exec /proc/self/exe: no such file or directory\""`

What command do you have in the healthcheck ? Does it work normally ?

The first panic you hit could happen in one possible error scenario which I am going to fix. Trying to understand if the healthcheck failures could be related to that.

**Comment by sanimej** [comment]
@JamesJJ I am not able to come up with a possible scenario for the 2nd panic. From the log, right before the panic there is this message..

`Sep 16 06:37:54 ip-10-10-44-248 dockerd[5037]: time="2016-09-16T06:37:51Z" level=info msg="Firewalld running: false"`

This check happens once, typically when the daemon comes up. So before this panic was there any daemon restart ? Do you have `live-restore` enabled or have containers with restart policies ? It looks like a specific sequence in daemon coming up caused this crash.

**Comment by JamesJJ** [comment]
> What command do you have in the healthcheck ? Does it work normally ?

`HEALTHCHECK --interval=4s CMD curl --max-time 3 --connect-timeout 2 -sSf http://127.0.0.1:9080/health || exit 1`

It works as expected: Usually starting-> healthy, at container start. Sometimes first check will fail if dependency container is not up yet, but that is only a brief condition (maybe 10 seconds). Only one of the containers has HEALTHCHECK ....  the others do not.

> This check happens once, typically when the daemon comes up. So before this panic was there any daemon restart ?

The `Firewalld` message starts from damon first start [2 days before panic] and continues until panic ... full log:
[panic-log.txt](https://github.com/docker/docker/files/486772/panic-log.txt)
(PID does not change)

> Do you have live-restore enabled

No

> ... have containers with restart policies

Yes: All containers have `restart: always` in `docker-compose.yml`

--
Many thanks for your help.

**Comment by sanimej** [comment]
#26844 brings in the change to fix the first crash reported in this issue. Second one is a different decode and can be tracked by a separate issue.

**Comment by piontec** [comment]
We still got this error with 1.12.4:
```
dockerd[100690]: panic: runtime error: invalid memory address or nil pointer dereference
dockerd[100690]: [signal 0xb code=0x1 addr=0x0 pc=0x601668]
dockerd[100690]: goroutine 457981 [running]:
dockerd[100690]: panic(0x1aa2760, 0xc82000c090)
dockerd[100690]: #011/usr/local/go/src/runtime/panic.go:481 +0x3e6
dockerd[100690]: github.com/docker/docker/libcontainerd.(*container).start(0xc823629140, 0x0, 0x0, 0x0)
dockerd[100690]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:143 +0x708
dockerd[100690]: github.com/docker/docker/libcontainerd.(*container).handleEvent.func1.1(0xc825c87980, 0xc823629140, 0xc826cbea80, 0xc829f27900)
dockerd[100690]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:227 +0x11a
dockerd[100690]: created by github.com/docker/docker/libcontainerd.(*container).handleEvent.func1
dockerd[100690]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:243 +0x226
systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

This is run on AWS, ubuntu 16.04.

Info outputs:
- docker version
```
Client:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64
```

docker info:
```
Containers: 422
 Running: 409
 Paused: 0
 Stopped: 13
Images: 1087
Server Version: 1.12.4
Storage Driver: aufs
 Root Dir: /opt/io1/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3627
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 128
Total Memory: 1.876 TiB
Name: ip-10-69-11-89
ID: UGZS:UFD3:GB4C:W5MX:JU2L:K7PH:6ZWS:4GPM:27Q5:UNNN:X3DC:YDT7
Docker Root Dir: /opt/io1/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

systemctl status docker
```
docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2016-12-20 08:49:36 UTC; 16min ago
     Docs: https://docs.docker.com
 Main PID: 32892 (dockerd)
    Tasks: 7528
   Memory: 115.2G
      CPU: 47min 57.175s
   CGroup: /system.slice/docker.service
```

**Comment by thaJeztah** [comment]
@piontec that panic looks different from the one reported here; could you open a new issue with more information how you ended up with that panic? Also note that 1.12.5 was released, which fixes one possible panic in networking, and and a race.

**Comment by piontec** [comment]
We needed to rollback from 1.12.5, as it crashed during startup with a stacktrace (unfortunately, I didn't save it). I can't repeat that deployment right now.

**Comment by sanimej** [comment]
@thaJeztah The last panic reported by @piontec is not in libnetwork.

**Comment by piontec** [comment]
I opened a new issue here: https://github.com/docker/docker/issues/29598

**Comment by aizatto** [comment]
Somewhat unrelated, but commenting just in case someone encounters the keywords that got me here.

Scenario:

Trying to do a docker build, and my Pi Hole (on docker) would crash.

Also received this error in `journalctl docker`

```
"runtime error: invalid memory address or nil pointer dereference" docker
```

Googling got me to this issue

Fixed my `/etc/resolv.conf` to not use pi hole and it worked.

**Comment by thaJeztah** [comment]
@aizatto an "invalid memory address or will pointer dereference" error can have many causes. If you are able to reproduce (with the "faulty" `/etc/resolv.conf`), could you open a new ticket with the full output of the error? If the error contains a "trace", it would allow finding _where_ the nil-pointer-exception occurs.

**Comment by remort** [comment]
Experienced the same error on `Docker version 20.10.17, build 100c701` under Ubuntu server 18.04:

```
Sep 08 21:47:20 thewall dockerd[909]: time="2022-09-08T16:47:20.469158710Z" level=warning msg="Your kernel does not support swap memory limit"
Sep 08 21:47:20 thewall dockerd[909]: time="2022-09-08T16:47:20.469190701Z" level=warning msg="Your kernel does not support CPU realtime scheduler"
Sep 08 21:47:20 thewall dockerd[909]: time="2022-09-08T16:47:20.469197363Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Sep 08 21:47:20 thewall dockerd[909]: time="2022-09-08T16:47:20.469202172Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Sep 08 21:47:20 thewall dockerd[909]: time="2022-09-08T16:47:20.469692204Z" level=info msg="Loading containers: start."
Sep 08 21:47:20 thewall dockerd[909]: time="2022-09-08T16:47:20.641146676Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Sep 08 21:47:20 thewall dockerd[909]: time="2022-09-08T16:47:20.679091947Z" level=info msg="Loading containers: done."
Sep 08 21:47:20 thewall dockerd[909]: time="2022-09-08T16:47:20.738197563Z" level=info msg="Docker daemon" commit=a89b842 graphdriver(s)=overlay2 version=20.10.17
Sep 08 21:47:20 thewall dockerd[909]: time="2022-09-08T16:47:20.739551039Z" level=info msg="Daemon has completed initialization"
Sep 08 21:47:20 thewall systemd[1]: Started Docker Application Container Engine.
Sep 08 21:47:20 thewall dockerd[909]: time="2022-09-08T16:47:20.767771130Z" level=info msg="API listen on /var/run/docker.sock"
Sep 08 21:50:17 thewall dockerd[909]: time="2022-09-08T16:50:17.655198794Z" level=info msg="Container failed to exit within 10s of signal 15 - using the force" container=729d16dc50a75488d0c3f676ffcaf7e184d77f64ce32d320f62c9fa4b522a2f0
Sep 08 21:50:17 thewall dockerd[909]: time="2022-09-08T16:50:17.717997495Z" level=info msg="ignoring event" container=729d16dc50a75488d0c3f676ffcaf7e184d77f64ce32d320f62c9fa4b522a2f0 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Sep 08 21:50:17 thewall dockerd[909]: time="2022-09-08T16:50:17.953995020Z" level=error msg="Handler for GET /v1.30/containers/16fab644374b4387c6bd5faac355cdbca276cabc2f5ee6ebeb0263257bf62480/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
Sep 08 21:50:17 thewall dockerd[909]: http: superfluous response.WriteHeader call from github.com/docker/docker/api/server/httputils.WriteJSON (httputils_write_json.go:11)
Sep 08 21:50:51 thewall dockerd[909]: time="2022-09-08T16:50:51.397433133Z" level=info msg="ignoring event" container=16fab644374b4387c6bd5faac355cdbca276cabc2f5ee6ebeb0263257bf62480 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Sep 08 21:51:09 thewall dockerd[909]: time="2022-09-08T16:51:09.822785340Z" level=warning msg="Health check for container 729d16dc50a75488d0c3f676ffcaf7e184d77f64ce32d320f62c9fa4b522a2f0 error: context deadline exceeded"
Sep 08 21:51:29 thewall dockerd[909]: time="2022-09-08T16:51:29.827337559Z" level=warning msg="Health check for container 729d16dc50a75488d0c3f676ffcaf7e184d77f64ce32d320f62c9fa4b522a2f0 error: context deadline exceeded"
Sep 08 21:52:19 thewall dockerd[909]: http: panic serving @: runtime error: invalid memory address or nil pointer dereference
                                      goroutine 962 [running]:
                                      net/http.(*conn).serve.func1()
                                              /usr/local/go/src/net/http/server.go:1802 +0xb9
                                      panic({0x55c38243d600, 0x55c3839ba410})
                                              /usr/local/go/src/runtime/panic.go:1047 +0x266
                                      net/textproto.MIMEHeader.Set(...)
                                              /usr/local/go/src/net/textproto/header.go:22
                                      net/http.Header.Set(...)
                                              /usr/local/go/src/net/http/header.go:38
                                      github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1({0x55c3827d42d8, 0xc000a16420}, {0x55c3827a5010, 0xc0014aa380}, 0x203000, 0x40)
                                              /go/src/github.com/docker/docker/api/server/middleware/version.go:47 +0x185
                                      github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1({0x55c3827d42d8, 0xc000a16420}, {0x55c3827a5010, 0xc0014aa380}, 0xc001a58400, 0xc000ae1a60)
                                              /go/src/github.com/docker/docker/pkg/authorization/middleware.go:59 +0x664
                                      github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1({0x55c3827a5010, 0xc0014aa380}, 0xc001a58300)
                                              /go/src/github.com/docker/docker/api/server/server.go:141 +0x2fa
                                      net/http.HandlerFunc.ServeHTTP(0xc001a58200, {0x55c3827a5010, 0xc0014aa380}, 0xc000f2d9f8)
                                              /usr/local/go/src/net/http/server.go:2047 +0x2f
                                      github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0006f2540, {0x55c3827a5010, 0xc0014aa380}, 0xc001061c00)
                                              /go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:210 +0x1cf
                                      net/http.serverHandler.ServeHTTP({0xc001336210}, {0x55c3827a5010, 0xc0014aa380}, 0xc001061c00)
                                              /usr/local/go/src/net/http/server.go:2879 +0x43b
                                      net/http.(*conn).serve(0xc000264c80, {0x55c3827d42d8, 0xc000898630})
                                              /usr/local/go/src/net/http/server.go:1930 +0xb08
                                      created by net/http.(*Server).Serve
                                              /usr/local/go/src/net/http/server.go:3034 +0x4e8
Sep 08 21:59:55 thewall dockerd[909]: time="2022-09-08T16:59:55.230145492Z" level=error msg="stream copy error: reading from a closed fifo"
Sep 08 21:59:55 thewall dockerd[909]: time="2022-09-08T16:59:55.230234950Z" level=error msg="stream copy error: reading from a closed fifo"

```

4 cores CPU, 8 Gb RAM, about 10 containers including three pretty heavy ones containing Java apps.

**Comment by davidsayre** [comment]
I'm seeing this error as well on docker-compose 2.15 and ubuntu 18
Will there be a retroactive fix or is the only solution upgrading ubuntu 18?

**Comment by thaJeztah** [comment]
@davidsayre this is a ticket from 2016, so about 7 years old now, and very likely your issue is unrelated to the original issue (but a stack dump output may "look" similar) . If you have details and reproduction steps, please open a new ticket instead with those steps.
