### ISSUE TITLE
docker-io 1.7.1 can't start in CentOS 6.5.I spend so much time in researching this,but I can't solve the problem.

### ISSUE THREAD

**Issue by martinko2009** [docker/docker#26364]
When I input service docker start or docker -d, docker can't start. I use yum -y install  docker-io in CentOS 6.5 to install docker-io, CentOs kernel's information is
```
Linux dc1 2.6.32-431.23.3.el6.x86_64 #1 SMP Wed Jul 16 06:12:23 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
```
```
[root@dc1 fs]# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
[root@dc1 fs]# 
```
When I want to start docker, everytime it is failure. the log is like below:
```
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
WARN[0000] You are running linux kernel version 2.6.32-431.23.3.el6.x86_64, which might be unstable running docker. Please upgrade your kernel to 3.10.0. 
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.gothrow(0xd64790, 0x2a)
        /usr/lib/golang/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
        /usr/lib/golang/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x404f40, 0xc2083c2d10, 0x0)
        /usr/lib/golang/src/runtime/cgocall.go:130 +0xf5 fp=0xc2083c2cf0 sp=0xc2083c2cc8
github.com/docker/docker/pkg/devicemapper._Cfunc_dm_task_get_info(0x2f0e4d0, 0xc2083c2d2c, 0x0)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/pkg/devicemapper/:134 +0x43 fp=0xc2083c2d10 sp=0xc2083c2cf0
github.com/docker/docker/pkg/devicemapper.dmTaskGetInfoFct(0x2f0e4d0, 0xc2080d9180, 0x0)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/pkg/devicemapper/devmapper_wrapper.go:211 +0x96 fp=0xc2083c2d78 sp=0xc2083c2d10
github.com/docker/docker/pkg/devicemapper.(*Task).GetInfo(0xc20803e338, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:220 +0x76 fp=0xc2083c2da0 sp=0xc2083c2d78
github.com/docker/docker/pkg/devicemapper.GetInfo(0xc2081bc100, 0x19, 0xc3e200, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/pkg/devicemapper/devmapper.go:540 +0xdc fp=0xc2083c2e00 sp=0xc2083c2da0
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).initDevmapper(0xc208192280, 0xc2081c0001, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:1061 +0xa94 fp=0xc2083c30b8 sp=0xc2083c2e00
github.com/docker/docker/daemon/graphdriver/devmapper.NewDeviceSet(0xc2081bc4a0, 0x1c, 0x1, 0x0, 0x0, 0x0, 0x473b3f, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:1792 +0x4e7 fp=0xc2083c32a0 sp=0xc2083c30b8
github.com/docker/docker/daemon/graphdriver/devmapper.Init(0xc2081bc4a0, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/daemon/graphdriver/devmapper/driver.go:43 +0x172 fp=0xc2083c3368 sp=0xc2083c32a0
github.com/docker/docker/daemon/graphdriver.GetDriver(0xc87350, 0xc, 0xc20802ad20, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/daemon/graphdriver/driver.go:99 +0x1a4 fp=0xc2083c3408 sp=0xc2083c3368
github.com/docker/docker/daemon/graphdriver.New(0xc20802ad20, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/daemon/graphdriver/driver.go:123 +0xa9d fp=0xc2083c3628 sp=0xc2083c3408
github.com/docker/docker/daemon.NewDaemon(0x126f7c0, 0xc20803ea70, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/daemon/daemon.go:733 +0x93d fp=0xc2083c3a10 sp=0xc2083c3628
main.mainDaemon()
        /builddir/build/BUILD/docker-1.7.1/docker/daemon.go:143 +0x82e fp=0xc2083c3bf8 sp=0xc2083c3a10
main.main()
        /builddir/build/BUILD/docker-1.7.1/docker/docker.go:93 +0x6b4 fp=0xc2083c3f98 sp=0xc2083c3bf8
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:63 +0xf3 fp=0xc2083c3fe0 sp=0xc2083c3f98
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2083c3fe8 sp=0xc2083c3fe0

goroutine 5 [syscall]:
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [chan receive]:
github.com/docker/docker/pkg/listenbuffer.(*defaultListener).Accept(0xc20800b4a0, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/pkg/listenbuffer/buffer.go:73 +0xb6
net/http.(*Server).Serve(0xc20819c7e0, 0x7f35a1d8f890, 0xc20800b4a0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/server.go:1728 +0x92
github.com/docker/docker/api/server.(*HttpServer).Serve(0xc20800b9a0, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/api/server/server.go:128 +0x4d
github.com/docker/docker/api/server.func·002(0x7f35a1d8f918, 0xc20800b9a0)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/api/server/server.go:104 +0x40
created by github.com/docker/docker/api/server.(*Server).ServeApi
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/api/server/server.go:108 +0x6ac

goroutine 9 [chan receive]:
github.com/docker/docker/api/server.(*Server).ServeApi(0xc2080d46c0, 0xc208072630, 0x1, 0x1, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/api/server/server.go:113 +0x74f
main.func·003()
        /builddir/build/BUILD/docker-1.7.1/docker/daemon.go:129 +0x5f
created by main.mainDaemon
        /builddir/build/BUILD/docker-1.7.1/docker/daemon.go:135 +0x6b6

goroutine 11 [runnable]:
github.com/docker/docker/daemon.func·021()
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/daemon/debugtrap.go:16
created by github.com/docker/docker/daemon.setupSigusr1Trap
        /builddir/build/BUILD/docker-1.7.1/_build/src/github.com/docker/docker/daemon/debugtrap.go:20 +0x18e
```

**Comment by icecrime** [comment]
Sorry, you seem to be running a host OS which isn't supported.

Please see the [CentOS installation instructions](https://docs.docker.com/engine/installation/linux/centos/):

> ## Prerequisites
> Docker requires a 64-bit installation regardless of your CentOS version. Also, your kernel must be 3.10 at minimum, which CentOS 7 runs.

**Comment by martinko2009** [comment]
Now I have upgrade kernel to 3.10.When I input docker -d, it will be like below:
```
[root@dc1 cpu]# docker -d
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
INFO[0000] [graphdriver] using prior storage driver "devicemapper" 
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1 
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule: iptables failed: iptables -t nat -I POSTROUTING -s 192.168.100.1/24 ! -o docker0 -j MASQUERADE: iptables v1.4.7: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```

Please tell me how i can resolve this,thank you.

**Comment by thaJeztah** [comment]
CentOS 6.x is no longer supported, and upgrading the kernel only may result in unexpected things. Please upgrade to CentOS 7.2, which is a supported platform
