### ISSUE TITLE
makeslice len out of range

### ISSUE THREAD

**Issue by justincormack** [docker/docker#26379]
```
moby:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

I got the following crash restarting Docker for Mac. The only thing I have changed recently is setting the log driver to syslog.

```
time="2016-09-07T16:41:42.749156127Z" level=debug msg="successfully loaded the Root CA: /var/lib/docker/swarm/certificates/swarm-root-ca.crt" 
time="2016-09-07T16:41:42.755656288Z" level=debug msg="successfully loaded the Root CA: /var/lib/docker/swarm/certificates/swarm-root-ca.crt" 
time="2016-09-07T16:41:42.756122579Z" level=debug msg="loaded local CA certificate: /var/lib/docker/swarm/certificates/swarm-root-ca.crt." 
time="2016-09-07T16:41:42.756953246Z" level=debug msg="loaded local TLS credentials: /var/lib/docker/swarm/certificates/swarm-node.crt." 
time="2016-09-07T16:41:42.757152555Z" level=debug msg="Requesting certificate for NodeID: c5fc3to9k9cgiquu90fe33do2" 
time="2016-09-07T16:41:42.780578061Z" level=debug msg="successfully loaded the Root CA: /var/lib/docker/swarm/certificates/swarm-root-ca.crt" 
time="2016-09-07T16:41:42.781744256Z" level=debug msg="(*Agent).run" module=agent 
time="2016-09-07T16:41:42.782194614Z" level=info msg="Listening for connections" addr="[::]:2377" proto=tcp 
time="2016-09-07T16:41:42.782370787Z" level=info msg="Listening for local connections" addr="/var/lib/docker/swarm/control.sock" proto=unix 
2016-09-07 16:41:42.783542 W | wal: ignored file 0.tmp in wal
time="2016-09-07T16:41:42.784673100Z" level=debug msg="(*session).start" module=agent 
panic: runtime error: makeslice: len out of range

goroutine 333 [running]:
panic(0x1b4cca0, 0xc820bc7fd0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/wal.(*decoder).decode(0xc8208ef170, 0xc82093ef70, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/wal/decoder.go:55 +0x142
github.com/coreos/etcd/wal.(*WAL).ReadAll(0xc820411a00, 0xc8209f0080, 0x3a, 0x40, 0xd, 0x71c0f690e9111cf7, 0x1e9, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/wal/wal.go:237 +0x442
github.com/docker/swarmkit/manager/state/raft.(*Node).readWAL(0xc820335200, 0x7f5aae2d3ce0, 0xc820319f80, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/manager/state/raft/storage.go:133 +0x335
github.com/docker/swarmkit/manager/state/raft.(*Node).loadAndStart(0xc820335200, 0x7f5aae2d3ce0, 0xc820319f80, 0xc820303c00, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/manager/state/raft/storage.go:65 +0x3c3
github.com/docker/swarmkit/manager/state/raft.(*Node).JoinAndStart(0xc820335200, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/manager/state/raft/raft.go:218 +0x85
github.com/docker/swarmkit/manager.(*Manager).Run(0xc82041b440, 0x7f5aaec72148, 0xc8200106c8, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/manager/manager.go:518 +0x1515
github.com/docker/swarmkit/agent.(*Node).runManager.func1(0xc82041b440, 0xc820423800)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/agent/node.go:624 +0x64
created by github.com/docker/swarmkit/agent.(*Node).runManager
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/agent/node.go:626 +0x579
```

```
moby:~# cat /etc/docker/daemon.json 
{"storage-driver":"overlay2","log-driver":"syslog"}
```

**Comment by justincormack** [comment]
Reverting the log driver setting fixes the issue apparently.

**Comment by aaronlehmann** [comment]
This is a known issue when trying to load raft state created by Docker master with Docker 1.12.1. See https://github.com/docker/swarmkit/issues/1475. https://github.com/docker/swarmkit/pull/1483 should solve this.

**Comment by justincormack** [comment]
Oh ok, I was probably changing versions when testing stuff...
