### ISSUE TITLE
Create container gives Conflict, while start container gives not found

### ISSUE THREAD

**Issue by pmcq** [docker/docker#26452]
**Output of `docker version`:**

```
Docker version 1.12.1, build 23cf638
```

**Output of `docker info`:**

```
Containers: 436
 Running: 18
 Paused: 0
 Stopped: 418
Images: 14
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1119
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-95-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.45 GiB
Name: ip-172-31-36-253
ID: G3MV:F3LU:S6QL:ZRVK:AD7L:GRJA:7Z4Z:7X7I:XGLX:HH2O:ESH7:OIBY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 127
 Goroutines: 175
 System Time: 2016-09-09T06:09:02.436034568Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
 - AWS EC2 instance
 - Using https://github.com/spotify/docker-client to make calls.  
 - I have also tried using https://github.com/docker-java/docker-java
 - Docker daemon listening on localhost, have tried `unix://` as well, neither seems to help
 - The vast majority of the containers which aren't running are created but not started due to this issue

**Steps to reproduce the issue:**
I haven't been able to recreate the issue with a simple testcase however it very reliable happens within our system with frequent container creates (total number of running containers on the machine is typically around 25)

**Describe the results you received:**
1.  After creating, starting, waiting a number of containers a POST to create container will give a socket timeout in the java client (even with a timeout of 30 seconds)
2.  Issuing a 2nd create (after socket timeout several seconds later) with the same container name gives a `Conflict - name in use`
3.  Issuing a start gives a `Container not found`
4.  Issuing a inspect gives a `Container not found`
5.  After seeing the issue I can manuallly log in and `docker ps` shows a created container
6.  I can `docker start` the created container at a later point in time and executes fine

Simple example without debug output
```
time="2016-09-08T22:57:18.538469039Z" level=error msg="Handler for GET /containers/dock-6e77589c-dfd2-4e08-b7ba-e4a46041f58d/json returned error: No such container: dock-6e77589c-dfd2-4e08-b7ba-e4a46041f58d" 
time="2016-09-08T22:57:19.825856604Z" level=error msg="Handler for POST /containers/create returned error: Conflict. The name \"/dock-6e77589c-dfd2-4e08-b7ba-e4a46041f58d\" is already in use by container d6e1de11bdfc4052770d96e221396358c9d38e9e4ce015779d11aaa3e6ac1d2d. You have to remove (or rename) that container to be able to reuse that name." 
time="2016-09-08T22:57:19.826794593Z" level=error msg="Handler for POST /containers/dock-6e77589c-dfd2-4e08-b7ba-e4a46041f58d/start returned error: No such container: dock-6e77589c-dfd2-4e08-b7ba-e4a46041f58d" 
```

With debug output (note the first line is 44 seconds before the create that got stuck...):
```
time="2016-09-09T02:03:00.890823821Z" level=debug msg="Calling GET /containers/dock-296f7147-edcf-4c73-aa93-6434ef4071e4/json"
time="2016-09-09T02:03:44.052627384Z" level=debug msg="Calling POST /containers/create?name=dock-ea7db429-008d-4e4d-90ec-2192cc1859f1"
time="2016-09-09T02:03:44.052807563Z" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":[\"dock-ea7db429-008d-4e4d-90ec-2192cc1859f1\",\"172.17.0.1:4160\"],\"HostConfig\":{\"Binds\":[\"/algorithmia/container-mounts/dock-ea7db429-008d-4e4d-90ec-2192cc1859f1:/algorithmia:ro\",\"/algorithmia/container-mounts/dock-ea7db429-008d-4e4d-90ec-2192cc1859f1/home:/home/algo\"],\"CpusetCpus\":\"1-7\",\"ExtraHosts\":[\"api.algorithmia.com:172.17.0.1\"],\"NetworkMode\":\"bridge\",\"PortBindings\":{\"9999/tcp\":[{\"HostIp\":\"0.0.0.0\",\"HostPort\":\"31013\"}]}},\"Image\":\"algorithmia/adock:latest\"}"
time="2016-09-09T02:03:49.114466453Z" level=debug msg="Calling POST /containers/create?name=dock-ea7db429-008d-4e4d-90ec-2192cc1859f1"
time="2016-09-09T02:03:49.114595735Z" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":[\"dock-ea7db429-008d-4e4d-90ec-2192cc1859f1\",\"172.17.0.1:4160\"],\"HostConfig\":{\"Binds\":[\"/algorithmia/container-mounts/dock-ea7db429-008d-4e4d-90ec-2192cc1859f1:/algorithmia:ro\",\"/algorithmia/container-mounts/dock-ea7db429-008d-4e4d-90ec-2192cc1859f1/home:/home/algo\"],\"CpusetCpus\":\"1-7\",\"ExtraHosts\":[\"api.algorithmia.com:172.17.0.1\"],\"NetworkMode\":\"bridge\",\"PortBindings\":{\"9999/tcp\":[{\"HostIp\":\"0.0.0.0\",\"HostPort\":\"31013\"}]}},\"Image\":\"algorithmia/adock:latest\"}"
time="2016-09-09T02:03:49.115777839Z" level=error msg="Handler for POST /containers/create returned error: Conflict. The name \"/dock-ea7db429-008d-4e4d-90ec-2192cc1859f1\" is already in use by container 4934675a665f8f2e7766719582e89b6e4254c6bf35564d4c53e6d21084047265. You have to remove (or rename) that container to be able to reuse that name."
time="2016-09-09T02:03:49.120758508Z" level=debug msg="Calling POST /containers/dock-ea7db429-008d-4e4d-90ec-2192cc1859f1/start"
time="2016-09-09T02:03:49.120813436Z" level=error msg="Handler for POST /containers/dock-ea7db429-008d-4e4d-90ec-2192cc1859f1/start returned error: No such container: dock-ea7db429-008d-4e4d-90ec-2192cc1859f1"
```
**Describe the results you expected:**
1. Docker create shouldn't hang 
2. Docker create, start, and get should be consistent in whether they report a container name in use so I could attempt a retry

**Additional information you deem important (e.g. issue happens only occasionally):**
It can happen several times in a minute, and routinely occurs though I haven't been able to correlate it to any certain frequency/number of calls or certain call order.  It does appear that the container creation step is the one that hangs, though it's possible start does at times too.

I've added locks in our java code to ensure that only one thread can be issuing create/start/inspect calls even and it does not seem to help.

Seems similar to this super old issue but I'd assume it's not still this: https://github.com/docker/docker/issues/1319
I thought https://github.com/docker/docker/issues/26251 might have been the issue but do not see anything in the logs related to ports in use

**Comment by pmcq** [comment]
I downgraded to docker 1.11.2 and the problem persists
version:
```Docker version 1.11.2, build b9f10c9```
Info: 
```
Containers: 29
 Running: 11
 Paused: 0
 Stopped: 18
Images: 65
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 302
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-95-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.45 GiB
Name: ip-172-31-43-86
ID: G3MV:F3LU:S6QL:ZRVK:AD7L:GRJA:7Z4Z:7X7I:XGLX:HH2O:ESH7:OIBY
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 71
 Goroutines: 129
 System Time: 2016-09-09T21:44:38.516448807Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
```

**Comment by pmcq** [comment]
For what it's worth when the container creates get stuck I do not see any debug messages like
`Assigning addresses for endpoint dock-e09d7575-4f4a-4846-ad0e-29b7013f503d's interface on network bridge`
or 
`Programming external connectivity on endpoint dock-e09d7575-4f4a-4846-ad0e-29b7013f503d (508e3bc54b01f88ed40c5d5624bd663dabb604beebafc8bb4ee699d4e8b5e244)`
Like I do for successful container creates

**Comment by cpuguy83** [comment]
This looks a lot like #23371, though I'm intrigued by the locking.

When the daemon gets blocked can you send `SIGUSR1` to the daemon process and collect the stack trace from the logs?

**Comment by pmcq** [comment]
Attaching trace here.  Was attempting to create dock-58a98438-6623-48e4-ab75-3b369b2e806a, no response ever came, though there were responses for other calls at that time (some GETs from my logs, not sure about others)
[docker.txt](https://github.com/docker/docker/files/468135/docker.txt)

**Comment by pmcq** [comment]
This is a slight guess, but based on application logging it *might* be the case that an inspect container <id> happens while the create container <id> call was in progress.  However even with application-level  locking to allow only 1 inspect/create/start command this error occurs (though seemingly much less frequently).

**Comment by pmcq** [comment]
Here's another stack trace that might more accurately represent the state when the failures were occurring.  In this example the application-level locking was enabled so only 1 thread could be calling create, start or inspect at the given time (though removes/container exits are definitely happening).

[single-threaded.txt](https://github.com/docker/docker/files/468707/single-threaded.txt)

Don't totally know what I'm looking at but this seems relevant:
```
goroutine 76329 [syscall]:
syscall.Syscall(0x4a, 0x3f, 0x0, 0x0, 0x9c6, 0x52e, 0x70c85f)
    /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Fsync(0x3f, 0x0, 0x0)
    /usr/local/go/src/syscall/zsyscall_linux_amd64.go:492 +0x4a
os.(*File).Sync(0xc821c64010, 0x0, 0x0)
    /usr/local/go/src/os/file_posix.go:121 +0x61
github.com/docker/docker/pkg/ioutils.(*atomicFileWriter).Close(0xc8210c4150, 0x0, 0x0)
    /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/ioutils/fswriters.go:68 +0x92
github.com/docker/docker/container.(*Container).WriteHostConfig(0xc821f0b4a0, 0x0, 0x0)
    /usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:209 +0x210
github.com/docker/docker/container.(*Container).ToDisk(0xc821f0b4a0, 0x0, 0x0)
    /usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:156 +0x228
github.com/docker/docker/daemon.(*Daemon).setHostConfig(0xc8200721a0, 0xc821f0b4a0, 0xc8211f5c00, 0x0, 0x0)
    /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:201 +0x1f3
github.com/docker/docker/daemon.(*Daemon).create(0xc8200721a0, 0xc82261f3cd, 0x29, 0xc822403680, 0xc8211f5c00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/create.go:118 +0x58f
github.com/docker/docker/daemon.(*Daemon).containerCreate(0xc8200721a0, 0xc82261f3cd, 0x29, 0xc822403680, 0xc8211f5c00, 0x0, 0xc820f6d700, 0x100, 0x0, 0x0, ...)
    /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/create.go:55 +0x4c3
github.com/docker/docker/daemon.(*Daemon).ContainerCreate(0xc8200721a0, 0xc82261f3cd, 0x29, 0xc822403680, 0xc8211f5c00, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
    /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/create.go:29 +0xc2
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersCreate(0xc820069940, 0x7f13c7f02db0, 0xc821113230, 0x7f13bc661df8, 0xc822ca3860, 0xc82093da40, 0xc8211131a0, 0x0, 0x0)
    /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:364 +0x3a4
```

```
goroutine 76411 [syscall]:
syscall.Syscall6(0x12, 0x15, 0xc8226ec000, 0x1000, 0x1000, 0x0, 0x0, 0x38, 0x38, 0x0)
    /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.Pwrite(0x15, 0xc8226ec000, 0x1000, 0x1000, 0x1000, 0x7f13c7f02708, 0x0, 0x0)
    /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1389 +0x89
os.(*File).pwrite(0xc821c64040, 0xc8226ec000, 0x1000, 0x1000, 0x1000, 0x1, 0x0, 0x0)
    /usr/local/go/src/os/file_unix.go:275 +0x64
os.(*File).WriteAt(0xc821c64040, 0xc8226ec000, 0x1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/os/file.go:160 +0xcc
os.(*File).WriteAt-fm(0xc8226ec000, 0x1000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
    /usr/src/docker/vendor/src/github.com/boltdb/bolt/db.go:192 +0x56
github.com/boltdb/bolt.(*Tx).writeMeta(0xc82298e620, 0x0, 0x0)
    /usr/src/docker/vendor/src/github.com/boltdb/bolt/tx.go:550 +0x123
github.com/boltdb/bolt.(*Tx).Commit(0xc82298e620, 0x0, 0x0)
    /usr/src/docker/vendor/src/github.com/boltdb/bolt/tx.go:221 +0x735
github.com/boltdb/bolt.(*DB).Update(0xc82185c1e0, 0xc823b530f8, 0x0, 0x0)
    /usr/src/docker/vendor/src/github.com/boltdb/bolt/db.go:602 +0x11d
github.com/docker/libkv/store/boltdb.(*BoltDB).AtomicPut(0xc820204cd0, 0xc821182a10, 0x64, 0xc821a8c0d4, 0xb, 0x40, 0xc8210c4d50, 0x0, 0x0, 0x0, ...)
    /usr/src/docker/vendor/src/github.com/docker/libkv/store/boltdb/boltdb.go:397 +0x253
github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic(0xc8204ae800, 0x7f13c7ebdad8, 0xc8227ab710, 0x0, 0x0)
    /usr/src/docker/vendor/src/github.com/docker/libnetwork/datastore/datastore.go:408 +0x5e9
github.com/docker/libnetwork.(*controller).updateToStore(0xc82025eb40, 0x7f13c7ebdad8, 0xc8227ab710, 0x0, 0x0)
    /usr/src/docker/vendor/src/github.com/docker/libnetwork/store.go:227 +0x1ea
github.com/docker/libnetwork.(*endpointCnt).atomicIncDecEpCnt(0xc8227ab710, 0xc821390300, 0x0, 0x0)
    /usr/src/docker/vendor/src/github.com/docker/libnetwork/endpoint_cnt.go:157 +0x2ae
github.com/docker/libnetwork.(*endpointCnt).DecEndpointCnt(0xc8227ab710, 0x0, 0x0)
    /usr/src/docker/vendor/src/github.com/docker/libnetwork/endpoint_cnt.go:177 +0x32
github.com/docker/libnetwork.(*endpoint).Delete(0xc82184e000, 0x7f13c7f07500, 0x0, 0x0)
    /usr/src/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:760 +0x872
github.com/docker/libnetwork.(*sandbox).delete(0xc822b88960, 0xc820f9f000, 0x0, 0x0)
    /usr/src/docker/vendor/src/github.com/docker/libnetwork/sandbox.go:221 +0xd55
github.com/docker/libnetwork.(*sandbox).Delete(0xc822b88960, 0x0, 0x0)
    /usr/src/docker/vendor/src/github.com/docker/libnetwork/sandbox.go:179 +0x32
github.com/docker/docker/daemon.(*Daemon).releaseNetwork(0xc8200721a0, 0xc8229c41e0)
    /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container_operations.go:758 +0x51c
github.com/docker/docker/daemon.(*Daemon).Cleanup(0xc8200721a0, 0xc8229c41e0)
    /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/start.go:172 +0x53
github.com/docker/docker/daemon.(*Daemon).StateChanged(0xc8200721a0, 0xc822f489c0, 0x40, 0xc820e03244, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:41 +0x629
github.com/docker/docker/libcontainerd.(*container).handleEvent.func1()
    /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:184 +0xab
github.com/docker/docker/libcontainerd.(*queue).append.func1(0xc82160fc00, 0x0, 0xc82157ca20, 0xc82207cde0)
    /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/queue_linux.go:26 +0x47
created by github.com/docker/docker/libcontainerd.(*queue).append
    /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/queue_linux.go:28 +0x1da
```

**Comment by pmcq** [comment]
Wow okay.... after doing some deeper digging it seems like the creation of the container directory is taking a REALLY long time (note: this is on amazon EC2 boxes with EBS volumes, and I'm intentionally running stuff that downloads stuff to the filesystem and uploads a bunch)

Application logs:
```
2016-09-13T16:55:13.829 [pool-10611-thread-1] WARN  timeout trying to create container dock-25685c80-cc50-4a5a-9c83-25c20c33ccf
```

The ps command also hung for a really long time before returning anything:
```
docker ps -a | grep dock-25685c80-cc50-4a5a-9c83-25c2e                                                                       
8f72b63601f3        algorithmia/langserver-single:latest        "/bin/init-langserver"   About a minute ago   Created     dock-25685c80-cc50-4a5a-9c83-25c2e0c33ccf
```

```
# ls --full-time | grep 8f72b63601f3
drwx------ 2 root root 4096 2016-09-13 16:55:57.144123529 +0000 8f72b63601f3850d985e13772de5fa1b01a89d7f29dc9e176d347480ec5ba019
# ls --full-time 8f72b63601f3850d985e13772de5fa1b01a89d7f29dc9e176d347480ec5ba019
total 8
-rw-rw-rw- 1 root root 2460 2016-09-13 16:55:53.364208898 +0000 config.v2.json
-rw-rw-rw- 1 root root 1311 2016-09-13 16:55:53.364208898 +0000 hostconfig.json
```

So there's about 40seconds of delay before the files got written... I guess this isn't a docker issue but have no idea why this might be happening with such absurd delays.

**Comment by pmcq** [comment]
It appears our EBS volumes getting terrible performance is the cause of this issue - resolving as unrelated to docker, apologies.

**Comment by cpuguy83** [comment]
Thanks @pmcq!
