### ISSUE TITLE
Etcd2 panics on restoring from backup

### ISSUE THREAD

**Issue by Seth-Karlo** [docker/docker#26544]
**Description**
I'm attempting to back up my etcd2 cluster to disk and then restore using the --force-new-cluster option. Whenever I try to do this, etcd2 crashes and refuses to start, preventing me from restoring my backup.

**Steps to reproduce the issue:**
1. Use `etcdctl backup` command to back up the `/var/lib/etcd2` directory on a node to disk.
2. Remove the `/var/lib/etcd2/member` directory and copy the backup `member` directory to `/var/lib/etcd2`.
3. Run `/usr/bin/etcd2 --data-dir=/var/lib/etcd2 --force-new-cluster`

**Describe the results you received:**

etcd2 crashes with the following error:

```
/usr/bin/etcd2 --data-dir=/var/lib/etcd2 --force-new-cluster
2016-09-13 18:58:23.224705 I | etcdmain: etcd Version: 2.3.1
2016-09-13 18:58:23.224820 I | etcdmain: Git SHA: 2b67f52
2016-09-13 18:58:23.224872 I | etcdmain: Go Version: go1.5.3
2016-09-13 18:58:23.224921 I | etcdmain: Go OS/Arch: linux/amd64
2016-09-13 18:58:23.224968 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2016-09-13 18:58:23.225096 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-09-13 18:58:23.225667 I | etcdmain: listening for peers on http://localhost:2380
2016-09-13 18:58:23.225831 I | etcdmain: listening for peers on http://localhost:7001
2016-09-13 18:58:23.225991 I | etcdmain: listening for client requests on http://localhost:2379
2016-09-13 18:58:23.226156 I | etcdmain: listening for client requests on http://localhost:4001
2016-09-13 18:58:23.280387 I | etcdserver: recovered store from snapshot at index 780078
2016-09-13 18:58:23.280516 I | etcdserver: name = default
2016-09-13 18:58:23.280566 I | etcdserver: force new cluster
2016-09-13 18:58:23.280618 I | etcdserver: data dir = /var/lib/etcd2
2016-09-13 18:58:23.280667 I | etcdserver: member dir = /var/lib/etcd2/member
2016-09-13 18:58:23.280723 I | etcdserver: heartbeat = 100ms
2016-09-13 18:58:23.280809 I | etcdserver: election = 1000ms
2016-09-13 18:58:23.280874 I | etcdserver: snapshot count = 10000
2016-09-13 18:58:23.280944 I | etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/coreos/etcd/wal.(*decoder).decode(0xc8203f3c80, 0xc82016de98, 0x0, 0x0)
       	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/wal/decoder.go:55 +0x142
github.com/coreos/etcd/wal.(*WAL).ReadAll(0xc8200b8000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
       	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/wal/wal.go:237 +0x214
github.com/coreos/etcd/etcdserver.readWAL(0xc8200ba000, 0x19, 0xbe72e, 0x3, 0x0, 0x0, 0x0, 0xc8200b8000, 0xc8200481c0, 0x0, ...)
       	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/etcdserver/storage.go:87 +0x227
github.com/coreos/etcd/etcdserver.restartAsStandaloneNode(0xc820087180, 0xc8200713b0, 0x29, 0xc82016e950, 0x0, 0x0, 0x0, 0x0)
       	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/etcdserver/raft.go:371 +0x10e
github.com/coreos/etcd/etcdserver.NewServer(0xc820087180, 0xc820087238, 0x0, 0x0)
       	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/etcdserver/server.go:331 +0x3ca6
github.com/coreos/etcd/etcdmain.startEtcd(0xc820089400, 0x0, 0x0, 0x0)
       	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:303 +0x1b44
github.com/coreos/etcd/etcdmain.Main()
       	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:119 +0x212d
main.main()
       	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/main.go:29 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
       	/usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 18 [chan receive]:
github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc8201425a0)
       	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x7c
created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
       	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xc0

goroutine 43 [chan receive]:
github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc8201644e0)
       	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x7c
created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
       	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xc0

goroutine 47 [syscall]:
os/signal.loop()
       	/usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
       	/usr/lib/go/src/os/signal/signal_unix.go:28 +0x37
```

**Describe the results you expected:**

Etcd2 to start up and allow me to reform my cluster.

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 4
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.5.0-coreos-r1
Operating System: CoreOS 1010.5.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.864 GiB
Name: mcppmgmt1-etcd01
ID: PUIK:3LCB:3VZW:Y74G:LHDW:TWZ5:JNTK:GPJQ:LLQF:6KD2:5ETY:2GQE
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CoreOS machines on KVM hypervisors in a private Cloud.

**Comment by LK4D4** [comment]
@aaronlehmann I think it's same downgrade problem as we saw with swarmkit? Could you pls post info from etcd repo and close this if it's unrelated to docker?

**Comment by Seth-Karlo** [comment]
Apologies, I had both docker and etcd repositories open in different tabs and pasted this into the wrong one! Closing.
