### ISSUE TITLE
deadlock in monitor.go

### ISSUE THREAD

**Issue by saiwl** [docker/docker#26561]
**Description**

Docker ps command hangs after the daemon process runs for a few days. Usually many containers has been killed and start on the host. I still cannot reproduce this problem manually. But it happens definitely after daemon runs for a few days. 
**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
wanglu@mesos22.aws.dev:~$ sudo docker info
Containers: 12045
 Running: 29
 Paused: 0
 Stopped: 12016
Images: 50
Server Version: 1.12.0
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.5.0-0.bpo.2-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 14.69 GiB
Name: mesos22
ID: WFEI:YJJD:2XQ3:GQHW:YVQZ:UCPT:NSLJ:KEPN:TDKS:WDZ7:PLSV:IZJN
Docker Root Dir: /data/data/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by saiwl** [comment]
I got the stack dump file. Here is the related part:
```
ngoroutine 776185020 [semacquire, 1400 minutes]:\nsync.runtime_Semacquire(0xc825372fcc)\n\t/usr/local/go/src/runtime/sema.go:47 +0x26\nsync.(*WaitGroup).Wait(0xc825372fc0)\n\t/usr/local/go/src/sync/waitgroup.go:127 +0xb4\ngithub.com/docker/docker/daemon.(*Daemon).StateChanged(0xc8200721a0, 0xc83bcab800, 0x40, 0x1e1cbf0, 0xc, 0x0, 0xc83bcab880, 0x40, 0x0, 0x0, ...)\n\t/go/src/github.com/docker/docker/daemon/monitor.go:68 +0xecc\ngithub.com/docker/docker/libcontainerd.(*container).handleEvent.func2()\n\t/go/src/github.com/docker/docker/libcontainerd/container_linux.go:202 +0x9e\ngithub.com/docker/docker/libcontainerd.(*queue).append.func1(0xc837c09c01, 0xc830b9c060, 0xc83dfcc4c0, 0xc828486480)\n\t/go/src/github.com/docker/docker/libcontainerd/queue_linux.go:26 +0x47\ncreated by github.com/docker/docker/libcontainerd.(*queue).append\n\t/go/src/github.com/docker/docker/libcontainerd/queue_linux.go:28 +0x1da\n\n```
The related code shows below:

```
case libcontainerd.StateExitProcess:
		c.Lock()
		defer c.Unlock()
		if execConfig := c.ExecCommands.Get(e.ProcessID); execConfig != nil {
			ec := int(e.ExitCode)
			execConfig.ExitCode = &ec
			execConfig.Running = false
			execConfig.Wait()
			if err := execConfig.CloseStreams(); err != nil {
				logrus.Errorf("%s: %s", c.ID, err)
			}

			// remove the exec command from the container's store only and not the
			// daemon's store so that the exec command can be inspected.
			c.ExecCommands.Delete(execConfig.ID)
		} else {
			logrus.Warnf("Ignoring StateExitProcess for %v but no exec command found", e)
		}
```
It stucks at the execConfig.Wait()

**Comment by tonistiigi** [comment]
@mlaventure Is this dupe of #26403 ?

@saiwl Are the exec process you are starting similar to what is described in #26403 (leaking children)?

**Comment by mlaventure** [comment]
It would depends on the type exec commands indeed.

@saiwl could you tell us what kind of exec you are running?

**Comment by saiwl** [comment]
I'm not sure about this. I just found the problem, without knowing what has caused it. Can you tell me what type of exec commands can produce this kind of problem? I can do some check.
@mlaventure

**Comment by saiwl** [comment]
I read about #26403, and reproduced the problem. But I checked the stack trace, it likely did not block in monitor.go. Still not sure where the deadlock is in #26403.
@tonistiigi

**Comment by mlaventure** [comment]
@saiwl any exec that would spawn a child that holds onto the initial process IOs

For instance, this will block the exec until `sleep` terminates:
```
$ docker exec -t <CID> sh
# sleep 1200 &
# exit
<hang in there until sleep exits>
```

This will not block it:
```
$ docker exec -t <CID> sh
# sleep 1200 <&- 1>&- 2>&-  &
# exit
```

@saiwl could you also provide us with the full stacktrace?

Thanks

**Comment by saiwl** [comment]
[docker.txt](https://github.com/docker/docker/files/474940/docker.txt)

Here's the full stacktrace. The format is a little chaotic.

**Comment by mlaventure** [comment]
@saiwl thanks, nothing `sed` can't solve :)

**Comment by tonistiigi** [comment]
@saiwl Can you estimate how many containers were running when you took that stacktrace? Trying to figure out if there is a leak.

**Comment by saiwl** [comment]
There are about 20 running containers, but hundreds of exited containers. What kind of leak can there be?
@tonistiigi
