### ISSUE TITLE
Container start hangs when attaching an NFS volume w/ no host NFS support

### ISSUE THREAD

**Issue by pdevine** [docker/docker#26612]
**Description**

If you create an NFS volume and then start a new container with the volume attached it will hang if the host kernel doesn't have NFS support.

**Steps to reproduce the issue:**
1. install Ubuntu (or Centos/RHEL) _without_ the nfs-common (nfs-util package for rpm based systems)

2. create an NFS volume (in my case I used the docker engine API with the settings:
     {
        "type": "nfs",
        "o": "addr=<ip address>,rw,sync,actime=0",
        "device": ":/<export path>",
     }

3. run the container with something like "$ docker run -it -v <my nfs volume>:/storage alpine sh"

**Describe the results you received:**

This just hangs for a long time (in my case, almost 30 minutes), however, you'll eventually get:

docker: Error response from daemon: connection timed out.

I also got this from journalctl:
Sep 15 14:27:33 clone12 dockerd[804]: time="2016-09-15T14:27:33.556725909-07:00" level=error msg="Handler for POST /v1.24/containers/create returned error: No such image: alpine:latest"
Sep 15 14:54:00 clone12 dockerd[804]: time="2016-09-15T14:54:00.594369062-07:00" level=error msg="Handler for POST /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/star
Sep 15 14:54:03 clone12 dockerd[804]: time="2016-09-15T14:54:03.694641606-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.848936589-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.849874636-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.851699714-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.852812583-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.853867226-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.856148212-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.857114403-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.858953450-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.862937065-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.864448312-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.864909330-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.865148071-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.865373410-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.865595739-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.865830012-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:05 clone12 dockerd[804]: time="2016-09-15T14:54:05.866059743-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.325933081-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.326472593-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.326676521-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.326960283-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.327168133-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.327344528-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.364525996-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.385039337-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.889867398-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.895392615-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.895828773-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.896140217-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.896437998-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.896745959-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.916582957-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.916936928-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.917146646-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.917380497-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 
Sep 15 14:54:06 clone12 dockerd[804]: time="2016-09-15T14:54:06.918721495-07:00" level=error msg="Handler for GET /v1.24/containers/34eafab48863d277989a993e86b2f201e28c33e76baa214d30a9864807e20973/json 

**Describe the results you expected:**

If you run this with nfs-common / nfs-utils, it will just work as expected.  In the failure case, I would expect it to fail immediately and return something like when you attempt to mount the file system manually.  This is the output you would get for mount:

$ sudo mount -t nfs <ip address>:/<export path> /mnt/foo
mount: wrong fs type, bad option, bad superblock on clone11.bombitron.com:/exports,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

The key here being that it returns immediately instead of hanging.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 12
 Running: 10
 Paused: 0
 Stopped: 2
Images: 19
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 72
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 975.1 MiB
Name: clone12
ID: OUXK:BOAF:7XQR:JBFB:7DS4:2RSQ:CTXW:C6TX:KSUG:ZE4X:MS4T:AZUJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster Store: etcd://192.168.36.251:12379
Cluster Advertise: 192.168.36.251:12376
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This was running in VMware Fusion, but I was seeing the same thing on EC2.

**Comment by tonistiigi** [comment]
Seems to be blocked on syscall:

```
goroutine 195 [syscall]:
syscall.Syscall6(0xa5, 0xc820ccbac0, 0xc820761b30, 0xc820ccba9c, 0x0, 0xc820cc1fe0,
Sep 20 23:22:02 tonis-ubuntu-2gb-sfo1-01 dockerd[10917]: 0x0, 0xc820cc1fe0, 0x11, 0x11)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.mount(0xc820d2d430, 0xd, 0xc820cf33e0, 0x21, 0xc820d2d447, 0x3, 0x0, 0xc820cc1fe0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:224 +0x18f
syscall.Mount(0xc820d2d430, 0xd, 0xc820cf33e0, 0x21, 0xc820d2d447, 0x3, 0x0, 0xc821106fc0, 0x10, 0x0, ...)
	/usr/local/go/src/syscall/syscall_linux.go:806 +0x151
github.com/docker/docker/pkg/mount.mount(0xc820d2d430, 0xd, 0xc820cf33e0, 0x21, 0xc820d2d447, 0x3, 0x0, 0xc821106fc0, 0x10, 0x0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/mount/mounter_linux.go:8 +0x9c
github.com/docker/docker/pkg/mount.ForceMount(0xc820d2d430, 0xd, 0xc820cf33e0, 0x21, 0xc820d2d447, 0x3, 0xc821106fc0, 0x13, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/mount/mount.go:49 +0xbb
github.com/docker/docker/pkg/mount.Mount(0xc820d2d430, 0xd, 0xc820cf33e0, 0x21, 0xc820d2d447, 0x3, 0xc821106fc0, 0x13, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/mount/mount.go:40 +0x100
github.com/docker/docker/volume/local.(*localVolume).mount(0xc820d04d70, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/volume/local/local_unix.go:68 +0xf1
github.com/docker/docker/volume/local.(*localVolume).Mount(0xc820d04d70, 0xc820d916c0, 0x40, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/volume/local/local.go:306 +0xa1
github.com/docker/docker/volume/store.(*volumeWrapper).Mount(0xc820cf38f0, 0xc820d916c0, 0x40, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:2 +0x82
github.com/docker/docker/volume.(*MountPoint).Setup(0xc8210d6870, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/volume/volume.go:114 +0xd9
github.com/docker/docker/daemon.(*Daemon).setupMounts(0xc8203549c0, 0xc820e17e00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/volumes_unix.go:31 +0x73a
github.com/docker/docker/daemon.(*Daemon).createSpec(0xc8203549c0, 0xc82
Sep 20 23:22:02 tonis-ubuntu-2gb-sfo1-01 dockerd[10917]: 0e17e00, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/oci_linux.go:660 +0xe6c
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc8203549c0, 0xc820e17e00, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/start.go:130 +0x25a
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc8203549c0, 0xc8203635f7, 0x40, 0x0, 0xc820d3fc01, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/start.go:80 +0x5e9
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStart(0xc82021a340, 0x7f1ca6759630, 0xc820b71a70, 0x7f1ca673c5f0, 0xc820ca3ee0, 0xc820c7fa40, 0xc820b71920, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:155 +0x184
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStart)-fm(0x7f1ca6759630, 0xc820b71a70, 0x7f1ca673c5f0, 0xc820ca3ee0, 0xc820c7fa40, 0xc820b71920, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:60 +0x74
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f1ca6759630, 0xc820b71a70, 0x7f1ca673c5f0, 0xc820ca3ee0, 0xc820c7fa40, 0xc820b71920, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x7f1ca6759630, 0xc820b719e0, 0x7f1ca673c5f0, 0xc820ca3ee0, 0xc820c7fa40, 0xc820b71920, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x68e
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f1ca673c5f0, 0xc820ca3ee0, 0xc820c7fa40)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x138
net/http.HandlerFunc.ServeHTTP(0xc820402100, 0x7f1ca673c5f0, 0xc820ca3ee0, 0xc820c7fa40)
	/usr/local/go/src/n
Sep 20 23:22:02 tonis-ubuntu-2gb-sfo1-01 dockerd[10917]: et/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82024a1e0, 0x7f1ca673c5f0, 0xc820ca3ee0, 0xc820c7fa40)
	/usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8207f9940, 0x7f1ca673c5f0, 0xc820ca3ee0, 0xc820c7fa40)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc8202a7400, 0x7f1ca673c5f0, 0xc820ca3ee0, 0xc820c7fa40)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820da3280)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

**Comment by pdevine** [comment]
You pretty much just have to reboot the host when you hit this and then remember to install the appropriate nfs package.  Not super ideal.

**Comment by cpuguy83** [comment]
@pdevine This sounds like a kernel bug. Seems odd for it to hang like this.

**Comment by pdevine** [comment]
@cpuguy83 maybe could timeout faster than 30 minutes?

**Comment by thaJeztah** [comment]
@pdevine this still an issue?
