### ISSUE TITLE
Panic when restart dockerd, seems related to swarmkit

### ISSUE THREAD

**Issue by allencloud** [docker/docker#26638]
**Description**

When I purged docker-engine, and install it again via `apt-get install -q docker-engine=1.12.1-0~trusty`, panic happened like the dockerd's log.
Got dockerd's log:
```
time="2016-09-16T09:49:29.313385576-07:00" level=error msg="controller resolution failed" module=worker task.id=3f8xwtduxy21l04i3m4g3h0ly
time="2016-09-16T09:49:29.313510319-07:00" level=error msg="failed to start taskManager" error="invalid bind mount source, source path not found: /datanotexist" module=worker
time="2016-09-16T09:49:29.313680887-07:00" level=error msg="controller resolution failed" module=worker task.id=3fdssji67blivs3ufgxaoho5t
time="2016-09-16T09:49:29.313791479-07:00" level=error msg="failed to start taskManager" error="invalid bind mount source, source path not found: /datanotexist" module=worker
time="2016-09-16T09:49:29.314016046-07:00" level=error msg="controller resolution failed" module=worker task.id=3fjaah8jsx611f638zziq86di
time="2016-09-16T09:49:29.314128182-07:00" level=error msg="failed to start taskManager" error="invalid bind mount source, source path not found: /datanotexist" module=worker
time="2016-09-16T09:49:29.314270243-07:00" level=error msg="controller resolution failed" module=worker task.id=3g20mf9zuy2u6wuy2hmuev7fv
time="2016-09-16T09:49:29.314378047-07:00" level=error msg="failed to start taskManager" error="invalid bind mount source, source path not found: /datanotexist" module=worker
time="2016-09-16T09:49:29.314543876-07:00" level=error msg="controller resolution failed" module=worker task.id=3gts1dxvcxkhhhusz4xq70oet
time="2016-09-16T09:49:29.314664455-07:00" level=error msg="failed to start taskManager" error="invalid bind mount source, source path not found: /datanotexist" module=worker
time="2016-09-16T09:49:29.314815536-07:00" level=error msg="controller resolution failed" module=worker task.id=3hd7iwwtcv02lg4i5dvuy1fro
panic: runtime error: makeslice: len out of range

goroutine 161 [running]:
panic(0x1a619a0, 0xc820884050)
       	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/wal.(*decoder).decode(0xc820862f60, 0xc820882f70, 0x0, 0x0)
       	/usr/src/docker/vendor/src/github.com/coreos/etcd/wal/decoder.go:55 +0x142
github.com/coreos/etcd/wal.(*WAL).ReadAll(0xc820450f70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
       	/usr/src/docker/vendor/src/github.com/coreos/etcd/wal/wal.go:237 +0x214
github.com/docker/swarmkit/manager/state/raft.(*Node).readWAL(0xc8202fbb00, 0x7fbbc31c0928, 0xc82085e8c0, 0x0, 0x0, 0x0, 0x0)
       	/usr/src/docker/vendor/src/github.com/docker/swarmkit/manager/state/raft/storage.go:133 +0x335
github.com/docker/swarmkit/manager/state/raft.(*Node).loadAndStart(0xc8202fbb00, 0x7fbbc31c0928, 0xc82085e8c0, 0xc820862700, 0x0, 0x0)
       	/usr/src/docker/vendor/src/github.com/docker/swarmkit/manager/state/raft/storage.go:65 +0x3c3
github.com/docker/swarmkit/manager/state/raft.(*Node).JoinAndStart(0xc8202fbb00, 0x0, 0x0)
       	/usr/src/docker/vendor/src/github.com/docker/swarmkit/manager/state/raft/raft.go:218 +0x85
github.com/docker/swarmkit/manager.(*Manager).Run(0xc82058b5f0, 0x7fbbc31b2940, 0xc82000e7f0, 0x0, 0x0)
       	/usr/src/docker/vendor/src/github.com/docker/swarmkit/manager/manager.go:518 +0x1515
github.com/docker/swarmkit/agent.(*Node).runManager.func1(0xc82058b5f0, 0xc820864720)
       	/usr/src/docker/vendor/src/github.com/docker/swarmkit/agent/node.go:624 +0x64
created by github.com/docker/swarmkit/agent.(*Node).runManager
       	/usr/src/docker/vendor/src/github.com/docker/swarmkit/agent/node.go:626 +0x579
/var/run/docker.sock is up
time="2016-09-16T09:49:29.377466275-07:00" level=info msg="libcontainerd: new containerd process, pid: 10565"
time="2016-09-16T09:49:29.473608173-07:00" level=info msg="[graphdriver] using prior storage driver \"aufs\""
time="2016-09-16T09:49:29.536570841-07:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-09-16T09:49:29.537014316-07:00" level=warning msg="Your kernel does not support swap memory limit."
time="2016-09-16T09:49:29.537316194-07:00" level=warning msg="mountpoint for pids not found"
time="2016-09-16T09:49:29.537865555-07:00" level=info msg="Loading containers: start."
..time="2016-09-16T09:49:29.544685790-07:00" level=info msg="Firewalld running: false"
time="2016-09-16T09:49:29.660913323-07:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
```

**Output of `docker version`:**

```
root@10-11-26-89:~/gocode/src/github.com/docker/docker# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
none(since dockerd does not work)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by allencloud** [comment]
When I `rm -rf /var/lib/docker/swarm` and restart dockerd, no panic happens and dockerd starts to work.

**Comment by tonistiigi** [comment]
@allencloud Did you run master before? I think the wal format changed so it can't be downgraded.

cc @aaronlehmann

**Comment by allencloud** [comment]
@tonistiigi 
Yes, I have run master before to test my code.

**Comment by aaronlehmann** [comment]
Yes, see docker/swarmkit#1483

@docker/core-swarmkit-maintainers: Please review that PR. The longer this goes unfixed, the more problems it will create for people.

**Comment by thaJeztah** [comment]
@aaronlehmann is a fix for this needed in 1.12.2 to allow downgrading, or is that for 1.13?

**Comment by aaronlehmann** [comment]
> @aaronlehmann is a fix for this needed in 1.12.2 to allow downgrading, or is that for 1.13?
> 

It's for 1.13.

**Comment by aluzzardi** [comment]
docker/swarmkit#1483 has been merged so this should be fixed in 1.13.

@aaronlehmann @allencloud Closing this down - please re-open if you disagree.

**Comment by allencloud** [comment]
Thanks a lot. @aluzzardi @aaronlehmann @thaJeztah

**Comment by thaJeztah** [comment]
@aluzzardi was that change vendored already in this repository?
