### ISSUE TITLE
[Windows] Unable to start: The VM couldn't get an IP address after 60 tries

### ISSUE THREAD

**Issue by ryan413** [docker/docker#26934]
**Description**

**Steps to reproduce the issue:**
1. right click on docker icon in taskbar
2. select switch to linux containers
3.

**Describe the results you received:**
error message:
Unable to start: The VM couldn't get an IP address after 60 tries
at <ScriptBlock>, <No file>: line 340
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

log:
[18:22:00.830][HyperV         ][Info   ] Hyper-V is running
[18:22:00.831][HyperV         ][Info   ] Create
[18:22:00.831][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[18:22:01.208][HyperV         ][Info   ] Using existing Switch: DockerNAT
[18:22:01.380][HyperV         ][Info   ] Using existing Switch IP address
[18:22:01.405][HyperV         ][Info   ] Using existing: MobyLinuxVM (state = Running)
[18:22:01.405][HyperV         ][Info   ] Stop
[18:22:01.405][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[18:22:01.435][HyperV         ][Info   ] Stopping VM MobyLinuxVM...
[18:22:03.211][HyperV         ][Info   ] Turn Off VM ...
[18:22:03.223][HyperV         ][Info   ] VM MobyLinuxVM killed. Waiting for state to change
[18:22:07.233][HyperV         ][Info   ] Killed VM MobyLinuxVM is off
[18:22:07.247][VpnKit         ][Info   ] Killing existing com.docker.slirp with PID 24276
[18:22:07.254][DataKit        ][Info   ] Killing existing com.docker.db with PID 23324
[18:22:07.257][HyperVGuids    ][Info   ] Installing GUIDs...
[18:22:07.257][HyperVGuids    ][Info   ] GUIDs installed
[18:22:07.257][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[18:22:08.134][Firewall       ][Info   ] Ports are opened
[18:22:08.135][HyperV         ][Info   ] Create
[18:22:08.136][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[18:22:08.415][HyperV         ][Info   ] Using existing Switch: DockerNAT
[18:22:08.458][HyperV         ][Info   ] Using existing Switch IP address
[18:22:08.475][HyperV         ][Info   ] Using existing: MobyLinuxVM (state = Off)
[18:22:08.683][HyperV         ][Info   ] Setting MobyLinuxVM vm CPUs to 2 and Memory to 2048 MB
[18:22:08.689][DataKit        ][Info   ] Starting...
[18:22:08.689][PowerShell     ][Info   ] Run script...
[18:22:08.702][DataKit        ][Info   ] Started
[18:22:08.706][VpnKit         ][Info   ] Starting...
[18:22:08.706][PowerShell     ][Info   ] Run script...
[18:22:08.720][VpnKit         ][Info   ] Started
[18:22:08.720][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[18:22:08.721][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[18:22:08.721][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[18:22:08.722][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[18:22:08.722][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[18:22:08.723][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[],"debug":false}
[18:22:08.723][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[18:22:08.724][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[18:22:08.747][DataKit        ][Info   ] 
[18:22:08.747][DataKit        ][Info   ] +4527us    Datakit  Starting com.docker.db.exe 09081b4 ...
[18:22:08.757][VpnKit         ][Info   ] com.docker.slirp.exe: Logging to stdout (stdout:true DEBUG:false)
[18:22:08.758][VpnKit         ][Info   ] com.docker.slirp.exe: Setting handler to ignore all SIGPIPE signals
[18:22:08.758][VpnKit         ][Info   ] com.docker.slirp.exe: vpnkit version %VERSION% with hostnet version local %HOSTNET_PINNED% uwt version 0.0.3 hvsock version 0.10.0 %HVSOCK_PINNED%
[18:22:08.758][VpnKit         ][Info   ] com.docker.slirp.exe: starting port_forwarding port_control_url:hyperv-connect://923316ef-b35e-4a1c-9933-3fdb60a0a107 max_connections:None vsock_path:
[18:22:08.759][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to 923316ef-b35e-4a1c-9933-3fdb60a0a107:0B95756A-9985-48AD-9470-78E060895BE7
[18:22:08.759][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://923316ef-b35e-4a1c-9933-3fdb60a0a107
[18:22:08.763][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to 923316ef-b35e-4a1c-9933-3fdb60a0a107:30D48B34-7D27-4B0B-AAAF-BBBED334DD59
[18:22:08.764][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://923316ef-b35e-4a1c-9933-3fdb60a0a107
[18:22:08.764][VpnKit         ][Info   ] com.docker.slirp.exe: hosts file has bindings for 
[18:22:09.699][Database       ][Info   ] Successfully wrote 8 value(s)
[18:22:09.699][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/exclude
[18:22:09.700][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/http
[18:22:09.700][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/https
[18:22:09.700][DataKit        ][Info   ] 
[18:22:09.701][DataKit        ][Info   ] +958078us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[18:22:09.873][Database       ][Info   ] Successfully removed 3 value(s)
[18:22:09.874][DataKit        ][Info   ] 
[18:22:09.874][DataKit        ][Info   ] +1131776us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[18:22:09.889][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/ssl/certs/ca-certificates.crt=C:\Windows\TEMP\tmp5544.tmp
[18:22:10.167][DataKit        ][Info   ] 
[18:22:10.167][DataKit        ][Info   ] +1424829us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[18:22:10.167][Database       ][Info   ] Successfully wrote value
[18:22:10.168][Database       ][Info   ] Writing com.docker.driver.amd64-linux/slirp/dns=nameserver 8.8.8.8
[18:22:10.440][DataKit        ][Info   ] 
[18:22:10.440][DataKit        ][Info   ] +1697680us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[18:22:10.440][Database       ][Info   ] Successfully wrote 1 value(s)
[18:22:10.441][HyperV         ][Info   ] Start
[18:22:10.441][PowerShell     ][Info   ] Run script with parameters: -Start True...
[18:22:10.456][HyperV         ][Info   ] Starting VM MobyLinuxVM...
[18:22:11.317][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:12.338][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:13.349][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:14.530][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:15.542][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:16.587][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:17.601][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:18.619][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:19.815][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:20.830][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:21.872][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:22.885][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:23.899][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:25.091][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:26.105][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:27.204][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:28.222][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:29.236][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:30.458][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:31.470][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:32.570][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:33.583][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:34.597][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:35.807][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:36.819][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:37.864][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:38.889][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:39.907][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:41.153][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:42.167][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:43.219][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:44.233][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:45.252][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:46.469][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:47.481][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:48.530][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:49.544][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:50.557][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:51.749][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:52.760][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:53.802][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:54.814][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:55.826][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:57.006][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:58.017][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:59.054][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:00.068][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:01.080][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:02.269][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:03.283][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:04.320][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:05.332][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:06.344][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:07.506][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:08.519][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:09.560][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:10.570][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:11.581][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:12.851][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:23:13.870][NamedPipeServer][Error  ] Unable to execute Start: Unable to start: The VM couldn't get an IP address after 60 tries
at <ScriptBlock>, <No file>: line 340    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[18:23:13.873][NamedPipeClient][Error  ] Unable to send Start: Unable to start: The VM couldn't get an IP address after 60 tries
at <ScriptBlock>, <No file>: line 340
[18:23:13.874][Notifications  ][Error  ] Unable to start: The VM couldn't get an IP address after 60 tries
at <ScriptBlock>, <No file>: line 340
[18:23:13.883][Program        ][Info   ] Sending Bugsnag report a831e1ef-e9c4-4aed-92b9-e6140d8e12ed...
[18:23:15.926][Program        ][Info   ] Bugsnag report a831e1ef-e9c4-4aed-92b9-e6140d8e12ed sent
[18:23:15.929][NamedPipeClient][Info   ] Sending DownloadVmLogs()...
[18:23:15.930][NamedPipeServer][Info   ] DownloadVmLogs()
[18:23:15.931][PowerShell     ][Info   ] Run script...

**Describe the results you expected:**
for docker to start

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      windows/amd64
 Experimental: true
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: The system cannot find the file specified.

```

**Output of `docker info`:**

```
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: open //./pipe/docker_engine: The system cannot find the file specified.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

tried setting dns 8.8.8.8, running on domain, had working before reimaged computer on non-domain computer

**Comment by justincormack** [comment]
Please could you report Docker for Windows specific issues in https://github.com/docker/for-win/issues - this is for specific issues in the Docker engine, and the people here will not be able to help you with these issues. You may find this issue has already been reported.
