### ISSUE TITLE
docker doesn't build images on macOS Sierra 

### ISSUE THREAD

**Issue by dangreen** [docker/docker#26992]
**Description**

After upgrading to Sierra docker some time  just freezes:

```
leadbean(new-landing*)$ docker -D --log-level=info build -t leadbean .
DEBU[0000] Trusting 1 certs                             
DEBU[0000] Skipping excluded path: .dockerignore        
DEBU[0000] Skipping excluded path: .git                 
DEBU[0000] Skipping excluded path: .gitignore           
DEBU[0000] Skipping excluded path: .gitmodules          
DEBU[0000] Skipping excluded path: .tmp                 
DEBU[0000] Skipping excluded path: Dockerfile           
DEBU[0000] Skipping excluded path: Procfile             
DEBU[0000] Skipping excluded path: circle.yml  
[freeze]   
```

Some times crushes with errors:

```
leadbean(new-landing*)$ docker -D --log-level=info build -t leadbean .
DEBU[0000] Trusting 1 certs                             
DEBU[0000] Skipping excluded path: .dockerignore        
DEBU[0000] Skipping excluded path: .git                 
DEBU[0000] Skipping excluded path: .gitignore           
DEBU[0000] Skipping excluded path: .gitmodules          
DEBU[0000] Skipping excluded path: .tmp                 
DEBU[0000] Skipping excluded path: Dockerfile           
DEBU[0000] Skipping excluded path: Procfile             
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x1991d5750 pc=0x40ce4c5]

goroutine 22 [running]:
runtime.throw(0x49eb920, 0x2a)
    /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820024600 sp=0xc8200245e8
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc820024650 sp=0xc820024600
runtime/internal/atomic.Load64(0x1991d5750, 0x1991d5752d2ec)
    /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0xc820024658 sp=0xc820024650
runtime.lfstackpop(0x4d16d48, 0x4024403)
    /usr/local/go/src/runtime/lfstack.go:38 +0x6d fp=0xc820024690 sp=0xc820024658
runtime.getempty(0x67, 0x0)
    /usr/local/go/src/runtime/mgcwork.go:341 +0x3b fp=0xc8200246c0 sp=0xc820024690
runtime.(*gcWork).init(0xc82001dc20)
    /usr/local/go/src/runtime/mgcwork.go:100 +0x53 fp=0xc8200246d8 sp=0xc8200246c0
runtime.(*gcWork).tryGet(0xc82001dc20, 0x1)
    /usr/local/go/src/runtime/mgcwork.go:141 +0x38 fp=0xc820024708 sp=0xc8200246d8
runtime.gcDrain(0xc82001dc20, 0x5)
    /usr/local/go/src/runtime/mgcmark.go:833 +0x22a fp=0xc820024740 sp=0xc820024708
runtime.gcBgMarkWorker(0xc82001ca00)
    /usr/local/go/src/runtime/mgc.go:1435 +0x583 fp=0xc8200247b8 sp=0xc820024740
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200247c0 sp=0xc8200247b8
created by runtime.gcBgMarkStartWorkers
    /usr/local/go/src/runtime/mgc.go:1330 +0x92

goroutine 1 [runnable]:
regexp/syntax.(*parser).push(0xc82034c420, 0xc820448f50, 0xc820448f50)
    /usr/local/go/src/regexp/syntax/parse.go:139 +0x197
regexp/syntax.(*parser).literal(0xc82034c420, 0x44)
    /usr/local/go/src/regexp/syntax/parse.go:210 +0x4a
regexp/syntax.Parse(0xc8201acf70, 0xc, 0x40100d4, 0xc8205246a8, 0x0, 0x0)
    /usr/local/go/src/regexp/syntax/parse.go:729 +0x680
regexp.compile(0xc8201acf70, 0xc, 0x40000d4, 0x0, 0x0, 0x0)
    /usr/local/go/src/regexp/regexp.go:164 +0x5d
regexp.Compile(0xc8201acf70, 0xc, 0xc820524698, 0x0, 0x0)
    /usr/local/go/src/regexp/regexp.go:129 +0x43
regexp.MatchString(0xc8201acf70, 0xc, 0xc820355be0, 0x17, 0x1, 0x0, 0x0)
    /usr/local/go/src/regexp/regexp.go:434 +0x3d
github.com/docker/docker/pkg/fileutils.regexpMatch(0xc82033def0, 0xa, 0xc820355be0, 0x17, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/pkg/fileutils/fileutils.go:209 +0xa71
github.com/docker/docker/pkg/fileutils.OptimizedMatches(0xc820355be0, 0x17, 0xc82002b000, 0x18, 0x20, 0xc820357800, 0x18, 0x20, 0x20, 0x0, ...)
    /go/src/github.com/docker/docker/pkg/fileutils/fileutils.go:98 +0x1e1
github.com/docker/docker/pkg/fileutils.Matches(0xc820355be0, 0x17, 0xc82002b000, 0x18, 0x20, 0x17, 0x0, 0x0)
    /go/src/github.com/docker/docker/pkg/fileutils/fileutils.go:76 +0x1a7
github.com/docker/docker/builder.ValidateContextDirectory.func1(0xc820355bc0, 0x37, 0x6251970, 0xc820347110, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/builder/context.go:45 +0x2d0
path/filepath.walk(0xc820355bc0, 0x37, 0x6251970, 0xc820347110, 0xc8203818c0, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:349 +0x80
path/filepath.walk(0xc820349a70, 0x2c, 0x6251970, 0xc82032eea0, 0xc8203818c0, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0xc8201b01e0, 0x23, 0x6251970, 0xc820347380, 0xc8203818c0, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0xc820381890, 0x1f, 0x6251970, 0xc8203a24e0, 0xc8203818c0, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:374 +0x4fc
path/filepath.Walk(0xc820381890, 0x1f, 0xc8203818c0, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:396 +0xe1
github.com/docker/docker/builder.ValidateContextDirectory(0xc820384d00, 0x1f, 0xc820307000, 0x18, 0x20, 0x0, 0x0)
    /go/src/github.com/docker/docker/builder/context.go:68 +0x10b
github.com/docker/docker/api/client/image.runBuild(0xc820096510, 0x7fff5fbff92d, 0x1, 0x0, 0x0, 0xc820333120, 0x4a623b0, 0x4d35240, 0x0, 0x0, ...)
    /go/src/github.com/docker/docker/api/client/image/build.go:174 +0xb62
github.com/docker/docker/api/client/image.NewBuildCommand.func1(0xc82033e480, 0xc820381590, 0x1, 0x3, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/client/image/build.go:75 +0x9c
github.com/spf13/cobra.(*Command).execute(0xc82033e480, 0xc820381500, 0x3, 0x3, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:593 +0x6fe
github.com/spf13/cobra.(*Command).ExecuteC(0xc820063b00, 0xc82033e480, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:683 +0x55c
github.com/spf13/cobra.(*Command).Execute(0xc820063b00, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:642 +0x2d
github.com/docker/docker/cli/cobraadaptor.CobraAdaptor.run(0xc820063b00, 0xc820096510, 0x7fff5fbff91b, 0x5, 0xc820078040, 0x3, 0x3, 0x0, 0x0)
    /go/src/github.com/docker/docker/cli/cobraadaptor/adaptor.go:118 +0x25f
github.com/docker/docker/cli/cobraadaptor.CobraAdaptor.Command.func1(0xc820078040, 0x3, 0x3, 0x0, 0x0)
    /go/src/github.com/docker/docker/cli/cobraadaptor/adaptor.go:126 +0x8c
github.com/docker/docker/cli.(*Cli).Run(0xc820348480, 0xc820078030, 0x4, 0x4, 0x0, 0x0)
    /go/src/github.com/docker/docker/cli/cli.go:81 +0x34b
main.main()
    /go/src/github.com/docker/docker/cmd/docker/docker.go:72 +0x599

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
    /usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

```
leadbean(new-landing*)$ docker -D build -t leadbean .
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x401357b]

runtime stack:
runtime.throw(0x49eb920, 0x2a)
    /usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x4d1c780)
    /usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x4d1c780, 0x4, 0x42, 0x624ed68)
    /usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
    /usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbffa48)
    /usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x4d1c780, 0x4, 0x10000000042, 0x401321f)
    /usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x4d1f730, 0x0)
    /usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x4d1f730, 0xc820082170)
    /usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x4d79960, 0x42, 0xc820082140)
    /usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
    /usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x4d16e00)
    /usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
    /usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
    /usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc8201fa460 sp=0xc8201fa458
runtime.mallocgc(0x8000, 0x468f780, 0x1, 0xc8203ef800)
    /usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc8201fa538 sp=0xc8201fa460
runtime.newarray(0x468f780, 0x2000, 0xc8203ef800)
    /usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc8201fa578 sp=0xc8201fa538
runtime.makeslice(0x4673f00, 0xc, 0x2000, 0x0, 0x0, 0x0)
    /usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc8201fa5c8 sp=0xc8201fa578
regexp.(*bitState).reset(0xc8203d37a0, 0xd, 0x0)
    /usr/local/go/src/regexp/backtrack.go:87 +0x101 fp=0xc8201fa648 sp=0xc8201fa5c8
regexp.(*machine).backtrack(0xc8203e2360, 0x6252198, 0xc8203e2438, 0x0, 0xd, 0x0, 0xc8200e1600)
    /usr/local/go/src/regexp/backtrack.go:324 +0x106 fp=0xc8201fa6c0 sp=0xc8201fa648
regexp.(*Regexp).doExecute(0xc8203d88c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc820350e60, 0xd, 0x0, 0x0, ...)
    /usr/local/go/src/regexp/exec.go:449 +0x423 fp=0xc8201fa820 sp=0xc8201fa6c0
regexp.(*Regexp).MatchString(0xc8203d88c0, 0xc820350e60, 0xd, 0x0)
    /usr/local/go/src/regexp/regexp.go:411 +0x67 fp=0xc8201fa890 sp=0xc8201fa820
regexp.MatchString(0xc82037b8c0, 0x1e, 0xc820350e60, 0xd, 0x1, 0x0, 0x0)
    /usr/local/go/src/regexp/regexp.go:438 +0x83 fp=0xc8201fa8c0 sp=0xc8201fa890
github.com/docker/docker/pkg/fileutils.regexpMatch(0xc820339f40, 0x16, 0xc820350e60, 0xd, 0xc820347101, 0x0, 0x0)
    /go/src/github.com/docker/docker/pkg/fileutils/fileutils.go:209 +0xa71 fp=0xc8201faa28 sp=0xc8201fa8c0
github.com/docker/docker/pkg/fileutils.OptimizedMatches(0xc820350e60, 0xd, 0xc82030d200, 0x18, 0x20, 0xc82037c000, 0x18, 0x20, 0x20, 0x0, ...)
    /go/src/github.com/docker/docker/pkg/fileutils/fileutils.go:98 +0x1e1 fp=0xc8201faba0 sp=0xc8201faa28
github.com/docker/docker/pkg/fileutils.Matches(0xc820350e60, 0xd, 0xc82030d200, 0x18, 0x20, 0xd, 0x0, 0x0)
    /go/src/github.com/docker/docker/pkg/fileutils/fileutils.go:76 +0x1a7 fp=0xc8201fac30 sp=0xc8201faba0
github.com/docker/docker/builder.ValidateContextDirectory.func1(0xc820350e40, 0x2d, 0x6251d88, 0xc8203575f0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/builder/context.go:45 +0x2d0 fp=0xc8201fad20 sp=0xc8201fac30
path/filepath.walk(0xc820350e40, 0x2d, 0x6251d88, 0xc8203575f0, 0xc820350db0, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:349 +0x80 fp=0xc8201fae58 sp=0xc8201fad20
path/filepath.walk(0xc820350d80, 0x1f, 0x6251d88, 0xc820357520, 0xc820350db0, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8201faf90 sp=0xc8201fae58
path/filepath.Walk(0xc820350d80, 0x1f, 0xc820350db0, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:396 +0xe1 fp=0xc8201faff8 sp=0xc8201faf90
github.com/docker/docker/builder.ValidateContextDirectory(0xc820339d00, 0x1f, 0xc82030d000, 0x18, 0x20, 0x0, 0x0)
    /go/src/github.com/docker/docker/builder/context.go:68 +0x10b fp=0xc8201fb058 sp=0xc8201faff8
github.com/docker/docker/api/client/image.runBuild(0xc8200a0510, 0x7fff5fbffd34, 0x1, 0x0, 0x0, 0xc820339240, 0x4a623b0, 0x4d35240, 0x0, 0x0, ...)
    /go/src/github.com/docker/docker/api/client/image/build.go:174 +0xb62 fp=0xc8201fb7b8 sp=0xc8201fb058
github.com/docker/docker/api/client/image.NewBuildCommand.func1(0xc820348240, 0xc820350a80, 0x1, 0x3, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/client/image/build.go:75 +0x9c fp=0xc8201fb8d8 sp=0xc8201fb7b8
github.com/spf13/cobra.(*Command).execute(0xc820348240, 0xc8203509f0, 0x3, 0x3, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:593 +0x6fe fp=0xc8201fba00 sp=0xc8201fb8d8
github.com/spf13/cobra.(*Command).ExecuteC(0xc8200a38c0, 0xc820348240, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:683 +0x55c fp=0xc8201fbb10 sp=0xc8201fba00
github.com/spf13/cobra.(*Command).Execute(0xc8200a38c0, 0x0, 0x0)
    /go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:642 +0x2d fp=0xc8201fbb38 sp=0xc8201fbb10
github.com/docker/docker/cli/cobraadaptor.CobraAdaptor.run(0xc8200a38c0, 0xc8200a0510, 0x7fff5fbffd22, 0x5, 0xc82006e090, 0x3, 0x3, 0x0, 0x0)
    /go/src/github.com/docker/docker/cli/cobraadaptor/adaptor.go:118 +0x25f fp=0xc8201fbbe0 sp=0xc8201fbb38
github.com/docker/docker/cli/cobraadaptor.CobraAdaptor.Command.func1(0xc82006e090, 0x3, 0x3, 0x0, 0x0)
    /go/src/github.com/docker/docker/cli/cobraadaptor/adaptor.go:126 +0x8c fp=0xc8201fbc50 sp=0xc8201fbbe0
github.com/docker/docker/cli.(*Cli).Run(0xc820350480, 0xc82006e080, 0x4, 0x4, 0x0, 0x0)
    /go/src/github.com/docker/docker/cli/cli.go:81 +0x34b fp=0xc8201fbcd8 sp=0xc8201fbc50
main.main()
    /go/src/github.com/docker/docker/cmd/docker/docker.go:72 +0x599 fp=0xc8201fbf00 sp=0xc8201fbcd8
runtime.main()
    /usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc8201fbf50 sp=0xc8201fbf00
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8201fbf58 sp=0xc8201fbf50

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
    /usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 42
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 37
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.16-boot2docker
Operating System: Boot2Docker 1.12.0 (TCL 7.2); HEAD : e030bab - Fri Jul 29 00:29:14 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: VCT2:EFVA:PREM:GO22:A77O:P5ZO:IMZA:3REW:Q4CU:M7ZK:P4U3:W2QT
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 23
 System Time: 2016-09-28T18:58:31.312292706Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Comment by dangreen** [comment]
`sudo launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist` helps me

**Comment by thaJeztah** [comment]
This is a known issue due to changes in Sierra introduced after 1.12.0; first of all, make sure to fully update your docker toolbox (docker 1.12.1 was released with various fixes https://github.com/docker/toolbox/releases/tag/v1.12.1).

However, I don't think that version ships with the required changes (the bug is in Go, not in Docker); you can obtain a client binary that works with MacOS Sierra here; https://github.com/docker/docker/releases/tag/v1.12.2-rc1, it's a release candidate of 1.12.2 (which will be released soon).

**Comment by justincormack** [comment]
You can also download Docker for Mac and use the docker client from that, you should be able to find  it under `/Applications/Docker` even if it is not installed.

**Comment by thaJeztah** [comment]
Actually, docker toolbox 1.12.2-rc1 was released; https://github.com/docker/toolbox/releases/tag/v1.12.2-rc1

**Comment by justincormack** [comment]
Toolbox 1.12.3 is out. Closing this issue as this should be resolved, let us know if there are any other issues.
