### ISSUE TITLE
Docker daemon crashed upon swarm --force-new-cluster command

### ISSUE THREAD

**Issue by rogaha** [docker/docker#27023]
**Description**

I was trying to create a new cluster based on a existing one. 

```
rogaha@Robertos-MacBook-Pro:~/development/rogaha/docker-hackaton/data-processing-pipeline$ docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
6ayjzi4j68yiz54yacq4u9hek    node3     Ready   Active
6yi4i7c3u9030tamntqnqfsg0 *  master1   Ready   Active        Reachable
9slvcbqb9q4km7is0mt9slqfh    node1     Ready   Active
c5gqm7m90r6yq4zc31larqrg8    node2     Ready   Active
elk3egxngmlxxk08hr97cij9v    master2   Ready   Active        Leader
```

**Steps to reproduce the issue:**
1.  docker swarm init --force-new-cluster --advertise-addr 192.168.99.101

**Describe the results you received:**
An error occurred trying to connect: Post https://192.168.99.101:2376/v1.24/swarm/init: EOF

**logs**
```
time="2016-09-29T13:57:18.231455930Z" level=debug msg="(*session).listen" module=agent session.id=e4xc419p40igymldmuqy4nw94
time="2016-09-29T13:57:18.231506981Z" level=error msg="closing session after fatal error" error="rpc error: code = 3 desc = session invalid" module=agent
time="2016-09-29T13:57:18.231555520Z" level=error msg="failed reporting status to agent" error="rpc error: code = 3 desc = session invalid" module=agent
time="2016-09-29T13:57:18.231589190Z" level=debug msg="(*Agent).UpdateTaskStatus" module=agent task.id=d164y1zsp4n80mk1scfym3s9g
time="2016-09-29T13:57:18.231686019Z" level=debug msg="agent: registered" module=agent
time="2016-09-29T13:57:18.231700002Z" level=debug msg="agent: rebuild session" module=agent
time="2016-09-29T13:57:18.231709829Z" level=debug msg="(*Agent).run exited" module=agent
panic: invalid argument to Int63n

goroutine 1163 [running]:
panic(0x17c4600, 0xc8222aa3c0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
math/rand.(*Rand).Int63n(0xc82000e2b0, 0x0, 0x1)
	/usr/local/go/src/math/rand/rand.go:64 +0x79
math/rand.Int63n(0x0, 0x1f91590)
	/usr/local/go/src/math/rand/rand.go:203 +0x2d
github.com/docker/swarmkit/agent.(*Agent).run(0xc820cb32d0, 0x7fbbd49c6af8, 0xc8214c5650)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/agent/agent.go:204 +0x1376
created by github.com/docker/swarmkit/agent.(*Agent).Start
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/agent/agent.go:81 +0x37d
```
**Describe the results you expected:**
new cluster created with the old state.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      darwin/amd64
 Experimental: true
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.2-rc1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: active
 NodeID: elk3egxngmlxxk08hr97cij9v
 Error: rpc error: code = 4 desc = context deadline exceeded
 Is Manager: true
 ClusterID:
 Managers: 0
 Nodes: 0
 Orchestration:
  Task History Retention Limit: 0
 Raft:
  Snapshot Interval: 0
  Heartbeat Tick: 0
  Election Tick: 0
 Dispatcher:
  Heartbeat Period: Less than a second
 CA Configuration:
  Expiry Duration: Less than a second
 Node Address: 192.168.99.104
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.22-boot2docker
Operating System: Boot2Docker 1.12.2-rc1-experimental (TCL 7.2); HEAD : a59c9e4 - Wed Sep 28 20:03:50 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: master2
ID: QLFN:3QDG:KLCE:YOZW:DLPH:LZSK:74XB:OEWV:TIEP:5DIA:7OR5:CEV3
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 38
 Goroutines: 98
 System Time: 2016-09-29T14:03:24.66945495Z
 EventsListeners: 2
Username: rogaha
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rogaha** [comment]
It seems to be related to https://github.com/docker/docker/issues/25431

**Comment by tonistiigi** [comment]
I think this was fixed with #26538 https://github.com/docker/docker/commit/eeceb0ccc8318ecbf577147363666b959959450e#diff-4427575eb49ec9e8ff03aa5647e56890R218

**Comment by rogaha** [comment]
Awesome, I'll test it with the current master (aka `1.13.0-dev`). Thanks for the heads up @tonistiigi

**Comment by rogaha** [comment]
It seems to be fixed now.

**Comment by rogaha** [comment]
Closing

**Comment by aaronlehmann** [comment]
ping @stevvooe: I see that we added an `if backoff > 0` check in https://github.com/docker/swarmkit/pull/1374, but this check doesn't exist in 1.12.x. Should we add a check in 1.12.2 to fix the panic?
