### ISSUE TITLE
#26843 causes a Windows daemon crash on docker cp

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#27050]
@anusha-ragunathan @cpuguy83 

Investigating why, but after this #26843 was merged, the following steps cause the goroutine handling the docker cp to crash while holding the container lock, effectively causing the daemon to become unresponsive.

Repro:

```
E:\go\src\github.com\docker\docker> docker run -d -v c:\dockerlog:c:\dockerlog nanoserver cmd.exe "/c echo test > c:\
output.txt & ping 127.0.0.1 -t"
f221886f21b3a862d35f96df33ac6f4d5dffa924c8eb2e251df5399f70fbc05e
PS E:\go\src\github.com\docker\docker> docker cp f2:c:\output.txt c:\output.txt
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/containers/f2/archive?path=c%3A%2Foutput.txt: EOF
```

And the daemon call-stack
```
2016-09-29 15:18:51.222355 I | http: panic serving //./pipe/docker_engine: runtime error: slice bounds out of range
goroutine 68 [running]:
net/http.(*conn).serve.func1(0xc042228380)
        C:/Go/src/net/http/server.go:1491 +0x131
panic(0x15ec020, 0xc04200a0d0)
        C:/Go/src/runtime/panic.go:458 +0x251
syscall.Readlink(0xc0420fb200, 0x3a, 0xc042159080, 0x80, 0x80, 0x0, 0x0, 0x0)
        C:/Go/src/syscall/syscall_windows.go:1031 +0x3a9
os.Readlink(0xc0420fb200, 0x3a, 0x1ee0300, 0xc04222faa0, 0x0, 0x0)
        C:/Go/src/os/file_posix.go:21 +0x94
github.com/docker/docker/pkg/symlink.evalSymlinksInScope(0x0, 0x0, 0xc0420fb1c0, 0x30, 0x0, 0x0, 0x0, 0x0)
        e:/go/src/github.com/docker/docker/pkg/symlink/fs.go:122 +0x816
github.com/docker/docker/pkg/symlink.FollowSymlinkInScope(0xc0420fb140, 0x3a, 0xc0420fb1c0, 0x30, 0x0, 0x0, 0x0, 0x0)
        e:/go/src/github.com/docker/docker/pkg/symlink/fs.go:30 +0x21c
github.com/docker/docker/container.(*Container).GetResourcePath(0xc0420de9c0, 0xc04227074d, 0xc, 0x0, 0x0, 0x0, 0x0)
        e:/go/src/github.com/docker/docker/container/container.go:262 +0x1a1
github.com/docker/docker/container.(*Container).UnmountVolumes(0xc0420de9c0, 0x1, 0xc042785240, 0x0, 0x0)
        e:/go/src/github.com/docker/docker/container/container_windows.go:58 +0x14d
github.com/docker/docker/daemon.(*Daemon).containerArchivePath.func3(0x0, 0x0)
        e:/go/src/github.com/docker/docker/daemon/archive.go:160 +0xd3
github.com/docker/docker/pkg/ioutils.(*readCloserWrapper).Close(0xc0424c3480, 0xc042261590, 0xd)
        e:/go/src/github.com/docker/docker/pkg/ioutils/readers.go:17 +0x32
github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersArchive(0xc0424b4780, 0x1edc8e0, 0xc04208dec0, 0x1ed93e0, 0xc0423efba0, 0xc0423acd20, 0xc04208db90, 0x0, 0x0)
        e:/go/src/github.com/docker/docker/api/server/router/container/copy.go:108 +0x37b
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersArchive)-fm(0x1edc8e0, 0xc04208dec0, 0x1ed93e0, 0xc0423efba0, 0xc0423acd20, 0xc04208db90, 0x0, 0x0)
        e:/go/src/github.com/docker/docker/api/server/router/container/container.go:53 +0xb2
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x1edc8e0, 0xc04208dec0, 0x1ed93e0, 0xc0423efba0, 0xc0423acd20, 0xc04208db90, 0x0, 0x0)
        e:/go/src/github.com/docker/docker/api/server/middleware/version.go:49 +0x871
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x1edc8e0, 0xc04208dcb0, 0x1ed93e0, 0xc0423efba0, 0xc0423acd20, 0xc04208db90, 0x0, 0x0)
        e:/go/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x4ac
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x1edc860, 0xc04203eb90, 0x1ed93e0, 0xc0423efba0, 0xc0423acd20, 0xc04208db90, 0x0, 0x0)
        e:/go/src/github.com/docker/docker/pkg/authorization/middleware.go:34 +0xd4
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x1ed93e0, 0xc0423efba0, 0xc0423acd20)
        e:/go/src/github.com/docker/docker/api/server/server.go:139 +0x106
net/http.HandlerFunc.ServeHTTP(0xc04242acc0, 0x1ed93e0, 0xc0423efba0, 0xc0423acd20)
        C:/Go/src/net/http/server.go:1726 +0x4b
github.com/gorilla/mux.(*Router).ServeHTTP(0xc04214eeb0, 0x1ed93e0, 0xc0423efba0, 0xc0423acd20)
        e:/go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:103 +0x333
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc0421a7380, 0x1ed93e0, 0xc0423efba0, 0xc0423acd20)
        e:/go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x84
net/http.serverHandler.ServeHTTP(0xc04232c880, 0x1ed93e0, 0xc0423efba0, 0xc0423acd20)
        C:/Go/src/net/http/server.go:2202 +0x84
net/http.(*conn).serve(0xc042228380, 0x1edade0, 0xc0420faa80)
        C:/Go/src/net/http/server.go:1579 +0x4be
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2293 +0x454
```

**Comment by jhowardmsft** [comment]
Understood. Will submit a PR tomorrow
