### ISSUE TITLE
Fails to install on windows 10

### ISSUE THREAD

**Issue by simonm3** [docker/docker#27255]
Downloaded the installer. Ran it. Get this error message.

Unable to start: 'MobyLinuxVM' failed to start.
at <ScriptBlock>, <No file>: line 340
   at Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Core.Backend.BackendClient.Start(Settings settings)
   at Docker.Actions.DoStart(Settings settings, Boolean showWelcomeWindow)
   at Docker.Actions.<>c__DisplayClass13_0.<Start>b__0()
   at Docker.Core.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

**Comment by simonm3** [comment]
Here is the log if that helps:

[15:59:27.455][Program        ][Info   ] Version: 1.12.1-stable
[15:59:27.520][Program        ][Info   ] Starting on: 10/10/2016 3:59:27 PM
[15:59:27.524][Program        ][Info   ] Resources: C:\Program Files\Docker\Docker\Resources
[15:59:27.528][Program        ][Info   ] OS: Windows 10 Pro
[15:59:27.531][Program        ][Info   ] Edition: Professional
[15:59:27.534][Program        ][Info   ] Id: 1607
[15:59:27.537][Program        ][Info   ] Build: 14393
[15:59:27.540][Program        ][Info   ] BuildLabName: 14393.206.amd64fre.rs1_release.160915-0644
[15:59:27.544][Program        ][Info   ] Sha1: 995236d98308333f27e3a36505dd761ac9c843f3
[15:59:27.547][Program        ][Info   ] You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:59:28.428][TrackingStatus ][Info   ] Crash report and usage statistics are enabled
[15:59:28.475][Analytics      ][Info   ] Usage Statistic: appLaunched
[15:59:28.559][NamedPipeClient][Info   ] Sending Version()...
[15:59:28.581][NamedPipeClient][Info   ] Received response for Version
[15:59:28.581][Analytics      ][Info   ] Usage Statistic: heartbeat
[15:58:41.595][BackendServer  ][Info   ] Started
[15:59:28.575][NamedPipeServer][Info   ] Version()
[15:59:28.578][NamedPipeServer][Info   ] Version done.
[15:59:29.462][Notifications  ][Info   ] Docker is starting...
[15:59:29.462][Updater        ][Info   ] Checking for updates on channel Stable...
[15:59:29.493][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[15:59:29.504][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[15:59:29.511][HyperVGuids    ][Info   ] Installing GUIDs...
[15:59:29.517][HyperVGuids    ][Info   ] GUIDs installed
[15:59:29.557][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[15:59:29.931][Updater        ][Info   ] Local build 7135 is as good as the remote 7135 on channel Stable
[15:59:31.266][Firewall       ][Info   ] Ports are opened
[15:59:31.273][HyperV         ][Info   ] Create
[15:59:31.305][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[15:59:34.540][HyperV         ][Info   ] Creating Switch: DockerNAT...
[15:59:36.832][HyperV         ][Info   ] Switch created.
[15:59:37.937][HyperV         ][Info   ] Set IP address on switch
[15:59:39.279][HyperV         ][Info   ] Creating dynamic VHD: C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[15:59:40.388][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[15:59:43.316][HyperV         ][Info   ] VM created.
[15:59:43.325][DataKit        ][Info   ] Starting...
[15:59:43.331][PowerShell     ][Info   ] Run script...
[15:59:43.409][DataKit        ][Info   ] Started
[15:59:43.417][VpnKit         ][Info   ] Starting...
[15:59:43.421][PowerShell     ][Info   ] Run script...
[15:59:43.452][VpnKit         ][Info   ] Started
[15:59:43.470][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[15:59:43.473][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[15:59:43.476][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[15:59:43.479][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[15:59:43.482][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[15:59:43.485][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[],"debug":false}
[15:59:43.488][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[15:59:43.493][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[15:59:43.880][DataKit        ][Info   ] 
[15:59:43.891][DataKit        ][Info   ] +6954us    Datakit  Starting com.docker.db.exe 09081b4 ...
[15:59:45.235][DataKit        ][Info   ] 
[15:59:45.235][DataKit        ][Info   ] +1364063us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[15:59:45.837][VpnKit         ][Info   ] com.docker.slirp.exe: Logging to stdout (stdout:true DEBUG:false)
[15:59:45.837][VpnKit         ][Info   ] com.docker.slirp.exe: Setting handler to ignore all SIGPIPE signals
[15:59:45.837][VpnKit         ][Info   ] com.docker.slirp.exe: vpnkit version %VERSION% with hostnet version local %HOSTNET_PINNED% uwt version 0.0.3 hvsock version 0.10.0 %HVSOCK_PINNED%
[15:59:45.837][VpnKit         ][Info   ] com.docker.slirp.exe: starting port_forwarding port_control_url:hyperv-connect://379e6795-ad94-4c70-942a-ea9f78f5232a max_connections:None vsock_path:
[15:59:45.853][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to 379e6795-ad94-4c70-942a-ea9f78f5232a:0B95756A-9985-48AD-9470-78E060895BE7
[15:59:45.853][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://379e6795-ad94-4c70-942a-ea9f78f5232a
[15:59:45.853][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to 379e6795-ad94-4c70-942a-ea9f78f5232a:30D48B34-7D27-4B0B-AAAF-BBBED334DD59
[15:59:45.853][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://379e6795-ad94-4c70-942a-ea9f78f5232a
[15:59:45.853][VpnKit         ][Info   ] com.docker.slirp.exe: hosts file has bindings for 
[15:59:46.839][Database       ][Info   ] Successfully wrote 8 value(s)
[15:59:46.839][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/exclude
[15:59:46.839][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/http
[15:59:46.839][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/https
[15:59:47.386][Database       ][Info   ] Successfully removed 3 value(s)
[15:59:47.401][DataKit        ][Info   ] 
[15:59:47.409][DataKit        ][Info   ] +3530078us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[15:59:47.456][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/ssl/certs/ca-certificates.crt=C:\WINDOWS\TEMP\tmp2AFE.tmp
[15:59:48.470][Database       ][Info   ] Successfully wrote value
[15:59:48.473][DataKit        ][Info   ] 
[15:59:48.484][DataKit        ][Info   ] +4601643us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[15:59:48.490][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[15:59:48.729][Database       ][Info   ] Writing com.docker.driver.amd64-linux/slirp/dns=nameserver 192.168.1.1
nameserver 192.168.1.1
search lan
[15:59:49.943][Database       ][Info   ] Successfully wrote 1 value(s)
[15:59:49.947][HyperV         ][Info   ] Start
[15:59:49.952][PowerShell     ][Info   ] Run script with parameters: -Start True...
[15:59:49.956][DataKit        ][Info   ] 
[15:59:49.966][DataKit        ][Info   ] +6084314us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[15:59:49.992][HyperV         ][Info   ] Starting VM MobyLinuxVM...
[16:00:04.202][HyperV         ][Info   ] Hyper-V is running
[16:00:04.202][HyperV         ][Info   ] Create
[16:00:04.202][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[16:00:04.584][HyperV         ][Info   ] Using existing Switch: DockerNAT
[16:00:04.650][HyperV         ][Info   ] Using existing Switch IP address
[16:00:04.703][HyperV         ][Info   ] Using existing: MobyLinuxVM (state = Off)
[16:00:04.988][HyperV         ][Info   ] Setting MobyLinuxVM vm CPUs to 2 and Memory to 2048 MB
[16:00:04.988][HyperV         ][Info   ] Stop
[16:00:04.988][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[16:00:05.035][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[16:00:05.051][VpnKit         ][Info   ] Killing existing com.docker.slirp with PID 5536
[16:00:05.066][DataKit        ][Info   ] Killing existing com.docker.db with PID 8948
[16:00:05.066][HyperVGuids    ][Info   ] Installing GUIDs...
[16:00:05.066][HyperVGuids    ][Info   ] GUIDs installed
[16:00:05.089][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[16:00:07.302][Firewall       ][Info   ] Ports are opened
[16:00:07.317][HyperV         ][Info   ] Create
[16:00:07.317][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[16:00:07.417][HyperV         ][Info   ] Using existing Switch: DockerNAT
[16:00:07.480][HyperV         ][Info   ] Using existing Switch IP address
[16:00:07.502][HyperV         ][Info   ] Using existing: MobyLinuxVM (state = Off)
[16:00:07.533][HyperV         ][Info   ] Setting MobyLinuxVM vm CPUs to 2 and Memory to 2048 MB
[16:00:07.533][DataKit        ][Info   ] Starting...
[16:00:07.533][PowerShell     ][Info   ] Run script...
[16:00:07.565][DataKit        ][Info   ] Started
[16:00:07.565][VpnKit         ][Info   ] Starting...
[16:00:07.565][PowerShell     ][Info   ] Run script...
[16:00:07.602][VpnKit         ][Info   ] Started
[16:00:07.618][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[16:00:07.649][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[16:00:07.665][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[16:00:07.665][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[16:00:07.680][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[16:00:07.700][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[],"debug":false}
[16:00:07.708][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[16:00:07.713][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[16:00:07.874][DataKit        ][Info   ] 
[16:00:07.879][DataKit        ][Info   ] +6749us    Datakit  Starting com.docker.db.exe 09081b4 ...
[16:00:07.891][VpnKit         ][Info   ] com.docker.slirp.exe: Logging to stdout (stdout:true DEBUG:false)
[16:00:07.895][VpnKit         ][Info   ] com.docker.slirp.exe: Setting handler to ignore all SIGPIPE signals
[16:00:07.898][VpnKit         ][Info   ] com.docker.slirp.exe: vpnkit version %VERSION% with hostnet version local %HOSTNET_PINNED% uwt version 0.0.3 hvsock version 0.10.0 %HVSOCK_PINNED%
[16:00:07.902][VpnKit         ][Info   ] com.docker.slirp.exe: starting port_forwarding port_control_url:hyperv-connect://379e6795-ad94-4c70-942a-ea9f78f5232a max_connections:None vsock_path:
[16:00:07.906][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to 379e6795-ad94-4c70-942a-ea9f78f5232a:0B95756A-9985-48AD-9470-78E060895BE7
[16:00:07.909][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://379e6795-ad94-4c70-942a-ea9f78f5232a
[16:00:07.913][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to 379e6795-ad94-4c70-942a-ea9f78f5232a:30D48B34-7D27-4B0B-AAAF-BBBED334DD59
[16:00:07.916][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://379e6795-ad94-4c70-942a-ea9f78f5232a
[16:00:07.920][VpnKit         ][Info   ] com.docker.slirp.exe: hosts file has bindings for 
[16:00:09.058][Database       ][Info   ] Successfully wrote 8 value(s)
[16:00:09.058][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/exclude
[16:00:09.058][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/http
[16:00:09.073][DataKit        ][Info   ] 
[16:00:09.073][DataKit        ][Info   ] +1206387us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[16:00:09.073][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/https
[16:00:09.660][Database       ][Info   ] Successfully removed 3 value(s)
[16:00:09.676][DataKit        ][Info   ] 
[16:00:09.676][DataKit        ][Info   ] +1808625us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[16:00:09.707][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/ssl/certs/ca-certificates.crt=C:\WINDOWS\TEMP\tmp8208.tmp
[16:00:10.390][Database       ][Info   ] Successfully wrote value
[16:00:10.390][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[16:00:10.406][DataKit        ][Info   ] 
[16:00:10.406][DataKit        ][Info   ] +2540223us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[16:00:10.475][Database       ][Info   ] Writing com.docker.driver.amd64-linux/slirp/dns=nameserver 192.168.1.1
nameserver 192.168.1.1
search lan
[16:00:11.105][Database       ][Info   ] Successfully wrote 1 value(s)
[16:00:11.105][HyperV         ][Info   ] Start
[16:00:11.105][PowerShell     ][Info   ] Run script with parameters: -Start True...
[16:00:11.121][DataKit        ][Info   ] 
[16:00:11.121][DataKit        ][Info   ] +3257222us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[16:00:11.145][HyperV         ][Info   ] Starting VM MobyLinuxVM...
[16:00:11.507][NamedPipeServer][Error  ] Unable to execute Start: Unable to start: 'MobyLinuxVM' failed to start.
at <ScriptBlock>, <No file>: line 340    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[16:00:11.507][NamedPipeClient][Error  ] Unable to send Start: Unable to start: 'MobyLinuxVM' failed to start.
at <ScriptBlock>, <No file>: line 340
[16:00:11.522][Notifications  ][Error  ] Unable to start: 'MobyLinuxVM' failed to start.
at <ScriptBlock>, <No file>: line 340
[16:02:22.744][ErrorReportWindow][Info   ] Open logs

**Comment by justincormack** [comment]
Can you open an issue on the Docker for Windows support area https://github.com/docker/for-win/issues as they will be able to help you, we cannot help with issues specific to the installer here, only with core Docker engine issues.
