### ISSUE TITLE
Bad map state in aufs.go

### ISSUE THREAD

**Issue by dubglan** [docker/docker#27309]
We're hitting intermittent issue on docker 1.10.3 with aufs storage. When we attempt to start container, run command fails with 125 return code crashing in aufs.(*Driver).Get(), aufs.go:309. So far we were not able to reproduce the issue.

**Docker log:**
```
goroutine 4885 [running]:
runtime.throw(0x166ade0, 0xd)
	/usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xc82118ee00 sp=0xc82118ede8
runtime.evacuate(0x1184880, 0xc8206ad650, 0x14)
	/usr/local/go/src/runtime/hashmap.go:825 +0x3b1 fp=0xc82118eec0 sp=0xc82118ee00
runtime.growWork(0x1184880, 0xc8206ad650, 0x33)
	/usr/local/go/src/runtime/hashmap.go:795 +0x83 fp=0xc82118eee0 sp=0xc82118eec0
runtime.mapassign1(0x1184880, 0xc8206ad650, 0xc82118f030, 0xc82118efd8)
	/usr/local/go/src/runtime/hashmap.go:433 +0x176 fp=0xc82118ef88 sp=0xc82118eee0
github.com/docker/docker/daemon/graphdriver/aufs.(*Driver).Get(0xc82022dd10, 0xc821282100, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/aufs/aufs.go:309 +0x2be fp=0xc82118f0e8 sp=0xc82118ef88
github.com/docker/docker/layer.(*mountedLayer).Mount(0xc820088a50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/layer/mounted_layer.go:53 +0x8e fp=0xc82118f148 sp=0xc82118f0e8
github.com/docker/docker/layer.(*referencedRWLayer).Mount(0xc820cc4700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/layer/mounted_layer.go:135 +0x105 fp=0xc82118f1a8 sp=0xc82118f148
github.com/docker/docker/daemon.(*Daemon).Mount(0xc820001c80, 0xc820cfae00, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:894 +0x94 fp=0xc82118f2d0 sp=0xc82118f1a8
github.com/docker/docker/daemon.(*Daemon).conditionalMountOnStart(0xc820001c80, 0xc820cfae00, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon_unix.go:954 +0x37 fp=0xc82118f2f8 sp=0xc82118f2d0
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc820001c80, 0xc820cfae00, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/start.go:108 +0x159 fp=0xc82118f438 sp=0xc82118f2f8
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc820001c80, 0xc82023feb7, 0x40, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/start.go:69 +0x4e3 fp=0xc82118f560 sp=0xc82118f438
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStart(0xc8206b24b0, 0x7f3c8ea6b648, 0xc8209664b0, 0x7f3c8eada5f8, 0xc82177c4d0, 0xc820d02000, 0xc8209661b0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:182 +0x114 fp=0xc82118f600 sp=0xc82118f560
...
```
[docker.log.txt](https://github.com/docker/docker/files/523213/docker.log.txt)

**Output of `docker version`:**

```
Client:
 Version:      1.10.3-cs3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   6df5588
 Built:        Wed Apr 27 00:59:22 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3-cs3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   6df5588
 Built:        Wed Apr 27 00:59:22 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
This is captured on VM created from the same image, we were not able to collect info on the machine where the original failure happened.
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 1.10.3-cs3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 141
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.14.17.nn0-server
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.67 GiB
Name: colibri
ID: 4TWA:REWS:235S:LG45:GOYQ:IKTQ:YFU5:QLWV:HAMN:Q2EL:LE45:6OH6
WARNING: No swap limit support
```

**Comment by tonistiigi** [comment]
Thank you for the report. The code where this panic happens has been removed in `v1.12` so the issue shouldn't appear anymore. I can see a map race in `v1.10.3` codebase that probably caused this.
