### ISSUE TITLE
AuthZ plugin broken in experimental (panic)

### ISSUE THREAD

**Issue by runcom** [docker/docker#27485]
```
docker version                                            
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   84b6051-unsupported
 Built:        Tue Oct 18 10:33:44 2016
 OS/Arch:      linux/amd64
 Experimental: true
Error response from daemon: plugin test-plugin failed with error: legacy plugin: Plugin does not implement the requested driver

$ docker version                                                               
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   84b6051-unsupported
 Built:        Tue Oct 18 10:33:44 2016
 OS/Arch:      linux/amd64
 Experimental: true
error during connect: Get https://127.0.0.1:8080/v1.25/version: EOF
```
The plugin is an "old" v1 plugin and I cannot find document about this new "v2". The plugin just replies with Allow: true so not sure why it first fails and then panic.
Here is the panic:
```
Oct 18 10:48:53 localhost.localdomain docker[3609]: time="2016-10-18T10:48:53.714397869+02:00" level=debug msg="Calling GET /v1.25/version"
Oct 18 10:48:53 localhost.localdomain docker[3609]: time="2016-10-18T10:48:53.714494031+02:00" level=debug msg="AuthZ request using plugin test-plugin"
Oct 18 10:48:53 localhost.localdomain dockerd[3609]: http: panic serving 127.0.0.1:42856: runtime error: invalid memory address or nil pointer dereference
                                                     goroutine 72 [running]:
                                                     net/http.(*conn).serve.func1(0xc820118e80)
                                                             /usr/lib/golang/src/net/http/server.go:1389 +0xd2
                                                     panic(0x211f480, 0xc82000e070)
                                                             /usr/lib/golang/src/runtime/panic.go:443 +0x521
                                                     github.com/docker/docker/pkg/plugins.(*Client).callWithRetry(0x0, 0x254e830, 0x14, 0x7f204e1deeb8, 0xc8203ea690, 0xc821258f01, 0x0, 0x0, 0x0, 0x0)
                                                             /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/pkg/plugins/client.go:115 +0xda4
                                                     github.com/docker/docker/pkg/plugins.(*Client).Call(0x0, 0x254e830, 0x14, 0x1ccdb40, 0xc821282280, 0x1ccdba0, 0xc821258ff0, 0x0, 0x0)
                                                             /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/pkg/plugins/client.go:77 +0x212
                                                     github.com/docker/docker/pkg/authorization.(*authorizationPlugin).AuthZRequest(0xc82085ab10, 0xc821282280, 0xc821281270, 0x0, 0x0)
                                                             /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/pkg/authorization/plugin.go:70 +0x169
                                                     github.com/docker/docker/pkg/authorization.(*Ctx).AuthZRequest(0xc821281578, 0x7f2049c1c960, 0xc821237860, 0xc8212961c0, 0x0, 0x0)
                                                             /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/pkg/authorization/authz.go:86 +0x92a
                                                     github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x7f2049c03190, 0xc82000ed00, 0x7f2049c1c960, 0xc821237860, 0xc8212961c0, 0xc821258db0, 0x0, 0x0)
                                                             /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/pkg/authorization/middleware.go:60 +0x5cf
                                                     github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x7f2049c03190, 0xc82000ed00, 0x7f2049c1c960, 0xc821237860, 0xc8212961c0, 0xc821258db0, 0x0, 0x0)
                                                             /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/api/server/middleware/debug.go:22 +0xf20
                                                     github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f2049c1c960, 0xc821237860, 0xc8212961c0)
                                                             /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x184
                                                     net/http.HandlerFunc.ServeHTTP(0xc8202a0f80, 0x7f2049c1c960, 0xc821237860, 0xc8212961c0)
                                                             /usr/lib/golang/src/net/http/server.go:1618 +0x48
                                                     github.com/gorilla/mux.(*Router).ServeHTTP(0xc820206b40, 0x7f2049c1c960, 0xc821237860, 0xc8212961c0)
                                                             /home/amurdaca/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:103 +0x342
                                                     github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8207d0620, 0x7f2049c1c960, 0xc821237860, 0xc8212961c0)
                                                             /home/amurdaca/src/github.com/docker/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x97
                                                     net/http.serverHandler.ServeHTTP(0xc820119800, 0x7f2049c1c960, 0xc821237860, 0xc8212961c0)
                                                             /usr/lib/golang/src/net/http/server.go:2081 +0x207
                                                     net/http.(*conn).serve(0xc820118e80)
                                                             /usr/lib/golang/src/net/http/server.go:1472 +0x1566
                                                     created by net/http.(*Server).Serve
                                                             /usr/lib/golang/src/net/http/server.go:2137 +0x4d2
```

**Comment by runcom** [comment]
@anusha-ragunathan @tiborvass PTAL....

**Comment by anusha-ragunathan** [comment]
initPlugin errors with `Error response from daemon: plugin test-plugin failed with error: legacy plugin: Plugin does not implement the requested driver`. 

The initPlugin error should return immediately. But instead its strange that AuthzRequest proceeds to plugin.Call and callWithRetry and hence resulting in the panic. I'll look more.

@runcom : docs for pluginv2 are in https://github.com/docker/docker/tree/master/docs/extend mainly index.md and manifest.md. CLI and API reference docs are at docs/reference/{cli,api} folders.

**Comment by anusha-ragunathan** [comment]
@runcom : can you share your repro steps?

**Comment by anusha-ragunathan** [comment]
`The plugin just replies with Allow: true so not sure why it first fails and then panic.`
Maybe the first API requests is allowed by the plugin and it responds with `Allow`. 
Then during the next API request, there's some state corruption and hence the panic.

**Comment by anusha-ragunathan** [comment]
Also, can you confirm that this `test-plugin` worked before pluginv2 support was added in https://github.com/docker/docker/pull/27293/commits/c5393ee147e981ded8fdf12c8da790abd1130175 ?

**Comment by anusha-ragunathan** [comment]
@runcom : can you post your entire daemon logs run in debug mode? also, provide steps on how to repro including how the authz plugin was installed, the daemon start flags, the API calls made to the authz plugin.

**Comment by runcom** [comment]
@anusha-ragunathan sorted out, turns out it was me playing too much with the plugin :( sorry for the noise
