### ISSUE TITLE
Possible Volume issue on Windows Server 2016

### ISSUE THREAD

**Issue by Dilergore** [docker/docker#27537]
**Issue and explanation:**
I've created an IIS web server image which is using PHP. I've used the latest microsoft/windowssservercore image.

PHP install is working fine and I can open PHP files in my browser. But when I place the PHP files on a docker volume PHP stops working. In the browser I can only see "No input file specified". I think it must be a docker volume related issue (maybe something is different when the running program - in this case PHP - trying to reach the volume) because it is always working with any kind of scenario except when I place the PHP files on an attached volume.

**Create container:**
docker create -it --network=TransparentNetwork -h IIS --mac-address 10:10:10:10:10:02 -m 1G --restart unless-stopped -v D:/Volumes/iis/www:C:/www:rw waterwall/iis:2.0 powershell

**Inspection of the mount:**
"Mounts": [
            {
                "Type": "bind",
                "Source": "d:\\volumes\\iis\\www",
                "Destination": "c:\\www",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],

**Docker Version:**
Version:      1.13.0-dev
API version:  1.25
Go version:   go1.7.1
Git commit:   668189e
Built:        Tue Oct 18 17:05:04 2016
OS/Arch:      windows/amd64

**Docker Info:**
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.206.amd64fre.rs1_release.160915-0644)
Operating System: Windows Server 2016 Datacenter Evaluation
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.952 GiB
Name: CoreContainers
ID: RQID:KVGU:QMEL:YWVP:4QJY:Y7M5:QDRZ:SCJQ:NSIU:OPHK:ER55:SLDM
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by Dilergore** [comment]
And I had a kind of similar problem when I tried to use the latest stable MariaDB (fork of MySQL).

I've placed the DB files on a volume but it wasn't working until I've changed the service user of MariaDB from Network Service to Local System.

I just wanted to mention this because it is possible that these two are connected somehow.

**Comment by praparn** [comment]
We also found this problem when try to map "PHP" code with host. As we start this container with volume map (-v with host) to map sourcecode of php to running on container. We found error as "No input file specified". But when we try copy some php code to running on c:\intetpub\wwwroot (inside container). It run fine. So is anyone have solution for this ?

**Comment by Dilergore** [comment]
I have no solution, still struggling with this problem and I'm waiting for some kind of help or advice.

**Comment by friism** [comment]
I can reproduce these problems.

Using @StefanScherer's dockerfiles:

```
git clone https://github.com/StefanScherer/dockerfiles-windows
cd dockerfiles-windows\php
docker build -t php .
```

From this, we can build a Dockerfile that cleans out the `www` folder to mount into:

```
FROM php

RUN rm C:\www\*.*
```

```
docker build -t test .
```

Have dir on container host with php site (eg. from [here](https://github.com/StefanScherer/dockerfiles-windows/tree/master/php/stage/www)):

```
dir mount


    Directory: C:\code\repros\php-volume\mount


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12/26/2016  11:34 AM             58 index.php
-a----       12/26/2016  11:33 AM             21 phpinfo.php
-a----       12/26/2016  11:33 AM            379 web.config
```

```
docker run -p 80:80 -d -v code\repros\php-volume\mount:C:\www:rw test
```

This gets an IIS error when accessing the container.

cc @jhowardmsft @patrickLang

**Comment by StefanScherer** [comment]
@friism Is the directory empty when you run the container with another command? I assume the files are there. 

Indeed, the files are there:

```
PS C:\> docker exec 9cf3 cmd /c dir c:\www
 Volume in drive C has no label.
 Volume Serial Number is 464C-9AB1

 Directory of c:\www

12/26/2016  11:07 AM    <DIR>          .
12/26/2016  11:07 AM    <DIR>          ..
12/26/2016  11:07 AM                55 index.php
12/26/2016  11:07 AM                21 phpinfo.php
12/26/2016  11:07 AM               379 web.config
               3 File(s)            795 bytes
               2 Dir(s)  123,733,626,880 bytes free

PS C:\Users\vagrant> docker exec 9cf3 cmd /c type c:\www\index.php
<?php

echo "Hello from PHP on Windows Containers";
```

I've seen several problems using [Node.js](https://github.com/nodejs/node/issues/8897) and even [`git clone`](https://github.com/git-for-windows/git/issues/1007) in a volume mount point / reparse point.

Many tools seem to calculate the "real path" and struggle at the UNC path `\\?\ ContainerMappedDirectories\xxx` and interpret it as `C:\ContainerMappedDirectories`.

```
PS C:\Users\vagrant> docker exec 9cf3 cmd /c dir c:\
 Volume in drive C has no label.
 Volume Serial Number is 464C-9AB1

 Directory of c:\

12/26/2016  11:09 AM    <DIR>          inetpub
11/22/2016  02:45 PM             1,894 License.txt
07/16/2016  05:18 AM    <DIR>          PerfLogs
12/26/2016  11:09 AM    <DIR>          php
12/13/2016  12:05 AM    <DIR>          Program Files
07/16/2016  05:18 AM    <DIR>          Program Files (x86)
10/13/2016  03:55 PM           135,864 ServiceMonitor.exe
12/26/2016  11:09 AM    <DIR>          Users
12/26/2016  11:13 AM    <DIR>          Windows
12/26/2016  11:07 AM    <SYMLINKD>     www [\\?\ContainerMappedDirectories\B9C50539-7789-47B6-B86F-5B81FAA26EB7]
               2 File(s)        137,758 bytes
               8 Dir(s)  21,031,489,536 bytes free
```

It seems we need some good advice how to fix that for different other projects.

**Comment by friism** [comment]
@StefanScherer yeah, I can confirm that the files get mounted in just fine, but it seems like the PHP runtime can't figure out how to read them

**Comment by StefanScherer** [comment]
To see what's happening it's useful to install ProcessMonitor on the Docker host:

<img width="1311" alt="php-containermappeddirectories" src="https://cloud.githubusercontent.com/assets/207759/21495900/c222a132-cc1a-11e6-94be-372119ac574e.png">

PHP seems to interpet the symlink at `C:\www` as a relative symlink and append it to its current directory `C:\php` so it tries to open the file `C:\php\ContainerMappedDirectories\...` which is `\Device\Harddisk\Volume10\php` at the host shown in the screenshot, but PHP then can't find it.

So the interesting part of this is to document how to interpret that symlink. There is eg. [Naming Files, Paths, and Namespaces](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#fully_qualified_vs._relative_paths) that also explains the `\\?\` for long paths. So is this a relative long path, and absolute long path? Should other software follow that symlink manually or just stop at this point?

**Comment by praparn** [comment]
Some additional test told me that for this symlink to outside map still working for simple html / image file. But not for .php execution. That mean IIS in action can access the map path and getting file for read/write. But no idea why execution script like .php cannot operate via IIS ?

**Comment by friism** [comment]
@Dilergore I think this might be PHP-related, so consider also opening an issue for the PHP runtime...

**Comment by PatrickLang** [comment]
I'm pinging some devs internally on this. Can you add PHP or IIS to the title to make it easier to find? Something like "Cannot serve PHP pages from mapped volumes in Windows Server 2016 with IIS"

**Comment by StefanScherer** [comment]
I see the problem with PHP only as an example. It seems that Golang also has this problem while compiling sources in the mounted folder.

```
$ docker run -v C:$(pwd):C:/gopath golang:1.8-nanoserver go build webserver.go
Unable to find image 'golang:1.8-nanoserver' locally
1.8-nanoserver: Pulling from library/golang
5496abde368a: Already exists 
482ab31872a2: Already exists 
66c4c0000446: Already exists 
fadb3cd88a62: Already exists 
6ad305fc60a3: Already exists 
70ec80188525: Pull complete 
fd1bc4c4fdcc: Pull complete 
fdedc809027b: Pull complete 
574c52669c35: Pull complete 
b465e25782dc: Pull complete 
Digest: sha256:793ece7d07f3dec1e425542f58af0c28ba1323b8c1c540031890b86fa37af4be
Status: Downloaded newer image for golang:1.8-nanoserver
go build command-line-arguments: c:\go\pkg\tool\windows_amd64\compile.exe: chdir \ContainerMappedDirectories\1C626055-289C-4D35-84C4-21A6F93D6498: The system cannot find the path specified.
```

Golang also tries to find the directory at C:\ContainerMappedDirectories.
Not related to docker/docker repo, but a guideline how to handle this reparse point would be helpful. So all the several open source projects that should improve at that point can easily understand and implement it.

**Comment by PatrickLang** [comment]
Thanks! I pinged the Windows devs on this again

**Comment by PatrickLang** [comment]
From the procmon trace, it looks like the user mode code is trying to interpret and reissue IO against the symlinked path instead of letting the OS handle it automatically. That shouldn't be needed, hmm.

**Comment by StefanScherer** [comment]
Just FYI, opened https://github.com/golang/go/issues/18555, maybe this helps for the [Dockerfile.windows](https://github.com/docker/docker/blob/c43bac064ba634f04145ff94083137d2b24545e1/Dockerfile.windows#L139-L140) as well.

**Comment by StefanScherer** [comment]
A similar problem arised with OpenJDK https://github.com/docker-library/openjdk/pull/88#issuecomment-271232194 when trying to follow symlinks.

**Comment by sixeyed** [comment]
@StefanScherer I've found a workaround for this by mapping the volume directory to a drive letter in the container. It is not pretty but it's a single registry entry in the Dockerfile and it works for Server Core and Nano Server. cc @friism  and @PatrickLang.

```
VOLUME c:/data
RUN set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\DOS Devices' -Name 'G:' -Value '\??\C:\data' -Type String
```

Now apps in the container can reference the `G:` drive, without any symlinkery or long path confusion. Tried with Elasticsearch and your OpenJDK install and it works fine - for straight volumes and mounts:

```
mkdir c:\es-data
docker run -it --rm -p 9200:9200 -p 9300:9300 -v c:\es-data:C:\data sixeyed/elasticsearch:nanoserver
```

The Elasticsearch config uses `G:\` as the data path, so when ES writes data it actually goes:

```
G:\ -> C:\data -> \\?\\ContainerMappedDirectories\{GUID} -> c:\es-data [HOST]
```

It's clunky but it works at the OS level, so the platforms having problems with the symlinks (Go, PHP, Java and all the others we haven't found yet) don't need to change. 

Technically all it does is a [persistent version](https://answers.microsoft.com/en-us/surface/forum/surfpro2-surfusingpro/how-do-i-do-the-equivalent-of-making-subst-mapping/186c6f52-3d97-49b5-a0fd-b7da20dbf48f) of the `subst` command, because you can't use `subst` directly - it doesn't persist between layers and doesn't exist at all on Nano.

**Comment by friism** [comment]
@jhowardmsft @jstarks @johnstep It looks like a lot of language standard libraries fail to read paths produced by volume mounting on Windows (eg. PHP here, [Golang](https://github.com/golang/go/issues/17540) and [Java](https://github.com/docker-library/openjdk/pull/88#issuecomment-271448007)).

Are there mitigations (in addition to the one proposed by @sixeyed) we could add in Docker. Or should someone write a piece of documentation documenting to standard library implementers how to correctly interpret these paths?

**Comment by PatrickLang** [comment]
I talked to the filesystem devs last week and I'll ping them again. This is tracked by an internal work item  9118210

**Comment by PatrickLang** [comment]
@sixeyed Hmm, however what happens if that path isn't passed with -v? I guess any app that references `g:` in your example would just fail with file not found? Would that be acceptable?

In other words, it sounds like you're proposing to be able to share folders from the host to a volume (Windows definition - drive letter) in the container. I thought there was a separate issue on this but I can't find it.

**Comment by sixeyed** [comment]
@PatrickLang no - because the `VOLUME` is defined in the Dockerfile, it will always be stored outside of the container's filesystem. `-v` mounts it to a specific directory on the host, but if you don't do that the volume directory is still on the host, just buried in the Docker install directory.

From the app point of view, it always uses `G:` which always exists because that's part of the image. From the user point of view they work with `C:\data` which is the path of the volume, and the `G` drive is transparent to them. Disjointed but it does cover all the scenarios.

**Comment by PatrickLang** [comment]
@glennc any thoughts on the workaround @sixeyed proposes? Would this make sense for Visual Studio's interactive debugging scenario?

**Comment by StefanScherer** [comment]
@sixeyed I've [tried the workaround with Node.js](https://github.com/StefanScherer/dockerfiles-windows/commit/9fd8ce461ea48f206ae1c3a09680d7f70dad65db) and it fixes the problem so node.exe is able to read the sources from drive `G:`.

**Comment by lurock** [comment]
I can get this working with a simple php app using the mount G: drive hack listed above, but how do you get this working if you need to have php files live outside of your public web directory.  So how would you do this if your directory structure looked like this:

C:\inetpub\wwwroot\non-public\include.php
C:\inetpub\wwwroot\public\index.php

and you want IIS to point to C:\inetput\wwwroot\public\ as the root of your website.

If you map G: to \??\C:\inetpub\wwwroot\public then your index.php file will not know how to include the ..\non-public\include.php that is not part of your publicly facing files.

I tried mapping G: to  \??\C:\inetpub\wwwroot\ and then setting IIS to point to G:\public but that doesn't work.  I am back to getting the  "No input file specified" error.

**Comment by StefanScherer** [comment]
@PatrickLang Do you have any status update on https://github.com/docker/docker/issues/27537#issuecomment-271669707 ?

**Comment by PatrickLang** [comment]
@StefanScherer I don't think this is going to get a fix for Windows Server 2016 because it has some impacts at the Windows filesystem layer. I think the language/library workarounds may be more achievable. I think that the Windows APIs like CreateFile() should still work on those paths as long as you don't try to parse them as symlinks on your own.

**Comment by StefanScherer** [comment]
There is a commit https://github.com/golang/go/commit/53003621720ff39c4745a76f76847123c27b01ea just landed in golang/go repo that fixes it by using CreateFileW() and GetFileInformationByHandleW(). That could be a good advice to fix it for other languages like PHP or Node.js and so on.

**Comment by pwoszczyk** [comment]
I think it can be permission problem because IIS user has not ReadAndExecute permission on mounted files.

```
PS C:\inetpub\wwwroot> get-acl phpinfo.php | fl


Path   : Microsoft.PowerShell.Core\FileSystem::C:\inetpub\wwwroot\phpinfo.php
Owner  : O:S-1-5-21-564662737-1608546433-1253539930-1001
Group  : G:S-1-5-21-564662737-1608546433-1253539930-513
Access : BUILTIN\Administrators Allow  FullControl
         NT AUTHORITY\SYSTEM Allow  FullControl
         BUILTIN\Users Allow  ReadAndExecute, Synchronize
         NT AUTHORITY\Authenticated Users Allow  Modify, Synchronize
Audit  :
Sddl   : O:S-1-5-21-564662737-1608546433-1253539930-1001G:S-1-5-21-564662737-1608546433-1253539930-513D:AI(A;ID;FA;;;BA)(A;ID;FA;;;SY)(A;ID;0x1200a9;;;BU)(A;ID;0x1301bf;;;AU)
```

**Comment by AidarGatin** [comment]
@sixeyed  Thanks for your workaround, works grate  with 5.6 elastic version from sixeyed/elasticsearch:nanoserver.  I fail with build after updating  [DockerFile ](https://github.com/sixeyed/dockerfiles-windows/blob/master/elasticsearch/nanoserver/sac2016/Dockerfile), adding  new elastic version 6.4.3. 
Getting error after docker container run ..... with -v  e:\es-data:c:\data
[2018-11-12T18:08:13,525][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[g:\elasticsearch]]
 with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_no
des] (was [1])?
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.4.3.jar:6.4.3]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.4.3.jar:6.4.3]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.4.3.jar:6.4.3]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.4.3.jar:6.4.3]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.4.3.jar:6.4.3]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.4.3.jar:6.4.3]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.4.3.jar:6.4.3]
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[g:\elasticsearch]] with lock id [0]; maybe these loca
tions are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:247) ~[elasticsearch-6.4.3.jar:6.4.3]
        at org.elasticsearch.node.Node.<init>(Node.java:274) ~[elasticsearch-6.4.3.jar:6.4.3]
        at org.elasticsearch.node.Node.<init>(Node.java:256) ~[elasticsearch-6.4.3.jar:6.4.3]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.4.3.jar:6.4.3]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.4.3.jar:6.4.3]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.4.3.jar:6.4.3]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.4.3.jar:6.4.3]
        ... 6 more
May be you can suggest anything?

**Comment by AidarGatin** [comment]
Elastic 6.5.0 issue still remain.

**Comment by tburnett80** [comment]
Has there been any traction on this? The work around doesn't always work with mounting to the host directory when specifying a Volume on Docker EE.

**Comment by tburnett80** [comment]
This workaround doesn't work anymore. I am trying to run a java 8 application using C:\data and G:\ as a dos device and everything works fine until I try to make C:\data a volume or bind mount it to the host filesystem. 

After that I get the typical 

```
java.lang.RuntimeException: java.nio.file.NoSuchFileException: G:\blobs\default
```

Fun part is, G:\blobs\default  is there as is C:\data\blobs\default
Java just cant seem to find either.
