### ISSUE TITLE
Docker container thomass/dockerpanic exited with panic log

### ISSUE THREAD

**Issue by ThomasSteinbach** [docker/docker#27780]
**Description**

Running the pushed docker image leads to unknown errors.

**Steps to reproduce the issue:**
1. docker run --rm thomass/dockerpanic

**Describe the results you received:**

```
panic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]
    panic: standard_init_linux.go:175: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x7eacc0, 0xc820146000)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8201072e8)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7eacc0, 0xc820146000)
    /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc820106bf8, 0xc82001e088, 0xc820106d08)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc82005d400, 0x7f15f8aaa650, 0xc820146000)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc82007aa00, 0x0, 0x0)
    /go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74f5c0, 0x900fe8, 0x13, 0x847308, 0x4, 0xc820107268, 0x1, 0x1, 0x0, 0x0, ...)
    /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74f5c0, 0x900fe8, 0x13, 0xc820107268, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74f5c0, 0x900fe8, 0xc82007aa00, 0x0, 0x0)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x84a1c8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8e02a0, 0x51, 0x0, ...)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001800, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
    /go/src/github.com/opencontainers/runc/main.go:137 +0xe24
```

**Describe the results you expected:**

A loop echoing the current date

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 524
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 873
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.48 GiB
Name: tst460s
ID: MDQT:ZI3F:KKWX:TMXA:NQPE:YML4:INWZ:TETO:JLNL:NEBN:NQ3E:KSQ5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: thomass
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical (Lenovo T460s)

**Dockerfile**

```
FROM alpine
MAINTAINER thomas.steinbach

COPY access.log /root/access.log
COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

VOLUME /root

CMD ["start.sh"]
```

**start.sh**

```
while true; do
  date
  sleep 30
done
```

**docker images | grep alpine**

```
alpine    latest    baa5d63471ea    7 days ago    4.803 MB
```

**Comment by AkihiroSuda** [comment]
you need to add shebang in your start.sh

**Comment by justincormack** [comment]
It should not panic though...

**Comment by ThomasSteinbach** [comment]
justincormack mentioned the point. It should run anyway. My workaround was changing the command to `CMD ["sh","/opt/start.sh"]`. But the error mentioned above reveals a greater problem.

**Comment by thaJeztah** [comment]
ping @mlaventure PTAL!

**Comment by mlaventure** [comment]
The panic is in `runc`, the issue would have to be opened in opencontainers/runc.

Can you confirm which version of `runc` you are running?

**Comment by SpootDev** [comment]
So, I was having the same issue in my entrypoint script which was waiting for the database.  I found some windows lf's hiding in it.  Converted to unix lf's and it no longer panic'd.

**Comment by jpetazzo** [comment]
With Docker Engine 1.12.1 and 1.13.0-rc3, we just get the error message:
```
standard_init_linux.go:175: exec user process caused "exec format error"
```
Instead of panicking.

I think the error message could be improved (and will open a separate issue for it) but I think this issue can be closed.

**Comment by cpuguy83** [comment]
Thanks @jpetazzo!
