### ISSUE TITLE
[BUG]docker daemon panic frequently with those logs

### ISSUE THREAD

**Issue by BSWANG** [docker/docker#27781]
**Description**

**Steps to reproduce the issue:**
1. run docker containers with overlay network
2.a period of time

**Describe the results you received:**
docker daemon panic with those logs

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x58 pc=0x883324]

goroutine 1037049 [running]:
github.com/docker/libnetwork.(*sandbox).execFunc(0xc8205072c0, 0xc82134e150)
        /usr/src/docker/vendor/src/github.com/docker/libnetwork/sandbox.go:426 +0x44
github.com/docker/libnetwork.(*resolver).ServeDNS(0xc8214c1560, 0x7fa0227b94a0, 0xc821c11a40, 0xc822090870)
        /usr/src/docker/vendor/src/github.com/docker/libnetwork/resolver.go:317 +0x65a
github.com/miekg/dns.(*Server).serve(0xc8203e8ea0, 0x7fa0207581f0, 0xc821848090, 0x7fa022805f00, 0xc8214c1560, 0xc820ac1e00, 0x2e, 0x200, 0xc8205234a0, 0xc821eea4a0, ...)
        /usr/src/docker/vendor/src/github.com/miekg/dns/server.go:535 +0x7c1
created by github.com/miekg/dns.(*Server).serveUDP
        /usr/src/docker/vendor/src/github.com/miekg/dns/server.go:489 +0x3d5
```

**Output of `docker version`:**

```
1.11.2
```

**Output of `docker info`:**

```
Containers: 10
Images: 16
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 139
 Dirperm1 Supported: false
Logging Driver: json-file
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.4 LTS
CPUs: 4
Total Memory: 3.859 GiB
Name: c0d022eb9e85f49c7bd-node23
ID: SPV3:YHX5:54NC:N3ZJ:F3WT:4J4:6EYT:EUGN
WARNING: No swap limit support
Cluster store: etcd://xxx:2379/eb9e85f49be8b8a20910ec1c7bd
Cluster advertise: 10.1.1.1:2376
```

**Comment by cpuguy83** [comment]
ping @sanimej

**Comment by sanimej** [comment]
@BSWANG  Would you be able tory 1.1 2.2  ? In 1.12 the UDP connection caching was removed. So this part of the code has changed since 1.11.2.

**Comment by aboch** [comment]
This will anyway be fixed by https://github.com/docker/libnetwork/pull/1556
