### ISSUE TITLE
Starting Docker in Windows 10

### ISSUE THREAD

**Issue by Metwalli** [docker/docker#27952]
Unable to create: Multiple VMs exist with the name MobyLinuxVM. Delete invalid ones or reset Docker to factory defaults.
at <ScriptBlock>, <No file>: line 340
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by justincormack** [comment]
Can you open this issue in https://github.com/docker/for-win/issues as it is specific to Docker for Windows..

**Comment by thaJeztah** [comment]
Let me close the issue here
