### ISSUE TITLE
[1.12.3] dockerd: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by JamesJJ** [docker/docker#28112]
**Description**

```
Nov 03 07:22:10 ip-10-10-44-129 dockerd[5617]: time="2016-11-03T07:22:10Z" level=info msg="Firewalld running: false"
Nov 03 07:24:15 ip-10-10-44-129 dockerd[5617]: time="2016-11-03T07:24:15Z" level=info msg="Firewalld running: false"
Nov 03 07:26:21 ip-10-10-44-129 dockerd[5617]: time="2016-11-03T07:26:21Z" level=info msg="Firewalld running: false"
Nov 03 07:28:27 ip-10-10-44-129 dockerd[5617]: time="2016-11-03T07:28:27Z" level=info msg="Firewalld running: false"
Nov 03 07:34:20 ip-10-10-44-129 dockerd[5617]: time="2016-11-03T07:33:32.224229184Z" level=error msg="containerd: start container" error="containerd: container did not start before th
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: time="2016-11-03T07:35:07.467441186Z" level=error msg="libcontainerd: error restarting rpc error: code = 2 desc = containerd: container 
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: time="2016-11-03T07:35:07.467594499Z" level=error msg="libcontainerd: rpc error: code = 2 desc = containerd: container did not start bef
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: time="2016-11-03T07:35:07Z" level=info msg="Firewalld running: false"
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: [signal 0xb code=0x1 addr=0x0 pc=0xde171e]
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: goroutine 382225 [running]:
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: panic(0x1a90b60, 0xc82000a080)
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: github.com/miekg/dns.getUDPSocketName(0x0, 0x0, 0x0, 0x0, 0x0)
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/udp_linux.go:68 +0xce
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: github.com/miekg/dns.setUDPSocketOptions(0x0, 0x0, 0x0)
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/udp.go:23 +0x37
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: github.com/miekg/dns.(*Server).ActivateAndServe(0xc823964dd0, 0x0, 0x0)
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/miekg/dns/server.go:349 +0x1b7
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: github.com/docker/libnetwork.(*resolver).Start.func1(0xc823964dd0)
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/resolver.go:122 +0x21
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: created by github.com/docker/libnetwork.(*resolver).Start
Nov 03 07:35:07 ip-10-10-44-129 dockerd[5617]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/resolver.go:123 +0x2b1
Nov 03 07:35:07 ip-10-10-44-129 systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 03 07:35:07 ip-10-10-44-129 systemd[1]: Unit docker.service entered failed state.
Nov 03 07:35:07 ip-10-10-44-129 systemd[1]: docker.service failed.
```

**Steps to reproduce the issue:**
1. Docker from `yum.dockerproject.org/repo/testing/centos/7/Packages`
2. `rpm -qa docker-engine` ==> `docker-engine-1.12.3-0.0.20161025.001321.gitbad4d12.el7.centos.x86_64`

**Additional information you deem important (e.g. issue happens only occasionally):**

* Only happens occasionally

**Output of `docker version`:**

```
Client:
 Version:      1.12.3-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bad4d12
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bad4d12
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 1.12.3-rc1
Storage Driver: devicemapper
 Pool Name: docker_lvm_vg-docker_lvm
 Pool Blocksize: 524.3 kB
 Base Device Size: 8.59 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 7.327 GB
 Data Space Total: 49.92 GB
 Data Space Available: 42.6 GB
 Metadata Space Used: 2.273 MB
 Metadata Space Total: 1.615 GB
 Metadata Space Available: 1.613 GB
 Thin Pool Minimum Free Space: 3.494 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.451 GiB
Name: ip-10-10-44-129
ID: AE33:4DCO:EMNY:CPQ7:37QQ:AIJD:YHWP:Q74R:VHZD:APTT:MXCD:XTA5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
* Fully updated Centos 7
* AWS machines
* Using docker-compose:
    * All containers have `restart: always`
    * One container has a `HEALTHCHECK`

**Comment by justincormack** [comment]
I don't know if there were any differences in 1.12.3 final from -rc1 that would affect this, seems unlikely

@aboch PTAL

**Comment by sanimej** [comment]
There was no change between 1.12.3 and rc1 in this area. panic is from the docker dns server. I will take a look.
