### ISSUE TITLE
docker-machine fails to create a new vm (OS X)

### ISSUE THREAD

**Issue by jesuscript** [docker/docker#28388]
**Description**

Docker machine fails to create a new VM with an error.

**Steps to reproduce the issue:**
1. `docker-machine create --driver virtualbox default`

**Describe the results you received:**
```bash
Creating VirtualBox VM...
Creating SSH key...
failed MSpanList_Insert 0xc0a5c8 0x3fdcc82c7047 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0xb251f0, 0xc0a5c8)
	/usr/src/go/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Free(0xb25180, 0xc0a5c8, 0x0)
	/usr/src/go/src/runtime/mheap.c:500 +0x5b
runtime.MCentral_FreeSpan(0xb2cef8, 0xc0a5c8, 0x1c, 0xc208112000, 0xc208113e60, 0x0, 0x64)
	/usr/src/go/src/runtime/mcentral.c:181 +0x1bb
runtime.MSpan_Sweep(0xc0a5c8, 0x13100000100, 0x1)
	/usr/src/go/src/runtime/mgc0.c:1099 +0x477
runtime.MHeap_Alloc(0xb25180, 0x1, 0x10000000002, 0xdfd9)
	/usr/src/go/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0xb2bcf8, 0xc0a560)
	/usr/src/go/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0xc04000, 0x2, 0xc0a560)
	/usr/src/go/src/runtime/mcache.c:90 +0xa0

goroutine 1 [running]:
runtime.switchtoM()
	/usr/src/go/src/runtime/asm_amd64.s:198 fp=0xc2080e6080 sp=0xc2080e6078
runtime.mallocgc(0x8, 0x6d5460, 0x1, 0x0)
	/usr/src/go/src/runtime/malloc.go:147 +0x1bb fp=0xc2080e6130 sp=0xc2080e6080
runtime.newobject(0x6d5460, 0xc15cb8)
	/usr/src/go/src/runtime/malloc.go:353 +0x49 fp=0xc2080e6158 sp=0xc2080e6130
runtime.convT2I(0x6d5460, 0x635b40, 0xb1ccd0, 0xc2080e61e0, 0x0, 0x0)
	/usr/src/go/src/runtime/iface.go:163 +0x130 fp=0xc2080e61a0 sp=0xc2080e6158
os.(*File).write(0xc20804a348, 0xc208134000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/usr/src/go/src/os/file_unix.go:218 +0x1bf fp=0xc2080e6248 sp=0xc2080e61a0
os.(*File).Write(0xc20804a348, 0xc208134000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/src/go/src/os/file.go:139 +0x91 fp=0xc2080e62a0 sp=0xc2080e6248
github.com/docker/machine/drivers/virtualbox.zeroFill(0xc18ca0, 0xc2080783f0, 0x4c5f3ee00, 0x0, 0x0)
	/go/src/github.com/docker/machine/drivers/virtualbox/virtualbox.go:680 +0xe2 fp=0xc2080e6320 sp=0xc2080e62a0
github.com/docker/machine/drivers/virtualbox.createDiskImage(0xc2080ba840, 0x38, 0x4e20, 0xc18c20, 0xc208078360, 0x0, 0x0)
	/go/src/github.com/docker/machine/drivers/virtualbox/virtualbox.go:659 +0x499 fp=0xc2080e64a0 sp=0xc2080e6320
github.com/docker/machine/drivers/virtualbox.(*Driver).generateDiskImage(0xc20800a730, 0x4e20, 0x0, 0x0)
	/go/src/github.com/docker/machine/drivers/virtualbox/virtualbox.go:576 +0x86e fp=0xc2080e66a0 sp=0xc2080e64a0
github.com/docker/machine/drivers/virtualbox.(*Driver).Create(0xc20800a730, 0x0, 0x0)
	/go/src/github.com/docker/machine/drivers/virtualbox/virtualbox.go:206 +0x1cda fp=0xc2080e6e50 sp=0xc2080e66a0
github.com/docker/machine/libmachine.(*Host).Create(0xc20800a780, 0x7fff5fbffb62, 0x7, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/host.go:110 +0x71 fp=0xc2080e7168 sp=0xc2080e6e50
github.com/docker/machine/libmachine.(*Provider).Create(0xc20809f9f0, 0x7fff5fbffb62, 0x7, 0xc20809ef40, 0xa, 0xc2080ba8c0, 0xc169b8, 0xc2080b60c0, 0x0, 0x0, ...)
	/go/src/github.com/docker/machine/libmachine/provider.go:59 +0x5bd fp=0xc2080e72c8 sp=0xc2080e7168
github.com/docker/machine/commands.cmdCreate(0xc2080b60c0)
	/go/src/github.com/docker/machine/commands/create.go:98 +0x13ff fp=0xc2080e76f8 sp=0xc2080e72c8
github.com/codegangsta/cli.Command.Run(0x790930, 0x6, 0x0, 0x0, 0x7db650, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0x1038 fp=0xc2080e7ab8 sp=0xc2080e76f8
github.com/codegangsta/cli.(*App).Run(0xc208046270, 0xc20800a000, 0x5, 0x5, 0x0, 0x0)
	/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xcf7 fp=0xc2080e7d30 sp=0xc2080e7ab8
main.main()
	/go/src/github.com/docker/machine/main.go:114 +0x9bc fp=0xc2080e7f98 sp=0xc2080e7d30
runtime.main()
	/usr/src/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080e7fe0 sp=0xc2080e7f98
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080e7fe8 sp=0xc2080e7fe0

goroutine 5 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

```

**Describe the results you expected:**

A new VM successfully created

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Thu Aug 18 22:32:50 UTC 2016
 OS/Arch:      darwin/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
(cannot obtain, as I think this can only work from inside a VM)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual Box version: `Version 5.1.8 r111374 (Qt5.5.1)`

OS X Version: 10.12.1
Darwin Kernel Version 16.1.0

**Comment by jesuscript** [comment]
looks like I've been using a pretty old version of docker-machine (0.4.2). I thought that getting the latest version of the installer (https://docs.docker.com/docker-for-mac/) would update docker-machine too but looks like I was wrong. Grabbed 0.8.2 from https://github.com/docker/machine/releases/ and it seems like the problem has gone away. Closing

**Comment by thaJeztah** [comment]
@jesuscript also be aware that docker for Mac does not use VirtualBox, but when using docker-machine to create a new VirtualBox machine you may be overriding the default, so the client may be connecting to a VirtualBox VM, instead of "native" docker for Mac
