### ISSUE TITLE
Add custom Host: Failed to establish a new connection.

### ISSUE THREAD

**Issue by ununseptium** [docker/docker#28434]
**Description**

**Steps to reproduce the issue:**
1. Go to Hosts
2. Add custom Host
3. Type in the public IP of my Mac
4. Copied the given string 
5. Launched it inside the terminal

**Describe the results you received:**
```
INFO: Running Agent Registration Process, CATTLE_URL=http://172.20.10.2:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.12.3
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.12.3
INFO: docker version: Server API version: 1.24
INFO: docker version: Go version (server): go1.6.3
INFO: docker version: Git commit (server): 6b644ec
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 12
INFO: docker info: Images: 2
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 45
INFO: docker info: Dirperm1 Supported: true
INFO: docker info: Execution Driver:
INFO: docker info: Kernel Version: 4.4.27-moby
INFO: docker info: Operating System: Alpine Linux v3.4
INFO: docker info: CPUs: 4
INFO: docker info: Total Memory: 3.854 GiB
INFO: docker info: Name: moby
INFO: docker info: ID: LEUY:5RRY:IJYW:BTSC:N2CL:2OTN:LFMM:GCYC:SBTZ:VNQ5:SAPZ:BNQO
INFO: docker info: Debug mode (server): true
INFO: docker info: Debug mode (client): false
INFO: docker info: Fds: 26
INFO: docker info: Goroutines: 44
INFO: docker info: System Time: Tue Nov 15 13:29:02 UTC 2016
INFO: docker info: EventsListeners: 2
INFO: docker info: Docker Root Dir: /var/lib/docker
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy: *.local, 169.254/16
INFO: Attempting to connect to: http://172.20.10.2:8080/v1
INFO: http://172.20.10.2:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Systemd: false
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 608, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 627, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 313, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 262, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f945c7bee50>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Describe the results you expected:**
I expected to not get this issue and have the host entry inside the ui...

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 12
 Running: 1
 Paused: 0
 Stopped: 11
Images: 2
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.854 GiB
Name: moby
ID: LEUY:5RRY:IJYW:BTSC:N2CL:2OTN:LFMM:GCYC:SBTZ:VNQ5:SAPZ:BNQO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 38
 System Time: 2016-11-15T13:34:45.715863423Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
As you can tell. This is happening on an Macbook Pro.

**Comment by ununseptium** [comment]
Uhm i dunno what happend, but i meant to post this issue somewhere else.
