### ISSUE TITLE
docker ps hangs. How to diagnose it ?

### ISSUE THREAD

**Issue by boskiv** [docker/docker#28575]
**Description**

I have 66 containers running on Ubuntu VM (Vmware ESXi)
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```
free -m
             total       used       free     shared    buffers     cached
Mem:         16047       8850       7196         13        370        969
-/+ buffers/cache:       7510       8537
Swap:         4095          0       4095
```

`Docker version 1.12.3, build 6b644ec`

Every day I come to work and my deploy system cannot connect to docker
```
fatal: [dev6]: FAILED! => {"changed": false, "failed": true, "msg": "ReadTimeout(ReadTimeoutError(\"UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)\",),)"}
```

docker ps command hangs.
I cant do anything except reboot server.

How to diagnose it ?

```
root@docker-01:~# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 64100
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 65535
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

```
root@docker-01:~# cat /etc/default/docker

DOCKER_OPTS="-H tcp://10.129.4.103:2375 -H unix:///var/run/docker.sock"

```

```
root@docker-01:~# lsof -w | wc -l
167224
```

```
root@docker-01:~# docker info
Containers: 65
 Running: 62
 Paused: 0
 Stopped: 3
Images: 601
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 783
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: docker-01.public.exness.local
ID: K6WX:ERB4:NB7X:TDBL:DGMN:OKWQ:ECCZ:N5W3:CLPC:GALB:3O5E:4JUS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by cpuguy83** [comment]
Can you send `SIGUSR1` to the dockerd process then grab the stack dump from the logs?

**Comment by boskiv** [comment]
I have send `kill -SIGUSR1 1151` but nothing happends in logs

**Comment by cpuguy83** [comment]
@boskiv Where are you looking at logs? Do you see other details (such as logs for requests?)

**Comment by boskiv** [comment]
I look into `/var/log/syslog` (I have Ubuntu 14.04 there)

**Comment by cpuguy83** [comment]
Logs would be in `/var/log/upstart/docker.log`

**Comment by boskiv** [comment]
https://gist.github.com/boskiv/02aff5da81f7ba2dd20b0b872c267b88

**Comment by boskiv** [comment]
@cpuguy83 can I reebot my server or your need some else while it hanged ?

**Comment by cpuguy83** [comment]
Reboot away, I'll check out this stack trace.

**Comment by cpuguy83** [comment]
@boskiv It seems to be hung trying to close out the syslog logger which is itself is also stuck in a write call to the network connection.

**Comment by boskiv** [comment]
Ok, I will setup it back to json. I suspect it.

**Comment by cpuguy83** [comment]
ping @sirsean, wdyt about setting a socket timeout?

Also not sure why this would hang indefinitely:
```
goroutine 3729 [IO wait, 340 minutes]:
net.runtime_pollWait(0x7f19810eb308, 0x77, 0xc824ede2c0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8213acb50, 0x77, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitWrite(0xc8213acb50, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:82 +0x36
net.(*netFD).Write(0xc8213acaf0, 0xc824ede2c0, 0x144, 0x160, 0x0, 0x7f1981224168, 0xc8200101a0)
	/usr/local/go/src/net/fd_unix.go:336 +0x414
net.(*conn).Write(0xc82014ec38, 0xc824ede2c0, 0x144, 0x160, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0xe4
github.com/RackSec/srslog.(*netConn).writeString(0xc8227de800, 0x216faa8, 0x216fac0, 0x1b, 0xc825291480, 0x1d, 0xc8227de3a0, 0xa, 0xc820d5b0e0, 0x11e, ...)
	/usr/src/docker/vendor/src/github.com/RackSec/srslog/net_conn.go:23 +0x180
github.com/RackSec/srslog.(*Writer).write(0xc8235e6c00, 0x1b, 0xc820d5b0e0, 0x11e, 0xc820d5afc0, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/RackSec/srslog/writer.go:156 +0x1cc
github.com/RackSec/srslog.(*Writer).writeAndRetry(0xc8235e6c00, 0x3, 0xc820d5afc0, 0x11d, 0x0, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/RackSec/srslog/writer.go:138 +0xe0
github.com/RackSec/srslog.(*Writer).Err(0xc8235e6c00, 0xc820d5afc0, 0x11d, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/RackSec/srslog/writer.go:99 +0x4c
github.com/docker/docker/daemon/logger/syslog.(*syslogger).Log(0xc82014ec48, 0xc821d35b80, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/syslog/syslog.go:138 +0xd1
github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc824ab3c80, 0x1d5add8, 0x6, 0x7f19811c2440, 0xc824ab3bc0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:56 +0x4c6
created by github.com/docker/docker/daemon/logger.(*Copier).Run
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/copier.go:37 +0x12b
```


Here's the bit causing everything in docker to hang due to the above hang while the syslogger is locked:
```
goroutine 42873 [semacquire, 61 minutes]:
sync.runtime_Semacquire(0xc821ee7684)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc821ee7680)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/RackSec/srslog.(*Writer).Close(0xc821ee7680, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/RackSec/srslog/writer.go:64 +0x3c
github.com/docker/docker/daemon/logger/syslog.(*syslogger).Close(0xc820bf8e38, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/syslog/syslog.go:144 +0x30
github.com/docker/docker/container.(*Container).Reset(0xc8205feb40, 0x2174900)
	/usr/src/docker/.gopath/src/github.com/docker/docker/container/monitor.go:42 +0x665
github.com/docker/docker/daemon.(*Daemon).StateChanged(0xc82042c000, 0xc823716000, 0x40, 0xc8250fa000, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:34 +0x44c
github.com/docker/docker/libcontainerd.(*container).handleEvent.func1()
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:184 +0xab
github.com/docker/docker/libcontainerd.(*queue).append.func1(0xc820cdfc00, 0x0, 0xc8234551d0, 0xc820ca2120)
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/queue_linux.go:26 +0x47
created by github.com/docker/docker/libcontainerd.(*queue).append
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/queue_linux.go:28 +0x1da
```

**Comment by cpuguy83** [comment]
@boskiv How is your syslog driver configured?

**Comment by sirsean** [comment]
Well that sure doesn't look good.

I'll dig into this and see how srslog could be hanging there.

**Comment by sirsean** [comment]
First thought: I don't like the way `srslog`'s `connect` function demands that you must `Lock` before calling it. This means we're holding the lock far too long, and putting responsibility for it in the wrong place.

I need to investigate whether it's possible to make that locking more granular, and more focused on getting _access_ to the `conn` rather than the use of it. (Because using `conn` should be threadsafe.)

Meanwhile, have you come up with a repeatable test case or is it only happening occasionally/intermittently?

**Comment by LK4D4** [comment]
@sirsean yup, indeed. It should be kinda easy to make `conn()/setConn()` methods with locks and remove locking everywhere else. From the code, it looks like mutex protects only conn field.

**Comment by sirsean** [comment]
You're right that the mutex only protects the `conn` field.

I think this should be closer to what we want:

https://github.com/RackSec/srslog/pull/21

If someone wants to give that a quick review.

**Comment by boskiv** [comment]
@cpuguy83 
```
 "Config": {
                    "syslog-address": "tcp://192.168.168.240:514",
                    "tag": "verificator-service-service-dev"
                }
```

**Comment by sirsean** [comment]
`srslog` just merged something that _should_ fix this.
