### ISSUE TITLE
unexpected EOF on docker push

### ISSUE THREAD

**Issue by scottstensland** [docker/docker#28596]
For past several days I am seeing sporadic docker push failures with :  unexpected EOF
Typical occurrence :  

```
docker push   092412666666.dkr.ecr.us-east-1.amazonaws.com/primacyofdirectexperience/loudnginx 
The push refers to a repository [092412666666.dkr.ecr.us-east-1.amazonaws.com/primacyofdirectexperience/loudnginx]
4401c2bfac7b: Pushed 
afa9a64379e0: Pushed 
ae2109db9571: Pushed 
8b1f37a4aa19: Pushed 
7482de28a333: Pushed 
ecd8de2e9d55: Pushed 
01a74858f5af: Pushed 
409b4185633a: Pushed 
aa5daca48898: Pushed 
1b40fad72f04: Pushed 
c20fdb23d0a2: Pushed 
d93bba2ff7bb: Pushed 
d19ade0aca78: Pushed 
9f25548572f4: Pushed 
9cd83bca7ea0: Pushed 
0e20f4f8a593: Pushed 
1633f88f8c9f: Pushed 
46c98490f575: Pushed 
8ba4b4ea187c: Pushed 
c854e44a1a5a: Layer already exists 
unexpected EOF
```

This is breaking my automation - however the docker push works upon manual intervention.
Currently seeing about 25% of all docker push are now failing in this way ... I will revert to using an earlier docker release and see if it helps yet I figured booking this ticket may thwart pain in others.

Am doing the docker push into a private AWS repository which has been fine until now.

```
docker version
Client:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 19:47:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc1
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          75fd88b
 Built:               Fri Nov 11 19:47:07 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

```
docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 799
Server Version: 1.13.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 475
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 8517738ba4b82aff5662c97ca4627e7e4d03b531
runc version: ac031b5bf1cc92239461125f4c1ffb760522bbf2
init version: N/A (expected: v0.13.0)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: hakkoichiu
ID: BTBZ:L3XM:VXHB:5E2I:GY4R:4G4B:PK6O:FWXT:BFO5:KI3Y:L2EM:FTI5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by tonistiigi** [comment]
@scottstensland Could you send us the daemon logs during the push. `unexpected EOF` usually means dropped connection between client and daemon, possibly even a fatal error in daemon that should be logged with a stacktrace.

**Comment by scottstensland** [comment]
shared link to log excerpt (272k)   https://drive.google.com/file/d/0BwsqAY439yBDX0FHbktJVXZIRGc/view?usp=sharing

one such offending bit

journalctl -u docker.service

```
Nov 18 19:46:46 hakkoichiu dockerd[1400]: time="2016-11-18T19:46:46.203696570Z" level=info msg="Layer sha256:4ae7cfc80f5cbd983afccbd087300b583e0040ba22df46cbd96505c00c759c0f cleaned up"
Nov 18 19:46:47 hakkoichiu dockerd[1400]: time="2016-11-18T19:46:47.250748066Z" level=info msg="Layer sha256:2e4352cbcf0c089ae286dfd2b5b15e366ecb5ee9c090db7c1951be4044920170 cleaned up"
Nov 18 19:47:07 hakkoichiu dockerd[1400]: time="2016-11-18T19:47:07.027109697Z" level=warning msg="failed to upload schema2 manifest: unsupported: Invalid parameter at 'ImageManifest' failed to satisfy constraint: 'Invalid JSON syntax' - falling back to schema1"
Nov 18 19:47:07 hakkoichiu dockerd[1400]: http: panic serving @: could not find ':' in digest: 
                                          goroutine 37797 [running]:
                                          net/http.(*conn).serve.func1(0xc420aa1d80)
                                                  /usr/local/go/src/net/http/server.go:1491 +0x12a
                                          panic(0x171efa0, 0xc420ccfbf0)
                                                  /usr/local/go/src/runtime/panic.go:458 +0x243
                                          github.com/docker/docker/vendor/github.com/docker/distribution/digest.Digest.sepIndex(0x0, 0x0, 0xc4214a2960)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/docker/distribution/digest/digest.go:135 +0xec
                                          github.com/docker/docker/vendor/github.com/docker/distribution/digest.Digest.Hex(0x0, 0x0, 0x1c, 0xc4211276c0)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/docker/distribution/digest/digest.go:124 +0x35
                                          github.com/docker/docker/vendor/github.com/docker/distribution/manifest/schema1.(*configManifestBuilder).Build(0xc420d261c0, 0x7fb7794a6f58, 0xc421581400, 0x7fb7794a6f58, 0xc421581400, 0x70, 0x17dbd20)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/docker/distribution/manifest/schema1/config_builder.go:135 +0x2ac
                                          github.com/docker/docker/distribution.manifestFromBuilder(0x23e9d00, 0xc421581400, 0x23e15c0, 0xc420d261c0, 0xc421000c00, 0x14, 0x20, 0x0, 0x0, 0x0, ...)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/push_v2.go:245 +0x120
                                          github.com/docker/docker/distribution.(*v2Pusher).pushV2Tag(0xc421590500, 0x23e9d00, 0xc421581400, 0x23ed020, 0xc422cdeab0, 0xc422a9abe0, 0x47, 0x0, 0x0)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/push_v2.go:200 +0x13df
                                          github.com/docker/docker/distribution.(*v2Pusher).pushV2Repository(0xc421590500, 0x23e9d00, 0xc421581400, 0x0, 0xc421590280)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/push_v2.go:110 +0x251
                                          github.com/docker/docker/distribution.(*v2Pusher).Push(0xc421590500, 0x23e9d00, 0xc421581400, 0xc421590280, 0x2)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/push_v2.go:79 +0x268
                                          github.com/docker/docker/distribution.Push(0x23e9d00, 0xc421581400, 0x23eb340, 0xc420bff8a0, 0xc422915e60, 0xc4213f3200, 0xc4213f3380)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/push.go:149 +0x5f4
                                          github.com/docker/docker/daemon.(*Daemon).PushImage(0xc42039e960, 0x23e9d00, 0xc421581400, 0xc4213cbe93, 0x50, 0xc4213cbee9, 0x0, 0xc420cc9f50, 0xc42117a620, 0x23d1140, ...)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/image_push.go:54 +0x34f
                                          github.com/docker/docker/api/server/router/image.(*imageRouter).postImagesPush(0xc420bf6780, 0x23e9d00, 0xc421581300, 0x23e65c0, 0xc422de6a90, 0xc420822690, 0xc420cc9d40, 0x0, 0x0)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/image/image_routes.go:163 +0x723
                                          github.com/docker/docker/api/server/router/image.(*imageRouter).(github.com/docker/docker/api/server/router/image.postImagesPush)-fm(0x23e9d00, 0xc421581300, 0x23e65c0, 0xc422de6a90, 0xc420822690, 0xc420cc9d40, 0xc420bff7b0, 0x1)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/image/image.go:44 +0x69
                                          github.com/docker/docker/api/server/router.cancellableHandler.func1(0x23e9dc0, 0xc420cc9e60, 0x23e65c0, 0xc422de6a90, 0xc420822690, 0xc420cc9d40, 0x0, 0x0)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/local.go:84 +0x104
                                          github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x23e9dc0, 0xc420cc9e60, 0x23e65c0, 0xc422de6a90, 0xc420822690, 0xc420cc9d40, 0x19, 0x22)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
                                          github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x23e9dc0, 0xc420cc9e30, 0x23e65c0, 0xc422de6a90, 0xc420822690, 0xc420cc9d40, 0x19cc8ea, 0x413545)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:47 +0x5ca
                                          github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x23e9dc0, 0xc420cc9e30, 0x23e65c0, 0xc422de6a90, 0xc420822690, 0xc420cc9d40, 0xc420f8daf0, 0x75500b)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/authorization/middleware.go:43 +0x83f
                                          github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x23e65c0, 0xc422de6a90, 0xc420822690)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x233
                                          net/http.HandlerFunc.ServeHTTP(0xc4203d08c0, 0x23e65c0, 0xc422de6a90, 0xc420822690)
                                                  /usr/local/go/src/net/http/server.go:1726 +0x44
                                          github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420ba81e0, 0x23e65c0, 0xc422de6a90, 0xc420822690)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
                                          github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc4211f78c0, 0x23e65c0, 0xc422de6a90, 0xc420822690)
                                                  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
                                          net/http.serverHandler.ServeHTTP(0xc420289c80, 0x23e65c0, 0xc422de6a90, 0xc420822690)
                                                  /usr/local/go/src/net/http/server.go:2202 +0x7d
                                          net/http.(*conn).serve(0xc420aa1d80, 0x23e8200, 0xc42142f780)
                                                  /usr/local/go/src/net/http/server.go:1579 +0x4b7
                                          created by net/http.(*Server).Serve
                                                  /usr/local/go/src/net/http/server.go:2293 +0x44d
Nov 18 19:52:11 hakkoichiu dockerd[1400]: time="2016-11-18T19:52:11.277393390Z" level=warning msg="failed to retrieve docker-init version: unknown output format"
Nov 18 19:52:21 hakkoichiu dockerd[1400]: time="2016-11-18T19:52:21.830268500Z" level=warning msg="failed to upload schema2 manifest: unsupported: Invalid parameter at 'ImageManifest' failed to satisfy constraint: 'Invalid JSON syntax' - falling back to schema1"
Nov 18 19:52:48 hakkoichiu dockerd[1400]: time="2016-11-18T19:52:48.209466650Z" level=warning msg="failed to retrieve docker-init version: unknown output format"
Nov 18 19:57:39 hakkoichiu dockerd[1400]: time="2016-11-18T19:57:39.412079259Z" level=warning msg="failed to retrieve docker-init version: unknown output format"
Nov 18 20:13:49 hakkoichiu dockerd[1400]: time="2016-11-18T20:13:49.380533674Z" level=warning msg="failed to retrieve docker-init version: unknown output format"
Nov 18 20:15:40 hakkoichiu dockerd[1400]: time="2016-11-18T20:15:40.558605487Z" level=warning msg="failed to retrieve docker-init version: unknown output format"
Nov 18 20:18:56 hakkoichiu dockerd[1400]: time="2016-11-18T20:18:56.122582844Z" level=warning msg="failed to retrieve docker-init version: unknown output format"

```

**Comment by tonistiigi** [comment]
ping @aaronlehmann @dmcgowan

**Comment by aaronlehmann** [comment]
This looks very similar to https://github.com/docker/docker/issues/9132

**Comment by scottstensland** [comment]
My push is a single image at a time

**Comment by aaronlehmann** [comment]
Thanks, that's a useful data point. To clarify, I don't think this is the same problem as #9132, but the same stack trace emerged while debugging that issue, so there's some similarity.

**Comment by scottstensland** [comment]
This exact issue continues to happen ... here on a different server

```
The push refers to a repository [064066309977.dkr.ecr.us-east-1.amazonaws.com/ruptureofthemundaneplane/loudweb-enduser]
26312f670ae5: Pushed 
17ce657eb6eb: Pushed 
badc1f4022c6: Pushed 
8ba95d72560e: Pushed 
1dacdc9451dc: Pushed 
c8fa7004c803: Pushed 
5aa6400e1826: Layer already exists 
beaf752f44a0: Layer already exists 
990977fe39cb: Pushed 
412797a1f141: Pushed 
10306259d977: Pushed 
27fdaf26093c: Pushed 
c1bd37d01c89: Pushed 
943edb549a83: Pushed 
bf6751561805: Pushed 
f934e33a54a6: Pushed 
e7ebc6e16708: Layer already exists 
unexpected EOF
The push refers to a repository [064066309977.dkr.ecr.us-east-1.amazonaws.com/ruptureofthemundaneplane/loudweb-enduser]
26312f670ae5: Layer already exists 
17ce657eb6eb: Layer already exists 
badc1f4022c6: Layer already exists 
8ba95d72560e: Layer already exists 
1dacdc9451dc: Layer already exists 
c8fa7004c803: Layer already exists 
5aa6400e1826: Layer already exists 
beaf752f44a0: Layer already exists 
990977fe39cb: Layer already exists 
412797a1f141: Layer already exists 
10306259d977: Layer already exists 
27fdaf26093c: Layer already exists 
c1bd37d01c89: Layer already exists 
943edb549a83: Layer already exists 
bf6751561805: Layer already exists 
f934e33a54a6: Layer already exists 
e7ebc6e16708: Layer already exists 
latest: digest: sha256:db3e17accaa4a175cf17d0a78ff97b7139e4260396395922b18212e820eef90b size: 22008

```

here is docker server log

```
sudo journalctl -u 

-- Logs begin at Tue 2016-11-22 23:13:49 UTC, end at Wed 2016-11-23 02:47:06 UTC. --
Nov 22 23:18:32 mahabharata systemd[1]: Starting Docker Application Container Engine...
Nov 22 23:18:32 mahabharata dockerd[19608]: time="2016-11-22T23:18:32.086197775Z" level=info msg="libcontainerd: new containerd process, pid: 19617"
Nov 22 23:18:33 mahabharata dockerd[19608]: time="2016-11-22T23:18:33.169198748Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Nov 22 23:18:33 mahabharata dockerd[19608]: time="2016-11-22T23:18:33.1694

..
...
...

Nov 23 02:05:58 mahabharata dockerd[1447]: time="2016-11-23T02:05:58.386339029Z" level=warning msg="failed to retrieve docker-init version: unknown output format"
Nov 23 02:15:25 mahabharata dockerd[1447]: time="2016-11-23T02:15:25.431832803Z" level=warning msg="failed to retrieve docker-init version: unknown output format"
Nov 23 02:18:37 mahabharata dockerd[1447]: time="2016-11-23T02:18:37.710878089Z" level=warning msg="Your kernel does not support swap memory limit."
Nov 23 02:18:37 mahabharata dockerd[1447]: time="2016-11-23T02:18:37.710970025Z" level=warning msg="Your kernel does not support cgroup rt period"
Nov 23 02:18:37 mahabharata dockerd[1447]: time="2016-11-23T02:18:37.710985861Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Nov 23 02:18:38 mahabharata dockerd[1447]: time="2016-11-23T02:18:38.107456236Z" level=info msg="Layer sha256:c13dcdeb408c3cc5b494bed6b76b2e80d64c0f4c14f3bc72de0e79643ed81c02 cleaned up"
Nov 23 02:18:38 mahabharata dockerd[1447]: time="2016-11-23T02:18:38.589684094Z" level=warning msg="Your kernel does not support swap memory limit."
Nov 23 02:18:38 mahabharata dockerd[1447]: time="2016-11-23T02:18:38.589745312Z" level=warning msg="Your kernel does not support cgroup rt period"
Nov 23 02:18:38 mahabharata dockerd[1447]: time="2016-11-23T02:18:38.589762987Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Nov 23 02:18:38 mahabharata dockerd[1447]: time="2016-11-23T02:18:38.964398965Z" level=info msg="Layer sha256:b756c9eba456dd39bc076b393e2bd10a0f738ad402a9ccd2cdc2c2dbbe544433 cleaned up"
Nov 23 02:18:39 mahabharata dockerd[1447]: time="2016-11-23T02:18:39.057097166Z" level=warning msg="Your kernel does not support swap memory limit."
Nov 23 02:18:39 mahabharata dockerd[1447]: time="2016-11-23T02:18:39.057538438Z" level=warning msg="Your kernel does not support cgroup rt period"
Nov 23 02:18:39 mahabharata dockerd[1447]: time="2016-11-23T02:18:39.057864766Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Nov 23 02:18:39 mahabharata dockerd[1447]: time="2016-11-23T02:18:39.440627106Z" level=info msg="Layer sha256:b756c9eba456dd39bc076b393e2bd10a0f738ad402a9ccd2cdc2c2dbbe544433 cleaned up"
Nov 23 02:18:39 mahabharata dockerd[1447]: time="2016-11-23T02:18:39.738854823Z" level=warning msg="Your kernel does not support swap memory limit."
Nov 23 02:18:39 mahabharata dockerd[1447]: time="2016-11-23T02:18:39.738934830Z" level=warning msg="Your kernel does not support cgroup rt period"
Nov 23 02:18:39 mahabharata dockerd[1447]: time="2016-11-23T02:18:39.738949160Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Nov 23 02:18:40 mahabharata dockerd[1447]: time="2016-11-23T02:18:40.365958929Z" level=info msg="Layer sha256:8b27a5465f719c605c3d88ae932e5e8f7717a81aad25a134b0bcb343170f67cb cleaned up"
Nov 23 02:18:40 mahabharata dockerd[1447]: time="2016-11-23T02:18:40.526076691Z" level=info msg="Layer sha256:8b27a5465f719c605c3d88ae932e5e8f7717a81aad25a134b0bcb343170f67cb cleaned up"
Nov 23 02:18:40 mahabharata dockerd[1447]: time="2016-11-23T02:18:40.649486528Z" level=info msg="Layer sha256:8b27a5465f719c605c3d88ae932e5e8f7717a81aad25a134b0bcb343170f67cb cleaned up"
Nov 23 02:18:53 mahabharata dockerd[1447]: time="2016-11-23T02:18:53.220912673Z" level=warning msg="failed to upload schema2 manifest: unsupported: Unsupported manifest type: \"application/vnd.docker.distribution.manifest.v2+json\" - falling back to schema1"
Nov 23 02:25:30 mahabharata dockerd[1447]: time="2016-11-23T02:25:30.218788407Z" level=warning msg="failed to retrieve docker-init version: unknown output format"
Nov 23 02:27:32 mahabharata dockerd[1447]: time="2016-11-23T02:27:32.318481344Z" level=info msg="Layer sha256:0cbb916f47615faf74debd039717f472f862208268220e09f115ce79904cefd9 cleaned up"
Nov 23 02:27:32 mahabharata dockerd[1447]: time="2016-11-23T02:27:32.427475970Z" level=info msg="Layer sha256:0cbb916f47615faf74debd039717f472f862208268220e09f115ce79904cefd9 cleaned up"
Nov 23 02:27:32 mahabharata dockerd[1447]: time="2016-11-23T02:27:32.551730392Z" level=info msg="Layer sha256:0cbb916f47615faf74debd039717f472f862208268220e09f115ce79904cefd9 cleaned up"
Nov 23 02:27:44 mahabharata dockerd[1447]: time="2016-11-23T02:27:44.878716073Z" level=warning msg="Your kernel does not support swap memory limit."
Nov 23 02:27:44 mahabharata dockerd[1447]: time="2016-11-23T02:27:44.879858588Z" level=warning msg="Your kernel does not support cgroup rt period"
Nov 23 02:27:44 mahabharata dockerd[1447]: time="2016-11-23T02:27:44.880155697Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Nov 23 02:27:45 mahabharata dockerd[1447]: time="2016-11-23T02:27:45.353693294Z" level=info msg="Layer sha256:fc88793e6266b9eb1d8b79fdae6f46a795f8e48fcab6bef69ee3f3ad771749ed cleaned up"
Nov 23 02:27:45 mahabharata dockerd[1447]: time="2016-11-23T02:27:45.798902191Z" level=warning msg="Your kernel does not support swap memory limit."
Nov 23 02:27:45 mahabharata dockerd[1447]: time="2016-11-23T02:27:45.799205584Z" level=warning msg="Your kernel does not support cgroup rt period"
Nov 23 02:27:45 mahabharata dockerd[1447]: time="2016-11-23T02:27:45.799390230Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Nov 23 02:27:46 mahabharata dockerd[1447]: time="2016-11-23T02:27:46.184114166Z" level=info msg="Layer sha256:c72d01fe936d14c64c4b397d39586d12f13a227a5aea6254a9352c3530e927fd cleaned up"
Nov 23 02:27:46 mahabharata dockerd[1447]: time="2016-11-23T02:27:46.268663559Z" level=warning msg="Your kernel does not support swap memory limit."
Nov 23 02:27:46 mahabharata dockerd[1447]: time="2016-11-23T02:27:46.269012721Z" level=warning msg="Your kernel does not support cgroup rt period"
Nov 23 02:27:46 mahabharata dockerd[1447]: time="2016-11-23T02:27:46.269248850Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Nov 23 02:27:46 mahabharata dockerd[1447]: time="2016-11-23T02:27:46.660262246Z" level=info msg="Layer sha256:c72d01fe936d14c64c4b397d39586d12f13a227a5aea6254a9352c3530e927fd cleaned up"
Nov 23 02:27:46 mahabharata dockerd[1447]: time="2016-11-23T02:27:46.951650686Z" level=warning msg="Your kernel does not support swap memory limit."
Nov 23 02:27:46 mahabharata dockerd[1447]: time="2016-11-23T02:27:46.952049803Z" level=warning msg="Your kernel does not support cgroup rt period"
Nov 23 02:27:46 mahabharata dockerd[1447]: time="2016-11-23T02:27:46.952256547Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Nov 23 02:27:47 mahabharata dockerd[1447]: time="2016-11-23T02:27:47.531854818Z" level=info msg="Layer sha256:a67ca95f73cfe5f1c9daa0fc9a624909cb87f3bf62e00d487a31bb050fbd7bd6 cleaned up"
Nov 23 02:27:47 mahabharata dockerd[1447]: time="2016-11-23T02:27:47.652104759Z" level=info msg="Layer sha256:a67ca95f73cfe5f1c9daa0fc9a624909cb87f3bf62e00d487a31bb050fbd7bd6 cleaned up"
Nov 23 02:27:47 mahabharata dockerd[1447]: time="2016-11-23T02:27:47.796979281Z" level=info msg="Layer sha256:a67ca95f73cfe5f1c9daa0fc9a624909cb87f3bf62e00d487a31bb050fbd7bd6 cleaned up"
Nov 23 02:28:07 mahabharata dockerd[1447]: time="2016-11-23T02:28:07.581926790Z" level=warning msg="failed to upload schema2 manifest: unsupported: Unsupported manifest type: \"application/vnd.docker.distribution.manifest.v2+json\" - falling back to schema1"
Nov 23 02:28:07 mahabharata dockerd[1447]: http: panic serving @: could not find ':' in digest: 
                                           goroutine 899 [running]:
                                           net/http.(*conn).serve.func1(0xc420d09900)
                                                   /usr/local/go/src/net/http/server.go:1491 +0x12a
                                           panic(0x171efa0, 0xc420c52520)
                                                   /usr/local/go/src/runtime/panic.go:458 +0x243
                                           github.com/docker/docker/vendor/github.com/docker/distribution/digest.Digest.sepIndex(0x0, 0x0, 0xc421089d10)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/docker/distribution/digest/digest.go:135 +0xec
                                           github.com/docker/docker/vendor/github.com/docker/distribution/digest.Digest.Hex(0x0, 0x0, 0x26, 0xc4218e6000)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/docker/distribution/digest/digest.go:124 +0x35
                                           github.com/docker/docker/vendor/github.com/docker/distribution/manifest/schema1.(*configManifestBuilder).Build(0xc42034df10, 0x7f9662571158, 0xc4216ac480, 0x7f9662571158, 0xc4216ac480, 0x70, 0x17dbd20)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/docker/distribution/manifest/schema1/config_builder.go:135 +0x2ac
                                           github.com/docker/docker/distribution.manifestFromBuilder(0x23e9d00, 0xc4216ac480, 0x23e15c0, 0xc42034df10, 0xc420af0c00, 0x11, 0x20, 0x0, 0x0, 0x0, ...)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/push_v2.go:245 +0x120
                                           github.com/docker/docker/distribution.(*v2Pusher).pushV2Tag(0xc42095a600, 0x23e9d00, 0xc4216ac480, 0x23ed020, 0xc4220ada40, 0xc421fec190, 0x47, 0x0, 0x0)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/push_v2.go:200 +0x13df
                                           github.com/docker/docker/distribution.(*v2Pusher).pushV2Repository(0xc42095a600, 0x23e9d00, 0xc4216ac480, 0x0, 0xc420d09b80)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/push_v2.go:110 +0x251
                                           github.com/docker/docker/distribution.(*v2Pusher).Push(0xc42095a600, 0x23e9d00, 0xc4216ac480, 0xc420d09b80, 0x2)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/push_v2.go:79 +0x268
                                           github.com/docker/docker/distribution.Push(0x23e9d00, 0xc4216ac480, 0x23eb340, 0xc4225e62c0, 0xc420dd6090, 0xc4216fc420, 0xc4216fc540)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/push.go:149 +0x5f4
                                           github.com/docker/docker/daemon.(*Daemon).PushImage(0xc42039e000, 0x23e9d00, 0xc4216ac480, 0xc42095a113, 0x55, 0xc42095a16e, 0x0, 0xc4213a0f60, 0xc42184a2a0, 0x23d1140, ...)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/image_push.go:54 +0x34f
                                           github.com/docker/docker/api/server/router/image.(*imageRouter).postImagesPush(0xc420946200, 0x23e9d00, 0xc4216ac300, 0x23e65c0, 0xc4204700d0, 0xc422a5e0f0, 0xc4213a09c0, 0x0, 0x0)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/image/image_routes.go:163 +0x723
                                           github.com/docker/docker/api/server/router/image.(*imageRouter).(github.com/docker/docker/api/server/router/image.postImagesPush)-fm(0x23e9d00, 0xc4216ac300, 0x23e65c0, 0xc4204700d0, 0xc422a5e0f0, 0xc4213a09c0, 0xc4225e6210, 0x1)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/image/image.go:44 +0x69
                                           github.com/docker/docker/api/server/router.cancellableHandler.func1(0x23e9dc0, 0xc4213a0de0, 0x23e65c0, 0xc4204700d0, 0xc422a5e0f0, 0xc4213a09c0, 0x0, 0x0)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/local.go:84 +0x104
                                           github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x23e9dc0, 0xc4213a0de0, 0x23e65c0, 0xc4204700d0, 0xc422a5e0f0, 0xc4213a09c0, 0x19, 0x22)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
                                           github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x23e9dc0, 0xc4213a0cc0, 0x23e65c0, 0xc4204700d0, 0xc422a5e0f0, 0xc4213a09c0, 0x19cc8ea, 0x413545)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:47 +0x5ca
                                           github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x23e9dc0, 0xc4213a0cc0, 0x23e65c0, 0xc4204700d0, 0xc422a5e0f0, 0xc4213a09c0, 0xc42094daf0, 0x75500b)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/authorization/middleware.go:43 +0x83f
                                           github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x23e65c0, 0xc4204700d0, 0xc422a5e0f0)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x233
                                           net/http.HandlerFunc.ServeHTTP(0xc420a27c20, 0x23e65c0, 0xc4204700d0, 0xc422a5e0f0)
                                                   /usr/local/go/src/net/http/server.go:1726 +0x44
                                           github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202262d0, 0x23e65c0, 0xc4204700d0, 0xc422a5e0f0)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
                                           github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc420783110, 0x23e65c0, 0xc4204700d0, 0xc422a5e0f0)
                                                   /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
                                           net/http.serverHandler.ServeHTTP(0xc42027fb80, 0x23e65c0, 0xc4204700d0, 0xc422a5e0f0)
                                                   /usr/local/go/src/net/http/server.go:2202 +0x7d
                                           net/http.(*conn).serve(0xc420d09900, 0x23e8200, 0xc4219b4300)
                                                   /usr/local/go/src/net/http/server.go:1579 +0x4b7
                                           created by net/http.(*Server).Serve
                                                   /usr/local/go/src/net/http/server.go:2293 +0x44d
Nov 23 02:28:23 mahabharata dockerd[1447]: time="2016-11-23T02:28:23.280074896Z" level=warning msg="failed to upload schema2 manifest: unsupported: Unsupported manifest type: \"application/vnd.docker.distribution.manifest.v2+json\" - falling back to schema1"


```
