### ISSUE TITLE
Write multiple log files to the stdout in parallel

### ISSUE THREAD

**Issue by speechkey** [docker/docker#28752]
I have following use case. There is a process which runs in a docker container. The process writes two logs in parallel: `process.log` and `connection.log`. Both are linked to the `/dev/stdout` by `ln -sf /dev/stdout process.log` and `ln -sf /dev/stdout connection.log`. If a Java exception with a stacktrace have to be written to the both logs to the same time following is written:
```
Exception in thread "main" Exception in thread "main" java.lang.NumberFormatException: For input string: "Hello Integer!!!"java.lang.NumberFormatException: For input string: "Hello Integer!!!"

    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at HelloInteger.main(HelloInteger.java:3)
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at HelloInteger.main(HelloInteger.java:3)
```

On that way the logs should be written:

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "Hello Integer!!!"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at HelloInteger.main(HelloInteger.java:3)
Exception in thread "main" java.lang.NumberFormatException: For input string: "Hello Long!!!"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Long.parseLong(Long.java:589)
    at java.lang.Long.parseLong(Long.java:631)
    at HelloLong.main(HelloLong.java:3)
```

**Comment by cpuguy83** [comment]
Yep, it's a problem. The logger in java should synchronize access to the output stream.
Docker is only consuming what's sent to the stdio streams and breaks them up by line.

http://stackoverflow.com/questions/7469316/why-is-exception-printstacktrace-considered-bad-practice seems to have a pretty good explaination.

Closing as this does not seem to be a Docker issue.
