### ISSUE TITLE
docker ps does not complete, possible goroutine leak

### ISSUE THREAD

**Issue by nickethier** [docker/docker#28767]
**Description**

The docker daemon does no respond to the ps command and the stackdump seems suspect that there is a goroutine leak. The daemon had been running for about 36 hours when this started to occur.

**Steps to reproduce the issue:**
One of our kubernetes workers started failing to make requests to docker. 
I don't have specific steps to reproduce yet

**Describe the results you received:**
docker ps hangs indefinitely
remote api requests to list containers timeout or don't complete

**Describe the results you expected:**
docker ps and similar requests to he API should not timeout

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 91
 Running: 71
 Paused: 0
 Stopped: 20
Images: 51
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.7.3-coreos-r2
Operating System: CoreOS 1185.3.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 62.95 GiB
Name: bm08
ID: SSUD:OJ6I:HONF:HLYI:NKWP:D4EN:UC7Q:RYPC:MLH7:TEKI:XBK2:TDQJ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on a physical host.

There are alot of goroutines referenced to `github.com/vishvananda/netlink.LinkSubscribe`. 
I am using a custom network setup in kubernetes where after the container is created with bridge networking, I add a couple additional interfaces configured by a third party process.

[dockerd_stackdump.txt](https://github.com/docker/docker/files/609546/dockerd_stackdump.txt)

**Comment by cpuguy83** [comment]
Looks like it's stuck waiting to receive a netlink message back from the kernel.
Can you check `dmesg`?

**Comment by cpuguy83** [comment]
Here's the blocking thread:

```
goroutine 333245 [syscall, 1036 minutes, locked to thread]:
syscall.Syscall6(0x2d, 0x3d, 0xc83903b000, 0x1000, 0x0, 0xc840118028, 0xc840118024, 0x0, 0xc840117f87, 0x66b5a6)
	/usr/lib/go1.6/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.recvfrom(0x3d, 0xc83903b000, 0x1000, 0x1000, 0x0, 0xc840118028, 0xc840118024, 0x427289, 0x0, 0x0)
	/usr/lib/go1.6/src/syscall/zsyscall_linux_amd64.go:1712 +0x9e
syscall.Recvfrom(0x3d, 0xc83903b000, 0x1000, 0x1000, 0x0, 0x1000, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go1.6/src/syscall/syscall_unix.go:251 +0xb9
github.com/vishvananda/netlink/nl.(*NetlinkSocket).Receive(0xc8409ead20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/vendor/src/github.com/vishvananda/netlink/nl/nl_linux.go:341 +0xae
github.com/vishvananda/netlink/nl.(*NetlinkRequest).Execute(0xc83fc4ccc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/vendor/src/github.com/vishvananda/netlink/nl/nl_linux.go:228 +0x20b
github.com/vishvananda/netlink.LinkSetMasterByIndex(0x7fd0acd7a2b0, 0xc839ef45a0, 0xe, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/vendor/src/github.com/vishvananda/netlink/link_linux.go:231 +0x3b0
github.com/vishvananda/netlink.LinkSetMaster(0x7fd0acd7a2b0, 0xc839ef45a0, 0xc840118550, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/vendor/src/github.com/vishvananda/netlink/link_linux.go:205 +0xb7
github.com/docker/libnetwork/drivers/bridge.addToBridge(0xc83e0cef50, 0xb, 0x177bf88, 0x7, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go:782 +0x275
github.com/docker/libnetwork/drivers/bridge.(*driver).CreateEndpoint(0xc820272690, 0xc820228d00, 0x40, 0xc840574e00, 0x40, 0x7fd0acd7a268, 0xc82143a700, 0xc83bdc69f0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go:1004 +0x1436
github.com/docker/libnetwork.(*network).addEndpoint(0xc82a5a17a0, 0xc837b36700, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/vendor/src/github.com/docker/libnetwork/network.go:749 +0x21b
github.com/docker/libnetwork.(*network).CreateEndpoint(0xc82a5a17a0, 0xc83dfdee41, 0x5c, 0xc83e4f24e0, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/vendor/src/github.com/docker/libnetwork/network.go:813 +0xaa7
github.com/docker/docker/daemon.(*Daemon).connectToNetwork(0xc820420a80, 0xc8411a8c40, 0x177aea8, 0x6, 0xc8210af140, 0x0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/daemon/container_operations.go:539 +0x39f
github.com/docker/docker/daemon.(*Daemon).allocateNetwork(0xc820420a80, 0xc8411a8c40, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/daemon/container_operations.go:401 +0x373
github.com/docker/docker/daemon.(*Daemon).initializeNetworking(0xc820420a80, 0xc8411a8c40, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/daemon/container_operations.go:680 +0x459
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc820420a80, 0xc8411a8c40, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/daemon/start.go:125 +0x219
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc820420a80, 0xc83feb9451, 0x40, 0x0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/daemon/start.go:75 +0x575
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStart(0xc820796510, 0x7fd0acdc2030, 0xc83f1e1a40, 0x7fd0a0739130, 0xc8354260d0, 0xc8383c4ee0, 0xc83f1e19b0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:160 +0x114
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStart)-fm(0x7fd0acdc2030, 0xc83f1e1a40, 0x7fd0a0739130, 0xc8354260d0, 0xc8383c4ee0, 0xc83f1e19b0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:47 +0x74
github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7fd0acdc2030, 0xc83f1e1a40, 0x7fd0a0739130, 0xc8354260d0, 0xc8383c4ee0, 0xc83f1e19b0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43
github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7fd0acdc2030, 0xc83f1e1a10, 0x7fd0a0739130, 0xc8354260d0, 0xc8383c4ee0, 0xc83f1e19b0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:34 +0x6a9
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fd0a0739130, 0xc8354260d0, 0xc8383c4ee0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/server.go:132 +0x138
net/http.HandlerFunc.ServeHTTP(0xc82046f740, 0x7fd0a0739130, 0xc8354260d0, 0xc8383c4ee0)
	/usr/lib/go1.6/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8200bfef0, 0x7fd0a0739130, 0xc8354260d0, 0xc8383c4ee0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8207fdbc0, 0x7fd0a0739130, 0xc8354260d0, 0xc8383c4ee0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.11.2-r5/work/docker-1.11.2/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc8202b3c00, 0x7fd0a0739130, 0xc8354260d0, 0xc8383c4ee0)
	/usr/lib/go1.6/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82be05c00)
	/usr/lib/go1.6/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/lib/go1.6/src/net/http/server.go:2137 +0x44e
```

**Comment by nickethier** [comment]
I believe this to be a bug in our networking agent that caused netlink to be overwhelmed with messages. I'm unable to reproduce but if I find this is not the case, I will reopen this issue. Thanks for taking a look.

**Comment by cpuguy83** [comment]
@nickethier Thanks for letting us know!
