### ISSUE TITLE
Docker daemon panic with: fatal error: bad map state

### ISSUE THREAD

**Issue by weekface** [docker/docker#29499]
**Description**

Docker daemon panic.

**Steps to reproduce the issue:**

**Describe the results you received:**
```
Dec 17 16:12:08 10 docker[32579]: fatal error: bad map state
Dec 17 16:12:08 10 docker[32579]: goroutine 525825 [running]:
Dec 17 16:12:08 10 docker[32579]: runtime.throw(0x171bf30, 0xd)
Dec 17 16:12:08 10 docker[32579]: #011/usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xc834fa0c08 sp=0xc834fa0bf0
Dec 17 16:12:08 10 docker[32579]: runtime.evacuate(0x1234780, 0xc820737ce0, 0x0)
Dec 17 16:12:08 10 docker[32579]: #011/usr/local/go/src/runtime/hashmap.go:825 +0x3b1 fp=0xc834fa0cc8 sp=0xc834fa0c08
Dec 17 16:12:08 10 docker[32579]: runtime.growWork(0x1234780, 0xc820737ce0, 0x1b1)
Dec 17 16:12:08 10 docker[32579]: #011/usr/local/go/src/runtime/hashmap.go:795 +0x83 fp=0xc834fa0ce8 sp=0xc834fa0cc8
Dec 17 16:12:08 10 docker[32579]: runtime.mapassign1(0x1234780, 0xc820737ce0, 0xc834fa0ed0, 0xc834fa0e00)
Dec 17 16:12:08 10 docker[32579]: #011/usr/local/go/src/runtime/hashmap.go:433 +0x176 fp=0xc834fa0d90 sp=0xc834fa0ce8
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/daemon/graphdriver/aufs.(*Driver).Create(0xc820241ef0, 0xc825269270, 0x45, 0xc820a687c0, 0x40, 0x0, 0x0, 0x0, 0x0)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/daemon/graphdriver/aufs/aufs.go:230 +0x6e7 fp=0xc834fa0f70 sp=0xc834fa0d90
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/layer.(*layerStore).initMount(0xc82021cd40, 0xc82c597f00, 0x40, 0xc820a687c0, 0x40, 0x0, 0x0, 0xc831bd36b0, 0x0, 0x0, ...)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/layer/layer_store.go:559 +0x1c9 fp=0xc834fa1068 sp=0xc834fa0f70
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/layer.(*layerStore).CreateRWLayer(0xc82021cd40, 0xc82c597c00, 0x40, 0xc8252691d0, 0x47, 0x0, 0x0, 0xc831bd36b0, 0x0, 0x0, ...)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/layer/layer_store.go:454 +0x452 fp=0xc834fa1178 sp=0xc834fa1068
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/daemon.(*Daemon).setRWLayer(0xc8205eed80, 0xc82ac72380, 0x0, 0x0)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/daemon/create.go:158 +0x1f9 fp=0xc834fa1248 sp=0xc834fa1178
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/daemon.(*Daemon).create(0xc8205eed80, 0xc82f2e676d, 0x61, 0xc8250c2800, 0xc822ab6600, 0x0, 0x0, 0x0, 0x0, 0x0)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/daemon/create.go:87 +0x32a fp=0xc834fa13a0 sp=0xc834fa1248
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/daemon.(*Daemon).ContainerCreate(0xc8205eed80, 0xc82f2e676d, 0x61, 0xc8250c2800, 0xc822ab6600, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/daemon/create.go:42 +0x4a4 fp=0xc834fa1448 sp=0xc834fa13a0
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersCreate(0xc829aff2c0, 0x7f26044a1d20, 0xc82b0be660, 0x7f26044a1bf0, 0xc8298873f0, 0xc8307d2460, 0xc82b0be600, 0x0, 0x0)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/api/server/router/container/container_routes.go:381 +0x30f fp=0xc834fa1600 sp=0xc834fa1448
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersCreate)-fm(0x7f26044a1d20, 0xc82b0be660, 0x7f26044a1bf0, 0xc8298873f0, 0xc8307d2460, 0xc82b0be600, 0x0, 0x0)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/api/server/router/container/container.go:45 +0x74 fp=0xc834fa1650 sp=0xc834fa1600
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/api/server.versionMiddleware.func1(0x7f26044a1d20, 0xc82b0be660, 0x7f26044a1bf0, 0xc8298873f0, 0xc8307d2460, 0xc82b0be600, 0x0, 0x0)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a fp=0xc834fa17d0 sp=0xc834fa1650
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7f260f098ce8, 0xc820089440, 0x7f26044a1bf0, 0xc8298873f0, 0xc8307d2460, 0xc82b0be600, 0x0, 0x0)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa fp=0xc834fa1830 sp=0xc834fa17d0
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7f260f098ce8, 0xc820089440, 0x7f26044a1bf0, 0xc8298873f0, 0xc8307d2460, 0xc82b0be600, 0x0, 0x0)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be fp=0xc834fa1940 sp=0xc834fa1830
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f26044a1bf0, 0xc8298873f0, 0xc8307d2460)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/api/server/server.go:169 +0x2ad fp=0xc834fa1a68 sp=0xc834fa1940
Dec 17 16:12:08 10 docker[32579]: net/http.HandlerFunc.ServeHTTP(0xc8293a90a0, 0x7f26044a1bf0, 0xc8298873f0, 0xc8307d2460)
Dec 17 16:12:08 10 docker[32579]: #011/usr/local/go/src/net/http/server.go:1422 +0x3a fp=0xc834fa1a88 sp=0xc834fa1a68
Dec 17 16:12:08 10 docker[32579]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc8299da7d0, 0x7f26044a1bf0, 0xc8298873f0, 0xc8307d2460)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e fp=0xc834fa1ba0 sp=0xc834fa1a88
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8292a3c90, 0x7f26044a1bf0, 0xc8298873f0, 0xc8307d2460)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72 fp=0xc834fa1bd0 sp=0xc834fa1ba0
Dec 17 16:12:08 10 docker[32579]: net/http.serverHandler.ServeHTTP(0xc820086a80, 0x7f26044a1bf0, 0xc8298873f0, 0xc8307d2460)
Dec 17 16:12:08 10 docker[32579]: #011/usr/local/go/src/net/http/server.go:1862 +0x19e fp=0xc834fa1c30 sp=0xc834fa1bd0
Dec 17 16:12:08 10 docker[32579]: net/http.(*conn).serve(0xc831cf3550)
Dec 17 16:12:08 10 docker[32579]: #011/usr/local/go/src/net/http/server.go:1361 +0xbee fp=0xc834fa1f88 sp=0xc834fa1c30
Dec 17 16:12:08 10 docker[32579]: runtime.goexit()
Dec 17 16:12:08 10 docker[32579]: #011/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc834fa1f90 sp=0xc834fa1f88
Dec 17 16:12:08 10 docker[32579]: created by net/http.(*Server).Serve
Dec 17 16:12:08 10 docker[32579]: #011/usr/local/go/src/net/http/server.go:1910 +0x3f6
Dec 17 16:12:08 10 docker[32579]: goroutine 1 [chan receive, 7390 minutes]:
Dec 17 16:12:08 10 docker[32579]: main.(*DaemonCli).CmdDaemon(0xc820261420, 0xc820090020, 0x22, 0x22, 0x0, 0x0)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/docker/daemon.go:305 +0x20a7
Dec 17 16:12:08 10 docker[32579]: reflect.callMethod(0xc820736e40, 0xc8295a7c78)
Dec 17 16:12:08 10 docker[32579]: #011/usr/local/go/src/reflect/value.go:628 +0x1fc
Dec 17 16:12:08 10 docker[32579]: reflect.methodValueCall(0xc820090020, 0x22, 0x22, 0x1, 0xc820736e40, 0x0, 0x0, 0xc820736e40, 0x0, 0x4745b4, ...)
Dec 17 16:12:08 10 docker[32579]: #011/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
Dec 17 16:12:08 10 docker[32579]: github.com/docker/docker/cli.(*Cli).Run(0xc820736db0, 0xc820090010, 0x23, 0x23, 0x0, 0x0)
Dec 17 16:12:08 10 docker[32579]: #011/go/src/github.com/docker/docker/cli/cli.go:89 +0x383
Dec 17 16:12:08 10 docker[32579]: main.main()
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 15
 Running: 11
 Paused: 0
 Stopped: 4
Images: 2850
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 8914
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 94.37 GiB
Name: 10.130
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I think we should lock before operate the `active` attribute:
https://github.com/docker/docker/blob/v1.10.3/daemon/graphdriver/aufs/aufs.go#L230

```
// Create three folders for each id
// mnt, layers, and diff
func (a *Driver) Create(id, parent, mountLabel string) error {
	if err := a.createDirsFor(id); err != nil {
		return err
	}
	// Write the layers metadata
	f, err := os.Create(path.Join(a.rootPath(), "layers", id))
	if err != nil {
		return err
	}
	defer f.Close()

	if parent != "" {
		ids, err := getParentIds(a.rootPath(), parent)
		if err != nil {
			return err
		}

		if _, err := fmt.Fprintln(f, parent); err != nil {
			return err
		}
		for _, i := range ids {
			if _, err := fmt.Fprintln(f, i); err != nil {
				return err
			}
		}
	}
	a.active[id] = &data{}
	return nil
}
```

**Comment by justincormack** [comment]
This code seems to have changed a lot to master, can you replicate on a more recent version of Docker?

**Comment by weekface** [comment]
The panic do not always happen, after 40 days running, it only happen once,  i can't replicate. I use docker 1.10.3.

**Comment by weekface** [comment]
Docker 1.10 no longer maintained?

**Comment by thaJeztah** [comment]
Docker 1.10 is no longer maintained, correct.

**Comment by weekface** [comment]
OK
