### ISSUE TITLE
Cannot run hello-world container on Raspberry Pi 3 model B

### ISSUE THREAD

**Issue by piribes** [docker/docker#29617]
**Description**
After installation, while running hello-world container.

**Steps to reproduce the issue:**
1. Follow the installation guide at https://docs.docker.com/engine/installation/linux/debian/
2. Run sudo docker run hello-world 

**Describe the results you received:**

```
pi@meta:~ $ sudo docker run hello-world
panic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x335e30, 0x56e47280)
	/usr/local/go/src/runtime/panic.go:481 +0x330
github.com/urfave/cli.HandleAction.func1(0x56e9f958)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x328
panic(0x335e30, 0x56e47280)
	/usr/local/go/src/runtime/panic.go:443 +0x448
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0x56e9f5e0, 0x56dca308, 0x56e9f668)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x13c
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x56e44360, 0x4641f4b8, 0x56e47280)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x498
main.glob.func8(0x56e561e0, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x58
reflect.Value.call(0x2eb380, 0x3f26c8, 0x13, 0x364638, 0x4, 0x56e9f918, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0xeb4
reflect.Value.Call(0x2eb380, 0x3f26c8, 0x13, 0x56e9f918, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0x84
github.com/urfave/cli.HandleAction(0x2eb380, 0x3f26c8, 0x56e561e0, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x230
github.com/urfave/cli.Command.Run(0x366a58, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3d0ad0, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xcd0
github.com/urfave/cli.(*App).Run(0x56e30240, 0x56e12050, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0x84c
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xbb4
```
**Describe the results you expected:**

Hello from Docker!
This message shows that your installation appears to be working correctly.
[...]

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 03:20:35 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 03:20:35 2016
 OS/Arch:      linux/arm
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-179:2-134157-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 515.2 MB
 Data Space Total: 107.4 GB
 Data Space Available: 13.35 GB
 Metadata Space Used: 1.208 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.4.38-v7+
Operating System: Raspbian GNU/Linux 8 (jessie)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 925.5 MiB
Name: meta
ID: YZNI:JOJG:FNGF:MIL2:NCY6:A2SG:VYLI:MVFU:VY2T:VUTZ:VTLF:MH6X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpuset support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm running docker-engine Raspberry Pi 3 model B.
Uname: Linux meta 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux

**Comment by piribes** [comment]
Something similar happen with docker 1.12.2 on Fedora Server 25 for ARM.

```
Client:
 Version:         1.12.2
 API version:     1.24
 Package version: docker-common-1.12.2-5.git8f1975c.fc25.armv7hl
docker-common-1.12.5-1.git6009905.fc25.armv7hl
 Go version:      go1.7.1
 Git commit:      8f1975c/1.12.2
 Built:           
 OS/Arch:         linux/arm

Server:
 Version:         1.12.2
 API version:     1.24
 Package version: docker-common-1.12.2-5.git8f1975c.fc25.armv7hl
docker-common-1.12.5-1.git6009905.fc25.armv7hl
 Go version:      go1.7.1
 Git commit:      8f1975c/1.12.2
 Built:           
 OS/Arch:         linux/arm
```

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: docker-179:4-7031042-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 118.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 957.7 MB
 Metadata Space Used: 778.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 957.7 MB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.136 (2016-11-05)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Security Options: seccomp selinux
Kernel Version: 4.8.6-300.fc25.armv7hl
Operating System: Fedora 25 (Server Edition)
OSType: linux
Architecture: armv7l
Number of Docker Hooks: 0
CPUs: 4
Total Memory: 970 MiB
Name: localhost.localdomain
ID: Y3IJ:NIVU:X5UU:4CPF:PBQM:42SK:2UIH:VMFW:TKLS:J6DT:L3OX:GX3U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
```

```
Unable to find image 'docker/compose:1.9.0' locally
Trying to pull repository docker.io/docker/compose ... 
sha256:0e6c00cf72b8e472f22c23850b3095a488f296a4c1aebbe112dc5537f05e4f25: Pulling from docker.io/docker/compose
3690ec4760f9: Pull complete 
859748e15ac4: Pull complete 
732b292049b6: Pull complete 
fbd985eb0de8: Pull complete 
fa2d81037e59: Pull complete 
b2057161a631: Pull complete 
Digest: sha256:0e6c00cf72b8e472f22c23850b3095a488f296a4c1aebbe112dc5537f05e4f25
Status: Downloaded newer image for docker.io/docker/compose:1.9.0
panic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x2feec0, 0x96d9f580)
	/usr/lib/golang/src/runtime/panic.go:500 +0x33c
github.com/urfave/cli.HandleAction.func1(0x96de996c)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/runc-fa7507b73f54fca716eef4f78d3ea2dc9307f7f9/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x290
panic(0x2feec0, 0x96d9f580)
	/usr/lib/golang/src/runtime/panic.go:458 +0x454
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0x96de9600, 0x96d1c600, 0x96de9680)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/runc-fa7507b73f54fca716eef4f78d3ea2dc9307f7f9/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x100
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x96d4a6c0, 0x45e250, 0x96d9f580)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/runc-fa7507b73f54fca716eef4f78d3ea2dc9307f7f9/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x420
main.glob..func8(0x96d881e0, 0x0, 0x0)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/runc-fa7507b73f54fca716eef4f78d3ea2dc9307f7f9/main_unix.go:26 +0x58
reflect.Value.call(0x2e2250, 0x35b910, 0x13, 0x325485, 0x4, 0x96de992c, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/lib/golang/src/reflect/value.go:434 +0xd68
reflect.Value.Call(0x2e2250, 0x35b910, 0x13, 0x96de992c, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/reflect/value.go:302 +0x84
github.com/urfave/cli.HandleAction(0x2e2250, 0x35b910, 0x96d881e0, 0x0, 0x0)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/runc-fa7507b73f54fca716eef4f78d3ea2dc9307f7f9/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x1d0
github.com/urfave/cli.Command.Run(0x325655, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x336d32, 0x51, 0x0, ...)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/runc-fa7507b73f54fca716eef4f78d3ea2dc9307f7f9/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xc10
github.com/urfave/cli.(*App).Run(0x96d7e240, 0x96d0c090, 0x2, 0x2, 0x0, 0x0)
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/runc-fa7507b73f54fca716eef4f78d3ea2dc9307f7f9/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0x798
main.main()
	/builddir/build/BUILD/docker-8f1975c49713e745856f5861e9602c36ed0bcaa6/runc-fa7507b73f54fca716eef4f78d3ea2dc9307f7f9/main.go:137 +0xb1c
```

Linux localhost.localdomain 4.8.6-300.fc25.armv7hl #1 SMP Tue Nov 1 14:46:32 UTC 2016 armv7l armv7l armv7l GNU/Linux

**Comment by justincormack** [comment]
The images you are running are not compiled for arm. Try docker run
armhf/hello-world

**Comment by piribes** [comment]
Thank you, that works. It is ugly, but works.

**Comment by piribes** [comment]
So I guess that armhf containers cannot start FROM non-armhf containers, is it right ?

**Comment by cpuguy83** [comment]
@piribes Correct. There is no virtualization layer.
Closing since this is a non-issue.

**Comment by alexellis** [comment]
Hey, I do a lot of work with ARM and the Raspberry Pi. Have a read of this - and see if it's useful too. http://blog.alexellis.io/5-things-docker-rpi/

**Comment by piribes** [comment]
@cpuguy83 @justincormack Thanks. Is it possible to get an an error message, when we try to execute containers for a different architecture ?

**Comment by piribes** [comment]
@alexellis Thank you.

**Comment by thaJeztah** [comment]
There is an "official" [armhf/hello-world](https://hub.docker.com/r/armhf/hello-world/) image; can you try `sudo docker run armhf/hello-world` ?

**Comment by piribes** [comment]
@thaJeztah It works perfectly, thank you

**Comment by IanEdington** [comment]
For googlers check the Sha-Bang on your Entrypoint and CMD scripts.

#!/bin/bash

**Comment by alexellis** [comment]
See also armhf/alpine and blog.alexellis.io for Pi + Docker tutorials.

**Comment by alexellis** [comment]
@IanEdington what's the connection to arm vs. x86 images?

**Comment by IanEdington** [comment]
@alexellis This issue ranks high in google for the `standard_init_linux.go:175: exec user process caused "exec format error"` error. Forgetting the Sha-Bang is a common error. I just mentioned it here for people getting to this page by google searching for that error, no other reason. Sorry for the noise.

**Comment by LiJohnson** [comment]
Does that means all docker images need to rebuild in arm while using docker on RPI

**Comment by cpuguy83** [comment]
@LiJohnson Some official images now support multi-arch in the main image, but generally yes you do need the correct image for the platform.

**Comment by atline** [comment]
> @LiJohnson Some official images now support multi-arch in the main image, but generally yes you do need the correct image for the platform.

So, @cpuguy83 , does this mean, nowadays, for example on arm64 platform, we could directly use `docker pull ubuntu:latest`?

**Comment by cpuguy83** [comment]
Yes.

**Comment by thaJeztah** [comment]
you can find which architectures are supported for each tag on the tags tab on docker hub; https://hub.docker.com/_/ubuntu?tab=tags

**Comment by cpuguy83** [comment]
I also wrote a tool to inspect the raw registry objects, which will list the platforms for you: https://github.com/cpuguy83/zapp
Don't expect me to debug issues for you, though 😇 👼
