### ISSUE TITLE
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]

### ISSUE THREAD

**Issue by yeruisen** [docker/docker#29813]
When I build image, and Dockerfile:
```
FROM centos:6.8
RUN adduser tomcat
RUN usermod -G tomcat tomcat

WORKDIR /home/tomcat
ENV RMI_SERVER_NAME=localhost \
SET_JVM_Xms=2048m \
SET_JVM_Xmx=2048m \
SET_JVM_Xmn=268m \
SET_JVM_Xss=256k \
SET_JVM_XXPermSize=64m \
SET_JVM_XXMaxPermSize=256m
#外界得覆盖该环境变量
#ENV APPNAME=APP

#查看仓库是否有中文包
RUN yum grouplist |grep -i chinese
#安装中文语言包
RUN yum groupinstall Chinese-support -y

#设置支持中文语言
ENV LANG=zh_CN.utf8


COPY jdk1.6.0_38/ /usr/local/java/

RUN echo "开始安装zip" && \
yum install unzip -y && \
echo "安装成功"

RUN echo "开始安装git" && \
yum install git -y && \
echo "git 安装完成"

RUN mkdir -p /data/www/ROOT/

COPY tomcat/ /home/tomcat/tomcat/
COPY static/ /data/www/ROOT/
COPY java.sh /etc/profile.d

#远程debug 端口
EXPOSE 5801
EXPOSE 80

```

and then , throw exception：
```
Sending build context to Docker daemon 221.8 MB
Step 1 : FROM centos:6.8
 ---> 0cd976dc0a98
Step 2 : MAINTAINER yeruisen <yeruisen@sina.cn>
 ---> Using cache
 ---> 6e456ba49dcd
Step 3 : RUN adduser tomcat
 ---> Using cache
 ---> eaf24eac672e
Step 4 : RUN usermod -G tomcat tomcat
 ---> Using cache
 ---> 29dea361c5ed
Step 5 : WORKDIR /home/tomcat
 ---> Using cache
 ---> 3e921c5b824a
Step 6 : ENV RMI_SERVER_NAME localhost SET_JVM_Xms 2048m SET_JVM_Xmx 2048m SET_JVM_Xmn 268m SET_JVM_Xss 256k SET_JVM_XXPermSize 64m SET_JVM_XXMaxPermSize 256m
 ---> Using cache
 ---> 9e4a2edace24
Step 7 : RUN yum grouplist |grep -i chinese
 ---> Using cache
 ---> bd9fe81590b7
Step 8 : RUN yum groupinstall Chinese-support -y
 ---> Using cache
 ---> 5b621dcd5b2b
Step 9 : ENV LANG zh_CN.utf8
 ---> Using cache
 ---> aba17c6ec872
Step 10 : COPY jdk1.6.0_38/ /usr/local/java/
 ---> Using cache
 ---> 4fd2632a2ed5
Step 11 : RUN echo "开始安装zip" && yum install unzip -y && echo "安装成功"
 ---> Using cache
 ---> 5f56d4c9156d
Step 12 : RUN echo "开始安装git" && yum install git -y && echo "git 安装完成"
 ---> Using cache
 ---> 506b2cefc345
Step 13 : RUN mkdir -p /data/www/ROOT/
 ---> Running in 2408c17fde9c
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
        panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x7e9de0, 0xc8201682a0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8201292e8)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7e9de0, 0xc8201682a0)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc820128bf8, 0xc8200420c8, 0xc820128d08)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820081630, 0x7f56f36c0728, 0xc8201682a0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc8200a2a00, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74e5e0, 0x8ffda0, 0x13, 0x846308, 0x4, 0xc820129268, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74e5e0, 0x8ffda0, 0x13, 0xc820129268, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74e5e0, 0x8ffda0, 0xc8200a2a00, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x8491b8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8df0e0, 0x51, 0x0, ...)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001b00, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
        /go/src/github.com/opencontainers/runc/main.go:137 +0xe24
The command '/bin/sh -c mkdir -p /data/www/ROOT/' returned a non-zero code: 2
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 22
 Running: 19
 Paused: 0
 Stopped: 3
Images: 202
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-8594930304-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 34.81 GB
 Data Space Total: 107.4 GB
 Data Space Available: 72.57 GB
 Metadata Space Used: 64.86 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.083 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: active
 NodeID: 0ucr4iuloh1yydwe6oydplq4k
 Is Manager: false
 Node Address: 192.168.1.38
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.87 GiB
Name: 1.38
ID: ZPCQ:YE7G:IVZD:J7MT:5C2X:EXZU:VOOW:77AF:CCP2:W6LA:I5RY:SQOJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
custom physical , centos 7.2

**Comment by yeruisen** [comment]
my base image have a problem.
