### ISSUE TITLE
docker-engine 1.12.2, build a8c3fe4 - --security-opt=no-new-privileges causes a go panic

### ISSUE THREAD

**Issue by smuthali** [docker/docker#29928]
**Description**
docker-engine throws a panic when I attempt to use ```--security-opt=no-new-privileges```

I am attempting to use no-new-privileges flag in docker

Reference: 
```
http://www.projectatomic.io/blog/2016/03/no-new-privs-docker/
```

**Steps to reproduce the issue:**
1. Issue a ``` docker run ``` something along the lines

```
docker run --name=foo --rm --cap-drop=SETUID --cap-drop=SETGID -u $UID:$(id -g) --security-opt=no-new-privileges foo-image:1.0.0 whoami

```

**Describe the results you received:**
The following go exception/traceback is seen

```
panic: standard_init_linux.go:175: exec user process caused "operation not permitted" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "operation not permitted"

goroutine 1 [running, locked to thread]:
panic(0x7ea140, 0xc8201477a0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc82013f2e8)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7ea140, 0xc8201477a0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc82013ebf8, 0xc820036088, 0xc82013ed08)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc8200807d0, 0x7fa6f4bfa470, 0xc8201477a0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc8200a6780, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74ea40, 0x900280, 0x13, 0x846788, 0x4, 0xc82013f268, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74ea40, 0x900280, 0x13, 0xc82013f268, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74ea40, 0x900280, 0xc8200a6780, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x849648, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8df580, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001980, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
```

**Additional information you deem important (e.g. issue happens only occasionally):**

** OS **

```
Oracle Linux Server release 7.3
```
**Output of `docker version`:**
```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 68
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: vg_ngs_app-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 41.22 GB
 Data Space Total: 268.4 GB
 Data Space Available: 227.2 GB
 Metadata Space Used: 9.617 MB
 Metadata Space Total: 16.98 GB
 Metadata Space Available: 16.97 GB
 Thin Pool Minimum Free Space: 26.84 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
 Authorization: docker-acl-plugin
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.1.12-61.1.23.el7uek.x86_64
Operating System: Oracle Linux Server 7.3
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 125.5 GiB
Name: rn2-apgd-lapp01.<REDACTED>
ID: HF2H:RU4L:WUE5:2QJS:YAU6:RQ57:NYHG:55QJ:4PIS:EXDK:7XKO:DY6J
Docker Root Dir: /ngs/app/docker_storage
Debug Mode (client): false
Debug Mode (server): false

```
```
rpm -qa | grep docker
docker-engine-1.12.2-1.0.1.el7.x86_64

```

```
rpm -qa | grep selinux
libselinux-utils-2.5-6.el7.x86_64
selinux-policy-targeted-3.13.1-102.0.2.el7_3.7.noarch
libselinux-python-2.5-6.el7.x86_64
selinux-policy-3.13.1-102.0.2.el7_3.7.noarch
libselinux-2.5-6.el7.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical server (docker running on bare metal)

**Comment by thaJeztah** [comment]
ping @mlaventure

**Comment by smuthali** [comment]
Many thanks for looking in to this. Please let me know if I can provide any additional info.

**Comment by justincormack** [comment]
It works for me with 1.13.0-rc5 

```
docker run  --rm --cap-drop=SETUID --cap-drop=SETGID -u nobody:nogroup --security-opt=no-new-privileges alpine whoami
nobody
```

I will check on earlier versions. Odd, as I don't remember any related code changing.

Does it make a difference if you add `--security-opt seccomp=unconfined`?

**Comment by smuthali** [comment]
@justincormack - 
```
docker run --name=foo --rm --cap-drop=SETUID --cap-drop=SETGID -u $UID:$(id -g) --security-opt=no-new-privileges --security-opt seccomp=unconfined foo-test:1.0 whoami
```
```
panic: standard_init_linux.go:175: exec user process caused "operation not permitted" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "operation not permitted"

goroutine 1 [running, locked to thread]:
panic(0x7ea140, 0xc8201195e0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc82010d2e8)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7ea140, 0xc8201195e0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc82010cbf8, 0xc8200360d0, 0xc82010cd08)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820081630, 0x7fda5b0f5728, 0xc8201195e0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc8200a6a00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74ea40, 0x900280, 0x13, 0x846788, 0x4, 0xc82010d268, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74ea40, 0x900280, 0x13, 0xc82010d268, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74ea40, 0x900280, 0xc8200a6a00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x849648, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8df580, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001b00, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
```

**Comment by mlaventure** [comment]
Does it do the same with another innocuous binary like ls?

**Comment by smuthali** [comment]
@mlaventure - With docker-engine version
```
docker --version
Docker version 1.12.2, build bb80604

```
I don't run in to the problem

```
$ docker run -it --rm --user=$UID:$(id -g) --security-opt=no-new-privileges foo-img:1.0 whoami
Effective uid: 0

```

Problem is we have several hundred servers running in production so a blanket docker-engine upgrade will be very difficult.

**Comment by justincormack** [comment]
@smuthali sorry what is the exact difference between the working and non working ones? (full output of `docker version` and `docker info`)

**Comment by smuthali** [comment]
@justincormack , sorry for the confusion. I'll try to break it down

1. Non-working env (our production servers)
```
docker --version
Docker version 1.12.2, build a8c3fe4
```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 68
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: vg_ngs_app-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 41.22 GB
 Data Space Total: 268.4 GB
 Data Space Available: 227.2 GB
 Metadata Space Used: 9.617 MB
 Metadata Space Total: 16.98 GB
 Metadata Space Available: 16.97 GB
 Thin Pool Minimum Free Space: 26.84 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
 Authorization: docker-acl-plugin
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.1.12-61.1.23.el7uek.x86_64
Operating System: Oracle Linux Server 7.3
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 125.5 GiB
Name: rn2-apgd-lapp01.rno.apple.com
ID: HF2H:RU4L:WUE5:2QJS:YAU6:RQ57:NYHG:55QJ:4PIS:EXDK:7XKO:DY6J
Docker Root Dir: /ngs/app/docker_storage
Debug Mode (client): false
Debug Mode (server): false

```

----

Working (our test servers)

```
docker --version
Docker version 1.12.2, build bb80604

```

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: docker-251:0-3387043-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 255.3 MB
 Data Space Total: 107.4 GB
 Data Space Available: 37.66 GB
 Metadata Space Used: 745.5 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.1.12-37.6.3.el7uek.x86_64
Operating System: Oracle Linux Server 7.3
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.701 GiB
```

**Comment by mlaventure** [comment]
@smuthali any idea why the build sha is different for docker between the 2 servers? The test server is the one with the correct value

Also, just to rule it out, could you try with the test server after upgrading its kernel to the same version as production (i.e. `4.1.12-61.1.23.el7uek.x86_64`)

**Comment by smuthali** [comment]
@mlaventure -  the test server running OEL 7.3 has a different private OEL repo compared to our production servers hence the different docker-engine builds. I'll try after upgrading the kernel just so that the kernel versions match on both our test and production server(s). Thanks, will keep you posted.

**Comment by justincormack** [comment]
@smuthali what does `docker version` (ie the full one not the short form in `docker --version`) say on the production box?

**Comment by thaJeztah** [comment]
I think a8c3fe4 is a build created by Oracle, so not the official package

ping @Djelibeybi

**Comment by smuthali** [comment]
That's correct build a8c3fe4 is created by Oracle

**Comment by Djelibeybi** [comment]
If this is an issue with a `docker-engine` build from Oracle, I recommend opening an SR. Though, we don't actually change any Docker Go code (we just change the way the RPM is built).

It's more likely to be a problem between the older and newer UEK4 kernels here, i.e. the test system is running `4.1.12-37.6.3.el7uek.x86_64` and the production is running `4.1.12-61.1.23.el7uek.x86_64`

The first test would be to upgrade test to the same kernel as production to see if the issue reproduces. Then its definitely a UEK issue.

Either way, it needs an SR logged with Oracle.

**Comment by smuthali** [comment]
@Djelibeybi - I updated the UEK4 kernel version on my test system to match that running in our production env. The outcome is the i.e. I still see the go panic when trying to use ``` --security-opts```

**Comment by Djelibeybi** [comment]
Note that I can't seem to reproduce it on my local box:

```
# docker run --name=foo --rm --cap-drop=SETUID --cap-drop=SETGID -u $UID:$(id -g) --security-opt=no-new-privileges oraclelinux whoami
root

# rpm -qa | grep docker
docker-engine-1.12.2-1.0.1.el7.x86_64

# uname -r
4.1.12-61.1.16.el7uek.x86_64
```

So, there is possibly something else going on here.

**Comment by Djelibeybi** [comment]
Production has `Security Options: seccomp selinux` while Test only has `Security Options: seccomp`

Might point to an issue with the SElinux policies perhaps.

**Comment by smuthali** [comment]
@Djelibeybi  - sorry for the late reply. I updated the kernel to match the test server.

Specifics:

```
Containers: 20
 Running: 20
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: vg_ngs_app-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 5.794 GB
 Data Space Total: 268.4 GB
 Data Space Available: 262.6 GB
 Metadata Space Used: 2.929 MB
 Metadata Space Total: 16.98 GB
 Metadata Space Available: 16.98 GB
 Thin Pool Minimum Free Space: 26.84 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
 Authorization: docker-acl-plugin
Swarm: inactive
Runtimes: runc
Default Runtime: runc
**Security Options: seccomp selinux**
**Kernel Version: 4.1.12-61.1.23.el7uek.x86_64**
Operating System: Oracle Linux Server 7.3
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 125.5 GiB
Name: rn2-apgd-lapp01.rno.apple.com
ID: HF2H:RU4L:WUE5:2QJS:YAU6:RQ57:NYHG:55QJ:4PIS:EXDK:7XKO:DY6J
Docker Root Dir: /ngs/app/docker_storage
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```
```
docker --version
Docker version 1.12.2, build a8c3fe4
```
```
docker-runc --version
runc version 1.0.0-rc2
commit: 02f8fa7863dd3f82909a73e2061897828460d52f
spec: 1.0.0-rc2-dev
```
Test with ```--security-opt``` flag
```
**docker run --name=retail-foo --rm --cap-drop=SETUID --cap-drop=SETGID -u $UID:$(id -g) --security-opt=no-new-privileges <docker_image> whoami**

panic: standard_init_linux.go:175: exec user process caused "operation not permitted" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "operation not permitted"

goroutine 1 [running, locked to thread]:
panic(0x7ea140, 0xc82015a540)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8201172e8)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7ea140, 0xc82015a540)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc820116bf8, 0xc8200360c8, 0xc820116d08)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820075630, 0x7f39c3e0a728, 0xc82015a540)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc82009aa00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74ea40, 0x900280, 0x13, 0x846788, 0x4, 0xc820117268, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74ea40, 0x900280, 0x13, 0xc820117268, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74ea40, 0x900280, 0xc82009aa00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x849648, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8df580, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001b00, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24

```
without  ```--security-opt```
```
docker run --name=retail-foo --rm --cap-drop=SETUID --cap-drop=SETGID -u $UID:$(id -g) <docker-image> whoami

**docker-test**
```

**Comment by Djelibeybi** [comment]
I can't reproduce this on my Oracle Linux 7 box:

```
$ docker --version
Docker version 1.12.2, build a8c3fe4
```

```
$ docker-runc --version
runc version 1.0.0-rc2
commit: 02f8fa7863dd3f82909a73e2061897828460d52f
spec: 1.0.0-rc2-dev
```

```$ docker run --name=retail-foo --rm --cap-drop=SETUID --cap-drop=SETGID -u $UID:$(id -g) --security-opt=no-new-privileges oraclelinux whoami
whoami: cannot find name for user ID 1000
```

Can you try with the base `oraclelinux` image? Perhaps its an image issue?

**Comment by smuthali** [comment]
@Djelibeybi  - err okay I will try to get our system engineering folks give me a base image to give it a try.

**Comment by Djelibeybi** [comment]
@smuthali I have reproduced the issue. It occurs when SElinux is set to enforcing. Please open an SR with Oracle Support, as I suspect something must've been missed when we migrated from the Docker provided SElinux policies to the upstream selinux-policy-targeted RPM that includes stuff for Docker.

**Comment by Djelibeybi** [comment]
Though, it works with no changes to SElinux policy on the upstream 1.12.5 build, so perhaps it's been fixed since 1.12.2 and 1.12.5. 

Either way, opening an SR is the right way to get this resolved ASAP.

**Comment by smuthali** [comment]
@Djelibeybi - copy that. I'll get a service request going. Are you able to reproduce the panic if SELINUX is in permissive mode?

**Comment by Djelibeybi** [comment]
@smuthali yes, it reproduces in both Enforcing and Permissive.

**Comment by smuthali** [comment]
with SELinux disabled
```
docker run --name=foo --rm --cap-drop=SETUID --cap-drop=SETGID -u root:root --security-opt=no-new-privileges test-img:1.0 whoami

root
```
With SELinux in permissive mode
``` sestatus ```
```
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      29
```
```
docker run --name=retail-foo --rm --cap-drop=SETUID --cap-drop=SETGID -u root:root --security-opt=no-new-privileges test-img:1.0  whoami
```
```
panic: standard_init_linux.go:175: exec user process caused "operation not permitted" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "operation not permitted"

goroutine 1 [running, locked to thread]:
panic(0x7ea140, 0xc8201257a0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8201172e8)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7ea140, 0xc8201257a0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc820116bf8, 0xc8200360c8, 0xc820116d08)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820075630, 0x7f764a2be728, 0xc8201257a0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc82009aa00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74ea40, 0x900280, 0x13, 0x846788, 0x4, 0xc820117268, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74ea40, 0x900280, 0x13, 0xc820117268, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74ea40, 0x900280, 0xc82009aa00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x849648, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8df580, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001b00, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
```
We'll open an SR with OEL support

**Comment by thaJeztah** [comment]
thanks! let me close the issue here, but keep us posted if it's resolved :+1:

**Comment by smuthali** [comment]
@thaJeztah - will do for sure. Many thanks to @thaJeztah , @justincormack , @mlaventure and @Djelibeybi  for all your help.

**Comment by Djelibeybi** [comment]
I've just reproduced this on CentOS 7 with the upstream docker-engine-1.12.6-1 RPM:

```
[root@c7dev system]# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
```

Note that the default install of upstream doesn't enable SElinux security for Docker by default, so a default install works fine. However, if you add `--selinux-enabled` to the `ExecStart` for `/usr/bin/dockerd`, it breaks.

Docker info:

```
[root@c7dev system]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.6
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.859 GiB
Name: c7dev.lot209.com
ID: PNCH:X4K4:2RPC:DSZB:FVQX:YJTO:HBR2:C4JC:JOLK:ZB6N:OX7C:ELYX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

And the traceback:

```
[root@c7dev system]# docker run --name=retail-foo --rm --cap-drop=SETUID --cap-drop=SETGID -u $UID:$(id -g) --security-opt=no-new-privileges oraclelinux whoami
panic: standard_init_linux.go:178: exec user process caused "operation not permitted" [recovered]
	panic: standard_init_linux.go:178: exec user process caused "operation not permitted"

goroutine 1 [running, locked to thread]:
panic(0x7e9ea0, 0xc82012f8f0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200fb2e8)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7e9ea0, 0xc82012f8f0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200fabf8, 0xc82001e0c8, 0xc8200fad08)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc82005d630, 0x7f167e921728, 0xc82012f8f0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc82007aa00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74e680, 0x8ffe60, 0x13, 0x8463c8, 0x4, 0xc8200fb268, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74e680, 0x8ffe60, 0x13, 0xc8200fb268, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74e680, 0x8ffe60, 0xc82007aa00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x849278, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8df1a0, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001b00, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
```

So this implies its an issue upstream somewhere in the selinux policies.

**Comment by thaJeztah** [comment]
ping @cpuguy83 ^^

**Comment by Djelibeybi** [comment]
@smuthali if you edit `/etc/sysconfig/docker` and remove `--selinux-enabled` from the `OPTIONS` variable (which matches the default configuration from upstream), it'll work fine on OL7 in both Enforcing and Permissive mode.

**Comment by Djelibeybi** [comment]
FYI, @thtanaka pointed me at http://www.projectatomic.io/blog/2016/03/no-new-privs-docker/ which suggests that @rhatdan has fixed this in Fedora 24.

**Comment by smuthali** [comment]
@Djelibeybi  - that's correct.  I referenced the url when I created the github issue.
