### ISSUE TITLE
[1.13.0-rc7] panic in DockerSwarmSuite.TestAPISwarmForceNewCluster

### ISSUE THREAD

**Issue by tophj-ibm** [docker/docker#30189]
Fails if running all the tests suites on ppc64le, testing it now on x86. I haven't seen it on any other rc (haven't tested rc6)

```sh
--- FAIL: Test (3569.17s)
panic: DockerSwarmSuite.TestAPISwarmForceNewCluster test timed out after 5m0s [recovered]
        panic: DockerSwarmSuite.TestAPISwarmForceNewCluster test timed out after 5m0s

goroutine 18 [running]:
panic(0x10f15160, 0xc421e86010)
        /usr/local/go/src/runtime/panic.go:500 +0x3a8
testing.tRunner.func1(0xc420420300)
        /usr/local/go/src/testing/testing.go:579 +0x184
panic(0x10f15160, 0xc421e86010)
        /usr/local/go/src/runtime/panic.go:458 +0x4cc
github.com/docker/docker/vendor/github.com/go-check/check.(*suiteRunner).runTest(0xc420528d80, 0xc420366af0, 0xc421f5def0)
        /go/src/github.com/docker/docker/vendor/github.com/go-check/check/check.go:875 +0x238
github.com/docker/docker/vendor/github.com/go-check/check.(*suiteRunner).run(0xc420528d80, 0xc42040ca40)
        /go/src/github.com/docker/docker/vendor/github.com/go-check/check/check.go:621 +0x2e4
github.com/docker/docker/vendor/github.com/go-check/check.Run(0x10ff5500, 0xc42040ca40, 0xc42041eff0, 0xc421fd4750)
        /go/src/github.com/docker/docker/vendor/github.com/go-check/check/run.go:100 +0x4c
github.com/docker/docker/vendor/github.com/go-check/check.RunAll(0xc42041eff0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/go-check/check/run.go:92 +0xe4
github.com/docker/docker/vendor/github.com/go-check/check.TestingT(0xc420420300)
        /go/src/github.com/docker/docker/vendor/github.com/go-check/check/run.go:80 +0x344
github.com/docker/docker/integration-cli.Test(0xc420420300)
        /go/src/github.com/docker/docker/integration-cli/check_test.go:30 +0x12c
testing.tRunner(0xc420420300, 0x11144bd0)
        /usr/local/go/src/testing/testing.go:610 +0xd8
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:646 +0x370

```

Full log here https://gist.github.com/tophj-ibm/737bbfa00a61e1c8241d19d4bc639ae0

**Comment by tophj-ibm** [comment]
Happens on x86 as well. Closing because root issue is #29952
