### ISSUE TITLE
Stack deploy with external secret sets Mode incorrectly

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#30992]
Using: 1.13.1 experimental

credit to @mstanleyjones for discovery

Use this Compose file:

```yaml
version: '3.1'

services:
  foo:
    image: alpine
    command: sh -c 'while true; do ls -lah /run/secrets/mysec; sleep 1; done'
    secrets:
      - mysec

secrets:
  mysec:
    external: true
```

do this:

```console
$ echo password | docker secret create mysec - 
asdfasdfasdfasdf
$ docker stack deploy -c docker-compose.yml secbug
```

You can see in container logs, no one (even `root`) in resulting secret mount can read, write, or execute file. Oops.

```
$ docker service logs secbug_dir
secbug_foo.1.g4c2qddl04d7@default    | ----------    1 root     root          13 Feb 14 00:12 /run/secrets/mysec
secbug_foo.1.g4c2qddl04d7@default    | ----------    1 root     root          13 Feb 14 00:12 /run/secrets/mysec
secbug_foo.1.g4c2qddl04d7@default    | ----------    1 root     root          13 Feb 14 00:12 /run/secrets/mysec
secbug_foo.1.g4c2qddl04d7@default    | ----------    1 root     root          13 Feb 14 00:12 /run/secrets/mysec
```

`.Spec.TaskTemplate.Secrets.File.Mode` is set to `0` in `service inspect`. Looks like in "healthy" case it defaults to `292`. Not sure what the heck those notations are (I'm assuming something else masquerading in a base 10 number), but I'm assuming default value is not what it should be.

Interestingly Python Compose validation flunks this, insisting on an object:

```console
$ docker-compose up
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 88, in main
  File "compose/cli/main.py", line 137, in perform_command
  File "compose/cli/command.py", line 36, in project_from_options
  File "compose/cli/command.py", line 115, in get_project
  File "compose/project.py", line 110, in from_config
  File "compose/project.py", line 566, in get_secrets
AttributeError: 'str' object has no attribute 'source'
Failed to execute script docker-compose
```

ping @dnephin @shin- @thaJeztah

**Comment by nathanleclaire** [comment]
Oops, dupe of https://github.com/docker/docker/issues/30991
