### ISSUE TITLE
Concurrently create and delete volume device in different thinpool device using devmapper pkg will be panic

### ISSUE THREAD

**Issue by shentaosky** [docker/docker#31209]
**Description**
I use convoy, a volume management program, to concurrently create and delete volume appear panic. To find out reason of that, I code a program to verify. Then, I exclude the factor of system call of devicemapper. I think there is some problem of the pkg of devmapper, but i don't know what happened.

The program code as follow:

```
package main

import (
    "os/exec"
    "fmt"
    "sync"

    "github.com/docker/docker/pkg/devicemapper"
)

type mutexLock struct {
    mutex_bronze *sync.Mutex
    mutex_silver *sync.Mutex
    mutex_gold   *sync.Mutex
}

func main() {
    var mutex = mutexLock{
        mutex_bronze: &sync.Mutex{},
        mutex_silver: &sync.Mutex{},
        mutex_gold:   &sync.Mutex{},
    }

    var wait = make(chan int, 60)

    for i := 1; i <= 20; i++ {
        go mutex.createBronzeVolume(fmt.Sprintf("%d", i), wait)
        go mutex.createSilverVolume(fmt.Sprintf("%d", i), wait)
        go mutex.createGoldVolume(fmt.Sprintf("%d", i), wait)
    }

    for i := 1; i <= 60; i++ {
        if 1 == <-wait {
            fmt.Println(i)
        }
    }

    for i := 1; i <= 20; i++ {
        go mutex.deleteBronzeVolume(i, wait)
        go mutex.deleteSilverVolume(i, wait)
        go mutex.deleteGoldVolume(i, wait)
    }

    for i := 1; i <= 60; i++ {
        if 1 == <-wait {
            fmt.Println(i)
        }
    }
}

func (mutex *mutexLock)createBronzeVolume(id string, stop chan int) {
    mutex.mutex_bronze.Lock()
    defer mutex.mutex_bronze.Unlock()
    err := exec.Command("sh", "-c", "dmsetup message /dev/mapper/convoy_bronze 0 "+fmt.Sprintf("'create_thin %s'", id)).Run()
    if err != nil {
        fmt.Println(err)
        stop <- 0
        return
    }
    err = exec.Command("sh", "-c", "dmsetup create bronze_volume_"+id+" --table '0 131072 thin /dev/mapper/convoy_bronze "+id+"'").Run()
    if err != nil {
        fmt.Println(err)
        stop <- 0
        return
    }
    fmt.Println("complete create volume bronze_volume_", id)
    stop <- 1
}

func (mutex *mutexLock)createSilverVolume(id string, stop chan int) {
    mutex.mutex_silver.Lock()
    defer mutex.mutex_silver.Unlock()
    err := exec.Command("sh", "-c", "dmsetup message /dev/mapper/convoy_silver 0 "+fmt.Sprintf("'create_thin %s'", id)).Run()
    if err != nil {
        fmt.Println(err)
        stop <- 0
        return
    }
    err = exec.Command("sh", "-c", "dmsetup create silver_volume_"+id+" --table '0 131072 thin /dev/mapper/convoy_silver "+id+"'").Run()
    if err != nil {
        fmt.Println(err)
        stop <- 0
        return
    }
    fmt.Println("complete create volume silver_volume_", id)
    stop <- 1
}

func (mutex *mutexLock)createGoldVolume(id string, stop chan int) {
    mutex.mutex_gold.Lock()
    defer mutex.mutex_gold.Unlock()
    err := exec.Command("sh", "-c", "dmsetup message /dev/mapper/convoy_gold 0 "+fmt.Sprintf("'create_thin %s'", id)).Run()
    if err != nil {
        fmt.Println(err)
        stop <- 0
        return
    }
    err = exec.Command("sh", "-c", "dmsetup create gold_volume_"+id+" --table '0 131072 thin /dev/mapper/convoy_gold "+id+"'").Run()
    if err != nil {
        fmt.Println(err)
        stop <- 0
        return
    }
    fmt.Println("complete create volume gold_volume_", id)
    stop <- 1
}

func (mutex *mutexLock) deleteBronzeVolume(id int, stop chan int) {
    mutex.mutex_bronze.Lock()
    defer mutex.mutex_bronze.Unlock()

    err := devicemapper.RemoveDevice("bronze_volume_"+fmt.Sprintf("%d", id))
    if err != nil {
        fmt.Println(err)
        stop <- 0
        return
    }
    err = devicemapper.DeleteDevice("/dev/mapper/convoy_bronze", id)
    if err != nil {
        fmt.Println(err)
        stop <- 0
        return
    }
    fmt.Println("complete delete volume bronze_volume_", fmt.Sprintf("%d", id))
    stop <- 1
}
func (mutex *mutexLock) deleteSilverVolume(id int, stop chan int) {
    mutex.mutex_silver.Lock()
    defer mutex.mutex_silver.Unlock()

    err := devicemapper.RemoveDevice("silver_volume_"+fmt.Sprintf("%d", id))
    if err != nil {
        fmt.Println(err)
        stop <- 0
        return
    }
    err = devicemapper.DeleteDevice("/dev/mapper/convoy_silver", id)
    if err != nil {
        fmt.Println(err)
        stop <- 0
        return
    }
    fmt.Println("complete delete volume silver_volume_", fmt.Sprintf("%d", id))
    stop <- 1
}

func (mutex *mutexLock) deleteGoldVolume(id int, stop chan int) {
    mutex.mutex_gold.Lock()
    defer mutex.mutex_gold.Unlock()

    err := devicemapper.RemoveDevice("gold_volume_"+fmt.Sprintf("%d", id))
    if err != nil {
        fmt.Println(err)
        stop <- 0
        return
    }
    err = devicemapper.DeleteDevice("/dev/mapper/convoy_gold", id)
    if err != nil {
        fmt.Println(err)
        stop <- 0
        return
    }
    fmt.Println("complete delete volume gold_volume_", fmt.Sprintf("%d", id))
    stop <- 1
}
```

**Steps to reproduce the issue:**
1. Create three thin-pool loop-device
2. go run the program

**Describe the results you received:**
```
complete create volume bronze_volume_ 12
1
complete create volume silver_volume_ 1
2
complete create volume gold_volume_ 2
3
complete create volume bronze_volume_ 3
4
complete create volume gold_volume_ 20
5
complete create volume silver_volume_ 3
6
complete create volume bronze_volume_ 4
7
complete create volume silver_volume_ 4
8
complete create volume gold_volume_ 11
9
complete create volume silver_volume_ 5
complete create volume bronze_volume_ 5
10
11
complete create volume gold_volume_ 3
12
complete create volume bronze_volume_ 6
13
complete create volume silver_volume_ 6
14
complete create volume gold_volume_ 4
15
complete create volume bronze_volume_ 7
16
complete create volume gold_volume_ 5
17
complete create volume silver_volume_ 7
18
complete create volume bronze_volume_ 8
19
complete create volume gold_volume_ 6
20
...
complete create volume silver_volume_ 19
58
complete create volume gold_volume_ 19
59
complete create volume silver_volume_ 20
60
complete delete volume bronze_volume_ 1
1
complete delete volume silver_volume_ 1
2
complete delete volume gold_volume_ 20
3
complete delete volume bronze_volume_ 6
4
complete delete volume silver_volume_ 2
5
complete delete volume gold_volume_ 10
complete delete volume bronze_volume_ 2
6
7
complete delete volume silver_volume_ 3
8
complete delete volume bronze_volume_ 3
complete delete volume gold_volume_ 1
9
10
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7fbe61654027]

runtime stack:
runtime.throw(0x4ec70e, 0x2a)
        /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 71 [syscall, locked to thread]:
runtime.cgocall(0x4af7f0, 0xc420097dd8, 0x0)
        /usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc420097d90 sp=0xc420097d50
github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper._Cfunc_dm_udev_wait(0xd4dfcd8, 0x0)
        ??:0 +0x4d fp=0xc420097dd8 sp=0xc420097d90
github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper.dmUdevWaitFct(0xd4dfcd8, 0xc420081ba0)
        /root/gopath/src/github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper/devmapper_wrapper.go:222 +0x2a fp=0xc420097df8 sp=0xc420097dd8
github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper.UdevWait(0xc42000d370, 0x0, 0x0)
        /root/gopath/src/github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper/devmapper.go:259 +0x39 fp=0xc420097e40 sp=0xc420097df8
github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper.RemoveDevice(0xc42000d361, 0xd, 0x0, 0x0)
        /root/gopath/src/github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper/devmapper.go:345 +0x292 fp=0xc420097eb8 sp=0xc420097e40
main.(*mutexLock).deleteGoldVolume(0xc420010400, 0x2, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:151 +0x15d fp=0xc420097fa8 sp=0xc420097eb8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420097fb0 sp=0xc420097fa8
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:41 +0x522

goroutine 1 [chan receive]:
main.main()
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:45 +0x582

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 74 [semacquire]:
sync.runtime_Semacquire(0xc42000c594)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c590)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteGoldVolume(0xc420010400, 0x3, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:148 +0x44
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:41 +0x522

goroutine 75 [syscall, locked to thread]:
github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper._C2func_dm_task_run(0x7fbe58025710, 0x7fbe00000000, 0x0, 0x0)
        ??:0 +0x68
github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper.dmTaskRunFct(0x7fbe58025710, 0x1)
        /root/gopath/src/github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper/devmapper_wrapper.go:96 +0x75
github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper.(*Task).run(0xc4200d6af0, 0xc420191db8, 0x8)
        /root/gopath/src/github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper/devmapper.go:155 +0x35
github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper.DeleteDevice(0x4e958f, 0x19, 0x4, 0x0, 0x1)
        /root/gopath/src/github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper/devmapper.go:720 +0x299
main.(*mutexLock).deleteBronzeVolume(0xc420010400, 0x4, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:118 +0x23d
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:39 +0x4aa

goroutine 76 [syscall, locked to thread]:
github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper._C2func_dm_task_run(0x7fbe5001d3e0, 0x7fbe00000000, 0x0, 0x0)
        ??:0 +0x68
github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper.dmTaskRunFct(0x7fbe5001d3e0, 0x1)
        /root/gopath/src/github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper/devmapper_wrapper.go:96 +0x75
github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper.(*Task).run(0xc4200d6ae8, 0xc420191da8, 0x8)
        /root/gopath/src/github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper/devmapper.go:155 +0x35
github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper.DeleteDevice(0x4e95a8, 0x19, 0x4, 0x0, 0x1)
        /root/gopath/src/github.com/rancher/convoy/vendor/github.com/docker/docker/pkg/devicemapper/devmapper.go:720 +0x299
main.(*mutexLock).deleteSilverVolume(0xc420010400, 0x4, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:137 +0x23f
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:40 +0x4e6

goroutine 77 [semacquire]:
sync.runtime_Semacquire(0xc42000c594)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c590)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteGoldVolume(0xc420010400, 0x4, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:148 +0x44
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:41 +0x522

goroutine 78 [semacquire]:
sync.runtime_Semacquire(0xc42000c584)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c580)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteBronzeVolume(0xc420010400, 0x5, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:109 +0x43
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:39 +0x4aa

goroutine 79 [semacquire]:
sync.runtime_Semacquire(0xc42000c58c)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c588)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteSilverVolume(0xc420010400, 0x5, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:128 +0x44
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:40 +0x4e6

goroutine 80 [semacquire]:
sync.runtime_Semacquire(0xc42000c594)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c590)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteGoldVolume(0xc420010400, 0x5, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:148 +0x44
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:41 +0x522
goroutine 82 [semacquire]:
sync.runtime_Semacquire(0xc42000c58c)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c588)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteSilverVolume(0xc420010400, 0x6, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:128 +0x44
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:40 +0x4e6

goroutine 83 [semacquire]:
sync.runtime_Semacquire(0xc42000c594)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c590)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteGoldVolume(0xc420010400, 0x6, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:148 +0x44
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:41 +0x522

goroutine 84 [semacquire]:
sync.runtime_Semacquire(0xc42000c584)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c580)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteBronzeVolume(0xc420010400, 0x7, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:109 +0x43
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:39 +0x4aa

goroutine 85 [semacquire]:
sync.runtime_Semacquire(0xc42000c58c)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c588)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteSilverVolume(0xc420010400, 0x7, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:128 +0x44
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:40 +0x4e6

goroutine 86 [semacquire]:
sync.runtime_Semacquire(0xc42000c594)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c590)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteGoldVolume(0xc420010400, 0x7, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:148 +0x44
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:41 +0x522

goroutine 87 [semacquire]:
sync.runtime_Semacquire(0xc42000c584)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c580)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteBronzeVolume(0xc420010400, 0x8, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:109 +0x43
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:39 +0x4aa
...
goroutine 119 [semacquire]:                                                                                                                                                                                                    [0/1733]
sync.runtime_Semacquire(0xc42000c594)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c590)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteGoldVolume(0xc420010400, 0x12, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:148 +0x44
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:41 +0x522

goroutine 120 [semacquire]:
sync.runtime_Semacquire(0xc42000c584)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c580)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteBronzeVolume(0xc420010400, 0x13, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:109 +0x43
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:39 +0x4aa

goroutine 121 [semacquire]:
sync.runtime_Semacquire(0xc42000c58c)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c588)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteSilverVolume(0xc420010400, 0x13, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:128 +0x44
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:40 +0x4e6

goroutine 122 [semacquire]:
sync.runtime_Semacquire(0xc42000c594)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c590)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteGoldVolume(0xc420010400, 0x13, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:148 +0x44
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:41 +0x522

goroutine 123 [semacquire]:
sync.runtime_Semacquire(0xc42000c584)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c580)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteBronzeVolume(0xc420010400, 0x14, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:109 +0x43
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:39 +0x4aa

goroutine 124 [semacquire]:
sync.runtime_Semacquire(0xc42000c58c)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42000c588)
        /usr/local/go/src/sync/mutex.go:85 +0xd0
main.(*mutexLock).deleteSilverVolume(0xc420010400, 0x14, 0xc42007c000)
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:128 +0x44
created by main.main
        /root/gopath/src/github.com/rancher/convoy/concurrentcreatevolume.go:40 +0x4e6
exit status 2

```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker code version`:**
update at 21 February 2017, master branch
```
:~/docker$ git log
commit 25500d56a5f3a94456bd8172a64bf119cc36dd7f
Merge: f100851 d735972
Author: Sebastiaan van Stijn <thaJeztah@users.noreply.github.com>
Date:   Tue Feb 21 00:59:58 2017 +0100

    Merge pull request #30814 from YuPengZTE/devSwarmCliExplain
    
    fix the type

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
`3.10.0-327.10.1.el7.x86_64 GNU/Linux`

```
# dmsetup --version
Library version:   1.02.107-RHEL7 (2016-06-09)
Driver version:    4.33.0
```

```
# go version
go version go1.7.3 linux/amd64
```

**Comment by mYmNeo** [comment]
I think you should paste the output of `docker info` that will give more detail information.

**Comment by shentaosky** [comment]
@mYmNeo In fact, I don't use docker in this issue, though I paste the `docker info` as follows:
```
Containers: 14
 Running: 1
 Paused: 0
 Stopped: 13
Images: 72
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 64.42 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 6.481 GB
 Data Space Total: 1.501 TB
 Data Space Available: 1.494 TB
 Metadata Space Used: 4.014 MB
 Metadata Space Total: 15.8 GB
 Metadata Space Available: 15.79 GB
 Thin Pool Minimum Free Space: 150.1 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.593 GiB
Name: zhenghc-tos
ID: BPDG:PHGO:FJTJ:4YF2:AI65:5IAP:VF2Y:NAJV:22F5:4KM6:DNI6:4CJM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 172.16.1.41:5000
 127.0.0.0/8
```

**Comment by shentaosky** [comment]
@mYmNeo I update the docker pkg of devicemapper and copy to gopath vendor and go run the test file. I'm sure it is shared library.

**Comment by thaJeztah** [comment]
ping @rhvgoyal PTAL

**Comment by rhvgoyal** [comment]
This program is wrong. You need to use one mutex for all three kind of volumes to make sure only one thread is calling library code at a time. You have used 3 mutexes and that means more than one thread might be calling in to libdevmapper and bad things are sure to happen.

**Comment by shentaosky** [comment]
@rhvgoyal That means if I use library code to operate different pool volume, it would happen bad things. So the library code doesn't surpport for concurrent calling volume though it is produced by different thin-pool. But the system call of devicemapper is surpported. Would library surpporte that in the future?

**Comment by rhvgoyal** [comment]
library is not currently thread safe. That means in a process, only one thread can be calling into the library at a time.

I am not aware of any plans to make library thread safe.

**Comment by cpuguy83** [comment]
Closing since this seems related to improper usage by the library caller.
