### ISSUE TITLE
"docker exec" sometimes loses stdout, but "docker-compose exec -T" works

### ISSUE THREAD

**Issue by jamshid** [docker/docker#31368]
**Description**
Sorry I don't have a full repro, but I've seen problems where `docker exec` output is lost when running the docker client in a bash script running in a docker container. 

Maybe the below error from `docker-compose exec` is a clue about what's going wrong. 

So I have a bash script running in a container, and it runs `docker exec CONTAINER bash -c 'echo $(date)'`, where CONTAINER is started by a compose service. On some docker servers, that fails to output anything. The container running the bash script does have the latest 1.13.1 docker and 1.11.1 docker-compose clients installed.

To workaround that problem I tried changing the bash script to call `docker-compose exec service`, letting it pick one of my containers at random instead of specifying a specific container. `docker-compose` then output the below error, I guess because it doesn't have a PTY? 

```
++ docker-compose exec testexample bash -c 'echo $(date)'
++ tee
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 88, in main
  File "compose/cli/main.py", line 140, in perform_command
  File "compose/cli/main.py", line 486, in exec_command
  File "site-packages/dockerpty/pty.py", line 338, in start
  File "site-packages/dockerpty/io.py", line 32, in set_blocking
ValueError: file descriptor cannot be a negative integer (-1)
```

So I tried using `docker-compose exec -T testexample bash -c 'echo $(date)'` and that fixes the problem.

I'm wondering if this indicates why `docker exec` sometimes does not output anything. I tried using one or both of `-i` and `-t` with `docker exec` but it didn't seem to help. I guess `docker-compose exec` does things differently thatn `docker exec`?

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 96
 Running: 44
 Paused: 0
 Stopped: 52
Images: 4346
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 2ock66ylofs1od60jag0mhfyp
 Is Manager: true
 ClusterID: tem00egy0e5fazv9cqh88y95n
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.2.61
 Manager Addresses:
  192.168.2.61:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.6 GiB
Name: 61
ID: N7OB:5SO5:FQWH:CBY5:4MUF:YD5A:KHNV:SFYV:HKED:U5W2:HRDS:57WQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=generic
Experimental: false
Insecure Registries:
 192.168.2.61:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by jamshid** [comment]
This can be closed, found a reliable repro of this `docker exec` bug where it returns immediately (before the remote command finishes) in https://github.com/docker/docker/issues/31438.
