### ISSUE TITLE
Throw error instead of http panic when extra hosts are malformed

### ISSUE THREAD

**Issue by eivantsov** [docker/docker#31378]
**Description**

Server panic when extra hosts are malformed

**Steps to reproduce the issue:**
1. Create a container with the following config:

```
{
       "Hostname": "",
       "Domainname": "",
       "User": "",
       "AttachStdin": false,
       "AttachStdout": true,
       "AttachStderr": true,
       "Tty": false,
       "OpenStdin": false,
       "StdinOnce": false,
       "Env": [
               "FOO=bar",
               "BAZ=quux"
       ],
       "Cmd": [
               "date"
       ],
       "Entrypoint": "",
       "Image": "alpine",
       "Labels": {
               "com.example.vendor": "Acme",
               "com.example.license": "GPL",
               "com.example.version": "1.0"
       },
       "Volumes": {
         "/volumes/data": {}
       },
       "WorkingDir": "",
       "NetworkDisabled": false,
       "MacAddress": "12:34:56:78:9a:bc",
       "ExposedPorts": {
               "22/tcp": {}
       },
       "StopSignal": "SIGTERM",
       "HostConfig": {
         "Binds": ["/tmp:/tmp"],
         "PortBindings": { "22/tcp": [{ "HostPort": "11022" }] },
         "PublishAllPorts": false,
         "Privileged": false,
         "ReadonlyRootfs": false,
         "Dns": ["8.8.8.8"],
         "DnsOptions": [""],
         "DnsSearch": [""],
         "ExtraHosts": ["host,ip"],
         "NetworkMode": "bridge",
         "Devices": [],
         "Sysctls": { "net.ipv4.ip_forward": "1" },
         "Ulimits": [{}],
         "LogConfig": { "Type": "json-file", "Config": {} },
         "SecurityOpt": [],
         "StorageOpt": {},
         "CgroupParent": "",
         "VolumeDriver": "",
         "ShmSize": 67108864
      },
      "NetworkingConfig": {
          "EndpointsConfig": {
          }
      }
  }
```

Note invalid `"ExtraHosts": ["host,ip"]`

2. Start this container

**Describe the results you received:**

The following error is shown:

`error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/containers/d8c655aa31d3/start: EOF
`
**Describe the results you expected:**

A user friendly message indicating the reason of such a failure

**Additional information you deem important (e.g. issue happens only occasionally):**

http panic instead of a proper error handling:

```
http: panic serving @: runtime error: index out of range
                                                       goroutine 5720 [running]:
                                                       net/http.(*conn).serve.func1(0xc421cbd380)
                                                               /usr/lib/golang/src/net/http/server.go:1491 +0x12a
                                                       panic(0x15dad40, 0xc420010090)
                                                               /usr/lib/golang/src/runtime/panic.go:458 +0x243
                                                       github.com/docker/docker/daemon.(*Daemon).buildSandboxOptions(0xc420093ba0, 0xc420494f00, 0x222d9c0, 0xc4219aef00, 0x222c0c0, 0xc421908840, 0x0)
                                                               /builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/_build/src/github.com/docker/docker/daemon/container_operations.go:121 +0xd
ed
                                                       github.com/docker/docker/daemon.(*Daemon).connectToNetwork(0xc420093ba0, 0xc420494f00, 0xc420f70540, 0x2a, 0xc421d7ef00, 0x0, 0x0, 0x0)
                                                               /builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/_build/src/github.com/docker/docker/daemon/container_operations.go:590 +0x7
9a
                                                       github.com/docker/docker/daemon.(*Daemon).allocateNetwork(0xc420093ba0, 0xc420494f00, 0x58ce00, 0xc4221131e0)
                                                               /builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/_build/src/github.com/docker/docker/daemon/container_operations.go:426 +0x2
7d
                                                       github.com/docker/docker/daemon.(*Daemon).initializeNetworking(0xc420093ba0, 0xc420494f00, 0x0, 0x0)
                                                               /builddir/build/BUILD/docker-047e51b797564227b0bf26f3aa448f563bea5c71/_build/src/github.com/docker/docker/daemon/container_operations.go:703 +0x2
a5

```

**Output of `docker version`:**

```
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: VolGroup01-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 3.692 GB
 Data Space Total: 329.4 GB
 Data Space Available: 325.7 GB
 Metadata Space Used: 1.606 MB
 Metadata Space Total: 1.074 GB
 Metadata Space Available: 1.072 GB
 Thin Pool Minimum Free Space: 32.94 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge null host overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 8
Total Memory: 62.75 GiB
Name: denatb3dhcod02
ID: D7GF:EZNF:2ZZA:64UO:JYY4:L2NL:4SLH:BLTX:ON2E:5V2S:NSDQ:LLZ5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
Insecure Registries:
 127.0.0.0/8
Registries: registry.access.redhat.com (secure), docker.io (secure)

```

**Comment by allencloud** [comment]
#dibs

**Comment by thaJeztah** [comment]
I was able to reproduce this on current master;

Start the daemon;

    dockerd --debug --iptables=false -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock

Pull buxybox image;

    docker pull busybox

Create container with invalid configuration;


```bash
curl -v \
  -X POST \
  "http://localhost:2375/v1.24/containers/create?name=foobar" \
  -H "Content-Type: application/json" \
  -d '{"Image":"busybox","HostConfig":{"ExtraHosts":["host,ip"]}}'
```

Start the container;

```bash
docker start foobar
```

**Comment by thaJeztah** [comment]
@allencloud I suggest to also add validation to the _create_ step of the container, to prevent the container from being created with the wrong configuration. That won't prevent a container that's already been created with the wrong configuration from being there, but in this case I think that's a reasonable trade-off, as such a container would never have been able to run (and it can still be removed)

**Comment by allencloud** [comment]
Thanks for your suggestions. @thaJeztah 
However I am still not sure whether extraHosts is platform specific or not.
But I am sure that we should validate that on Linux, then what about Solaris and Windows?

**Comment by thaJeztah** [comment]
We should limit the validation to just what we "need", i.e. the format is `<hostname>:<ip-address>`; possibly just checking that there's a "key" (`hostname`) and a "value (`ip-address`) would be a good start.

The panic is a cause of that, because it splits the value, without checking if both a "key" and a "value" are there; https://github.com/docker/docker/blob/v1.12.5/daemon/container_operations.go#L118-L122

**Comment by thaJeztah** [comment]
Just something like this somewhere in a validation step would be sufficient I think;

```go
if h := strings.SplitN(extraHost, ":", 2); len(h) != 2 {
    // configuration is invalid ...
}
```

**Comment by allencloud** [comment]
While more input for this issue from me is that, we seem to have a validate for extraHosts in https://github.com/docker/docker/blob/master/opts/hosts.go#L155-L165. There we validate two parts, `bad format` and `invalid IP.`

What is more, if we hope to add validation for the create step of container, then https://github.com/docker/docker/blob/v1.12.5/daemon/container_operations.go#L118-L122 in buildSandboxOptions may be not OK for us. Since it is after the creation.

**Comment by allencloud** [comment]
I also found that in SwarmKit, for a service `Host` in `ContainerSpec` is not validated, either.

**Comment by thaJeztah** [comment]
Validation can probably go into [`verifyContainerSettings()`](https://github.com/docker/docker/blob/6dd2a82458016d15786b0bb12ba4cecde9b6bb90/daemon/container.go#L208-L291), which is called both on `create` and `update` of a container

**Comment by thaJeztah** [comment]
Oh, I see you did in your PR :smile:
