### ISSUE TITLE
docker exec fails: rpc error: code = 14 desc = grpc: the connection is unavailable

### ISSUE THREAD

**Issue by fencekicker** [docker/docker#31383]
**Description**

After running over the weekend under significant load, I found this VM in a state where I can't docker exec into any of the running docker containers. They all show up under 'docker ps', though 'ps axf' suggests at least one of the containers is dead. The error is always the same: 

```
$ docker exec -it <container1> bash
rpc error: code = 14 desc = grpc: the connection is unavailable
```

I haven't tried this repeatedly to see if this is consistently reproducible. I would expect it not to be. 

**Steps to reproduce the issue:**
Not sure at this point

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 56
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 62
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: N/A (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.7 GiB
Name: vatip-test-vm
ID: 6NYT:5JFR:6YHH:IZ5N:D6IB:XIE5:C3AJ:M7HW:PLIL:KFUR:Y65M:QY7X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

uname -a:
```
Linux vatip-test-vm 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

This is in a VM with Ubuntu 14.04 running over VMWare ESXi 5.5. 

The /var/log/upstart/docker.log has this to say:

```
time="2017-02-27T10:53:05.219720554Z" level=error msg="Error running exec in container: rpc error: code = 14 desc = grpc: the connection is unavailable" 
time="2017-02-27T10:53:05.219869610Z" level=error msg="Handler for POST /v1.26/exec/0bf6f029fecc8f13c189caaa1c92440c90a6eacf559ab724ecffe63b3844ef0a/resize returned error: rpc error: code = 14 desc = grpc: the connection is unavailable" 
```

**Comment by thaJeztah** [comment]
> After running over the weekend under significant load

Could the container be OOM-killed? (i.e. did you run out of memory, and was the container's process killed by the kernel to free up resources?)

Was the container still showing up as "running" or was it showing as "exited"?

**Comment by fencekicker** [comment]
I don't see any indication of this in /var/log/syslog. 

What's weird is the process tree, as far as I can tell. In another VM I see the hierarchy like this, with docker-containerd processes as children of dockerd, each with a docker-containerd-shim child:

```
  793 ?        Ssl    0:16 /usr/bin/dockerd --raw-logs
 1105 ?        Ssl    0:05  \_ docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock [...]
 1239 ?        Sl     0:00      \_ docker-containerd-shim 69e9d4abc591dc4bdc1117269a4f5079c31eafa10449de2156808c06b422621b /var/run/docker/libcontainerd/69e9d4abc591dc4bdc1117269a4f5079c31eafa10449de2156808c06b422621b docker-runc 
```
In the problematic VM, I don't see docker-containerd under dockerd, and the shims are orphaned (PPID is 1). Not sure what happened to the docker-containerd instances: 
```
 810 ?        Ssl   33:19 /usr/bin/dockerd --raw-logs
[... other processes]
 1256 ?        Sl     0:36 docker-containerd-shim 7532568298da08631365229ab60c7147e43f7f8806aed66665fdbbd3a616f126 [...]
[...]
```

**Comment by fencekicker** [comment]
There's also this part earlier in /var/log/upstart/docker.log, maybe that's an indication of why docker-containerd crashed:
```
time="2017-02-27T08:52:45.116463340Z" level=info msg="libcontainerd: new containerd process, pid: 19312" 
time="2017-02-27T08:52:46.581362153Z" level=info msg="libcontainerd: new containerd process, pid: 19317" 
time="2017-02-27T08:52:48.120303565Z" level=info msg="libcontainerd: new containerd process, pid: 19326" 
time="2017-02-27T08:52:49.867158018Z" level=info msg="libcontainerd: new containerd process, pid: 19337" 
2017/02/27 08:52:56 grpc: Server.processUnaryRPC failed to write status stream error: code = 4 desc = "context deadline exceeded"
time="2017-02-27T09:04:56.157536866Z" level=info msg="Container 18be41c1c932295ab76a8ad2a287990d1a93202ff07a640bb436209286e87439 failed to exit within 10 seconds of signal 15 - using the force" 
panic: close of nil channel

goroutine 1524 [running]:
panic(0x8082e0, 0xc420470780)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/containerd/supervisor.(*Supervisor).execExit.func1(0xc4202def00, 0xc420140dd0, 0x0)
        /tmp/tmp.ezSaVZlwBZ/src/github.com/docker/containerd/supervisor/exit.go:90 +0x10c
created by github.com/docker/containerd/supervisor.(*Supervisor).execExit
        /tmp/tmp.ezSaVZlwBZ/src/github.com/docker/containerd/supervisor/exit.go:91 +0xee
time="2017-02-27T09:04:58.110539623Z" level=error msg="libcontainerd: failed to receive event from containerd: rpc error: code = 13 desc = transport is closing"
```

**Comment by thaJeztah** [comment]
ping @mlaventure PTAL

**Comment by mlaventure** [comment]
It looks like it is the same issue as https://github.com/docker/docker/issues/30984

**Comment by thaJeztah** [comment]
ok let's close this one, and continue the discussion on https://github.com/docker/docker/issues/30984
