### ISSUE TITLE
dockerd with many images takes a very long time to start

### ISSUE THREAD

**Issue by tianon** [docker/docker#31462]
**Description**

When `dockerd` restarts, it takes a very long time before commands actually work.  We have two build servers which exhibit the issue reasonably regularly (we try not to restart the daemon if we can avoid it, so I can't say for certain if it's 100% consistent, but IIRC it is), one on AUFS and one on overlay2.  They both have a very large number of images, and a very small number of active containers (but a large number of short-lived containers, due to their role as build servers).

**Steps to reproduce the issue:**

I'm not 100% sure exactly what it takes to reproduce, but for the servers where we've got it, we just have to restart the daemon and it'll hang, spiking IO (if we run `iotop` while it's hung, it shows `dockerd` very clearly doing a huge amount of IO for the entire time it's "stuck").

**Describe the results you received:**

`dockerd` hangs on startup (for anywhere from 15m or more -- the one I hit yesterday took 20m).

**Describe the results you expected:**

`dockerd` doesn't take 20 minutes to start? :innocent: (really just looking for what the expected behavior really ought to be in these sorts of cases and whether it can be improved or at least documented :+1:)

**Additional information you deem important (e.g. issue happens only occasionally):**

The closest already-filed issue I or @thaJeztah could find was #30520, but that one is AUFS-related, and as can be seen in the `docker info` output below, we're seeing this on both AUFS and overlay2, and even then the AUFS dirs number isn't nearly as large as that mentioned in #30520.

**Output of `docker version`:**

```console
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
```console
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:17:57 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:17:57 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```console
$ time docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 14689
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.0-0.bpo.2-amd64
Operating System: Alpine Linux v3.5 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.307 GiB
Name: 5ffe207e0b93
ID: 47KF:2WYZ:TK6I:AH7Q:RXYM:AXLE:2BAW:DI53:A5PU:ZMUM:T33V:S7MN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: redacted
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

real	0m4.352s
user	0m0.008s
sys	0m0.004s
```
```console
$ time docker info
Containers: 9
 Running: 3
 Paused: 0
 Stopped: 6
Images: 59181
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /mnt/docker/var-lib-docker/aufs
 Backing Filesystem: extfs
 Dirs: 22609
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.321 GiB
Name: redacted
ID: HOSB:GEKJ:FCZ7:CN5R:63JH:QSCI:CUOU:BALS:AJGE:SOE2:TH7G:YEV5
Docker Root Dir: /mnt/docker/var-lib-docker
Debug Mode (client): false
Debug Mode (server): false
Username: redacted
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8

real	0m18.405s
user	0m0.004s
sys	0m0.004s
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

These boxes are running in AWS.

Here are the systemd service logs for the most recent incident (from yesterday) where the startup took ~20m (as can be seen from the timestamps in the log):
```
systemd[1]: Starting Docker Application Container Engine...
dockerd[7477]: time="2017-02-28T16:18:26.549423864-08:00" level=debug msg="Listener created for HTTP on fd ()"
dockerd[7477]: time="2017-02-28T16:18:26.552154913-08:00" level=info msg="libcontainerd: new containerd process, pid: 7483"
dockerd[7477]: time="2017-02-28T16:18:26.554105636-08:00" level=debug msg="libcontainerd: containerd connection state change: TRANSIENT_FAILURE"
dockerd[7477]: time="2017-02-28T16:18:27.558627045-08:00" level=debug msg="Using default logging driver json-file"
dockerd[7477]: time="2017-02-28T16:18:27.558682586-08:00" level=debug msg="Golang's threads limit set to 53820"
dockerd[7477]: time="2017-02-28T16:18:27.558707953-08:00" level=debug msg="[graphdriver] trying provided driver \"aufs\""
dockerd[7477]: time="2017-02-28T16:18:27.561552996-08:00" level=debug msg="Using graph driver aufs"
dockerd[7477]: time="2017-02-28T16:18:29.554345890-08:00" level=debug msg="libcontainerd: containerd connection state change: READY"
dockerd[7477]: time="2017-02-28T16:29:59.412325276-08:00" level=debug msg="Max Concurrent Downloads: 3"
dockerd[7477]: time="2017-02-28T16:29:59.412360646-08:00" level=debug msg="Max Concurrent Uploads: 5"
dockerd[7477]: time="2017-02-28T16:38:26.719889304-08:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
dockerd[7477]: time="2017-02-28T16:38:26.734889403-08:00" level=warning msg="Your kernel does not support kernel memory limit."
dockerd[7477]: time="2017-02-28T16:38:26.734945935-08:00" level=warning msg="Your kernel does not support cgroup cfs period"
dockerd[7477]: time="2017-02-28T16:38:26.734966469-08:00" level=warning msg="Your kernel does not support cgroup cfs quotas"
dockerd[7477]: time="2017-02-28T16:38:26.735096976-08:00" level=warning msg="mountpoint for pids not found"
dockerd[7477]: time="2017-02-28T16:38:26.737123918-08:00" level=info msg="Loading containers: start."
dockerd[7477]: time="2017-02-28T16:38:26.747449600-08:00" level=error msg="Failed to load container 1600f560e713745adba662d56aca1264502922e7eaafcb3a6947436238462b4d: open /mnt/docker/var-lib-docker/containers/1600f560e713745adba662d56aca1264502922e7eaafcb3a6947436238462b4d/c
dockerd[7477]: time="2017-02-28T16:38:26.785962664-08:00" level=debug msg="Loaded container 1e767fb8dba9e64bcbf218b6bde14b5458185b494d01046db82ba6a22ad3bd24"
dockerd[7477]: time="2017-02-28T16:38:26.786224788-08:00" level=debug msg="Loaded container 2191a0f823f26b359978ead1386ce055839b20084c0f994a2aa40ede3047eb34"
dockerd[7477]: time="2017-02-28T16:38:26.826233461-08:00" level=debug msg="Loaded container 412770393b346924d322e0d3cfbdd67e18d206914326f310d4ce4f5ba16f8327"
dockerd[7477]: time="2017-02-28T16:38:26.826533682-08:00" level=debug msg="Loaded container 420352251dc8f47b18c325d460440e43e3353ee88f1ae808bd8e58eafc37f06e"
dockerd[7477]: time="2017-02-28T16:38:26.826760909-08:00" level=debug msg="Loaded container 4a910bd403b72b5c5e28419473b1f318ccac7297ddab05726c3c65a83365f04f"
dockerd[7477]: time="2017-02-28T16:38:26.827032075-08:00" level=debug msg="Loaded container 698d1671d23e7e795505cd50e948ef576942b18c2c25961d66fb504cb5ca525d"
dockerd[7477]: time="2017-02-28T16:38:26.827246873-08:00" level=debug msg="Loaded container cb304507744c837c73a57b0caa992924b2f2ab6c03633a2c996d9a33781cef33"
dockerd[7477]: time="2017-02-28T16:38:26.851166620-08:00" level=debug msg="Loaded container d3a17c16571a965c9b3aa96d1b997754a5756d179a95fc258fa85d6b6bf88c33"
dockerd[7477]: time="2017-02-28T16:38:26.851332818-08:00" level=debug msg="Option DefaultDriver: bridge"
dockerd[7477]: time="2017-02-28T16:38:26.851349429-08:00" level=debug msg="Option DefaultNetwork: bridge"
dockerd[7477]: time="2017-02-28T16:38:26.868539046-08:00" level=debug msg="Fail to initialize firewalld: Failed to connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory, using raw iptables instead"
dockerd[7477]: time="2017-02-28T16:38:26.873480346-08:00" level=debug msg="/sbin/iptables, [--wait --version]"
```

cc @yosifkit

**Comment by tianon** [comment]
Just rebooted that system again and it took a full hour before Docker was responding again. :disappointed: (on 17.04.0-ce now)
```
-- Logs begin at Thu 2017-04-13 13:38:11 PDT. --
time="2017-04-13T13:38:14.635865695-07:00" level=debug msg="Listener created for HTTP on fd ()"
time="2017-04-13T13:38:14.638094297-07:00" level=info msg="libcontainerd: new containerd process, pid: 420"
time="2017-04-13T13:38:15.144440667-07:00" level=debug msg="libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable"
time="2017-04-13T13:38:15.644400975-07:00" level=debug msg="libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable"
time="2017-04-13T13:38:15.654923326-07:00" level=debug msg="Using default logging driver json-file"
time="2017-04-13T13:38:15.654955398-07:00" level=debug msg="Golang's threads limit set to 53820"
time="2017-04-13T13:38:15.714019500-07:00" level=debug msg="[graphdriver] trying provided driver: aufs"
time="2017-04-13T13:38:15.725074616-07:00" level=debug msg="Using graph driver aufs"
time="2017-04-13T13:56:01.529576151-07:00" level=debug msg="Max Concurrent Downloads: 3"
time="2017-04-13T13:56:01.529609317-07:00" level=debug msg="Max Concurrent Uploads: 5"
time="2017-04-13T14:40:24.502562084-07:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
...
(many lines here, removed for brevity -- setting up routes, iptables, etc)
...
time="2017-04-13T14:40:47.035145773-07:00" level=debug msg="Registering POST, /networks/prune"
time="2017-04-13T14:40:47.035248489-07:00" level=debug msg="Registering DELETE, /networks/{id:.*}"
Started Docker Application Container Engine.
time="2017-04-13T14:40:47.035779382-07:00" level=info msg="API listen on /var/run/docker.sock"
time="2017-04-13T14:40:47.036783021-07:00" level=debug msg="Calling GET /_ping"
time="2017-04-13T14:40:47.037431670-07:00" level=debug msg="Calling GET /v1.28/version"
```

```console
$ docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 17:45:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 17:45:49 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```console
$ docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 69910
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /mnt/docker/var-lib-docker/aufs
 Backing Filesystem: extfs
 Dirs: 26630
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.321GiB
Name: official-images-build-server
ID: HOSB:GEKJ:FCZ7:CN5R:63JH:QSCI:CUOU:BALS:AJGE:SOE2:TH7G:YEV5
Docker Root Dir: /mnt/docker/var-lib-docker
Debug Mode (client): false
Debug Mode (server): false
Username: stackbrew
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Comment by thaJeztah** [comment]
ping @tonistiigi any ideas?

**Comment by tonistiigi** [comment]
By the logs it appears between https://github.com/docker/docker/blob/41f4c3cf7e270086bb2f6a6bd4622d9aeb8f741f/daemon/daemon.go#L632-L671 . `NewImageStore` does read all config into memory but these are small files so there needs to be a bug somewhere that does something very inefficiently.

Can you try `opensnoop` or send `SIGUSR1` to the dockerd process to get the traces while this is hanging. If the signal handler is not set up by that time you can send `SIGQUIT`.

**Comment by tianon** [comment]
I had to reboot to reproduce (just restarting the daemon restarted surprisingly fast this time), and `SIGUSR1` didn't respond so I did `SIGQUIT`, and here's that trace:
```
-- Logs begin at Fri 2017-04-14 12:44:15 PDT. --
12:44:18 systemd[1]: Starting Docker Application Container Engine...
12:44:19 dockerd[389]: time="2017-04-14T12:44:19.124207394-07:00" level=debug msg="Listener created for HTTP on fd ()"
12:44:19 dockerd[389]: time="2017-04-14T12:44:19.127262385-07:00" level=info msg="libcontainerd: new containerd process, pid: 419"
12:44:19 dockerd[389]: time="2017-04-14T12:44:19.633149052-07:00" level=debug msg="libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable"
12:44:20 dockerd[389]: time="2017-04-14T12:44:20.146421012-07:00" level=debug msg="Using default logging driver json-file"
12:44:20 dockerd[389]: time="2017-04-14T12:44:20.146474819-07:00" level=debug msg="Golang's threads limit set to 53820"
12:44:20 dockerd[389]: time="2017-04-14T12:44:20.232399001-07:00" level=debug msg="[graphdriver] trying provided driver: aufs"
12:44:20 dockerd[389]: time="2017-04-14T12:44:20.243972849-07:00" level=debug msg="Using graph driver aufs"
12:45:41 dockerd[389]: time="2017-04-14T12:45:41.427407996-07:00" level=info msg="Processing signal 'quit'"
12:45:41 dockerd[389]: goroutine 8 [running]:
12:45:41 dockerd[389]: github.com/docker/docker/pkg/signal.DumpStacks(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
12:45:41 dockerd[389]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:82 +0xfc
12:45:41 dockerd[389]: github.com/docker/docker/pkg/signal.Trap.func1.1(0xc42033a88c, 0xc42020a9c0, 0x24030c0, 0xc4214fa658)
12:45:41 dockerd[389]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:60 +0x2d5
12:45:41 dockerd[389]: created by github.com/docker/docker/pkg/signal.Trap.func1
12:45:41 dockerd[389]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:65 +0x12c
12:45:41 dockerd[389]: goroutine 1 [syscall]:
12:45:41 dockerd[389]: syscall.Syscall(0x0, 0x3, 0xc421521900, 0x247, 0x1, 0xc420956ad0, 0x0)
12:45:41 dockerd[389]: /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
12:45:41 dockerd[389]: syscall.read(0x3, 0xc421521900, 0x247, 0x247, 0x19a9e3e, 0x19a9e3d, 0xc41fff6341)
12:45:41 dockerd[389]: /usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x55
12:45:41 dockerd[389]: syscall.Read(0x3, 0xc421521900, 0x247, 0x247, 0x41d1fe, 0x20, 0x2)
12:45:41 dockerd[389]: /usr/local/go/src/syscall/syscall_unix.go:161 +0x49
12:45:41 dockerd[389]: os.(*File).read(0xc4203ce5d0, 0xc421521900, 0x247, 0x247, 0xc421521900, 0x0, 0xc42010c000)
12:45:41 dockerd[389]: /usr/local/go/src/os/file_unix.go:228 +0x4f
12:45:41 dockerd[389]: os.(*File).Read(0xc4203ce5d0, 0xc421521900, 0x247, 0x247, 0xc420956c08, 0xc420956c18, 0x4629c0)
12:45:41 dockerd[389]: /usr/local/go/src/os/file.go:101 +0x59
12:45:41 dockerd[389]: bytes.(*Buffer).ReadFrom(0xc420956c38, 0x23f8240, 0xc4203ce5d0, 0xc421521900, 0x0, 0x247)
12:45:41 dockerd[389]: /usr/local/go/src/bytes/buffer.go:176 +0x155
12:45:41 dockerd[389]: io/ioutil.readAll(0x23f8240, 0xc4203ce5d0, 0x247, 0x0, 0x0, 0x0, 0x0, 0x0)
12:45:41 dockerd[389]: /usr/local/go/src/io/ioutil/ioutil.go:33 +0x147
12:45:41 dockerd[389]: io/ioutil.ReadFile(0xc4215df700, 0x7a, 0x0, 0x0, 0x0, 0x0, 0x0)
12:45:41 dockerd[389]: /usr/local/go/src/io/ioutil/ioutil.go:70 +0x12e
12:45:41 dockerd[389]: github.com/docker/docker/layer.(*fileMetadataStore).GetDiffID(0xc42023cad0, 0xc42013bdb0, 0x47, 0x47, 0x246d040, 0x0, 0x0)
12:45:41 dockerd[389]: /usr/src/docker/.gopath/src/github.com/docker/docker/layer/filestore.go:177 +0x70
12:45:41 dockerd[389]: github.com/docker/docker/layer.(*layerStore).loadLayer(0xc420121b40, 0xc42013bdb0, 0x47, 0xc4215b10e0, 0x0, 0x0)
12:45:41 dockerd[389]: /usr/src/docker/.gopath/src/github.com/docker/docker/layer/layer_store.go:115 +0xb5
12:45:41 systemd[1]: docker.service: main process exited, code=exited, status=131/n/a
```

**Comment by tianon** [comment]
(If that doesn't have anything helpful in it, I'll start looking into getting `opensnoop` going on that system)

**Comment by tonistiigi** [comment]
cc @dmcgowan

**Comment by tianon** [comment]
Assuming that https://github.com/brendangregg/perf-tools/blob/master/opensnoop is the `opensnoop` you're referring to, I've run `sudo ./opensnoop -p 520` (which 520 is the current pid of `dockerd`) and there's still no output so far beyond the headers (been running for a couple minutes now). :disappointed:
```console
$ ps aux | grep dockerd
root       520  2.1  0.6 504060 50104 ?        Ssl  12:45   0:05 /usr/bin/dockerd -H fd://
$ sudo ./opensnoop -p 520
Tracing open()s issued by PID 520. Ctrl-C to end.
COMM             PID      FD FILE

```

**Comment by tianon** [comment]
@yosifkit is doing `ls -l /proc/520/fd` and there's a file descriptor in there that keeps changing between different files, so I think `opensnoop` isn't seeing the `open` syscalls :disappointed:

**Comment by tianon** [comment]
(which makes sense, because doing `ioutil.ReadFile` on that ~70 byte `diff` file shouldn't be hanging and stopping the loop from doing more `open(1)`s)

**Comment by tianon** [comment]
Doing `./opensnoop` without specifying a PID has a lot more output, but nothing from `dockerd` :disappointed:

**Comment by tianon** [comment]
`strace` gives me some love: (although it looks like we've moved on to a different part of startup code, since we got some more output from the daemon -- `Max Concurrent {Uploads,Downloads}...`)
```console
$ sudo strace -f -p 520 2>&1 | grep open
[pid   520] openat(AT_FDCWD, "/mnt/docker/var-lib-docker/image/aufs/imagedb/content/sha256/00bdd6dcaeffaa6cedd4015f57c68bbdb30f768ba13fc586ab68e8af57028c45", O_RDONLY|O_CLOEXEC) = 3
[pid   520] openat(AT_FDCWD, "/mnt/docker/var-lib-docker/image/aufs/imagedb/metadata/sha256/00bdd6dcaeffaa6cedd4015f57c68bbdb30f768ba13fc586ab68e8af57028c45/parent", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid   520] <... openat resumed> )      = 3
[pid   520] openat(AT_FDCWD, "/mnt/docker/var-lib-docker/image/aufs/imagedb/content/sha256/00be05185c1193014527a20c26e73669d5191bddeb750829fc8ddab5ff6528bb", O_RDONLY|O_CLOEXEC) = 3
[pid   520] openat(AT_FDCWD, "/mnt/docker/var-lib-docker/image/aufs/imagedb/content/sha256/00be05185c1193014527a20c26e73669d5191bddeb750829fc8ddab5ff6528bb", O_RDONLY|O_CLOEXEC) = 3
[pid   520] openat(AT_FDCWD, "/mnt/docker/var-lib-docker/image/aufs/imagedb/metadata/sha256/00be05185c1193014527a20c26e73669d5191bddeb750829fc8ddab5ff6528bb/parent", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid   520] <... openat resumed> )      = 3
[pid   520] openat(AT_FDCWD, "/mnt/docker/var-lib-docker/image/aufs/imagedb/content/sha256/00bede0c5186b3bf509bfa8a42d8ca1af88d3a206a29de64a698ca0978a7b8fb", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid   520] <... openat resumed> )      = 3
[pid   520] openat(AT_FDCWD, "/mnt/docker/var-lib-docker/image/aufs/imagedb/content/sha256/00bede0c5186b3bf509bfa8a42d8ca1af88d3a206a29de64a698ca0978a7b8fb", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid   520] <... openat resumed> )      = 3
[pid   520] openat(AT_FDCWD, "/mnt/docker/var-lib-docker/image/aufs/imagedb/metadata/sha256/00bede0c5186b3bf509bfa8a42d8ca1af88d3a206a29de64a698ca0978a7b8fb/parent", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid   520] <... openat resumed> )      = 3
```

**Comment by tonistiigi** [comment]
It is normal that this section open lots of files. It reads all image config and layer metadata. But these are all small files so this should never be take more than a couple of seconds unless there is a bug and files are read more times than they should be. Maybe just add logging for every `loadLayer` and `imagestore.Get`. That strace already shows same image ID opened multiple times, but that may be only because some containers also use that image.

**Comment by tianon** [comment]
This system's only currently got three containers total (see `docker info` above), so that can't account for much. :innocent:

**Comment by tonistiigi** [comment]
@tianon Yes, I didn't mean that. Just that from that output it is hard to say if the loading phase did duplicate `openat` calls for this specific image. I can check how many syscalls per image are run on startup locally as well to check that.

**Comment by tianon** [comment]
As additional confirmation that this behavior is number-of-images dependent, we deleted a ton of images and the startup speed improved, as expected.

**Comment by ddevault** [comment]
2 years later... and what the heck is dockerd doing for 20 minutes? Totally nuts.

**Comment by rulatir** [comment]
To anyone affected - can you test what effect `barrier` has on this issue? It seems that it "helps" substantially when restarting, much less so with a fully cold start. ("Helps" in scare quotes because disabling `barrier` is, of course, NOT an acceptable workaround).
