### ISSUE TITLE
Builder causes daemon panic if --build-arg FOO env var is not set

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#31990]
**Description**

```
$ echo 'FROM alpine
> ARG SPAM
> ARG EGGS' | docker build --build-arg SPAM --build-arg EGGS -
Sending build context to Docker daemon 2.048 kB
Step 1/3 : FROM alpine
 ---> 88e169ea8f46
Step 2/3 : ARG SPAM
 ---> Using cache
 ---> f7d6c77134d4

$ echo $?
0
```

O_O

```
$ docker-machine ssh default tail -n 50 /var/log/docker.log
time="2017-03-22T00:41:30.937071601Z" level=debug msg="[BUILDER] Use cached version: [/bin/sh -c #(nop)  ARG SPAM]"
time="2017-03-22T00:41:33.164976156Z" level=debug msg="Calling GET /_ping"
time="2017-03-22T00:41:33.166988496Z" level=debug msg="Calling POST /v1.26/build?buildargs=%7B%22SPAM%22%3Anull%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&ulimits=null"
time="2017-03-22T00:41:33.182757547Z" level=debug msg="[BUILDER] Use cached version: [/bin/sh -c #(nop)  ARG SPAM]"
time="2017-03-22T00:41:41.049953213Z" level=debug msg="Calling GET /_ping"
time="2017-03-22T00:41:41.051951690Z" level=debug msg="Calling POST /v1.26/build?buildargs=%7B%22SPAM%22%3Anull%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&ulimits=null"
time="2017-03-22T00:41:41.068645527Z" level=debug msg="[BUILDER] Use cached version: [/bin/sh -c #(nop)  ARG SPAM]"
time="2017-03-22T00:41:56.421415458Z" level=debug msg="Calling GET /_ping"
time="2017-03-22T00:41:56.423540746Z" level=debug msg="Calling POST /v1.26/build?buildargs=%7B%22EGGS%22%3Anull%2C%22SPAM%22%3Anull%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&ulimits=null"
time="2017-03-22T00:41:56.439312418Z" level=debug msg="[BUILDER] Use cached version: [/bin/sh -c #(nop)  ARG SPAM]"
2017-03-22 00:41:56.439748 I | http: panic serving 192.168.99.1:61221: runtime error: invalid memory address or nil pointer dereference
goroutine 583 [running]:
net/http.(*conn).serve.func1(0xc420d32c80)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x1777c40, 0xc420010090)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/docker/docker/builder/dockerfile.(*Builder).dispatch(0xc4214126c0, 0x2, 0x3, 0xc420955570, 0xc420a290b0, 0x1)
	/go/src/github.com/docker/docker/builder/dockerfile/evaluator.go:161 +0x57f
github.com/docker/docker/builder/dockerfile.(*Builder).build(0xc4214126c0, 0x2509c20, 0xc4202aeae0, 0x2509be0, 0xc4202aeb00, 0x2509120, 0xc4202aeac0, 0x0, 0x0, 0xc4214126c0, ...)
	/go/src/github.com/docker/docker/builder/dockerfile/builder.go:266 +0x2b5
github.com/docker/docker/builder/dockerfile.(*BuildManager).BuildFromContext(0xc4224911d0, 0x2522860, 0xc4220aa680, 0x25169a0, 0xc4220aa5c0, 0x0, 0x0, 0xc4213823c0, 0x2509120, 0xc4202aeac0, ...)
	/go/src/github.com/docker/docker/builder/dockerfile/builder.go:117 +0x323
github.com/docker/docker/api/server/router/build.(*buildRouter).postBuild(0xc42160c6f0, 0x2522860, 0xc4220aa680, 0x251f060, 0xc4213cf380, 0xc42137e4b0, 0xc4210cd140, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/router/build/build_routes.go:212 +0x87f
github.com/docker/docker/api/server/router/build.(*buildRouter).(github.com/docker/docker/api/server/router/build.postBuild)-fm(0x2522860, 0xc4220aa680, 0x251f060, 0xc4213cf380, 0xc42137e4b0, 0xc4210cd140, 0xc421988a60, 0x1)
	/go/src/github.com/docker/docker/api/server/router/build/build.go:27 +0x69
github.com/docker/docker/api/server/router.cancellableHandler.func1(0x2522920, 0xc4210cd200, 0x251f060, 0xc4213cf380, 0xc42137e4b0, 0xc4210cd140, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/router/local.go:84 +0x104
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x2522920, 0xc4210cd200, 0x251f060, 0xc4213cf380, 0xc42137e4b0, 0xc4210cd140, 0x1d, 0xe0ff5cb400000001)
	/go/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xd8
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x2522920, 0xc4210cd1a0, 0x251f060, 0xc4213cf380, 0xc42137e4b0, 0xc4210cd140, 0xc4229f3ad0, 0x8)
	/go/src/github.com/docker/docker/api/server/middleware/version.go:47 +0x5ca
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x2522920, 0xc4210cd1a0, 0x251f060, 0xc4213cf380, 0xc42137e4b0, 0xc4210cd140, 0x756ea17098b0a0, 0xc420a29988)
	/go/src/github.com/docker/docker/pkg/authorization/middleware.go:43 +0x83f
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1(0x2522920, 0xc4210cd1a0, 0x251f060, 0xc4213cf380, 0xc42137e4b0, 0xc4210cd140, 0xc400000000, 0xc421412000)
	/go/src/github.com/docker/docker/api/server/middleware/debug.go:25 +0x9bf
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x251f060, 0xc4213cf380, 0xc42137e4b0)
	/go/src/github.com/docker/docker/api/server/server.go:139 +0x233
net/http.HandlerFunc.ServeHTTP(0xc4222760c0, 0x251f060, 0xc4213cf380, 0xc42137e4b0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4221d3770, 0x251f060, 0xc4213cf380, 0xc42137e4b0)
	/go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc421f92a90, 0x251f060, 0xc4213cf380, 0xc42137e4b0)
	/go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc420056a00, 0x251f060, 0xc4213cf380, 0xc42137e4b0)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420d32c80, 0x2520ca0, 0xc4220aa500)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

:(

If I set the value of those as environment variables it works fine though.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.03.1-ce-rc1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce-rc1
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3476dbf
 Built:        Fri Mar 17 00:27:41 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
$ docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 128
Server Version: 17.03.1-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: vn5p5pcs5glevymwyvfvak64a
 Is Manager: true
 ClusterID: 0mxekj55chzgzv4gzbz8bdorp
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.99.100
 Manager Addresses:
  192.168.99.100:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.54-boot2docker
Operating System: Boot2Docker 17.03.1-ce-rc1 (TCL 7.2); HEAD : dd6af02 - Fri Mar 17 22:17:14 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: U2B5:IGEE:LMFY:SWJW:JUPB:IUJS:YO7T:WEXF:PYPE:TZBF:MXYA:TJDN
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 126
 System Time: 2017-03-22T00:43:19.192419783Z
 EventsListeners: 0
Username: nathanleclaire
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by tonistiigi** [comment]
This is fixed by https://github.com/docker/docker/pull/31351

`0` exit code needs to be addressed as well.
