### ISSUE TITLE
Error closing logger: invalid argument

### ISSUE THREAD

**Issue by mschwager** [docker/docker#32239]
**Description**

I'm seeing the following error when attempting to `commit` a running container.

```
Mar 30 16:53:50 x1 dockerd[1173]: time="2017-03-30T16:53:50.108905324-04:00" level=error msg="Error closing logger: invalid argument"
Mar 30 16:53:50 x1 dockerd[1173]: time="2017-03-30T16:53:50.263311304-04:00" level=error msg="Error unmounting container eaf3d589471c45714baaddd17d3d863861978bad16b01d7dba80e30767100313: no such file or directory
Mar 30 16:53:50 x1 dockerd[1173]: time="2017-03-30T16:53:50.263391788-04:00" level=error msg="Handler for POST /v1.26/commit returned error: Error: driver aufs is returning inconsistent paths for container eaf3d5
```

This happens running `docker-py` on Python 3. In Python I get the following error:

```
b'2017-03-30T21:27:15.881302433Z + tar --gzip --create --directory /usr/local --file /opt/duo/dag_third_party.tgz bin etc lib/python2.7 sbin ssl'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 214, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.26/commit?tag=latest&container=bfa1c04149e3cd6318722b0063b725319dfd08ecb3e3247c405cdc522fcdfd3a&repo=duosecurity%2Faccess-gateway-builder-thirdparty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tupperware.py", line 877, in <module>
    main()
  File "tupperware.py", line 871, in main
    dispatch[args.command](**vars(args))
  File "tupperware.py", line 361, in build
    build_third_party_tarball(client, DAG_BUILDBASE_DOCKERFILE, tag, force=force)
  File "tupperware.py", line 398, in build_third_party_tarball
    commit_docker_container(client, third_party_id, DAG_BUILDER_THIRDPARTY_IMAGE)
  File "tupperware.py", line 183, in commit_docker_container
    client.commit(container, repository=repository, tag=tag)
  File "/usr/local/lib/python3.5/dist-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/container.py", line 129, in commit
    json=True)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 220, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Error: driver aufs is returning inconsistent paths for container bfa1c04149e3cd6318722b0063b725319dfd08ecb3e3247c405cdc522fcdfd3a ('/var/lib/docker/aufs/mnt/79ca5cbc252b6f52162f370595c790973d480e9b88d89a2dad6fbfe41af59005' then '/var/lib/docker/aufs/diff/79ca5cbc252b6f52162f370595c790973d480e9b88d89a2dad6fbfe41af59005')")
```

**Steps to reproduce the issue:**
1. It appears to happen from a `commit` call in `docker-py`: https://docker-py.readthedocs.io/en/stable/api.html#docker.api.container.ContainerApiMixin.commit

**Describe the results you received:**

The `commit` call fails.

**Describe the results you expected:**

The `commit` call continues as expected.

**Additional information you deem important (e.g. issue happens only occasionally):**

I noticed it's referencing `500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.26/commit?tag=latest&container=bfa1c04149e3cd6318722b0063b725319dfd08ecb3e3247c405cdc522fcdfd3a` version `1.26` but my `docker version` reports `1.27`. Could that be a problem?

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1362
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2689
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-71-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.679 GiB
Name: x1
ID: AS5A:3REA:TXRP:IGYF:R4AI:IC63:KDLD:OPR2:USZX:77W2:KGNH:22S6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: mattsduosec
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

```
$ uname -a
Linux x1 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mschwager** [comment]
I'm not really sure where to even start with this. I don't have a method to easily reproduce this, it happens about 30min into a build process. I'm hoping someone will be able to quickly recognize what could be going wrong.

**Comment by mschwager** [comment]
Downgrading `docker-py` from 2.2.1 to 2.1.0 fixed the issue. I'll take it up with them!
