### ISSUE TITLE
Swarm/networking deadlock when shutting down daemon

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#32441]
This was discovered in a CI run on #32283. We don't think it's related to the changes in that PR.

See the stack traces in https://gist.github.com/aboch/ed05184c21313f98d62748ac4c74718f

Stopping the swarm node times out because the agent main loop is wedged and `agent.Leave` times out. This is a stack trace of the agent main loop:

```
goroutine 146 [semacquire]:
sync.runtime_Semacquire(0xc42000aff0)
	/usr/local/go/src/runtime/sema.go:47 +0x38
sync.(*Mutex).Lock(0xc42000afec)
	/usr/local/go/src/sync/mutex.go:85 +0x2f8
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).getStores(0xc42000af00, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/store.go:76 +0x58
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).getNetworksFromStore(0xc42000af00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/store.go:145 +0x60
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).Networks(0xc42000af00, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:868 +0x50
github.com/docker/docker/daemon.(*Daemon).GetNetworkDriverList(0xc420496200, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/network.go:459 +0x368
github.com/docker/docker/daemon.(*Daemon).showPluginsInfo(0xc420496200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/info.go:176 +0x64
github.com/docker/docker/daemon.(*Daemon).SystemInfo(0xc420496200, 0xc42001d502, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/info.go:101 +0x840
github.com/docker/docker/daemon/cluster/executor/container.(*executor).Describe(0xc420e72760, 0x3fff9e4a08e0, 0xc420a758c0, 0x9, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/executor.go:34 +0x60
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*Agent).nodeDescriptionWithHostname(0xc420eb6dc0, 0x3fff9e4a08e0, 0xc420a758c0, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/agent.go:521 +0x6c
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*Agent).run(0xc420eb6dc0, 0x3fff9e4a08e0, 0xc420a758c0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/agent.go:314 +0x15fc
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*Agent).Start.func1
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/agent.go:79 +0x84
```

It can't get the controller lock because it's held by this goroutine, that's trying to get the cluster lock:

```
goroutine 467 [semacquire]:
sync.runtime_Semacquire(0xc42007186c)
	/usr/local/go/src/runtime/sema.go:47 +0x38
sync.(*RWMutex).RLock(0xc420071860)
	/usr/local/go/src/sync/rwmutex.go:43 +0x9c
github.com/docker/docker/daemon/cluster.(*Cluster).IsAgent(0xc420071860, 0x117ba000)
	/go/src/github.com/docker/docker/daemon/cluster/cluster.go:240 +0x48
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).isAgent(0xc42000af00, 0xc42000af00)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:638 +0x110
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*network).driver(0xc4210a9e00, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/network.go:767 +0xe0
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*network).addEndpoint(0xc4210a9e00, 0xc421705e40, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/network.go:875 +0x44
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*network).CreateEndpoint(0xc4210a9e00, 0xc420fc11d1, 0x21, 0xc4217311a0, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/network.go:950 +0xabc
github.com/docker/docker/daemon.(*Daemon).connectToNetwork(0xc420496200, 0xc4207bd400, 0x1164b5f6, 0x6, 0xc421714480, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_operations.go:735 +0x668
github.com/docker/docker/daemon.(*Daemon).allocateNetwork(0xc420496200, 0xc4207bd400, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_operations.go:526 +0x378
github.com/docker/docker/daemon.(*Daemon).initializeNetworking(0xc420496200, 0xc4207bd400, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_operations.go:903 +0x3d0
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc420496200, 0xc4207bd400, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/start.go:140 +0x1f4
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc420496200, 0xc421764000, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/start.go:86 +0x5d4
github.com/docker/docker/daemon/cluster/executor/container.(*containerAdapter).start(0xc421085830, 0x3fff9e4d62b8, 0xc420d77640, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/adapter.go:285 +0xd8
github.com/docker/docker/daemon/cluster/executor/container.(*controller).Start(0xc420f264b0, 0x3fff9e4d62b8, 0xc420d77640, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/cluster/executor/container/controller.go:189 +0x164
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/exec.Do(0x3fff9e4d62b8, 0xc420d77640, 0xc4210a9b00, 0x11fdf000, 0xc420f264b0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/exec/controller.go:314 +0x720
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*taskManager).run.func2(0x3fff9e4a08e0, 0xc420f2b140, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/task.go:134 +0x290
github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.runctx(0x3fff9e4a08e0, 0xc420f2b140, 0xc420eafb00, 0xc420f60300, 0xc420d776c0)
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/helpers.go:9 +0x50
created by github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*taskManager).run
	/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/task.go:150 +0x51c
```

cc @aboch @tonistiigi

**Comment by tonistiigi** [comment]
It's not really a deadlock but a timeout.

One of the issues is that `agent.Leave` does not cancel the context for other select cases in `agent.run()`. So if `Describe()` is running nothing cancels it when `agent.Stop()/Leave()` is called(it would be cancelled on `node.Stop()` if there was no `Leave()` call there). Maybe it should at least have a timeout.

Other way would be to allow `IsAgent` while the `swarmnode.Stop()` is running.

**Comment by aaronlehmann** [comment]
Why does libnetwork call into the `Cluster` code in the first place? This seems to introduce a circular dependency and it leads to the locking issue.

What is libnetwork using the result for? Could we refactor this so that the engine calls into libnetwork to tell it when it becomes and agent or stops being an agent?

**Comment by tonistiigi** [comment]
@aaronlehmann From the stack trace it seems on container startup(that could be joining a swarm network but not sure if that is actually the case this time).

If the source for these calls is daemon pkg, that itself shouldn't be a problem(unless `node.Stop` also calls to networkcontroller in some other codepath). Based on this stacktrace I would put more blame on `Agent` that is not processing a call to `Stop/Leave` because at the same time it is blocked on doing a call to `executor.Describe()`.

**Comment by aaronlehmann** [comment]
Hm, to me the root cause is that `Describe` is hanging. I think `Describe` should not be a long-running call, and the agent should not be responsible for timing it out.

**Comment by aaronlehmann** [comment]
Also I don't see how it would help to cancel the context in `agent`. If `Describe` is blocked on a mutex, cancelling a context is not going to cause it to return.

**Comment by tonistiigi** [comment]
@aaronlehmann `node.Stop()` shouldn't be a long-running call either and caller should not be responsible for predicting that it may call back to something else.

> Also I don't see how it would help to cancel the context in agent. If Describe is blocked on a mutex, cancelling a context is not going to cause it to return.

If `node.Stop()` returns it releases the mutex and result from executor is discarded as node is already stopped.

**Comment by aaronlehmann** [comment]
@tonistiigi: I don't understand your preferred solution. Earlier you said:

> So if Describe() is running nothing cancels it when agent.Stop()/Leave() is called(it would be cancelled on node.Stop() if there was no Leave() call there). 

But I don't think this is right (or I'm misunderstanding). There's no way to "cancel" a function call that's blocked on acquiring a mutex in go.

**Comment by tonistiigi** [comment]
@aaronlehmann Ah, yes. For some reason I didn't think `Describe` is called directly but that there is some cancelable caller-handler logic between them. But yes, the implementation of `Describe` completely ignores context. Could fake it with 
```
go func() {res<-Describe()}
select {
case <-ctx.Done():
case <-res:
}
```

but on caller side this doesn't make sense. This would make sense inside executor though to make `Describe` cancelable but we would still need to change the `Leave()` logic as well.
