### ISSUE TITLE
An unreproduced crash in the client while running `docker logs --follow`

### ISSUE THREAD

**Issue by alco** [docker/docker#5375]
I didn't know that the ^P^Q shortcut did not apply to "docker logs --follow", but when I tried it a couple of times, the client just crashed. I may have also pressed Enter accidentally just before the crash, but I wasn't able to reproduce it again.

I'm filing this issue because I got a stacktrace from docker. Maybe it'll point to some issue in the code.

```
λ docker logs --follow 66eee
Erlang/OTP 17 [erts-6.0] [source-07b8f44] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Started listening on port 8000...

^P^P^P^P^P^P^P^P^P^P^P^P^P^P^P^P^P^P^P^P^P^P^\SIGQUIT: quit
PC=0x2ca03

runtime.kevent(0x7fff00000004, 0x0, 0x0, 0x7fff5fbfedd8, 0x7fff00000040, ...)
	/usr/local/go/src/pkg/runtime/sys_darwin_amd64.s:469 +0x23
runtime.netpoll(0xaf3c01)
	/usr/local/go/src/pkg/runtime/netpoll_kqueue.c:83 +0xae
findrunnable()
	/usr/local/go/src/pkg/runtime/proc.c:1222 +0x386
schedule()
	/usr/local/go/src/pkg/runtime/proc.c:1320 +0xe3
goexit0(0x210d64120)
	/usr/local/go/src/pkg/runtime/proc.c:1417 +0x102
runtime.mcall(0x2a5ad)
	/usr/local/go/src/pkg/runtime/asm_amd64.s:178 +0x4b

goroutine 1 [chan receive]:
github.com/dotcloud/docker/api/client.(*DockerCli).hijack(0x210d1d230, 0x503460, 0x4, 0x210cb2340, 0x3a, ...)
	/go/src/github.com/dotcloud/docker/api/client/utils.go:291 +0x959
github.com/dotcloud/docker/api/client.(*DockerCli).CmdLogs(0x210d1d230, 0x210cb2020, 0x2, 0x2, 0x0, ...)
	/go/src/github.com/dotcloud/docker/api/client/commands.go:1607 +0x934
reflect.callMethod(0x210d1cfc0, 0x2210e198d0)
	/usr/local/go/src/pkg/reflect/value.go:676 +0x17b
reflect.methodValueCall(0x210cb2020, 0x2, 0x2, 0x210d1cfc0, 0x40487401)
	/usr/local/go/src/pkg/reflect/asm_amd64.s:26 +0x24
github.com/dotcloud/docker/api/client.(*DockerCli).ParseCommands(0x210d1d230, 0x210cb2010, 0x3, 0x3, 0xc79140, ...)
	/go/src/github.com/dotcloud/docker/api/client/cli.go:41 +0x23c
main.main()
	/go/src/github.com/dotcloud/docker/docker/docker.go:220 +0x2c19

goroutine 3 [syscall]:
os/signal.loop()
	/usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 6 [IO wait]:
net.runtime_pollWait(0xc7ab58, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0x210d1d990, 0x72, 0xc790c0, 0x23)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0x210d1d990, 0x23, 0xc790c0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0x210d1d930, 0x210d67000, 0x1000, 0x1000, 0x0, ...)
	/usr/local/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0x210ca8f28, 0x210d67000, 0x1000, 0x1000, 0x0, ...)
	/usr/local/go/src/pkg/net/net.go:122 +0xc5
bufio.(*Reader).fill(0x210ce19c0)
	/usr/local/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).WriteTo(0x210ce19c0, 0xc79140, 0x210ca8008, 0x87, 0x0, ...)
	/usr/local/go/src/pkg/bufio/bufio.go:413 +0x108
io.Copy(0xc79140, 0x210ca8008, 0xc7ad78, 0x210ce19c0, 0x0, ...)
	/usr/local/go/src/pkg/io/io.go:344 +0xa5
github.com/dotcloud/docker/api/client.func·017(0x0, 0x0)
	/go/src/github.com/dotcloud/docker/api/client/utils.go:263 +0xf8
github.com/dotcloud/docker/utils.func·002()
	/go/src/github.com/dotcloud/docker/utils/utils.go:44 +0x2e
created by github.com/dotcloud/docker/utils.Go
	/go/src/github.com/dotcloud/docker/utils/utils.go:45 +0xa7

rax     0x4
rbx     0x0
rcx     0x7fff5fbfed68
rdx     0x0
rdi     0x4
rsi     0x0
rbp     0x1
rsp     0x7fff5fbfed68
r8      0x40
r9      0x0
r10     0x7fff5fbfedd8
r11     0x246
r12     0x4de180
r13     0xc
r14     0x210d5ce10
r15     0xc78e80
rip     0x2ca03
rflags  0x247
cs      0x7
fs      0x0
gs      0x0
```

**Comment by jfrazelle** [comment]
this is no longer a problem on the latest version or even Docker 1.0 closing
