### ISSUE TITLE
Problems running registry on Centos 6.5

### ISSUE THREAD

**Issue by acasanova** [docker/docker#8575]
I've been able to run a private registry successfully with all defaults on a local ubuntu 14.04 machine. I'm now trying to run on a Centos 6.5 machine. I've been getting some warnings that I'm not sure what to do with. ie `lxc-start: Device or resource busy - failed to set memory.use_hierarchy to 1; continuing`  I can pull down a Centos image and run a container. But I've tried getting the registry to work with S3 backend and without. The container quits on it own after a minute. With the non-s3 container it stays alive up until I try to push to the registry.

I initially was getting the error below
````
2014/06/19 20:40:34 unable to remount sys readonly: unable to mount sys as readonly max retries reached
````
So i changed  /etc/sysconfig/docker to have this:
````
other_args="--exec-driver=lxc --selinux-enabled"
````

Then that issue went away and this one started. The version in the EPEL for CentOS 6 is 1.1.2. I haven't found any docs on upgrading to a later version.

Run The Registry

docker run -e SETTINGS_FLAVOR=s3 -e AWS_BUCKET=custom-docker-registry -e STORAGE_PATH=/registry -e AWS_KEY=“xxxxxx" -e AWS_SECRET=“xxxxxx" -p 8000:5000 registry

````
lxc-start: Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
lxc-start: Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
2014-10-14 22:39:32,012 WARNING: Cache storage disabled!
2014-10-14 22:39:32,013 WARNING: LRU cache disabled!
2014-10-14 22:39:32,084 WARNING: No S3 region specified, using boto default region, this may affect performance and stability.
Traceback (most recent call last):
  File "/usr/local/bin/docker-registry", line 9, in <module>
    load_entry_point('docker-registry==0.8.1', 'console_scripts', 'docker-registry')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
** [Bugsnag] No API key configured, couldn't notify
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/run.py", line 18, in <module>
    from .tags import *  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/tags.py", line 21, in <module>
    store = storage.load()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/storage/__init__.py", line 38, in load
    config=cfg)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/s3.py", line 65, in __init__
    super(Storage, self).__init__(path, config)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/core/boto.py", line 135, in __init__
    self._config.boto_bucket)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 471, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 490, in head_bucket
    response = self.make_request('HEAD', bucket_name, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 633, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1046, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 922, in _mexe
    request.body, request.headers)
  File "/usr/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 570, in create_connection
    for res in getaddrinfo(host, port, 0 if has_ipv6 else AF_INET, SOCK_STREAM):
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 621, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, socktype, proto, flags)
  File "/usr/local/lib/python2.7/dist-packages/gevent/resolver_thread.py", line 34, in getaddrinfo
    return self.pool.apply_e(self.expected_errors, _socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/threadpool.py", line 225, in apply_e
    raise result
socket.gaierror: [Errno -2] Name or service not known
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --logpriority options.
````

Exit after 2 minutes
````
docker logs 5baf37aa62a3
lxc-start: Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
lxc-start: Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
2014-10-14 22:17:17,875 WARNING: Cache storage disabled!
2014-10-14 22:17:17,876 WARNING: LRU cache disabled!
2014-10-14 22:17:18,089 WARNING: No S3 region specified, using boto default region, this may affect performance and stability.
````

Tried again without S3 Environment variables

````
[root@com-Len acasanova]# docker logs c82a7cf6e635
lxc-start: Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
lxc-start: Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
2014-10-14 22:20:29,588 WARNING: Cache storage disabled!
2014-10-14 22:20:29,589 WARNING: LRU cache disabled!
2014-10-14 22:20:29,595 DEBUG: Will return docker-registry.drivers.file.Storage
2014-10-14 22:20:31 [1] [INFO] Starting gunicorn 18.0
2014-10-14 22:20:31 [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
2014-10-14 22:20:31 [1] [INFO] Using worker: gevent
2014-10-14 22:20:31 [16] [INFO] Booting worker with pid: 16
2014-10-14 22:20:31 [17] [INFO] Booting worker with pid: 17
2014-10-14 22:20:31 [18] [INFO] Booting worker with pid: 18
2014-10-14 22:20:31 [23] [INFO] Booting worker with pid: 23
2014-10-14 22:20:31,995 WARNING: Cache storage disabled!
2014-10-14 22:20:31,996 WARNING: LRU cache disabled!
2014-10-14 22:20:32,003 DEBUG: Will return docker-registry.drivers.file.Storage
2014-10-14 22:20:32,053 WARNING: Cache storage disabled!
2014-10-14 22:20:32,054 WARNING: LRU cache disabled!
2014-10-14 22:20:32,059 DEBUG: Will return docker-registry.drivers.file.Storage
2014-10-14 22:20:32,079 WARNING: Cache storage disabled!
2014-10-14 22:20:32,079 WARNING: LRU cache disabled!
2014-10-14 22:20:32,084 DEBUG: Will return docker-registry.drivers.file.Storage
2014-10-14 22:20:32,199 WARNING: Cache storage disabled!
2014-10-14 22:20:32,200 WARNING: LRU cache disabled!
2014-10-14 22:20:32,206 DEBUG: Will return docker-registry.drivers.file.Storage
````

Docker Version
````
docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.2
Git commit (client): d84a070/1.1.2
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.2
Git commit (server): d84a070/1.1.2
````

uname -a 
````
2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 23:32:49 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
````
docker info
````
Images: 54
Storage Driver: devicemapper
 Pool Name: docker-253:0-2098817-pool
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 1940.2 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 3.5 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: lxc-1.0.5
Kernel Version: 2.6.32-431.17.1.el6.x86_64
````

Thanks in advance

**Comment by jfrazelle** [comment]
is this still an issue with the latest version of docker and lxc 1.0.7, or can you try the native driver instead

**Comment by jfrazelle** [comment]
closing as stale please ping me with details to reproduce on latest and I will reopen
